import OperatorKO7.Meta.UniqueNormalization.LevelLabels

/-!
# RTA #79 route R2: decreasing-diagram certificate carrier

This module formalizes the exact local valley shape frozen in
`Distinction_Boundary/Roadmaps/klop/label-design.md`.

For a peak `t ->_a s` and `t ->_b u`, a decreasing certificate consists of

`s ->*_{<a} p ->^=_b q ->*_{<a or <b} m`

and

`u ->*_{<b} v ->^=_a w ->*_{<a or <b} m`.

The carrier is generic in states, labels, the labelled one-step relation, and the
strict label order.  The route-R2 `LevelLabelLt` of `LevelLabels.lean` is one
instance.  The theorem at the end checks the one-label diamond corner from the
roadmap: a literal diamond gives a decreasing certificate when the label order
is empty.

Trust: kernel checked. No external certificate or new axiom.
-/

set_option autoImplicit false

namespace OperatorKO7.Meta.UniqueNormalization

universe u v

variable {State : Type u} {Label : Type v}

/-- A labelled one-step relation. -/
abbrev LabelledStep (State : Type u) (Label : Type v) :=
  Label → State → State → Prop

/-- A step whose label is strictly below `a`. -/
def StepBelow (step : LabelledStep State Label) (lt : Label → Label → Prop)
    (a : Label) (x y : State) : Prop :=
  ∃ c : Label, lt c a ∧ step c x y

/-- A step whose label is below at least one side of a peak. -/
def StepBelowEither (step : LabelledStep State Label) (lt : Label → Label → Prop)
    (a b : Label) (x y : State) : Prop :=
  ∃ c : Label, (lt c a ∨ lt c b) ∧ step c x y

/-- Zero or more steps generated by a relation. -/
abbrev Star (r : State → State → Prop) : State → State → Prop :=
  Relation.ReflTransGen r

/-- Zero or one step at an exact label. -/
def OptionalLabelStep (step : LabelledStep State Label) (a : Label)
    (x y : State) : Prop :=
  x = y ∨ step a x y

/-- A labelled local peak with a common source. -/
structure LocalPeak (step : LabelledStep State Label) where
  source : State
  left : State
  right : State
  leftLabel : Label
  rightLabel : Label
  leftStep : step leftLabel source left
  rightStep : step rightLabel source right

/-- The exact van-Oostrom decreasing valley shape for one local peak. -/
structure DecreasingValley (step : LabelledStep State Label)
    (lt : Label → Label → Prop) (peak : LocalPeak step) : Type (max u v) where
  leftAfterLow : State
  leftAfterPeakLabel : State
  join : State
  rightAfterLow : State
  rightAfterPeakLabel : State
  leftLow : Star (StepBelow step lt peak.leftLabel) peak.left leftAfterLow
  leftPeakLabel : OptionalLabelStep step peak.rightLabel leftAfterLow leftAfterPeakLabel
  leftBoth : Star (StepBelowEither step lt peak.leftLabel peak.rightLabel)
    leftAfterPeakLabel join
  rightLow : Star (StepBelow step lt peak.rightLabel) peak.right rightAfterLow
  rightPeakLabel : OptionalLabelStep step peak.leftLabel rightAfterLow rightAfterPeakLabel
  rightBoth : Star (StepBelowEither step lt peak.leftLabel peak.rightLabel)
    rightAfterPeakLabel join

/-- A local peak is decreasing when it has the exact decreasing valley. -/
def LocalPeak.Decreasing (lt : Label → Label → Prop)
    {step : LabelledStep State Label} (peak : LocalPeak step) : Prop :=
  Nonempty (DecreasingValley step lt peak)

/-- Every local peak of a labelled relation is decreasing. -/
def AllLocalPeaksDecreasing (step : LabelledStep State Label)
    (lt : Label → Label → Prop) : Prop :=
  ∀ peak : LocalPeak step, peak.Decreasing lt

/-- The empty strict order on a one-label carrier. -/
def UnitLabelLt : Unit → Unit → Prop :=
  fun _ _ => False

/-- Local diamond property for a one-label relation. Each arm may take zero
or one joining step, so a peak whose two branches already agree is a diamond. -/
def UnitDiamond (step : LabelledStep State Unit) : Prop :=
  ∀ {t s u : State}, step () t s → step () t u →
    ∃ m : State, OptionalLabelStep step () s m ∧ OptionalLabelStep step () u m

/-- **Diamond corner of decreasing diagrams.** With one label and the empty
strict order, every literal local diamond is a decreasing local peak. -/
theorem allLocalPeaksDecreasing_of_unitDiamond
    {step : LabelledStep State Unit} (hdiamond : UnitDiamond step) :
    AllLocalPeaksDecreasing step UnitLabelLt := by
  intro peak
  obtain ⟨m, hleft, hright⟩ := hdiamond peak.leftStep peak.rightStep
  refine ⟨{
    leftAfterLow := peak.left
    leftAfterPeakLabel := m
    join := m
    rightAfterLow := peak.right
    rightAfterPeakLabel := m
    leftLow := Relation.ReflTransGen.refl
    leftPeakLabel := hleft
    leftBoth := Relation.ReflTransGen.refl
    rightLow := Relation.ReflTransGen.refl
    rightPeakLabel := hright
    rightBoth := Relation.ReflTransGen.refl
  }⟩

/-! ## A nontrivial diamond fixture -/

inductive DiamondNode
  | top
  | left
  | right
  | bottom
  deriving DecidableEq, Repr

inductive DiamondStep : LabelledStep DiamondNode Unit
  | top_left : DiamondStep () .top .left
  | top_right : DiamondStep () .top .right
  | left_bottom : DiamondStep () .left .bottom
  | right_bottom : DiamondStep () .right .bottom

/-- The four-node fixture has the literal diamond property. -/
theorem diamondStep_unitDiamond : UnitDiamond DiamondStep := by
  intro t s u hts htu
  cases hts <;> cases htu
  · exact ⟨.left, Or.inl rfl, Or.inl rfl⟩
  · exact ⟨.bottom, Or.inr DiamondStep.left_bottom, Or.inr DiamondStep.right_bottom⟩
  · exact ⟨.bottom, Or.inr DiamondStep.right_bottom, Or.inr DiamondStep.left_bottom⟩
  · exact ⟨.right, Or.inl rfl, Or.inl rfl⟩
  · exact ⟨.bottom, Or.inl rfl, Or.inl rfl⟩
  · exact ⟨.bottom, Or.inl rfl, Or.inl rfl⟩

/-- The nontrivial four-node diamond therefore has decreasing local peaks. -/
theorem diamondStep_allLocalPeaksDecreasing :
    AllLocalPeaksDecreasing DiamondStep UnitLabelLt :=
  allLocalPeaksDecreasing_of_unitDiamond diamondStep_unitDiamond

end OperatorKO7.Meta.UniqueNormalization

#check @OperatorKO7.Meta.UniqueNormalization.LabelledStep
#check @OperatorKO7.Meta.UniqueNormalization.StepBelow
#check @OperatorKO7.Meta.UniqueNormalization.StepBelowEither
#check @OperatorKO7.Meta.UniqueNormalization.Star
#check @OperatorKO7.Meta.UniqueNormalization.OptionalLabelStep
#check @OperatorKO7.Meta.UniqueNormalization.LocalPeak
#check @OperatorKO7.Meta.UniqueNormalization.DecreasingValley
#check @OperatorKO7.Meta.UniqueNormalization.LocalPeak.Decreasing
#check @OperatorKO7.Meta.UniqueNormalization.AllLocalPeaksDecreasing
#check @OperatorKO7.Meta.UniqueNormalization.UnitLabelLt
#check @OperatorKO7.Meta.UniqueNormalization.UnitDiamond
#check @OperatorKO7.Meta.UniqueNormalization.allLocalPeaksDecreasing_of_unitDiamond
#check @OperatorKO7.Meta.UniqueNormalization.DiamondNode
#check @OperatorKO7.Meta.UniqueNormalization.DiamondStep
#check @OperatorKO7.Meta.UniqueNormalization.diamondStep_unitDiamond
#check @OperatorKO7.Meta.UniqueNormalization.diamondStep_allLocalPeaksDecreasing

#print axioms OperatorKO7.Meta.UniqueNormalization.allLocalPeaksDecreasing_of_unitDiamond
#print axioms OperatorKO7.Meta.UniqueNormalization.diamondStep_unitDiamond
#print axioms OperatorKO7.Meta.UniqueNormalization.diamondStep_allLocalPeaksDecreasing
