import OperatorKO7.Meta.UniqueNormalization.DecreasingLocalMeasure

/-!
# RTA #79 route R2: whole-prefix downsets and hypothesis decrease

This module ports the load-bearing strict-measure lemma used in the formal
valley proof of decreasing diagrams. For a nonempty input label sequence
`tau`, a measured diagram on `(tau, sigma)` makes the recursive peak formed by
an arbitrary suffix and the corresponding joining output strictly smaller than
`(tau ++ suffix, sigma)`.

The proof is by one direct Dershowitz-Manna witness. Split the recursive peak
measure into labels lying below the downset generated by `tau` and labels that
survive it. The former are jointly replaced by `lexMax tau`; nonemptiness of
`tau` makes that replacement strict. The measured-diagram inequality then
closes the surviving part.

Trust: kernel checked. No external certificate or new axiom.
-/

set_option autoImplicit false

namespace OperatorKO7.Meta.UniqueNormalization

/-- A key lies in the strict downset generated by a label list. -/
def BelowList (labels : List LevelLabel) (x : LevelKey) : Prop :=
  ∃ a ∈ labels, x < a.toKey

/-- Remove every multiset key in the downset generated by a label list. -/
noncomputable def removeBelowList (M : Multiset LevelKey) (labels : List LevelLabel) :
    Multiset LevelKey := by
  classical
  exact M.filter (fun x => ¬ BelowList labels x)

/-- Keep exactly the part of a multiset in the downset generated by a label list. -/
noncomputable def belowListPart (M : Multiset LevelKey) (labels : List LevelLabel) :
    Multiset LevelKey := by
  classical
  exact M.filter (BelowList labels)

@[simp] theorem belowList_nil (x : LevelKey) : ¬ BelowList [] x := by
  intro h
  rcases h with ⟨a, ha, -⟩
  cases ha

@[simp] theorem belowList_cons (a : LevelLabel) (labels : List LevelLabel)
    (x : LevelKey) :
    BelowList (a :: labels) x ↔ x < a.toKey ∨ BelowList labels x := by
  constructor
  · rintro ⟨b, hb, hxb⟩
    rcases List.mem_cons.mp hb with rfl | hb
    · exact Or.inl hxb
    · exact Or.inr ⟨b, hb, hxb⟩
  · rintro (hxa | htail)
    · exact ⟨a, List.mem_cons_self, hxa⟩
    · rcases htail with ⟨b, hb, hxb⟩
      exact ⟨b, List.mem_cons_of_mem _ hb, hxb⟩

/-- The downset part and its complement partition the multiset. -/
theorem belowListPart_add_removeBelowList
    (M : Multiset LevelKey) (labels : List LevelLabel) :
    belowListPart M labels + removeBelowList M labels = M := by
  classical
  simpa [belowListPart, removeBelowList] using
    (Multiset.filter_add_not (p := BelowList labels) M)

/-- Filtering by a generated downset distributes over multiset addition. -/
theorem removeBelowList_add (M N : Multiset LevelKey) (labels : List LevelLabel) :
    removeBelowList (M + N) labels =
      removeBelowList M labels + removeBelowList N labels := by
  classical
  simp [removeBelowList, Multiset.filter_add]

/-- Filtering below a head after filtering below the tail is filtering below the
whole cons list. -/
theorem removeBelow_removeBelowList_eq_cons
    (M : Multiset LevelKey) (a : LevelLabel) (labels : List LevelLabel) :
    removeBelow (removeBelowList M labels) a.toKey =
      removeBelowList M (a :: labels) := by
  classical
  ext x
  simp only [removeBelow, removeBelowList, Multiset.count_filter]
  by_cases hxa : x < a.toKey
  · simp [hxa, BelowList]
  · by_cases htail : BelowList labels x
    · simp [hxa, BelowList]
    · simp [hxa, htail, belowList_cons]

/-- The lexicographic-maximum measure of an append is the prefix measure plus
what survives the prefix-generated downset. -/
theorem lexMax_append (xs ys : List LevelLabel) :
    lexMax (xs ++ ys) = lexMax xs + removeBelowList (lexMax ys) xs := by
  classical
  induction xs with
  | nil =>
      rw [List.nil_append, lexMax_nil, zero_add]
      symm
      change Multiset.filter (fun x => ¬ BelowList [] x) (lexMax ys) = lexMax ys
      apply Multiset.filter_eq_self.mpr
      intro x hx
      exact belowList_nil x
  | cons a xs ih =>
      rw [List.cons_append, lexMax_cons, ih, lexMax_cons]
      simp only [removeBelow, Multiset.filter_add]
      have hcomp := removeBelow_removeBelowList_eq_cons (lexMax ys) a xs
      simp only [removeBelow] at hcomp
      rw [hcomp]
      ac_rfl

/-- Every key below an actual source label is below some key retained by the
lexicographic maximum of the whole nonempty list. -/
theorem exists_mem_lexMax_gt_of_belowList
    {labels : List LevelLabel} {x : LevelKey}
    (hx : BelowList labels x) :
    ∃ z ∈ lexMax labels, x < z := by
  induction labels with
  | nil => exact False.elim (belowList_nil x hx)
  | cons a labels ih =>
      rw [belowList_cons] at hx
      rcases hx with hxa | htail
      · refine ⟨a.toKey, ?_, hxa⟩
        simp [lexMax_cons]
      · obtain ⟨z, hz, hxz⟩ := ih htail
        by_cases hza : z < a.toKey
        · refine ⟨a.toKey, ?_, hxz.trans hza⟩
          simp [lexMax_cons]
        · refine ⟨z, ?_, hxz⟩
          simp only [lexMax_cons, Multiset.mem_add, Multiset.mem_singleton,
            removeBelow, Multiset.mem_filter]
          exact Or.inr ⟨hz, hza⟩

/-- A nonempty label list has a nonempty lexicographic-maximum multiset. -/
theorem lexMax_ne_zero_of_ne_nil {labels : List LevelLabel} (h : labels ≠ []) :
    lexMax labels ≠ 0 := by
  rcases labels with _ | ⟨a, labels⟩
  · contradiction
  · intro hz
    have ha : a.toKey ∈ lexMax (a :: labels) := by simp [lexMax_cons]
    rw [hz] at ha
    exact (Multiset.notMem_zero a.toKey) ha

/-- Replacing every key below the downset of a nonempty list by that list's
lexicographic maximum is a strict Dershowitz-Manna increase. -/
theorem dmLt_replace_belowListPart
    (M : Multiset LevelKey) {labels : List LevelLabel} (hne : labels ≠ []) :
    Multiset.IsDershowitzMannaLT M
      (lexMax labels + removeBelowList M labels) := by
  classical
  let B := belowListPart M labels
  let R := removeBelowList M labels
  have hpart : B + R = M := by
    simpa [B, R] using belowListPart_add_removeBelowList M labels
  refine ⟨R, B, lexMax labels, lexMax_ne_zero_of_ne_nil hne, ?_, ?_, ?_⟩
  · rw [← hpart]
    ac_rfl
  · simp [R, add_comm]
  · intro y hy
    have hyB : y ∈ belowListPart M labels := by simpa [B] using hy
    have hyDown : BelowList labels y :=
      (Multiset.mem_filter.mp (by simpa [belowListPart] using hyB)).2
    exact exists_mem_lexMax_gt_of_belowList hyDown

/-- A strict DM decrease followed by zero or more DM decreases is strict. -/
theorem dmLt_trans_dmLe {M N P : Multiset LevelKey}
    (hMN : Multiset.IsDershowitzMannaLT M N) (hNP : DMLe N P) :
    Multiset.IsDershowitzMannaLT M P := by
  induction hNP with
  | refl => exact hMN
  | tail _ hlast ih => exact Multiset.IsDershowitzMannaLT.trans ih hlast

/-- Adding the same multiset on the right preserves the non-strict DM order. -/
theorem DMLe.add_right (K : Multiset LevelKey) {M N : Multiset LevelKey}
    (h : DMLe M N) : DMLe (M + K) (N + K) := by
  simpa [add_comm] using DMLe.add_left K h

/-- **Lemma 3.6 analogue, left form.** If a measured diagram has a nonempty
left input `tau`, then replacing that input by an arbitrary suffix while keeping
the diagram's left joining output yields a strictly smaller peak. -/
theorem MeasuredJoin.hypothesisDecreaseLeft
    {State : Type*} {step : LabelledStep State LevelLabel}
    {tau sigma : List LevelLabel}
    {x y : State} (D : MeasuredJoin step tau sigma x y)
    (hne : tau ≠ []) (suffix : List LevelLabel) :
    PeakMeasureLt (suffix, D.leftOutput) (tau ++ suffix, sigma) := by
  have hreplace : Multiset.IsDershowitzMannaLT
      (lexMax D.leftOutput + lexMax suffix)
      (lexMax tau +
        removeBelowList (lexMax D.leftOutput + lexMax suffix) tau) :=
    dmLt_replace_belowListPart _ hne
  rw [removeBelowList_add] at hreplace
  have hbound0 : DMLe
      (lexMax (tau ++ D.leftOutput) + removeBelowList (lexMax suffix) tau)
      (peakMeasure (tau, sigma) + removeBelowList (lexMax suffix) tau) :=
    D.leftMeasure.add_right _
  rw [lexMax_append] at hbound0
  have hbound : DMLe
      (lexMax tau +
        (removeBelowList (lexMax D.leftOutput) tau +
          removeBelowList (lexMax suffix) tau))
      (peakMeasure (tau, sigma) + removeBelowList (lexMax suffix) tau) := by
    simpa [add_assoc] using hbound0
  have hstrict := dmLt_trans_dmLe hreplace hbound
  have hstrict' : Multiset.IsDershowitzMannaLT
      (lexMax suffix + lexMax D.leftOutput)
      ((lexMax tau + lexMax sigma) + removeBelowList (lexMax suffix) tau) := by
    simpa [peakMeasure, add_assoc, add_comm, add_left_comm] using hstrict
  change Multiset.IsDershowitzMannaLT
    (lexMax suffix + lexMax D.leftOutput)
    (lexMax (tau ++ suffix) + lexMax sigma)
  rw [lexMax_append]
  simpa only [add_assoc, add_comm, add_left_comm] using hstrict'

/-- **Lemma 3.6 analogue, right/mirrored form.** -/
theorem MeasuredJoin.hypothesisDecreaseRight
    {State : Type*} {step : LabelledStep State LevelLabel}
    {tau sigma : List LevelLabel} {x y : State}
    (D : MeasuredJoin step tau sigma x y)
    (hne : sigma ≠ []) (suffix : List LevelLabel) :
    PeakMeasureLt (D.rightOutput, suffix) (tau, sigma ++ suffix) := by
  have h : DMLe (lexMax (sigma ++ D.rightOutput)) (peakMeasure (sigma, tau)) := by
    simpa [peakMeasure, add_comm] using D.rightMeasure
  let Dfake : MeasuredJoin step sigma tau y x := {
    join := D.join
    leftOutput := D.rightOutput
    rightOutput := D.leftOutput
    leftPath := D.rightPath
    rightPath := D.leftPath
    leftMeasure := h
    rightMeasure := by simpa [peakMeasure, add_comm] using D.leftMeasure
  }
  have hdec := Dfake.hypothesisDecreaseLeft hne suffix
  dsimp [Dfake] at hdec
  change Multiset.IsDershowitzMannaLT
    (lexMax suffix + lexMax D.rightOutput)
    (lexMax (sigma ++ suffix) + lexMax tau) at hdec
  change Multiset.IsDershowitzMannaLT
    (lexMax D.rightOutput + lexMax suffix)
    (lexMax tau + lexMax (sigma ++ suffix))
  simpa [add_comm] using hdec

end OperatorKO7.Meta.UniqueNormalization

#check @OperatorKO7.Meta.UniqueNormalization.BelowList
#check @OperatorKO7.Meta.UniqueNormalization.removeBelowList
#check @OperatorKO7.Meta.UniqueNormalization.belowListPart
#check @OperatorKO7.Meta.UniqueNormalization.lexMax_append
#check @OperatorKO7.Meta.UniqueNormalization.exists_mem_lexMax_gt_of_belowList
#check @OperatorKO7.Meta.UniqueNormalization.lexMax_ne_zero_of_ne_nil
#check @OperatorKO7.Meta.UniqueNormalization.dmLt_replace_belowListPart
#check @OperatorKO7.Meta.UniqueNormalization.dmLt_trans_dmLe
#check @OperatorKO7.Meta.UniqueNormalization.DMLe.add_right
#check @OperatorKO7.Meta.UniqueNormalization.MeasuredJoin.hypothesisDecreaseLeft
#check @OperatorKO7.Meta.UniqueNormalization.MeasuredJoin.hypothesisDecreaseRight

#print axioms OperatorKO7.Meta.UniqueNormalization.lexMax_append
#print axioms OperatorKO7.Meta.UniqueNormalization.exists_mem_lexMax_gt_of_belowList
#print axioms OperatorKO7.Meta.UniqueNormalization.lexMax_ne_zero_of_ne_nil
#print axioms OperatorKO7.Meta.UniqueNormalization.dmLt_replace_belowListPart
#print axioms OperatorKO7.Meta.UniqueNormalization.dmLt_trans_dmLe
#print axioms OperatorKO7.Meta.UniqueNormalization.DMLe.add_right
#print axioms OperatorKO7.Meta.UniqueNormalization.MeasuredJoin.hypothesisDecreaseLeft
#print axioms OperatorKO7.Meta.UniqueNormalization.MeasuredJoin.hypothesisDecreaseRight
