import OperatorKO7.Meta.UniqueNormalization.DecreasingResidualAlgebra

/-!
# RTA #79 route R2: algebra for measured-diagram pasting

This module packages the remaining order-theoretic lemmas used by the formal
proof of decreasing-diagram Lemma 3.5: downset composition, antitonicity of
filtering as the generated downset grows, and addition of a multiset whose
members are dominated by the strict DM replacement witness.

Trust: kernel checked. No external certificate or new axiom.
-/

set_option autoImplicit false

namespace OperatorKO7.Meta.UniqueNormalization

/-- Strict downset generated by a multiset of level keys. -/
def BelowMultiset (M : Multiset LevelKey) (x : LevelKey) : Prop :=
  ∃ z ∈ M, x < z

@[simp] theorem belowList_append (xs ys : List LevelLabel) (x : LevelKey) :
    BelowList (xs ++ ys) x ↔ BelowList xs x ∨ BelowList ys x := by
  constructor
  · rintro ⟨a, ha, hxa⟩
    rcases List.mem_append.mp ha with hx | hy
    · exact Or.inl ⟨a, hx, hxa⟩
    · exact Or.inr ⟨a, hy, hxa⟩
  · rintro (⟨a, ha, hxa⟩ | ⟨a, ha, hxa⟩)
    · exact ⟨a, List.mem_append_left _ ha, hxa⟩
    · exact ⟨a, List.mem_append_right _ ha, hxa⟩

/-- The downset generated by the lexicographic maximum equals the downset of the
source label list. -/
theorem belowMultiset_lexMax_iff_belowList
    (labels : List LevelLabel) (x : LevelKey) :
    BelowMultiset (lexMax labels) x ↔ BelowList labels x := by
  constructor
  · rintro ⟨z, hz, hxz⟩
    obtain ⟨a, ha, rfl⟩ := mem_lexMax_source hz
    exact ⟨a, ha, hxz⟩
  · intro hx
    obtain ⟨z, hz, hxz⟩ := exists_mem_lexMax_gt_of_belowList hx
    exact ⟨z, hz, hxz⟩

/-- Two whole-prefix filters compose by concatenating their generators. -/
theorem removeBelowList_removeBelowList
    (M : Multiset LevelKey) (xs ys : List LevelLabel) :
    removeBelowList (removeBelowList M ys) xs =
      removeBelowList M (xs ++ ys) := by
  classical
  ext x
  simp only [removeBelowList, Multiset.count_filter, belowList_append]
  by_cases hx : BelowList xs x
  · simp [hx]
  · by_cases hy : BelowList ys x
    · simp [hx, hy]
    · simp [hx, hy]

/-- Any submultiset is below the larger multiset in the non-strict DM order. -/
theorem dmLe_of_multiset_le {M N : Multiset LevelKey} (h : M ≤ N) : DMLe M N := by
  obtain ⟨D, hND⟩ := Multiset.le_iff_exists_add.mp h
  by_cases hD : D = 0
  · subst D
    rw [add_zero] at hND
    subst N
    exact DMLe.refl M
  · apply DMLe.of_lt
    refine ⟨M, 0, D, hD, by simp, ?_, ?_⟩
    · simpa [add_comm] using hND
    · intro y hy
      simp at hy

/-- Filtering is antitone in its generated downset: a larger downset removes at
least as many keys and therefore produces a DM-smaller residual. -/
theorem removeBelowList_anti
    (M : Multiset LevelKey) {small big : List LevelLabel}
    (hsub : ∀ x, BelowList small x → BelowList big x) :
    DMLe (removeBelowList M big) (removeBelowList M small) := by
  classical
  apply dmLe_of_multiset_le
  rw [Multiset.le_iff_count]
  intro x
  simp only [removeBelowList, Multiset.count_filter]
  by_cases hbig : BelowList big x
  · simp [hbig]
  · have hsmall : ¬ BelowList small x := fun hs => hbig (hsub x hs)
    simp [hbig, hsmall]

/-- Membership downsets respect multiset addition. -/
@[simp] theorem belowMultiset_add (M N : Multiset LevelKey) (x : LevelKey) :
    BelowMultiset (M + N) x ↔ BelowMultiset M x ∨ BelowMultiset N x := by
  constructor
  · rintro ⟨z, hz, hxz⟩
    rcases Multiset.mem_add.mp hz with hz | hz
    · exact Or.inl ⟨z, hz, hxz⟩
    · exact Or.inr ⟨z, hz, hxz⟩
  · rintro (⟨z, hz, hxz⟩ | ⟨z, hz, hxz⟩)
    · exact ⟨z, Multiset.mem_add.mpr (Or.inl hz), hxz⟩
    · exact ⟨z, Multiset.mem_add.mpr (Or.inr hz), hxz⟩

/-- **Dominated addition, AFP Lemma 2.6.7a analogue.** If `M ≤DM N`, and every
new key is strictly below some key of `N` but below no key of `M`, then all new
keys can be added to `M` without exceeding `N`. -/
theorem DMLe.add_dominated {M N Q : Multiset LevelKey}
    (hMN : DMLe M N)
    (hQ : ∀ q ∈ Q, BelowMultiset N q ∧ ¬ BelowMultiset M q) :
    DMLe (Q + M) N := by
  rcases dmLe_iff_eq_or_lt.mp hMN with hEq | hlt
  · subst N
    have hQzero : Q = 0 := by
      by_contra hne
      obtain ⟨q, hq⟩ := Multiset.exists_mem_of_ne_zero hne
      exact (hQ q hq).2 (hQ q hq).1
    rw [hQzero, zero_add]
  · rcases hlt with ⟨X, Y, Z, hZ, hM, hN, hYZ⟩
    apply DMLe.of_lt
    refine ⟨X, Q + Y, Z, hZ, ?_, hN, ?_⟩
    · rw [hM]
      ac_rfl
    · intro y hy
      rcases Multiset.mem_add.mp hy with hq | hyY
      · obtain ⟨z, hzN, hyz⟩ := (hQ y hq).1
        have hzZ : z ∈ Z := by
          rw [hN] at hzN
          rcases Multiset.mem_add.mp hzN with hzX | hzZ
          · exact False.elim ((hQ y hq).2 ⟨z, by
              rw [hM]
              exact Multiset.mem_add.mpr (Or.inl hzX), hyz⟩)
          · exact hzZ
        exact ⟨z, hzZ, hyz⟩
      · exact hYZ y hyY

end OperatorKO7.Meta.UniqueNormalization

#check @OperatorKO7.Meta.UniqueNormalization.BelowMultiset
#check @OperatorKO7.Meta.UniqueNormalization.belowList_append
#check @OperatorKO7.Meta.UniqueNormalization.belowMultiset_lexMax_iff_belowList
#check @OperatorKO7.Meta.UniqueNormalization.removeBelowList_removeBelowList
#check @OperatorKO7.Meta.UniqueNormalization.dmLe_of_multiset_le
#check @OperatorKO7.Meta.UniqueNormalization.removeBelowList_anti
#check @OperatorKO7.Meta.UniqueNormalization.belowMultiset_add
#check @OperatorKO7.Meta.UniqueNormalization.DMLe.add_dominated

#print axioms OperatorKO7.Meta.UniqueNormalization.belowList_append
#print axioms OperatorKO7.Meta.UniqueNormalization.belowMultiset_lexMax_iff_belowList
#print axioms OperatorKO7.Meta.UniqueNormalization.removeBelowList_removeBelowList
#print axioms OperatorKO7.Meta.UniqueNormalization.dmLe_of_multiset_le
#print axioms OperatorKO7.Meta.UniqueNormalization.removeBelowList_anti
#print axioms OperatorKO7.Meta.UniqueNormalization.belowMultiset_add
#print axioms OperatorKO7.Meta.UniqueNormalization.DMLe.add_dominated
