import OperatorKO7.Meta.InformationalIncompleteness.ShannonFinite
import OperatorKO7.Meta.InformationalIncompleteness.FiniteSupportEntropy
import OperatorKO7.Meta.InformationalIncompleteness.ConditionalEntropy
import Mathlib.Analysis.SpecialFunctions.BinaryEntropy

/-!
# Partial-role information: entropy laws

A deterministic role partition spends the entropy of the observed partition
label and leaves the conditional entropy inside each partition cell. The
construction is finite and includes zero-mass cells by assigning an arbitrary
point-mass conditional there; those cells carry zero outer weight and therefore
contribute no residual entropy. The active/frame laws take an arbitrary active
mass and an arbitrary normalized frame law. `RolePartitionInformation`
identifies the r-ary dependency-pair channel with the active/frame partition;
the declarations here keep that namespace, so their names are unchanged.
-/

set_option autoImplicit false

open scoped BigOperators

namespace OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation

open OperatorKO7.Meta.InformationalIncompleteness.ShannonFinite
open OperatorKO7.Meta.InformationalIncompleteness.ConditionalEntropy
open OperatorKO7.Meta.InformationalIncompleteness.FiniteSupportEntropy

/- The entropy library is Type-0. -/
variable {R : Type} {C : Type}
variable [Fintype R] [Fintype C] [DecidableEq R] [DecidableEq C]

/-- A normalized finite role law. -/
structure RoleLaw (R : Type) [Fintype R] where
  prob : R → ℝ
  nonneg : ∀ r, 0 ≤ prob r
  sum_one : ∑ r, prob r = 1

/-- Mass of one deterministic partition cell. -/
def partitionMass (L : RoleLaw R) (part : R → C) (c : C) : ℝ :=
  ∑ r, if part r = c then L.prob r else 0

omit [Fintype C] [DecidableEq R] in
/-- Partition masses are nonnegative. -/
theorem partitionMass_nonneg (L : RoleLaw R) (part : R → C) (c : C) :
    0 ≤ partitionMass L part c := by
  unfold partitionMass
  apply Finset.sum_nonneg
  intro r _
  split
  · exact L.nonneg r
  · exact le_rfl

omit [DecidableEq R] in
/-- The deterministic partition law remains normalized. -/
theorem partitionMass_sum_one (L : RoleLaw R) (part : R → C) :
    ∑ c, partitionMass L part c = 1 := by
  unfold partitionMass
  rw [Finset.sum_comm]
  calc
    ∑ r, ∑ c, (if part r = c then L.prob r else 0) = ∑ r, L.prob r := by
      apply Finset.sum_congr rfl
      intro r _
      simp
    _ = 1 := L.sum_one

/-- Conditional role law within a partition cell. Zero-mass cells use the
supplied default point mass; their outer weight is zero. -/
noncomputable def withinCell (defaultRole : R) (L : RoleLaw R) (part : R → C) (c : C) : R → ℝ :=
  if partitionMass L part c = 0 then pointMass defaultRole
  else fun r => if part r = c then L.prob r / partitionMass L part c else 0

omit [Fintype C] in
/-- Every within-cell law is nonnegative, including zero-mass cells. -/
theorem withinCell_nonneg
    (defaultRole : R) (L : RoleLaw R) (part : R → C) (c : C) :
    ∀ r, 0 ≤ withinCell defaultRole L part c r := by
  intro r
  by_cases h : partitionMass L part c = 0
  · simp [withinCell, h, pointMass]
    split <;> norm_num
  · simp only [withinCell, h, if_false]
    by_cases hr : part r = c
    · simp [hr]
      exact div_nonneg (L.nonneg r) (partitionMass_nonneg L part c)
    · simp [hr]

omit [Fintype C] in
/-- Every within-cell law is normalized, including zero-mass cells. -/
theorem withinCell_sum_one (defaultRole : R) (L : RoleLaw R) (part : R → C) (c : C) :
    ∑ r, withinCell defaultRole L part c r = 1 := by
  by_cases h : partitionMass L part c = 0
  · simp [withinCell, h, pointMass]
  · simp only [withinCell, h, if_false]
    have hterm : ∀ r : R,
        (if part r = c then L.prob r / partitionMass L part c else 0) =
          (if part r = c then L.prob r else 0) / partitionMass L part c := by
      intro r
      by_cases hr : part r = c <;> simp [hr]
    calc
      (∑ r, if part r = c then L.prob r / partitionMass L part c else 0)
          = ∑ r, (if part r = c then L.prob r else 0) / partitionMass L part c := by
              apply Finset.sum_congr rfl
              intro r _
              exact hterm r
      _ = (∑ r, if part r = c then L.prob r else 0) / partitionMass L part c := by
            rw [Finset.sum_div]
      _ = 1 := by
            change partitionMass L part c / partitionMass L part c = 1
            exact div_self h

/-- Joint law generated by the partition mass and the within-cell conditionals. -/
noncomputable def partitionJoint
    (defaultRole : R) (L : RoleLaw R) (part : R → C) : R × C → ℝ :=
  jointDist (partitionMass L part) (withinCell defaultRole L part)

/-- Direct deterministic graph law on `(role, partition-label)`. -/
def deterministicPartitionJoint (L : RoleLaw R) (part : R → C) : R × C → ℝ :=
  fun rc => if part rc.1 = rc.2 then L.prob rc.1 else 0

omit [Fintype C] [DecidableEq R] in
/-- A role inside a zero-mass partition cell itself has zero mass. -/
theorem role_zero_of_partitionMass_zero
    (L : RoleLaw R) (part : R → C) {r : R} {c : C}
    (hr : part r = c) (hc : partitionMass L part c = 0) : L.prob r = 0 := by
  have hle : L.prob r ≤ partitionMass L part c := by
    unfold partitionMass
    have hnonneg : ∀ u ∈ (Finset.univ : Finset R),
        0 ≤ (if part u = c then L.prob u else 0) := by
      intro u _
      by_cases hu : part u = c <;> simp [hu, L.nonneg u]
    have hs := Finset.single_le_sum hnonneg (show r ∈ (Finset.univ : Finset R) by simp)
    simpa [hr] using hs
  exact le_antisymm (by simpa [hc] using hle) (L.nonneg r)

/-- The conditional construction reconstructs the deterministic joint exactly. -/
theorem partitionJoint_eq_deterministic
    (defaultRole : R) (L : RoleLaw R) (part : R → C) :
    partitionJoint defaultRole L part = deterministicPartitionJoint L part := by
  funext rc
  rcases rc with ⟨r, c⟩
  unfold partitionJoint jointDist deterministicPartitionJoint withinCell
  by_cases hc : partitionMass L part c = 0
  · simp [hc]
    by_cases hr : part r = c
    · simp [hr, role_zero_of_partitionMass_zero L part hr hc]
    · simp [hr]
  · simp [hc]
    by_cases hr : part r = c
    · simp [hr]
      field_simp [hc]
    · simp [hr]

/-- Zero-mass default choices do not change the reconstructed joint law. -/
theorem partitionJoint_default_independent
    (default₁ default₂ : R) (L : RoleLaw R) (part : R → C) :
    partitionJoint default₁ L part = partitionJoint default₂ L part := by
  rw [partitionJoint_eq_deterministic default₁ L part,
    partitionJoint_eq_deterministic default₂ L part]

omit [DecidableEq R] in
/-- Adding the deterministic partition label does not change role entropy. -/
theorem deterministicPartitionJoint_entropy
    (L : RoleLaw R) (part : R → C) :
    H (deterministicPartitionJoint L part) = H L.prob := by
  unfold H deterministicPartitionJoint
  rw [Fintype.sum_prod_type]
  apply Finset.sum_congr rfl
  intro r _
  rw [Finset.sum_eq_single (part r)]
  · simp
  · intro c _ hc
    simp [Ne.symm hc, Real.negMulLog]
  · simp

/-- **Finite deterministic partition chain rule.** The role entropy splits into
partition-label entropy plus residual within-cell entropy. -/
theorem role_partition_entropy_decomposition
    (defaultRole : R) (L : RoleLaw R) (part : R → C) :
    H L.prob =
      H (partitionMass L part) +
        condEntropy (partitionMass L part) (withinCell defaultRole L part) := by
  have hchain := entropy_chain_rule
    (partitionMass L part) (withinCell defaultRole L part)
    (withinCell_sum_one defaultRole L part)
  change H (partitionJoint defaultRole L part) =
    H (partitionMass L part) +
      condEntropy (partitionMass L part) (withinCell defaultRole L part) at hchain
  rw [partitionJoint_eq_deterministic defaultRole L part,
    deterministicPartitionJoint_entropy] at hchain
  exact hchain

/-- Information spent by a deterministic partition, in bits. -/
noncomputable def partitionSpentBits (L : RoleLaw R) (part : R → C) : ℝ :=
  H (partitionMass L part) / Real.log 2

/-- Residual within-partition role entropy, in bits. -/
noncomputable def partitionResidualBits
    (defaultRole : R) (L : RoleLaw R) (part : R → C) : ℝ :=
  condEntropy (partitionMass L part) (withinCell defaultRole L part) / Real.log 2

/-- Role entropy in bits equals spent partition information plus residual role
information. -/
theorem role_partition_bits_decomposition
    (defaultRole : R) (L : RoleLaw R) (part : R → C) :
    HBits L.prob = partitionSpentBits L part +
      partitionResidualBits defaultRole L part := by
  unfold HBits partitionSpentBits partitionResidualBits
  rw [role_partition_entropy_decomposition defaultRole L part]
  ring

/-! ## Nonuniform active/frame specialization -/

/-- Role law on one active role (`0`) plus `r` frame roles. -/
def activeFrameProb {r : Nat} (activeMass : ℝ) (frameLaw : Fin r → ℝ) :
    Fin (r + 1) → ℝ :=
  Fin.cases activeMass (fun i => (1 - activeMass) * frameLaw i)

/-- Active versus frame partition. -/
def activeFramePartition {r : Nat} : Fin (r + 1) → Bool :=
  Fin.cases true (fun _ => false)

/-- A normalized frame law gives a normalized active/frame role law. -/
theorem activeFrameProb_sum_one {r : Nat} (activeMass : ℝ) (frameLaw : Fin r → ℝ)
    (hframe : ∑ i, frameLaw i = 1) :
    ∑ x, activeFrameProb activeMass frameLaw x = 1 := by
  rw [Fin.sum_univ_succ]
  simp only [activeFrameProb, Fin.cases_zero, Fin.cases_succ]
  rw [← Finset.mul_sum, hframe]
  ring

/-- Nonnegativity of the active/frame role law. -/
theorem activeFrameProb_nonneg {r : Nat} (activeMass : ℝ) (frameLaw : Fin r → ℝ)
    (ha0 : 0 ≤ activeMass) (ha1 : activeMass ≤ 1)
    (hf0 : ∀ i, 0 ≤ frameLaw i) :
    ∀ x, 0 ≤ activeFrameProb activeMass frameLaw x := by
  intro x
  refine Fin.cases ha0 (fun i => ?_) x
  exact mul_nonneg (sub_nonneg.mpr ha1) (hf0 i)

/-- Normalized active/frame role law as a `RoleLaw`. -/
def activeFrameRoleLaw {r : Nat} (activeMass : ℝ) (frameLaw : Fin r → ℝ)
    (ha0 : 0 ≤ activeMass) (ha1 : activeMass ≤ 1)
    (hf0 : ∀ i, 0 ≤ frameLaw i) (hframe : ∑ i, frameLaw i = 1) :
    RoleLaw (Fin (r + 1)) where
  prob := activeFrameProb activeMass frameLaw
  nonneg := activeFrameProb_nonneg activeMass frameLaw ha0 ha1 hf0
  sum_one := activeFrameProb_sum_one activeMass frameLaw hframe

/-- Entropy of a nonuniform active/frame role law. -/
theorem H_activeFrameProb {r : Nat} (activeMass : ℝ) (frameLaw : Fin r → ℝ)
    (hframe : ∑ i, frameLaw i = 1) :
    H (activeFrameProb activeMass frameLaw) =
      Real.binEntropy activeMass + (1 - activeMass) * H frameLaw := by
  unfold H activeFrameProb
  rw [Fin.sum_univ_succ]
  simp only [Fin.cases_zero, Fin.cases_succ]
  have hsplit : ∀ i : Fin r,
      Real.negMulLog ((1 - activeMass) * frameLaw i) =
        frameLaw i * Real.negMulLog (1 - activeMass) +
          (1 - activeMass) * Real.negMulLog (frameLaw i) :=
    fun i => negMulLog_mul_total (1 - activeMass) (frameLaw i)
  calc
    Real.negMulLog activeMass +
        ∑ i, Real.negMulLog ((1 - activeMass) * frameLaw i)
      = Real.negMulLog activeMass +
          ∑ i, (frameLaw i * Real.negMulLog (1 - activeMass) +
            (1 - activeMass) * Real.negMulLog (frameLaw i)) := by
            congr 1
            apply Finset.sum_congr rfl
            intro i _
            exact hsplit i
    _ = Real.binEntropy activeMass + (1 - activeMass) * H frameLaw := by
          unfold H
          rw [Finset.sum_add_distrib, ← Finset.sum_mul, hframe, one_mul,
            ← Finset.mul_sum, Real.binEntropy_eq_negMulLog_add_negMulLog_one_sub]
          ring

/-- Information spent by the active-versus-frame decision. -/
noncomputable def activeFrameSpentBits (activeMass : ℝ) : ℝ :=
  Real.binEntropy activeMass / Real.log 2

/-- Frame identity left unresolved after learning only active versus frame. -/
noncomputable def activeFrameResidualBits {r : Nat}
    (activeMass : ℝ) (frameLaw : Fin r → ℝ) : ℝ :=
  (1 - activeMass) * HBits frameLaw

/-- Bit form: active/frame information spent is `h₂(a)` and the unresolved
frame identity is `(1-a) H(frameLaw)`. -/
theorem HBits_activeFrameProb {r : Nat} (activeMass : ℝ) (frameLaw : Fin r → ℝ)
    (hframe : ∑ i, frameLaw i = 1) :
    HBits (activeFrameProb activeMass frameLaw) =
      activeFrameSpentBits activeMass + activeFrameResidualBits activeMass frameLaw := by
  unfold activeFrameSpentBits activeFrameResidualBits
  change H (activeFrameProb activeMass frameLaw) / Real.log 2 =
    Real.binEntropy activeMass / Real.log 2 +
      (1 - activeMass) * (H frameLaw / Real.log 2)
  rw [H_activeFrameProb activeMass frameLaw hframe]
  ring

/-- The partial role channel spends exactly the binary entropy of the active
share. -/
theorem activeFrame_spent_formula (activeMass : ℝ) :
    activeFrameSpentBits activeMass = Real.binEntropy activeMass / Real.log 2 := rfl

/-- The same channel leaves exactly the frame-mass-weighted frame entropy. -/
theorem activeFrame_residual_formula {r : Nat}
    (activeMass : ℝ) (frameLaw : Fin r → ℝ) :
    activeFrameResidualBits activeMass frameLaw =
      (1 - activeMass) * HBits frameLaw := rfl

/-- The active/frame partition itself carries the binary entropy of the active
mass. -/
theorem activeFrame_partitionSpentBits {r : Nat}
    (activeMass : ℝ) (frameLaw : Fin r → ℝ)
    (ha0 : 0 ≤ activeMass) (ha1 : activeMass ≤ 1)
    (hf0 : ∀ i, 0 ≤ frameLaw i) (hframe : ∑ i, frameLaw i = 1) :
    partitionSpentBits
        (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe)
        activeFramePartition = activeFrameSpentBits activeMass := by
  have hmass : partitionMass
      (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe)
      activeFramePartition =
      fun b : Bool => if b then activeMass else 1 - activeMass := by
    funext b
    cases b with
    | false =>
        change partitionMass
          (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe)
          activeFramePartition false = 1 - activeMass
        unfold partitionMass
        rw [Fin.sum_univ_succ]
        simp only [activeFrameRoleLaw, activeFramePartition, activeFrameProb,
          Fin.cases_zero, Fin.cases_succ, Bool.true_eq_false, if_false,
          if_true, zero_add]
        rw [← Finset.mul_sum, hframe]
        ring
    | true =>
        change partitionMass
          (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe)
          activeFramePartition true = activeMass
        unfold partitionMass
        rw [Fin.sum_univ_succ]
        simp [activeFrameRoleLaw, activeFramePartition, activeFrameProb]
  unfold partitionSpentBits activeFrameSpentBits
  rw [hmass]
  unfold H
  rw [Fintype.sum_bool]
  simp
  rw [Real.binEntropy_eq_negMulLog_add_negMulLog_one_sub]

/-- The residual partition information is the frame-mass-weighted frame
entropy. -/
theorem activeFrame_partitionResidualBits {r : Nat}
    (activeMass : ℝ) (frameLaw : Fin r → ℝ)
    (ha0 : 0 ≤ activeMass) (ha1 : activeMass ≤ 1)
    (hf0 : ∀ i, 0 ≤ frameLaw i) (hframe : ∑ i, frameLaw i = 1) :
    partitionResidualBits 0
        (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe)
        activeFramePartition = activeFrameResidualBits activeMass frameLaw := by
  have hsplit := role_partition_bits_decomposition 0
    (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe)
    activeFramePartition
  change HBits (activeFrameProb activeMass frameLaw) =
    partitionSpentBits
      (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe) activeFramePartition +
    partitionResidualBits 0
      (activeFrameRoleLaw activeMass frameLaw ha0 ha1 hf0 hframe) activeFramePartition at hsplit
  rw [activeFrame_partitionSpentBits activeMass frameLaw ha0 ha1 hf0 hframe] at hsplit
  have htotal := HBits_activeFrameProb activeMass frameLaw hframe
  linarith

/-- At active mass one, every frame role has zero probability and residual frame
information vanishes. -/
theorem activeMass_one_residual_zero {r : Nat} (frameLaw : Fin r → ℝ) :
    activeFrameResidualBits 1 frameLaw = 0 := by
  simp [activeFrameResidualBits]

/-- At active mass zero, the active/frame bit spends zero and the complete frame
entropy remains. -/
theorem activeMass_zero_spent_zero :
    activeFrameSpentBits 0 = 0 := by
  simp [activeFrameSpentBits, Real.binEntropy]

/-- At active mass zero the residual is the entire frame entropy. -/
theorem activeMass_zero_residual_all {r : Nat} (frameLaw : Fin r → ℝ) :
    activeFrameResidualBits 0 frameLaw = HBits frameLaw := by
  simp [activeFrameResidualBits]

/-- With zero frame roles and active mass one, the unique role law is a point
mass and carries zero entropy. -/
theorem zero_frames_zero_entropy :
    HBits (activeFrameProb (r := 0) 1 (fun i => Fin.elim0 i)) = 0 := by
  simp [HBits, H, activeFrameProb, Real.negMulLog]

/-- Uniform conditional law on the frame roles. -/
noncomputable def uniformFrameLaw (r : Nat) : Fin r → ℝ := uniformMass (Fin r)

/-- Positive arity gives a normalized uniform frame law. -/
theorem uniformFrameLaw_sum_one {r : Nat} (hr : 1 ≤ r) :
    ∑ i, uniformFrameLaw r i = 1 := by
  letI : Nonempty (Fin r) := Fin.pos_iff_nonempty.mp (by omega)
  exact uniformMass_sum_one (Fin r)

/-- Uniform frame probabilities are nonnegative. -/
theorem uniformFrameLaw_nonneg (r : Nat) : ∀ i, 0 ≤ uniformFrameLaw r i := by
  intro i
  simp [uniformFrameLaw, uniformMass]

/-- The nonuniform active/frame construction specializes to the uniform role
law used by the existing r-ary channel. -/
theorem activeFrameProb_uniform_eq_uniformMass {r : Nat} (hr : 1 ≤ r) :
    activeFrameProb (1 / (r + 1 : ℝ)) (uniformFrameLaw r) =
      uniformMass (Fin (r + 1)) := by
  funext x
  refine Fin.cases ?_ (fun i => ?_) x
  · simp [activeFrameProb, uniformMass]
  · simp [activeFrameProb, uniformFrameLaw, uniformMass]
    have hr0 : (r : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt (by omega : 0 < r))
    field_simp
    ring

/-- The uniform active mass lies in the unit interval at positive arity. -/
theorem uniformActiveMass_mem_unitInterval {r : Nat} (hr : 1 ≤ r) :
    0 ≤ (1 / (r + 1 : ℝ)) ∧ (1 / (r + 1 : ℝ)) ≤ 1 := by
  constructor
  · positivity
  · have hden : (1 : ℝ) ≤ (r + 1 : ℝ) := by
      exact_mod_cast (show 1 ≤ r + 1 by omega)
    exact (div_le_one₀ (show (0 : ℝ) < r + 1 by positivity)).2 hden

/-- Any normalized law on the one-element frame carrier is the point mass. -/
theorem binary_frameLaw_eq_one
    (frameLaw : Fin 1 → ℝ) (hframe : ∑ i, frameLaw i = 1) :
    frameLaw 0 = 1 := by
  simpa using hframe

/-- Any normalized one-frame law has zero entropy. -/
theorem binary_frameLaw_entropy_zero
    (frameLaw : Fin 1 → ℝ) (hframe : ∑ i, frameLaw i = 1) :
    HBits frameLaw = 0 := by
  have h0 := binary_frameLaw_eq_one frameLaw hframe
  unfold HBits H
  simp [h0, Real.negMulLog]

/-- For an arbitrary active mass and any normalized one-frame conditional law,
the active/frame observation resolves the full binary role uncertainty. -/
theorem arbitrary_binary_role_law_resolves_all
    (activeMass : ℝ) (frameLaw : Fin 1 → ℝ)
    (hframe : ∑ i, frameLaw i = 1) :
    HBits (activeFrameProb activeMass frameLaw) = activeFrameSpentBits activeMass := by
  rw [HBits_activeFrameProb activeMass frameLaw hframe,
    activeFrameResidualBits, binary_frameLaw_entropy_zero frameLaw hframe]
  ring

end OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation
