import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityOrders
import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityInterpretations
import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityDependencyPairsSubstrate
import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityLabelingSorted
import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityCalculi
import OperatorKO7.Meta.RDRSTerminationMethodUniverse

/-!
# Method-row hypothesis necessity catalog

Generated by `gen_necessity_catalog.py`. Each row of `allMethodFamilies` has one necessity class
(`rowNecessityKind`), one statement (`RowNecessityStatement`) built from the row's own laws and
acceptance, and one proof (`rowNecessityEvidence`) that calls the row's own theorem.
-/

set_option autoImplicit false

namespace OperatorKO7.Methods.OrientationClosure.HypothesisNecessity

open OperatorKO7.RDRSTerminationMethodUniverse

/-- Necessity class of each method row. -/
def rowNecessityKind : RDRSMethodFamily → RowNecessityKind
  | .standardKBO => standardKBONecessityKind
  | .kboWithStatus => kboWithStatusNecessityKind
  | .generalizedKBO => generalizedKBONecessityKind
  | .subtermCoefficientKBO => subtermCoefficientKBONecessityKind
  | .acKBO => acKBONecessityKind
  | .transfiniteKBO => transfiniteKBONecessityKind
  | .lambdaFreeKBO => lambdaFreeKBONecessityKind
  | .acRPO => acRPONecessityKind
  | .rpoModuloPermutation => rpoModuloPermutationNecessityKind
  | .popStarFamily => popStarFamilyNecessityKind
  | .simpleTerminationOrderType => simpleTerminationOrderTypeNecessityKind
  | .cichonSlowGrowing => cichonSlowGrowingNecessityKind
  | .linearPolyQ => linearPolyQNecessityKind
  | .linearPolyR => linearPolyRNecessityKind
  | .negativeCoefficientPolynomial => negativeCoefficientPolynomialNecessityKind
  | .maxPolynomial => maxPolynomialNecessityKind
  | .nonlinearHigherDegreePolynomial => nonlinearHigherDegreePolynomialNecessityKind
  | .multilinearInterpretation => multilinearInterpretationNecessityKind
  | .matrixNScalarProjection => matrixNScalarProjectionNecessityKind
  | .matrixQRScalarProjection => matrixQRScalarProjectionNecessityKind
  | .arcticScalarProjection => arcticScalarProjectionNecessityKind
  | .tropicalScalarProjection => tropicalScalarProjectionNecessityKind
  | .triangularMatrix => triangularMatrixNecessityKind
  | .tupleInterpretationStrictS => tupleInterpretationStrictSNecessityKind
  | .higherOrderTupleInterpretation => higherOrderTupleInterpretationNecessityKind
  | .polynomialKBO => polynomialKBONecessityKind
  | .strictMonotoneAlgebraArchimedean => strictMonotoneAlgebraArchimedeanNecessityKind
  | .extendedMonotoneAlgebra => extendedMonotoneAlgebraNecessityKind
  | .semanticLabeling => semanticLabelingNecessityKind
  | .predictiveLabeling => predictiveLabelingNecessityKind
  | .rootLabeling => rootLabelingNecessityKind
  | .selfLabelingEquational => selfLabelingEquationalNecessityKind
  | .finiteModelTermination => finiteModelTerminationNecessityKind
  | .categoricalToposTermination => categoricalToposTerminationNecessityKind
  | .forwardClosures => forwardClosuresNecessityKind
  | .matchBounds => matchBoundsNecessityKind
  | .raiseConsistencyMatchBounds => raiseConsistencyMatchBoundsNecessityKind
  | .quasiDecreasingness => quasiDecreasingnessNecessityKind
  | .dpProcessorClassification => dpProcessorClassificationNecessityKind
  | .dpSubtermCriterion => dpSubtermCriterionNecessityKind
  | .dpArgumentFiltering => dpArgumentFilteringNecessityKind
  | .dpReductionPairProcessor => dpReductionPairProcessorNecessityKind
  | .dpNeutralProcessors => dpNeutralProcessorsNecessityKind
  | .dpReductionTriples => dpReductionTriplesNecessityKind
  | .usableRulesMinimality => usableRulesMinimalityNecessityKind
  | .formativeRules => formativeRulesNecessityKind
  | .typeIntroduction => typeIntroductionNecessityKind
  | .manySortedPersistence => manySortedPersistenceNecessityKind
  | .orderSortedDP => orderSortedDPNecessityKind
  | .contextSensitiveDP => contextSensitiveDPNecessityKind
  | .twoDDPForCTRS => twoDDPForCTRSNecessityKind
  | .operationalTerminationCTRS => operationalTerminationCTRSNecessityKind
  | .integerTermRewriting => integerTermRewritingNecessityKind
  | .lctrs => lctrsNecessityKind
  | .higherOrderLCTRS => higherOrderLCTRSNecessityKind
  | .horpoAdmittance => horpoAdmittanceNecessityKind
  | .cpoAdmittance => cpoAdmittanceNecessityKind
  | .generalSchemaAdmittance => generalSchemaAdmittanceNecessityKind
  | .sizedTypesAdmittance => sizedTypesAdmittanceNecessityKind
  | .coqGuardAdmittance => coqGuardAdmittanceNecessityKind
  | .bellantoniCookSplit => bellantoniCookSplitNecessityKind
  | .linearLogicTypingBarrier => linearLogicTypingBarrierNecessityKind
  | .ramifiedRecursionTypingBarrier => ramifiedRecursionTypingBarrierNecessityKind
  | .sharingNonConservativity => sharingNonConservativityNecessityKind
  | .weightedTypeGraphEscape => weightedTypeGraphEscapeNecessityKind
  | .generalizedWeightedTypeGraphs => generalizedWeightedTypeGraphsNecessityKind
  | .equationalQuotientNonConservativity => equationalQuotientNonConservativityNecessityKind
  | .cycleRewritingInapplicability => cycleRewritingInapplicabilityNecessityKind
  | .stringRewritingInapplicability => stringRewritingInapplicabilityNecessityKind
  | .leftLinearMatchBounds => leftLinearMatchBoundsNecessityKind
  | .sizeChangeTerminationEscape => sizeChangeTerminationEscapeNecessityKind
  | .infinitaryRewritingTermination => infinitaryRewritingTerminationNecessityKind
  | .piCalculusTerminationTranslation => piCalculusTerminationTranslationNecessityKind
  | .lambdaMuSNViaCPS => lambdaMuSNViaCPSNecessityKind
  | .abstractInterpretationAdmittance => abstractInterpretationAdmittanceNecessityKind
  | .quasiInterpretationsSharingAware => quasiInterpretationsSharingAwareNecessityKind

/-- Necessity statement of each method row. -/
def RowNecessityStatement : RDRSMethodFamily → Prop
  | .standardKBO => standardKBONecessityStatement
  | .kboWithStatus => kboWithStatusNecessityStatement
  | .generalizedKBO => generalizedKBONecessityStatement
  | .subtermCoefficientKBO => subtermCoefficientKBONecessityStatement
  | .acKBO => acKBONecessityStatement
  | .transfiniteKBO => transfiniteKBONecessityStatement
  | .lambdaFreeKBO => lambdaFreeKBONecessityStatement
  | .acRPO => acRPONecessityStatement
  | .rpoModuloPermutation => rpoModuloPermutationNecessityStatement
  | .popStarFamily => popStarFamilyNecessityStatement
  | .simpleTerminationOrderType => simpleTerminationOrderTypeNecessityStatement
  | .cichonSlowGrowing => cichonSlowGrowingNecessityStatement
  | .linearPolyQ => linearPolyQNecessityStatement
  | .linearPolyR => linearPolyRNecessityStatement
  | .negativeCoefficientPolynomial => negativeCoefficientPolynomialNecessityStatement
  | .maxPolynomial => maxPolynomialNecessityStatement
  | .nonlinearHigherDegreePolynomial => nonlinearHigherDegreePolynomialNecessityStatement
  | .multilinearInterpretation => multilinearInterpretationNecessityStatement
  | .matrixNScalarProjection => matrixNScalarProjectionNecessityStatement
  | .matrixQRScalarProjection => matrixQRScalarProjectionNecessityStatement
  | .arcticScalarProjection => arcticScalarProjectionNecessityStatement
  | .tropicalScalarProjection => tropicalScalarProjectionNecessityStatement
  | .triangularMatrix => triangularMatrixNecessityStatement
  | .tupleInterpretationStrictS => tupleInterpretationStrictSNecessityStatement
  | .higherOrderTupleInterpretation => higherOrderTupleInterpretationNecessityStatement
  | .polynomialKBO => polynomialKBONecessityStatement
  | .strictMonotoneAlgebraArchimedean => strictMonotoneAlgebraArchimedeanNecessityStatement
  | .extendedMonotoneAlgebra => extendedMonotoneAlgebraNecessityStatement
  | .semanticLabeling => semanticLabelingNecessityStatement
  | .predictiveLabeling => predictiveLabelingNecessityStatement
  | .rootLabeling => rootLabelingNecessityStatement
  | .selfLabelingEquational => selfLabelingEquationalNecessityStatement
  | .finiteModelTermination => finiteModelTerminationNecessityStatement
  | .categoricalToposTermination => categoricalToposTerminationNecessityStatement
  | .forwardClosures => forwardClosuresNecessityStatement
  | .matchBounds => matchBoundsNecessityStatement
  | .raiseConsistencyMatchBounds => raiseConsistencyMatchBoundsNecessityStatement
  | .quasiDecreasingness => quasiDecreasingnessNecessityStatement
  | .dpProcessorClassification => dpProcessorClassificationNecessityStatement
  | .dpSubtermCriterion => dpSubtermCriterionNecessityStatement
  | .dpArgumentFiltering => dpArgumentFilteringNecessityStatement
  | .dpReductionPairProcessor => dpReductionPairProcessorNecessityStatement
  | .dpNeutralProcessors => dpNeutralProcessorsNecessityStatement
  | .dpReductionTriples => dpReductionTriplesNecessityStatement
  | .usableRulesMinimality => usableRulesMinimalityNecessityStatement
  | .formativeRules => formativeRulesNecessityStatement
  | .typeIntroduction => typeIntroductionNecessityStatement
  | .manySortedPersistence => manySortedPersistenceNecessityStatement
  | .orderSortedDP => orderSortedDPNecessityStatement
  | .contextSensitiveDP => contextSensitiveDPNecessityStatement
  | .twoDDPForCTRS => twoDDPForCTRSNecessityStatement
  | .operationalTerminationCTRS => operationalTerminationCTRSNecessityStatement
  | .integerTermRewriting => integerTermRewritingNecessityStatement
  | .lctrs => lctrsNecessityStatement
  | .higherOrderLCTRS => higherOrderLCTRSNecessityStatement
  | .horpoAdmittance => horpoAdmittanceNecessityStatement
  | .cpoAdmittance => cpoAdmittanceNecessityStatement
  | .generalSchemaAdmittance => generalSchemaAdmittanceNecessityStatement
  | .sizedTypesAdmittance => sizedTypesAdmittanceNecessityStatement
  | .coqGuardAdmittance => coqGuardAdmittanceNecessityStatement
  | .bellantoniCookSplit => bellantoniCookSplitNecessityStatement
  | .linearLogicTypingBarrier => linearLogicTypingBarrierNecessityStatement
  | .ramifiedRecursionTypingBarrier => ramifiedRecursionTypingBarrierNecessityStatement
  | .sharingNonConservativity => sharingNonConservativityNecessityStatement
  | .weightedTypeGraphEscape => weightedTypeGraphEscapeNecessityStatement
  | .generalizedWeightedTypeGraphs => generalizedWeightedTypeGraphsNecessityStatement
  | .equationalQuotientNonConservativity => equationalQuotientNonConservativityNecessityStatement
  | .cycleRewritingInapplicability => cycleRewritingInapplicabilityNecessityStatement
  | .stringRewritingInapplicability => stringRewritingInapplicabilityNecessityStatement
  | .leftLinearMatchBounds => leftLinearMatchBoundsNecessityStatement
  | .sizeChangeTerminationEscape => sizeChangeTerminationEscapeNecessityStatement
  | .infinitaryRewritingTermination => infinitaryRewritingTerminationNecessityStatement
  | .piCalculusTerminationTranslation => piCalculusTerminationTranslationNecessityStatement
  | .lambdaMuSNViaCPS => lambdaMuSNViaCPSNecessityStatement
  | .abstractInterpretationAdmittance => abstractInterpretationAdmittanceNecessityStatement
  | .quasiInterpretationsSharingAware => quasiInterpretationsSharingAwareNecessityStatement

/-- Every method row satisfies its necessity statement. -/
theorem rowNecessityEvidence : ∀ f : RDRSMethodFamily, RowNecessityStatement f
  | .standardKBO => standardKBO_necessity
  | .kboWithStatus => kboWithStatus_necessity
  | .generalizedKBO => generalizedKBO_necessity
  | .subtermCoefficientKBO => subtermCoefficientKBO_necessity
  | .acKBO => acKBO_necessity
  | .transfiniteKBO => transfiniteKBO_necessity
  | .lambdaFreeKBO => lambdaFreeKBO_necessity
  | .acRPO => acRPO_necessity
  | .rpoModuloPermutation => rpoModuloPermutation_necessity
  | .popStarFamily => popStarFamily_necessity
  | .simpleTerminationOrderType => simpleTerminationOrderType_necessity
  | .cichonSlowGrowing => cichonSlowGrowing_necessity
  | .linearPolyQ => linearPolyQ_necessity
  | .linearPolyR => linearPolyR_necessity
  | .negativeCoefficientPolynomial => negativeCoefficientPolynomial_necessity
  | .maxPolynomial => maxPolynomial_necessity
  | .nonlinearHigherDegreePolynomial => nonlinearHigherDegreePolynomial_necessity
  | .multilinearInterpretation => multilinearInterpretation_necessity
  | .matrixNScalarProjection => matrixNScalarProjection_necessity
  | .matrixQRScalarProjection => matrixQRScalarProjection_necessity
  | .arcticScalarProjection => arcticScalarProjection_necessity
  | .tropicalScalarProjection => tropicalScalarProjection_necessity
  | .triangularMatrix => triangularMatrix_necessity
  | .tupleInterpretationStrictS => tupleInterpretationStrictS_necessity
  | .higherOrderTupleInterpretation => higherOrderTupleInterpretation_necessity
  | .polynomialKBO => polynomialKBO_necessity
  | .strictMonotoneAlgebraArchimedean => strictMonotoneAlgebraArchimedean_necessity
  | .extendedMonotoneAlgebra => extendedMonotoneAlgebra_necessity
  | .semanticLabeling => semanticLabeling_necessity
  | .predictiveLabeling => predictiveLabeling_necessity
  | .rootLabeling => rootLabeling_necessity
  | .selfLabelingEquational => selfLabelingEquational_necessity
  | .finiteModelTermination => finiteModelTermination_necessity
  | .categoricalToposTermination => categoricalToposTermination_necessity
  | .forwardClosures => forwardClosures_necessity
  | .matchBounds => matchBounds_necessity
  | .raiseConsistencyMatchBounds => raiseConsistencyMatchBounds_necessity
  | .quasiDecreasingness => quasiDecreasingness_necessity
  | .dpProcessorClassification => dpProcessorClassification_necessity
  | .dpSubtermCriterion => dpSubtermCriterion_necessity
  | .dpArgumentFiltering => dpArgumentFiltering_necessity
  | .dpReductionPairProcessor => dpReductionPairProcessor_necessity
  | .dpNeutralProcessors => dpNeutralProcessors_necessity
  | .dpReductionTriples => dpReductionTriples_necessity
  | .usableRulesMinimality => usableRulesMinimality_necessity
  | .formativeRules => formativeRules_necessity
  | .typeIntroduction => typeIntroduction_necessity
  | .manySortedPersistence => manySortedPersistence_necessity
  | .orderSortedDP => orderSortedDP_necessity
  | .contextSensitiveDP => contextSensitiveDP_necessity
  | .twoDDPForCTRS => twoDDPForCTRS_necessity
  | .operationalTerminationCTRS => operationalTerminationCTRS_necessity
  | .integerTermRewriting => integerTermRewriting_necessity
  | .lctrs => lctrs_necessity
  | .higherOrderLCTRS => higherOrderLCTRS_necessity
  | .horpoAdmittance => horpoAdmittance_necessity
  | .cpoAdmittance => cpoAdmittance_necessity
  | .generalSchemaAdmittance => generalSchemaAdmittance_necessity
  | .sizedTypesAdmittance => sizedTypesAdmittance_necessity
  | .coqGuardAdmittance => coqGuardAdmittance_necessity
  | .bellantoniCookSplit => bellantoniCookSplit_necessity
  | .linearLogicTypingBarrier => linearLogicTypingBarrier_necessity
  | .ramifiedRecursionTypingBarrier => ramifiedRecursionTypingBarrier_necessity
  | .sharingNonConservativity => sharingNonConservativity_necessity
  | .weightedTypeGraphEscape => weightedTypeGraphEscape_necessity
  | .generalizedWeightedTypeGraphs => generalizedWeightedTypeGraphs_necessity
  | .equationalQuotientNonConservativity => equationalQuotientNonConservativity_necessity
  | .cycleRewritingInapplicability => cycleRewritingInapplicability_necessity
  | .stringRewritingInapplicability => stringRewritingInapplicability_necessity
  | .leftLinearMatchBounds => leftLinearMatchBounds_necessity
  | .sizeChangeTerminationEscape => sizeChangeTerminationEscape_necessity
  | .infinitaryRewritingTermination => infinitaryRewritingTermination_necessity
  | .piCalculusTerminationTranslation => piCalculusTerminationTranslation_necessity
  | .lambdaMuSNViaCPS => lambdaMuSNViaCPS_necessity
  | .abstractInterpretationAdmittance => abstractInterpretationAdmittance_necessity
  | .quasiInterpretationsSharingAware => quasiInterpretationsSharingAware_necessity

/-- Rows of the catalog: the live method universe. -/
def methodCatalogRows : List RDRSMethodFamily := allMethodFamilies

theorem methodCatalogRows_eq : methodCatalogRows = allMethodFamilies := rfl

theorem methodCatalogRows_length : methodCatalogRows.length = 76 :=
  allMethodFamilies_length

theorem methodCatalogRows_nodup : methodCatalogRows.Nodup := allMethodFamilies_nodup

theorem methodCatalogRows_complete : ∀ f : RDRSMethodFamily, f ∈ methodCatalogRows :=
  allMethodFamilies_complete

/-- Rows per necessity class. -/
theorem rowNecessityKind_counts :
    (methodCatalogRows.filter (fun f => rowNecessityKind f = .deletedBarrierPremise)).length = 14 ∧
    (methodCatalogRows.filter (fun f => rowNecessityKind f = .lawFreeBarrierControl)).length = 7 ∧
    (methodCatalogRows.filter (fun f => rowNecessityKind f = .deletedEscapeFeature)).length = 42 ∧
    (methodCatalogRows.filter (fun f => rowNecessityKind f = .noApplicableHypothesis)).length = 13 := by
  decide

end OperatorKO7.Methods.OrientationClosure.HypothesisNecessity
