import OperatorKO7.Meta.BarrierPumpDischarge

/-!
# Reach gate: pump discharge (schema layer and KO7 specializations)

Pins every public declaration of the modules listed below with a paired
`#check @name` and `#print axioms name`. Source-to-reach and reach-to-axiom
differences are empty by construction: this file is generated from the
namespace-aware declaration inventory of those sources. Every axiom closure must
be a subset of `{propext, Classical.choice, Quot.sound}` and no closure may
mention `sorryAx`. This gate is import-and-check only; it proves no new content.

* `OperatorKO7/Meta/BarrierPumpDischarge_Schema.lean`: 59 public declarations
* `OperatorKO7/Meta/BarrierPumpDischarge.lean`: 21 public declarations
-/

set_option autoImplicit false

namespace OperatorKO7.Test.BarrierPumpDischargeReach

-- OperatorKO7/Meta/BarrierPumpDischarge_Schema.lean
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrapDouble
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrapDouble
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrapDouble_zero
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrapDouble_zero
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrapDouble_succ
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrapDouble_succ
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_affine
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_affine
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.affine_hasUnboundedRange_of_exists_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.affine_hasUnboundedRange_of_exists_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.affine_zero_or_hasUnboundedRange
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.affine_zero_or_hasUnboundedRange
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_affine_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_affine_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_affine_primary_nonstrict_orients_dup_step_of_exists_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_affine_primary_nonstrict_orients_dup_step_of_exists_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.zeroAffineMeasure
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.zeroAffineMeasure
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.zeroAffineMeasure_nonstrict_orients
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.zeroAffineMeasure_nonstrict_orients
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.nonstrict_affine_barrier_positivity_premise_necessary
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.nonstrict_affine_barrier_positivity_premise_necessary
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_affine
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_affine
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.global_orienter_not_affine_representable
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.global_orienter_not_affine_representable
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_quadratic
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_quadratic
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.quadratic_hasUnboundedRange_of_exists_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.quadratic_hasUnboundedRange_of_exists_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_quadratic_counter_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_quadratic_counter_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_quadratic
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_quadratic
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.global_orienter_not_quadratic_representable
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.global_orienter_not_quadratic_representable
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_cross
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_cross
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.crossTerm_hasUnboundedRange_of_exists_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.crossTerm_hasUnboundedRange_of_exists_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_cross_quadratic_orients_dup_step_of_bounded
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_cross_quadratic_orients_dup_step_of_bounded
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_cross_quadratic_of_bounded
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_cross_quadratic_of_bounded
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_multilinear
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_multilinear
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.multilinear_hasUnboundedRange_of_exists_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.multilinear_hasUnboundedRange_of_exists_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_multilinear_orients_dup_step_of_dominated
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_multilinear_orients_dup_step_of_dominated
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_multilinear_of_dominated
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_multilinear_of_dominated
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_poly
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_poly
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.polynomial_hasUnboundedRange_of_exists_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.polynomial_hasUnboundedRange_of_exists_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_polynomial_orients_dup_step_of_dominated
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_polynomial_orients_dup_step_of_dominated
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.polynomial_orienter_violates_base_dominance
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.polynomial_orienter_violates_base_dominance
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_polynomial_of_dominated
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_polynomial_of_dominated
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_wpoPolynomialDirect_orients_dup_step_of_dominated
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_wpoPolynomialDirect_orients_dup_step_of_dominated
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_wpoPolynomialDirect_of_dominated
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_wpoPolynomialDirect_of_dominated
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_max
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_ge_max
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.max_hasUnboundedRange
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.max_hasUnboundedRange
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_max_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_max_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_max
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_max
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_arctic_primary_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_arctic_primary_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_tropical_primary_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_tropical_primary_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_orients_dup_step_of_projected_primary_dominance_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_orients_dup_step_of_projected_primary_dominance_of_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_orients_dup_step_of_projected_primary_strict
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_orients_dup_step_of_projected_primary_strict
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_of_projected_primary_dominance_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_of_projected_primary_dominance_of_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_of_projected_primary_strict
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_of_projected_primary_strict
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixD_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixD_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixD
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixD
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrix2_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrix2_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrix2
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrix2
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrix2_lex_orients_dup_step_of_fst_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrix2_lex_orients_dup_step_of_fst_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrix2_lex_of_fst_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrix2_lex_of_fst_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixFunctional_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixFunctional_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixFunctional
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixFunctional
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixMix2_orients_dup_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixMix2_orients_dup_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixMix2
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixMix2
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixLexD_orients_dup_step_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixLexD_orients_dup_step_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixLexD_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixLexD_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixLexPermD_orients_dup_step_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixLexPermD_orients_dup_step_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixLexPermD_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixLexPermD_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixArbitrary_orients_dup_step_of_scalar_dominance_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_matrixArbitrary_orients_dup_step_of_scalar_dominance_of_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixArbitrary_of_scalar_dominance_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_matrixArbitrary_of_scalar_dominance_of_pos

-- OperatorKO7/Meta/BarrierPumpDischarge.lean
#check @OperatorKO7.BarrierPumpDischarge.no_affine_compositional_orients_rec_succ
#print axioms OperatorKO7.BarrierPumpDischarge.no_affine_compositional_orients_rec_succ
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_affine
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_affine
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_quadratic
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_quadratic
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_cross_quadratic_of_bounded
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_cross_quadratic_of_bounded
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_multilinear_of_dominated
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_multilinear_of_dominated
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_polynomial_of_dominated
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_polynomial_of_dominated
#check @OperatorKO7.BarrierPumpDischarge.polynomial_orienter_violates_base_dominance
#print axioms OperatorKO7.BarrierPumpDischarge.polynomial_orienter_violates_base_dominance
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_wpoPolynomialDirect_of_dominated
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_wpoPolynomialDirect_of_dominated
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_max
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_max
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_arctic_primary
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_arctic_primary
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_tropical_primary
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_tropical_primary
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixD
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixD
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix2
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix2
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix2_lex_of_fst_pos
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix2_lex_of_fst_pos
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixFunctional
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixFunctional
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixMix2
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixMix2
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixLexD_of_primary_pos
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixLexD_of_primary_pos
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixLexPermD_of_primary_pos
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixLexPermD_of_primary_pos
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixArbitrary_of_scalar_dominance_of_pos
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrixArbitrary_of_scalar_dominance_of_pos
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix_fixed_row
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix_fixed_row
#check @OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix_row_sum
#print axioms OperatorKO7.BarrierPumpDischarge.no_global_step_orientation_matrix_row_sum

end OperatorKO7.Test.BarrierPumpDischargeReach
