import OperatorKO7.Meta.OperationalInexpressibility.BethDefinability

/-! Full reach and axiom coverage for the `BethDefinability` module. Permanent. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ExplicitlyDefines
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.BethPropertyOn
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.PostcompositionClosed
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.licensed_of_explicitlyDefines
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.not_explicitlyDefines_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.not_explicitlyDefines_iff_not_licensed
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.bethPropertyOn_of_complete
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.padoa_sound_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.beth_complete_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.identityStatementLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.beth_postcomposition_is_required

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.licensed_of_explicitlyDefines
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.not_explicitlyDefines_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.not_explicitlyDefines_iff_not_licensed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.bethPropertyOn_of_complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.padoa_sound_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.beth_complete_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.beth_postcomposition_is_required
