import OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances

/-! Full reach and axiom coverage for the `BethDefinabilityInstances` module. Permanent. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.Orienting
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.grammarLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.projectionLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.grammar_fullReading_not_bethProperty
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.grammar_counter_sound_on_orienting
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.measureExpr_eval_mono_counter
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.measureExpr_double_step
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.bethGap
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.bethGap_orienting
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.bethGap_not_grammar_denotable
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.grammar_counter_not_bethProperty
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.projection_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.projection_bethProperty_on_orienting
#check @OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.projection_explicitlyDefines_iff_licensed

#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.grammar_fullReading_not_bethProperty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.grammar_counter_sound_on_orienting
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.measureExpr_eval_mono_counter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.measureExpr_double_step
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.bethGap_orienting
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.bethGap_not_grammar_denotable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.grammar_counter_not_bethProperty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.projection_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.projection_bethProperty_on_orienting
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BethDefinabilityInstances.projection_explicitlyDefines_iff_licensed
