import OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic

/-! Reach and axiom check for the `
BlackwellStochastic
` module. Permanent. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_iff_dominates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_iff_dominates
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_ofObserver_iff_refines
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_ofObserver_iff_refines
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.nonempty_output_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.nonempty_output_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.noisy_isGarbling_perfect_not_conversely
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.noisy_isGarbling_perfect_not_conversely

/-! ## Complete public-surface reach and axiom parity -/

#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.decisionValue
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.IsGarbling
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.Dominates
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominates_of_isGarbling
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.garblingPoint
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.experimentPoint
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_of_mem_convexHull
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.continuousLinearMap_apply_eq_sum
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_of_dominates
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.ofObserver
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.ofRational
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.gainVulnerability
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominates_iff_gainVulnerability_le
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.noisyBinaryExperiment
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.kernel
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.zeroOneUtility
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.decisionValue_ofObserver_zeroOne
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.DominatesZeroOne
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominatesZeroOne_of_dominates
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominatesZeroOne_ofObserver_iff_refines
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominatesZeroOne_ofObserver_iff_bayesRisk_le
#check @OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_ofObserver_iff_bayesRisk_le

#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.zeroOneUtility
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.decisionValue_ofObserver_zeroOne
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.DominatesZeroOne
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominatesZeroOne_of_dominates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominatesZeroOne_ofObserver_iff_refines
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominatesZeroOne_ofObserver_iff_bayesRisk_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_ofObserver_iff_bayesRisk_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.decisionValue
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.IsGarbling
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.Dominates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominates_of_isGarbling
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.garblingPoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.experimentPoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_of_mem_convexHull
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.continuousLinearMap_apply_eq_sum
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.isGarbling_of_dominates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.ofObserver
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.ofRational
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.gainVulnerability
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.dominates_iff_gainVulnerability_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.noisyBinaryExperiment
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.kernel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BlackwellStochastic.RealExperiment.sum_one
