import OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.BudgetedNoisyRecoveryReach

#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.budgetedSideEncoderCandidates
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.mem_budgetedSideEncoderCandidates_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_feasible
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_minimal
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.budgetedSideEncoderCandidates_mono
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_risk_antitone
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.zeroEncoderCost
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.zeroEncoderCost_candidates
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.oneEncoderCost
#check @OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.oneEncoderCost_zero_candidates

#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.budgetedSideEncoderCandidates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.mem_budgetedSideEncoderCandidates_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_feasible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_minimal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.budgetedSideEncoderCandidates_mono
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.bestBudgetedSideEncoder?_risk_antitone
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.zeroEncoderCost
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.zeroEncoderCost_candidates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.oneEncoderCost
#print axioms OperatorKO7.Meta.OperationalInexpressibility.BudgetedNoisyRecovery.oneEncoderCost_zero_candidates

end OperatorKO7.Test.BudgetedNoisyRecoveryReach
