import OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet

/-! Permanent reach and axiom audit for `CertificateAcceptedSet`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeNatPadded
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeWordsPadded
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.serializeBitsPadded
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeNatPadded_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeWordsPadded_replicate_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.serializeBitsPadded_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.bitsToNat_replicate_false
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.bitsToNat_append_replicate_false
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.bits_bitsToNat_append_replicate
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.decodeCompactWidth_eq_some_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.decodeNatCompact_eq_some_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.decodeWordsCompact_eq_some_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.ruleCode_of_decodeRuleCode
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.eq_serialize_of_deserialize
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.deserialize_eq_some_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.check_eq_true_iff_buildCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.deserializeBitsPrefix_eq_some_nil_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.checkSerializedBitsStrict_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.deserializeBitsPrefix_of_checkSerializedBitsStrict
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeNatPadded_length
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeWordsPadded_length
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.serializeBitsPadded_length
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.eq_replicate_zero_of_sum_eq_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.checkSerializedBitsStrict_length_canonical
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.padded_successorCertificate_accepted

#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeNatPadded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeWordsPadded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.serializeBitsPadded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeNatPadded_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeWordsPadded_replicate_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.serializeBitsPadded_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.bitsToNat_replicate_false
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.bitsToNat_append_replicate_false
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.bits_bitsToNat_append_replicate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.decodeCompactWidth_eq_some_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.decodeNatCompact_eq_some_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.decodeWordsCompact_eq_some_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.ruleCode_of_decodeRuleCode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.eq_serialize_of_deserialize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.deserialize_eq_some_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.check_eq_true_iff_buildCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.deserializeBitsPrefix_eq_some_nil_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.checkSerializedBitsStrict_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.deserializeBitsPrefix_of_checkSerializedBitsStrict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeNatPadded_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.encodeWordsPadded_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.serializeBitsPadded_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.eq_replicate_zero_of_sum_eq_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.checkSerializedBitsStrict_length_canonical
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.padded_successorCertificate_accepted
