import OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine

/-! Permanent reach and axiom audit for `CertificateBitMachine`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.FieldSlot
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitPhase
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitState
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitPhase.isHalted
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.startWords
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.fieldDone
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.finishField
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitStep
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitInit
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBits
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitReaches
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.phaseRank
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.wordStreamRuntime
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.streamOutput
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.phaseRank_le_two
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.startWords_facts
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.fieldDone_facts
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.finishField_facts
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitMeasure_bitStep_lt
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitStep_of_isHalted
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitStep_input
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_input_suffix
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_of_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBits_halted
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBits_eq_of_bitReaches
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_width_some
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_width_none
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_payload_some
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_payload_none
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_field_some
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_field_none
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_words_some
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_words_none
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_wordStream
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_eq_of_wordStream
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.deserializeBitsPrefixRuntimeWork_eq_wordStream
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_deserializeBitsPrefixRuntimeWork
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_deserialize_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.deserializeBitsPrefixRuntimeWork_eq_machine
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_serializeBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_nil
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_width
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_truncated_width
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_payload

#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.FieldSlot
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitPhase
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitState
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitPhase.isHalted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.startWords
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.fieldDone
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.finishField
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitInit
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.BitReaches
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.phaseRank
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.wordStreamRuntime
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.streamOutput
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.phaseRank_le_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.startWords_facts
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.fieldDone_facts
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.finishField_facts
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitMeasure_bitStep_lt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitStep_of_isHalted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitStep_input
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_input_suffix
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_of_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBits_halted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBits_eq_of_bitReaches
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_width_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_width_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_payload_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_payload_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_field_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_field_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_words_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_words_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_wordStream
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_eq_of_wordStream
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.deserializeBitsPrefixRuntimeWork_eq_wordStream
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.bitReaches_deserializeBitsPrefixRuntimeWork
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_deserialize_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.deserializeBitsPrefixRuntimeWork_eq_machine
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_serializeBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_nil
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_width
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_truncated_width
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_payload
