import OperatorKO7.Meta.OperationalInexpressibility.CertificateCodecCore

/-! Permanent reach and axiom audit for `CertificateCodecCore`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.natBitLength
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatPayloadWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_success
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_none
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_eq_some_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits_encodeNatBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits_encodeWordsBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth_encode_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat_bits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth_eq_payloadWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact_encode_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact_encode_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_none
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_snd_le_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits_pos

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.natBitLength
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatPayloadWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_success
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_eq_some_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits_encodeNatBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits_encodeWordsBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth_encode_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat_bits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth_eq_payloadWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact_encode_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact_encode_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_snd_le_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits_pos
