import OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening

/-! Permanent reach and axiom audit for `ClaimStrengthening`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projectionTransaction_ext
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projectionFamily_constant_of_license_constant
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordGenerator_eq_gen
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordGenerator_subsingleton
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.generator_bridge_unique
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.lcelQuasiFunctor_subsingleton
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.lcelComparisonWitness_subsingleton
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.cumCellMassDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.cumCellMass
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.cumCellMassDoubled_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCostDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCost
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCostDoubled_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCostDoubled_identity
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCost_identity
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCost_ge
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projBits
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projBits_spec
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.index_succ_lt_two_pow
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.explicitDescriptionLength_lt_repeatedCarrierMass
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.repeatedCarrierMass_lt_explicitDescriptionLength_at_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.SortedRecord
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.framePow
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.sortedRecord
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordDepth
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordBase
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordPayload
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordDepth_sortedRecord
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordBase_sortedRecord
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordPayload_sortedRecord
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.sortedRecord_injective
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.sortedRecord_zero_forgets_payload
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.framePow_frame
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.unsorted_depth_base_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.depth_sq_mul_payload_le_confessedBurdenDoubled

#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projectionTransaction_ext
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projectionFamily_constant_of_license_constant
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordGenerator_eq_gen
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordGenerator_subsingleton
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.generator_bridge_unique
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.lcelQuasiFunctor_subsingleton
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.lcelComparisonWitness_subsingleton
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.cumCellMassDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.cumCellMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.cumCellMassDoubled_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCostDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCost
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCostDoubled_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCostDoubled_identity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCost_identity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.bitCost_ge
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.projBits_spec
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.index_succ_lt_two_pow
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.explicitDescriptionLength_lt_repeatedCarrierMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.repeatedCarrierMass_lt_explicitDescriptionLength_at_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.SortedRecord
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.framePow
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.sortedRecord
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordDepth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordBase
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordPayload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordDepth_sortedRecord
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordBase_sortedRecord
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.recordPayload_sortedRecord
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.sortedRecord_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.sortedRecord_zero_forgets_payload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.framePow_frame
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.unsorted_depth_base_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ClaimStrengthening.depth_sq_mul_payload_le_confessedBurdenDoubled
