import OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport

/-! Permanent reach and axiom audit for `ConfluenceTransport`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.RelationConfluent
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.eq_of_relationNormal_of_reflTransGen
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.exists_relationNormal_of_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_wellFounded_and_relationUNred
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.relationUNred_of_relationConfluent
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.relationConfluent_iff_relationUNred_of_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_transports
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_wellFounded_and_UNconv
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.terminating_confluent_iff_UNconv
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.terminating_confluent_iff_UNred
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_TRS_transports
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.TriStep
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.DuoStep
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triToDuo
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triStep_normal_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.duoStep_normal_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.duoStep_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.duoStep_relationUNred
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triToDuoStuttering
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triToDuo_stepStarSimulation
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triStep_confluent_by_transport
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.forkStep_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.uniqueness_is_required_for_confluence

#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.RelationConfluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.eq_of_relationNormal_of_reflTransGen
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.exists_relationNormal_of_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_wellFounded_and_relationUNred
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.relationUNred_of_relationConfluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.relationConfluent_iff_relationUNred_of_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_transports
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_wellFounded_and_UNconv
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.terminating_confluent_iff_UNconv
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.terminating_confluent_iff_UNred
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.confluent_of_TRS_transports
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.TriStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.DuoStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triToDuo
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triStep_normal_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.duoStep_normal_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.duoStep_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.duoStep_relationUNred
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triToDuoStuttering
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triToDuo_stepStarSimulation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.triStep_confluent_by_transport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.forkStep_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.uniqueness_is_required_for_confluence
