import OperatorKO7.Meta.ConstructionRouteCatalog_Audit

namespace ConstructionRouteCatalogCertificateReach

open OperatorKO7.ConstructionRouteCatalog
open OperatorKO7.ConstructionRouteCatalogAudit
open OperatorKO7.ConstructionRouteCatalogCertificate

#check CanonicalConstructionCertificate
#check canonical_construction_certificate
#check canonical_construction_certificate_projects_route_catalog
#check canonical_construction_certificate_projects_payload_catalog
#check canonical_construction_certificate_projects_w1_imports
#check canonical_construction_certificate_projects_w2_transforms
#check canonical_construction_certificate_projects_fullDuplicating_separation
#check canonicalConstructionWitnesses
#check CanonicalWitnessHasPayload
#check canonicalConstructionWitnesses_complete
#check canonical_witness_has_payload
#check canonical_witness_has_payload_and_non_w0
#check canonical_construction_audit_catalog
#check canonical_construction_certificate_implies_audit_catalog

example : CanonicalConstructionWitness.w1Transparency ∈ canonicalConstructionWitnesses := by
  exact canonicalConstructionWitnesses_complete _

example : CanonicalConstructionAuditCatalog := by
  exact canonical_construction_certificate_implies_audit_catalog canonical_construction_certificate

end ConstructionRouteCatalogCertificateReach
