import OperatorKO7.Meta.ContextClosedBarrier_PumpDischarge

/-!
# Reach gate: context-closed lifts of the pump-discharged barriers

Pins every public declaration of the modules listed below with a paired
`#check @name` and `#print axioms name`. Source-to-reach and reach-to-axiom
differences are empty by construction: this file is generated from the
namespace-aware declaration inventory of those sources. Every axiom closure must
be a subset of `{propext, Classical.choice, Quot.sound}` and no closure may
mention `sorryAx`. This gate is import-and-check only; it proves no new content.

* `OperatorKO7/Meta/ContextClosedBarrier_PumpDischarge.lean`: 26 public declarations
-/

set_option autoImplicit false

namespace OperatorKO7.Test.ContextClosedBarrierPumpDischargeReach

-- OperatorKO7/Meta/ContextClosedBarrier_PumpDischarge.lean
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_affine
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_affine
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_quadratic
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_quadratic
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_cross_quadratic_of_bounded
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_cross_quadratic_of_bounded
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_multilinear_of_dominated
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_multilinear_of_dominated
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_polynomial_of_dominated
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_polynomial_of_dominated
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_wpoPolynomialDirect_of_dominated
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_wpoPolynomialDirect_of_dominated
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_max
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_max
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_arctic_primary
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_arctic_primary
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_tropical_primary
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_tropical_primary
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixD
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixD
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix2
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix2
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix2_lex_of_fst_pos
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix2_lex_of_fst_pos
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixFunctional
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixFunctional
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixMix2
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixMix2
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixLexD_of_primary_pos
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixLexD_of_primary_pos
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixLexPermD_of_primary_pos
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixLexPermD_of_primary_pos
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixArbitrary_of_scalar_dominance_of_pos
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixArbitrary_of_scalar_dominance_of_pos
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix_fixed_row
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix_fixed_row
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix_row_sum
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrix_row_sum
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_of_tracked_strict
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_of_tracked_strict
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_of_tracked_nonincreasing
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_of_tracked_nonincreasing
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_componentwise
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_componentwise
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_ewz
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_ewz
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_lexD_of_primary_pos
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_lexD_of_primary_pos
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_lexPermD_of_primary_pos
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_naturalMatrix_lexPermD_of_primary_pos
#check @OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixArbitrary_unit_certificateFree
#print axioms OperatorKO7.ContextClosedBarrierPumpDischarge.no_stepCtxFull_orientation_matrixArbitrary_unit_certificateFree

end OperatorKO7.Test.ContextClosedBarrierPumpDischargeReach
