import OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.CostWorkloadSemanticsReach

#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.directIncrementDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.cachedTraceCarryDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.cachedTraceCarryDoubled_eq_directCarryCostDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_eq_cumulativeCarryDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.cachedTraceCarryDoubled_closed
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_closed
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_succ
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_gt_cached_of_positive
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.zero_payload_workloads
#check @OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.workload_growth_pair

#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.directIncrementDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.cachedTraceCarryDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.cachedTraceCarryDoubled_eq_directCarryCostDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_eq_cumulativeCarryDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.cachedTraceCarryDoubled_closed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_closed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_succ
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.repeatedPrefixCarryDoubled_gt_cached_of_positive
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.zero_payload_workloads
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostWorkloadSemantics.workload_growth_pair

end OperatorKO7.Test.CostWorkloadSemanticsReach
