import OperatorKO7.Meta.OperationalInexpressibility.CostComparison

set_option autoImplicit false

namespace OperatorKO7.Test.CostComparisonReach

/-! Current public source surface, including generated structure projections and inductive constructors, for supervisor validation. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.WeakCrossing
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostTie
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingDecidable
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costTieDecidable
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossing_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costTie_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder.carryCheaper
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder.tie
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder.confessCheaper
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden_eq_carryCheaper_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden_eq_tie_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden_eq_confessCheaper_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_tie_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_never_strict
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.tie_depth_unique_of_payload_pos
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weak_crossing_exists
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_spec
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_least
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint?
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.strictCrossingPoint?
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint?_eq_some
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.strictCrossingPoint?_eq_some
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint?_zero_payload
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.strictCrossingPoint?_zero_payload
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_le_crossingPoint
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_le_weakCrossingPoint_succ
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_eq_weak_succ_of_tie
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_eq_weak_of_strict
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weak_tie_iff_strict_threshold_next
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costDifferenceDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costDifferenceDoubled_strict_growth
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled_succ
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled_succ
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled_closed
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled_closed
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.burdenRatio?
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.burdenRatio?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.burdenRatio?_isSome_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.carryResidualRatio?
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.carryResidualRatio?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.carryResidualRatio?_eq_some_of_pos
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostAction
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostAction.carry
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostAction.confess
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.optimalActions
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.optimalActions_tie
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.TieBreakPolicy
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.TieBreakPolicy.preferCarry
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.TieBreakPolicy.preferConfess
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.chooseOptimal
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.chooseOptimal_mem_optimalActions
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.tieBreakPolicies_differ_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.finite_horizon_stop_iff_edge_bound
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.positive_price_binary_stopping_region
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_gain_alone_not_a_stopping_rule

#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.WeakCrossing
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostTie
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingDecidable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costTieDecidable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossing_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costTie_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder.carryCheaper
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder.tie
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.BurdenOrder.confessCheaper
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden_eq_carryCheaper_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden_eq_tie_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.compareBurden_eq_confessCheaper_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_tie_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_never_strict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.tie_depth_unique_of_payload_pos
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weak_crossing_exists
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_spec
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_least
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.strictCrossingPoint?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint?_eq_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.strictCrossingPoint?_eq_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint?_zero_payload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.strictCrossingPoint?_zero_payload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_le_crossingPoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_le_weakCrossingPoint_succ
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_eq_weak_succ_of_tie
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_eq_weak_of_strict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weak_tie_iff_strict_threshold_next
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costDifferenceDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.costDifferenceDoubled_strict_growth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled_succ
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled_succ
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeCarryDoubled_closed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.cumulativeConfessDoubled_closed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.burdenRatio?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.burdenRatio?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.burdenRatio?_isSome_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.carryResidualRatio?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.carryResidualRatio?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.carryResidualRatio?_eq_some_of_pos
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostAction
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostAction.carry
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.CostAction.confess
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.optimalActions
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.optimalActions_tie
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.TieBreakPolicy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.TieBreakPolicy.preferCarry
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.TieBreakPolicy.preferConfess
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.chooseOptimal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.chooseOptimal_mem_optimalActions
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.tieBreakPolicies_differ_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.finite_horizon_stop_iff_edge_bound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.positive_price_binary_stopping_region
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_gain_alone_not_a_stopping_rule
end OperatorKO7.Test.CostComparisonReach
