import OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification

/-! Permanent reach and axiom audit for `DefinitionUnification`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.DimensionPresent
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.DependsOnDimension
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ConstrainsTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.LanguageInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ContextCollision
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.LicensedInContext
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ObserverInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.Sound
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.Complete
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ObserverSeesDimension
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.contextCollision_iff_not_licensedInContext
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.licensedInContext_iff_licensed_of_total
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.contextCollision_iff_unlicensed_of_total
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.not_constrainsTarget_of_contextCollision
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.languageInexpressible_of_observerInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.exists_incorporating_statement_of_not_contextCollision
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.observerInexpressible_of_languageInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.operationalInexpressibility_language_iff_observer
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.languageInexpressible_iff_unlicensed_of_total
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.noIncorporation_iff_constraining_licensed_by_forgetful
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.blindObserverLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.observerSeesDimension_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.constantStatementLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.complete_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.unsoundStatementLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.sound_is_required

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.DimensionPresent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.DependsOnDimension
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ConstrainsTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.LanguageInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ContextCollision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.LicensedInContext
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ObserverInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.Sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.Complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ObserverSeesDimension
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.contextCollision_iff_not_licensedInContext
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.licensedInContext_iff_licensed_of_total
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.contextCollision_iff_unlicensed_of_total
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.not_constrainsTarget_of_contextCollision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.languageInexpressible_of_observerInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.exists_incorporating_statement_of_not_contextCollision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.observerInexpressible_of_languageInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.operationalInexpressibility_language_iff_observer
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.languageInexpressible_iff_unlicensed_of_total
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.noIncorporation_iff_constraining_licensed_by_forgetful
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.blindObserverLanguage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.observerSeesDimension_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.constantStatementLanguage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.complete_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.unsoundStatementLanguage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.sound_is_required
