import OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnificationInstances

/-! Permanent reach and axiom audit for `DefinitionUnificationInstances`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ofFixedInputBoundary
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_observerInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_languageInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_languageInexpressible_iff_operationallyIncomplete
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7FixedInput_observerInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7FixedInput_languageInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_dependsOnDimension_iff_unlicensed
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_operationallyIncomplete_iff_license_face
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_license_face_holds
#check @OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_operationallyIncomplete_via_license

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ObservedLanguage.ofFixedInputBoundary
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_observerInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_languageInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ofFixedInputBoundary_languageInexpressible_iff_operationallyIncomplete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7FixedInput_observerInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7FixedInput_languageInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_dependsOnDimension_iff_unlicensed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_operationallyIncomplete_iff_license_face
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_license_face_holds
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DefinitionUnification.ko7StepArgument_operationallyIncomplete_via_license
