import OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense

/-! Reach and axiom check for the `
DependencyLicense
` module. Permanent. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_iff_semanticallyImplies
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_iff_semanticallyImplies
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdListHoldsOn_familyDependencies_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdListHoldsOn_familyDependencies_iff

/-! ## Complete public-surface reach and axiom parity -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.restrictTo
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.restrictTo_eq_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDHoldsOn
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdHoldsOn_iff_licensedOn
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdHoldsOn_of_subset
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDHoldsOn.augment
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDHoldsOn.trans
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdHoldsOn_union_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.licensedOn_jointPair_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.licensedOn_pi_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FD
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.SemanticallyImplies
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.TwoTupleImplies
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.union
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.mono_right
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_iff_forall_singleton
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_of_twoTupleImplies
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.oneTuple_satisfies_every_dependency
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.twoTuple_family_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDListHoldsOn
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdListHoldsOn_iff_licensedOn_each
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.familyTuples
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.familyDependencies
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.member
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.refl
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.augment
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.trans

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.restrictTo
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.restrictTo_eq_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDHoldsOn
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdHoldsOn_iff_licensedOn
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdHoldsOn_of_subset
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDHoldsOn.augment
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDHoldsOn.trans
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdHoldsOn_union_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.licensedOn_jointPair_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.licensedOn_pi_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FD
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.SemanticallyImplies
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.TwoTupleImplies
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.union
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.mono_right
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_iff_forall_singleton
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_of_twoTupleImplies
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.oneTuple_satisfies_every_dependency
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.twoTuple_family_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.FDListHoldsOn
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.fdListHoldsOn_iff_licensedOn_each
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.familyTuples
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.familyDependencies
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.member
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.refl
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.augment
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.ArmstrongDerivable.trans
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.SemanticallyImpliesU
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_soundU
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_of_semanticallyImpliesU
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.semanticallyImpliesU_iff_twoTupleImplies
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_iff_semanticallyImplies_universal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_soundU
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_of_semanticallyImpliesU
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.semanticallyImpliesU_iff_twoTupleImplies
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyLicense.armstrongDerivable_iff_semanticallyImplies_universal

