import OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence

/-! Full reach and axiom coverage for the `DependencyPairEquivalence` module. Permanent. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.argSteps_stepStar
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.minChainStep_transGen
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.minChain_wf_of_terminating
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.terminating_iff_minChain_wf
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.wellFounded_flip_iff_no_infinite_chain
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.terminating_iff_no_infinite_minimalChain
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.NoRunOfLength
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.BoundedRunsAt
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.not_noRunOfLength_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.NoRunOfLength.mono
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.NoRunOfLength.succ_inv
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.noRunOfLength_succ_of_forall
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.acc_of_boundedRunsAt
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.boundedRunsAt_of_acc
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.acc_iff_boundedRunsAt
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.decidableNoRunOfLength
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.sn_iff_boundedRunsAt
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.terminating_iff_boundedRuns
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.decidableNoRunOfLength_step
#check @OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.freeRecursor_boundedRuns

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.argSteps_stepStar
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.minChainStep_transGen
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.minChain_wf_of_terminating
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.terminating_iff_minChain_wf
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.wellFounded_flip_iff_no_infinite_chain
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.terminating_iff_no_infinite_minimalChain
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.not_noRunOfLength_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.NoRunOfLength.mono
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.NoRunOfLength.succ_inv
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.noRunOfLength_succ_of_forall
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.acc_of_boundedRunsAt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.boundedRunsAt_of_acc
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.acc_iff_boundedRunsAt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.sn_iff_boundedRunsAt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.terminating_iff_boundedRuns
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DependencyPairEquivalence.freeRecursor_boundedRuns
