import OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarLicense

/-! Permanent reach and axiom audit for `DirectGrammarLicense`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadBlind_iff_licensed_by_counter
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.usesPayload_iff_unlicensed_by_counter
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammar_orienting_denotations_licensed_by_counter
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.orienting_denotations_licensed_by_counter_of_denotational_subgrammar
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_payload_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_target_unlicensed_by_counter
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_projection_orients_and_licensed
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_orients_and_unlicensed_by_counter

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadBlind_iff_licensed_by_counter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.usesPayload_iff_unlicensed_by_counter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammar_orienting_denotations_licensed_by_counter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.orienting_denotations_licensed_by_counter_of_denotational_subgrammar
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_payload_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_target_unlicensed_by_counter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_projection_orients_and_licensed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_orients_and_unlicensed_by_counter
