import OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary

/-! Permanent reach and axiom audit for `DirectGrammarBoundary`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivation
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivable
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivation
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivable_complete
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.UsesPayload
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.AdequateForDupOrientation
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_usesPayload
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_not_adequateForDupOrientation
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_adequateForDupOrientation
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_not_usesPayload
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.no_directGrammar_measure_usesPayload_and_orients
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivation.no_payload_orientation
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivable_no_payload_orientation
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_side_nonempty
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.target_side_nonempty
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_orients
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_not_payloadBlind
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_not_grammar_denotable
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.no_payload_orientation_of_denotational_subgrammar
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.denotational_subgrammar_premise_necessary
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.no_payload_orientation_of_same_grammar

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivable_complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.UsesPayload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.AdequateForDupOrientation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_usesPayload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_not_adequateForDupOrientation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_adequateForDupOrientation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.counter_not_usesPayload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.no_directGrammar_measure_usesPayload_and_orients
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivation.no_payload_orientation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivable_no_payload_orientation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_side_nonempty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.target_side_nonempty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_orients
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_not_payloadBlind
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_not_grammar_denotable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.no_payload_orientation_of_denotational_subgrammar
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.denotational_subgrammar_premise_necessary
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.no_payload_orientation_of_same_grammar
