import OperatorKO7.Meta.DirectToolSearchMapping

namespace DirectToolSearchMappingReach

open OperatorKO7

#check OperatorKO7.DirectToolSearchMapping.AdditiveFragment
#check OperatorKO7.DirectToolSearchMapping.AffineUnboundedFragment
#check OperatorKO7.DirectToolSearchMapping.AffineSuccPumpFragment
#check OperatorKO7.DirectToolSearchMapping.AffineWrapPumpFragment
#check OperatorKO7.DirectToolSearchMapping.QuadraticUnboundedFragment
#check OperatorKO7.DirectToolSearchMapping.QuadraticSuccPumpFragment
#check OperatorKO7.DirectToolSearchMapping.QuadraticWrapPumpFragment
#check OperatorKO7.DirectToolSearchMapping.MultilinearUnboundedFragment
#check OperatorKO7.DirectToolSearchMapping.MultilinearSuccPumpFragment
#check OperatorKO7.DirectToolSearchMapping.MultilinearWrapPumpFragment
#check OperatorKO7.DirectToolSearchMapping.PolynomialUnboundedFragment
#check OperatorKO7.DirectToolSearchMapping.PolynomialSuccPumpFragment
#check OperatorKO7.DirectToolSearchMapping.PolynomialWrapPumpFragment

#check OperatorKO7.DirectToolSearchMapping.additive_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.affineUnbounded_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.affineSuccPump_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.affineWrapPump_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.quadraticUnbounded_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.quadraticSuccPump_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.quadraticWrapPump_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.multilinearUnbounded_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.multilinearSuccPump_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.multilinearWrapPump_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.polynomialUnbounded_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.polynomialSuccPump_fragment_no_global_orientation
#check OperatorKO7.DirectToolSearchMapping.polynomialWrapPump_fragment_no_global_orientation

end DirectToolSearchMappingReach
