import OperatorKO7.Meta.EscapeTrichotomy_PumpFree

/-!
# Reach gate: pump-free escape trichotomy

Pins every public declaration of the modules listed below with a paired
`#check @name` and `#print axioms name`. Source-to-reach and reach-to-axiom
differences are empty by construction: this file is generated from the
namespace-aware declaration inventory of those sources. Every axiom closure must
be a subset of `{propext, Classical.choice, Quot.sound}` and no closure may
mention `sorryAx`. This gate is import-and-check only; it proves no new content.

* `OperatorKO7/Meta/EscapeTrichotomy_PumpFree.lean`: 8 public declarations
* structure constructor and projections pinned explicitly: 34
-/

set_option autoImplicit false

namespace OperatorKO7.Test.EscapeTrichotomyPumpFreeReach

-- OperatorKO7/Meta/EscapeTrichotomy_PumpFree.lean
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree
#check @OperatorKO7.EscapeTrichotomyPumpFree.ko7_nat_direct_escape_trichotomy_pumpFree
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.ko7_nat_direct_escape_trichotomy_pumpFree
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.primaryScalar
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.primaryScalar
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.Orients
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.Orients
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree
#check @OperatorKO7.EscapeTrichotomyPumpFree.ko7_direct_escape_trichotomy_pumpFree
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.ko7_direct_escape_trichotomy_pumpFree
#check @OperatorKO7.EscapeTrichotomyPumpFree.pumpFree_of_withPump
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.pumpFree_of_withPump

-- structure constructor and projections
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.additive
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.additive
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.compositionalTransparent
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.compositionalTransparent
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.affine
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.affine
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.quadratic
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.quadratic
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.crossQuadraticBounded
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.crossQuadraticBounded
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.multilinearDominated
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.multilinearDominated
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.polynomialDominated
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.polynomialDominated
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.max
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.max
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.depth
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.depth
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.precedence
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7NatDirectBarrierRepresentablePumpFree.precedence
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.nat
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.nat
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.pairComponentwise
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.pairComponentwise
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.pairLex
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.pairLex
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecComponentwise
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecComponentwise
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecEwz
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecEwz
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecLex
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecLex
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecPermLex
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectOrienterPumpFree.vecPermLex
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.additive
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.additive
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.compositionalTransparent
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.compositionalTransparent
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.affine
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.affine
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.quadratic
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.quadratic
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.crossQuadraticBounded
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.crossQuadraticBounded
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.multilinearDominated
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.multilinearDominated
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.polynomialDominated
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.polynomialDominated
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.max
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.max
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.depth
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.depth
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.precedence
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.precedence
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrix2Componentwise
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrix2Componentwise
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrix2LexOfFstPos
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrix2LexOfFstPos
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrixLexDOfPrimaryPos
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrixLexDOfPrimaryPos
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrixLexPermDOfPrimaryPos
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.matrixLexPermDOfPrimaryPos
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.naturalMatrixComponentwise
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.naturalMatrixComponentwise
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.naturalMatrixEwz
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.naturalMatrixEwz
#check @OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.naturalMatrixLexDOfPrimaryPos
#print axioms OperatorKO7.EscapeTrichotomyPumpFree.KO7DirectBarrierRepresentablePumpFree.naturalMatrixLexDOfPrimaryPos

end OperatorKO7.Test.EscapeTrichotomyPumpFreeReach
