import OperatorKO7.Meta.ExtendedDirectToolSearchMapping

namespace ExtendedDirectToolSearchMappingReach

open OperatorKO7

#check OperatorKO7.ExtendedDirectToolSearchMapping.CrossQuadraticUnboundedFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.CrossQuadraticSuccPumpFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.CrossQuadraticWrapPumpFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.MaxUnboundedFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.MaxSuccPumpFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.MaxWrapPumpFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.WPOPolynomialDirectUnboundedFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.WPOPolynomialDirectSuccPumpFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.WPOPolynomialDirectWrapPumpFragment
#check OperatorKO7.ExtendedDirectToolSearchMapping.WPOPolynomialDirectBaseDominanceFailureFragment

#check OperatorKO7.ExtendedDirectToolSearchMapping.crossQuadraticUnbounded_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.crossQuadraticSuccPump_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.crossQuadraticWrapPump_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.maxUnbounded_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.maxSuccPump_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.maxWrapPump_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.wpoPolynomialDirectUnbounded_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.wpoPolynomialDirectSuccPump_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.wpoPolynomialDirectWrapPump_fragment_no_global_orientation
#check OperatorKO7.ExtendedDirectToolSearchMapping.wpoPolynomialDirectBaseDominanceFailure_fragment_escape_requires_failure_of_base_dominance

end ExtendedDirectToolSearchMappingReach
