import OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_normalize_state
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_normalize_state

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_cost_state
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_cost_state

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_complete_state
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_complete_state

set_option autoImplicit false

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_deterministic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_deterministic

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.root_deterministic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.root_deterministic

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dp_deterministic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dp_deterministic

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.unit_fold_constant
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.unit_fold_constant

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsedDPChannel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsedDPChannel

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsedDPChannel_always_true
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsedDPChannel_always_true

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsedDPChannel_fails_separation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsedDPChannel_fails_separation

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_injective

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_hom
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_hom

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.State
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.State

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.point
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.point

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.equiv
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.equiv

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.decode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.decode

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.decode_point
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.decode_point

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.point_decode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.point_decode

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_decode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_decode

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.Realized
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.Realized

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_state_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_state_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.closedEmbedding
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.closedEmbedding

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.relationIso
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.relationIso

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.Root
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.Root

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.DP
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.DP

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.Contextual
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.Contextual

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextEval
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextEval

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextEval_encode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextEval_encode

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_iff_context_contraction
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_iff_context_contraction

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.freeRecursor_step_iff_realized_step
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.freeRecursor_step_iff_realized_step

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.freeRecursor_dp_iff_realized_dp
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.freeRecursor_dp_iff_realized_dp

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.freeRecursor_context_iff_realized_context
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.freeRecursor_context_iff_realized_context

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_acc
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_acc

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_acc_reflect
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_acc_reflect

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_acc_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_acc_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_star_map
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_star_map

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_star_pull
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_star_pull

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_confluent_at
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.closedEmbedding_confluent_at

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_wellFounded

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.root_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.root_wellFounded

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dp_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dp_wellFounded

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_wellFounded

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_confluent_at
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_confluent_at

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_confluent

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.root_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.root_confluent

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dp_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dp_confluent

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextual_confluent

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.extractor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.extractor

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.extractor_point
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.extractor_point

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_processor_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_processor_sound

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_next_point
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_next_point

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_step_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_step_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_normalize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_normalize

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_cost
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportMachine_cost

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootNormalizer
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootNormalizer

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dpNormalizer
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dpNormalizer

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootNormalizer_step_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootNormalizer_step_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dpNormalizer_step_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.dpNormalizer_step_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_root_cost
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_root_cost

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_dp_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_dp_length

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_dp_normalize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_dp_normalize

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextNormalize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.contextNormalize

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_context_normalization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_context_normalization

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.observedSubterm
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.observedSubterm

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.observedSubterm_point
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.observedSubterm_point

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.roleDecision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.roleDecision

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_option_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.encode_option_injective

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.roleDecision_eq_free
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.roleDecision_eq_free

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_role_separator
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_role_separator

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realizedOrbit
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realizedOrbit

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_progress_orbit_iso
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_progress_orbit_iso

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_recursor_orbit_dp_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.realized_recursor_orbit_dp_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportHierarchy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportHierarchy

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportHierarchy_adequate_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.transportHierarchy_adequate_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.RootTerminates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.RootTerminates

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootTerminates_point_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootTerminates_point_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootTerminates_pullback
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.rootTerminates_pullback

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_witness_depths
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_witness_depths

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_boundary_minimum
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.faithfulRealization_boundary_minimum

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7Algebra
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7Algebra

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ofTrace
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ofTrace

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ofTrace_fold
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ofTrace_fold

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.fold_ofTrace
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.fold_ofTrace

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7Realization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7Realization

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_encode_ofTrace
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_encode_ofTrace

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.KO7RecursorStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.KO7RecursorStep

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_root_exact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_root_exact

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_dp_exact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_dp_exact

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7RecursorStep_sub_fullStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7RecursorStep_sub_fullStep

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_adapter_not_all_root_rules
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ko7_adapter_not_all_root_rules

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.unitAlgebra
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.unitAlgebra

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsed_realization_not_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsed_realization_not_injective

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsed_realization_cannot_reflect
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.collapsed_realization_cannot_reflect

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.EscapingAmbient
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.EscapingAmbient

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.escapingAmbient_reflects
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.escapingAmbient_reflects

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.escapingAmbient_not_outgoing_closed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.escapingAmbient_not_outgoing_closed

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.escapingAmbient_not_accessible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.escapingAmbient_not_accessible

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ambient_transport_of_exact_outgoing
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ambient_transport_of_exact_outgoing

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ambient_exact_outgoing_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.ambient_exact_outgoing_iff

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.mk

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.algebra
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.algebra

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.FaithfulRealization.injective

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.KO7RecursorStep.zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.KO7RecursorStep.zero

#check @OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.KO7RecursorStep.succ
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization.KO7RecursorStep.succ

open OperatorKO7.Meta.OperationalInexpressibility.FaithfulRecursorRealization
#check @ambient_confluence_of_exact_outgoing
#print axioms ambient_confluence_of_exact_outgoing

open OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorKernel
open OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorRoleGate
open OperatorKO7.Meta.Recursor.DPConfessionLicense

example : ko7Realization.Root (.recΔ .void .void .void) .void :=
  (ko7_root_exact _ _).mpr (.zero .void .void)

example : ko7Realization.DP (.recΔ .void .void (.delta .void)) (.recΔ .void .void .void) :=
  (ko7_dp_exact _ _).mpr (.rec_succ .void .void .void)

example : ko7Realization.dpNormalizer.cost
    (ko7Realization.point (.recR .void .void (.delta (.delta (.delta .void))))) = 3 := by
  rw [ko7Realization.faithfulRealization_dp_length]
  rfl

example : ko7Realization.roleDecision ⟨.void, .void, .void⟩ .frame = false :=
  (ko7Realization.faithfulRealization_role_separator _).2.2.1

example : ko7Realization.roleDecision ⟨.void, .void, .void⟩ .active = true :=
  (ko7Realization.faithfulRealization_role_separator _).2.2.2.1

example : ko7Realization.Contextual (.app .void (.recΔ .void .void .void)) (.app .void .void) :=
  ko7Realization.freeRecursor_context_iff_realized_context _ _ |>.mp
    (.inContext (.appRight .void .hole) (.zero .void .void))

example : ¬ ko7Realization.Root (.merge .void .void) .void :=
  ko7_adapter_not_all_root_rules.2

example : ¬ Acc (fun b a => EscapingAmbient a b) (some RecursorTerm.void) :=
  escapingAmbient_not_accessible

example : Nonempty (FaithfulRealization OperatorKO7.Trace) := ⟨ko7Realization⟩

example : (ko7Realization.transportHierarchy
    OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorWitnessOrder.boundaryHierarchy).hasAdequateAtDepth
    2 ko7Realization.RootTerminates (ko7Realization.point .void) :=
  (ko7Realization.faithfulRealization_witness_depths _ 2).2.mpr (by decide)
