import OperatorKO7.Meta.OperationalInexpressibility.FiberEntropyBound

/-! Permanent reach and axiom audit for `FiberEntropyBound`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.targetCondEntropy
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.LicensedOnSupport
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberMass_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.sum_fiberTargetMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.sum_fiberMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.single_le_fiberMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.single_le_fiberTargetMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass_le_fiberMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_le_one
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass_eq_zero_of_not_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_eq_zero_of_not_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberVerdicts_nonempty
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_condLaw_eq_sum_fiberVerdicts
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_fiberLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberLaw_sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_condLaw_le_log_card
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_le_log_fiberMultiplicity
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropyBits_le_logb_fiberMultiplicity
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.negMulLog_eq_zero_iff_of_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_eq_zero_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.exists_pos_of_fiberTargetMass_ne_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_eq_zero_iff_licensedOnSupport
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.eq_uniform_of_H_eq_log_card
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_condLaw_eq_log_of_uniform
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_eq_log_fiberMultiplicity_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.nonuniformPrior
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.nonuniform_fiber_law_lt_log_fiberMultiplicity
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.pointPrior
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.zeroMass_collision_conditionalEntropy_eq_zero

#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.targetCondEntropy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.LicensedOnSupport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberMass_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.sum_fiberTargetMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.sum_fiberMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.single_le_fiberMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.single_le_fiberTargetMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass_le_fiberMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_le_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberTargetMass_eq_zero_of_not_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.condLaw_eq_zero_of_not_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberVerdicts_nonempty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_condLaw_eq_sum_fiberVerdicts
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_fiberLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.fiberLaw_sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_condLaw_le_log_card
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_le_log_fiberMultiplicity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropyBits_le_logb_fiberMultiplicity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.negMulLog_eq_zero_iff_of_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_eq_zero_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.exists_pos_of_fiberTargetMass_ne_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_eq_zero_iff_licensedOnSupport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.eq_uniform_of_H_eq_log_card
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.H_condLaw_eq_log_of_uniform
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_eq_log_fiberMultiplicity_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.nonuniformPrior
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.nonuniform_fiber_law_lt_log_fiberMultiplicity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.pointPrior
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.zeroMass_collision_conditionalEntropy_eq_zero
