import OperatorKO7.Meta.OperationalInexpressibility.FiberDeficitCore

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.FiberDeficitCore`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.FiberDeficitCoreReach

#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCodeDeficit
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.mem_fiberVerdicts
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts_card_le_of_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts_card_le_one_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_le_one_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_eq_zero_iff_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_pos_iff_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.additional_channel_card_lower_bound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.additional_channel_bits_lower_bound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts_card_le
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCodeEmbedding
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCode
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCode_injective_on_fiber
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.exists_optimal_side_channel
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_is_minimum_side_channel_cardinality
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.exists_binary_side_channel_at_fiberCodeDeficit
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCodeDeficit_is_minimum_fixedLength_bits
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_le_of_kernel_refines
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_le_of_kernel_refines
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_le_of_refines
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_le_of_refines

#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCodeDeficit
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.mem_fiberVerdicts
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts_card_le_of_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts_card_le_one_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_le_one_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_eq_zero_iff_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_pos_iff_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.additional_channel_card_lower_bound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.additional_channel_bits_lower_bound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberVerdicts_card_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCodeEmbedding
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCode_injective_on_fiber
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.exists_optimal_side_channel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_is_minimum_side_channel_cardinality
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.exists_binary_side_channel_at_fiberCodeDeficit
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberCodeDeficit_is_minimum_fixedLength_bits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_le_of_kernel_refines
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_le_of_kernel_refines
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberMultiplicity_le_of_refines
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberDeficit.fiberDeficit_le_of_refines

end OperatorKO7.Test.FiberDeficitCoreReach
