import OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel

/-! Permanent reach and axiom audit for `FiniteProbabilityChannel`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution.pointMassU
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution.normalized
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution.point
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.row
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.deterministic
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.deterministic_selected_mass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryMass
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryDistribution
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.fairBinary
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryMass_entropy
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteChannel
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteChannel.residual
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteChannel.normalized
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryDistribution_nonvacuous

#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution.pointMassU
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution.normalized
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteDistribution.point
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.row
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.deterministic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.deterministic_selected_mass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryDistribution
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.ConditionalKernel.fairBinary
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryMass_entropy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteChannel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteChannel.residual
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.FiniteChannel.normalized
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteProbabilityChannel.fairBinaryDistribution_nonvacuous
