import OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms

set_option autoImplicit false

namespace OperatorKO7.Test.FiniteCoordinateAlgorithmsReach

/-! Public source surface for OI-1 validation. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.explicit
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.stepB
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.Step
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.step_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reachableB
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reachableB_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.normalB
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.normalB_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalSupport
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalMultiplicity
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.joinableB
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.joinableB_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.joinableB_comm
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceConfluentB
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceConfluentB_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom.singleton
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom.snoc
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom.reachable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome_isSome_of_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reconstructPath
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reconstructPath_isSome_of_mem_indexedReachIter
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.path?
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.path?_complete_of_reachable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reconstructPath_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.path?_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.left
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.right
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.left_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.right_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.distinct
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?_spec
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?_complete
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.normal_reachable_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.distinct_normal_forms_not_joinable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.left
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.right
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.left_reachable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.right_reachable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.nonjoinable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinablePairs
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinabilityPair?
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinabilityPair?_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinabilityPair?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal.empty
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal.log2Support
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalHartley
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal.real?
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalHartley_real?_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalHartley_eq_empty_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates.terminalCount
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates.confluentAtSource
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.relationOnlyCoordinates
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.relationOnlyCoordinates_congr
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.source
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.left
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.right
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput.items
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput.complete
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.IsDefect
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.peakItemIsDefectDecidable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.peakDefects
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_peakDefects_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.peakDefects_complete
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.CriticalPairItem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.CriticalPairInput
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.criticalPairDefects
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_criticalPairDefects_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.leftRule
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.rightRule
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.leftRule_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.rightRule_mem
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.position
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.subterm
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.unifier
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.source
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.left
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.right
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.position_nonvariable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.subterm_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.unify_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.source_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.left_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.right_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.trsCriticalPairOrigin_is_peak
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.exists_trsCriticalPairOrigin_of_mem_criticalPairs
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.items
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.complete
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.covers_criticalPairs
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.table
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.realize
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.realize_injective
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.step_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.step_reflect
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reduction_closed
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reach_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reach_reflect
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reach_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.joinable_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.nonjoinable_of_joinableB_false
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.origin
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.sourceAddr
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.leftAddr
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.rightAddr
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.source_realizes
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.left_realizes
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.right_realizes
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adaptedCriticalPair_is_genuine
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adaptedCriticalPair_nonjoinable_in_trs
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.interventions
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.bad
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.closes
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.price
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.argminNat
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.argminNat_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.argminNat_sound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.listSubsets
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.filter_mem_listSubsets
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.allRepairSelections
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.repairCoverDecidable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.repairCandidatesExec
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_allRepairSelections
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_repairCandidatesExec_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?_sound_minimal
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?_sound_minimal
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?_card_eq_reference
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?_cost_eq_reference
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_le
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_sound_bool
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_minimal
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_witnessRank_of_some
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_witnessRank
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_sound_graded
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.emptyEnumeration
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.emptyTable
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.unitEnumeration
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonLoop
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonNormal
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonRepairCheap
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonRepairCostly
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonRepairUncovering
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.identical_relation_different_auxiliary_price
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.identical_relation_different_auxiliary_coverage
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adequateAtZero
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adequateAtTwo
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.identical_relation_different_adequacy_and_bound
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.fin3Enumeration
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.chain3
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.fork3
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonNormal_has_one_terminal
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonLoop_has_no_terminal
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.chain3_source_confluent
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.fork3_source_not_confluent
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.rank_zero_found
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.bounded_rank_exhausted

#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.explicit
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.stepB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.Step
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationTable.step_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reachableB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reachableB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.normalB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.normalB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalSupport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalMultiplicity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.joinableB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.joinableB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.joinableB_comm
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceConfluentB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceConfluentB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom.singleton
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom.snoc
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PathFrom.reachable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome_isSome_of_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.firstSome_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reconstructPath
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reconstructPath_isSome_of_mem_indexedReachIter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.path?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.path?_complete_of_reachable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.reconstructPath_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.path?_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.left
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.right
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.left_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.right_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.NonjoinabilityEvidence.distinct
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?_spec
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.nonjoinabilityPair?_complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.normal_reachable_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.distinct_normal_forms_not_joinable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.left
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.right
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.left_reachable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.right_reachable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.SourceNonjoinabilityEvidence.nonjoinable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinablePairs
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinabilityPair?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinabilityPair?_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.sourceNonjoinabilityPair?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal.empty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal.log2Support
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalHartley
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.HartleyTerminal.real?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalHartley_real?_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.terminalHartley_eq_empty_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates.terminalCount
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RelationOnlyCoordinates.confluentAtSource
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.relationOnlyCoordinates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.relationOnlyCoordinates_congr
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.source
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.left
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.right
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput.items
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakInput.complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.PeakItem.IsDefect
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.peakItemIsDefectDecidable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.peakDefects
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_peakDefects_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.peakDefects_complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.CriticalPairItem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.CriticalPairInput
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.criticalPairDefects
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_criticalPairDefects_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.leftRule
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.rightRule
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.leftRule_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.rightRule_mem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.position
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.subterm
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.unifier
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.source
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.left
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.right
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.position_nonvariable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.subterm_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.unify_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.source_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.left_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairOrigin.right_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.trsCriticalPairOrigin_is_peak
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.exists_trsCriticalPairOrigin_of_mem_criticalPairs
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.items
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSCriticalPairInput.covers_criticalPairs
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.table
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.realize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.realize_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.step_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.step_reflect
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reduction_closed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reach_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reach_reflect
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.reach_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.joinable_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.TRSFiniteAdapter.nonjoinable_of_joinableB_false
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.origin
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.sourceAddr
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.leftAddr
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.rightAddr
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.source_realizes
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.left_realizes
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.AdaptedCriticalPair.right_realizes
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adaptedCriticalPair_is_genuine
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adaptedCriticalPair_nonjoinable_in_trs
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.interventions
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.bad
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.closes
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.RepairInput.price
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.argminNat
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.argminNat_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.argminNat_sound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.listSubsets
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.filter_mem_listSubsets
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.allRepairSelections
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.repairCoverDecidable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.repairCandidatesExec
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_allRepairSelections
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.mem_repairCandidatesExec_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?_sound_minimal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?_sound_minimal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumRepairCover?_card_eq_reference
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.minimumPriceRepair?_cost_eq_reference
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_sound_bool
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_minimal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_witnessRank_of_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_witnessRank
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_sound_graded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.emptyEnumeration
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.emptyTable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.unitEnumeration
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonLoop
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonNormal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonRepairCheap
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonRepairCostly
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonRepairUncovering
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.identical_relation_different_auxiliary_price
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.identical_relation_different_auxiliary_coverage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adequateAtZero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.adequateAtTwo
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.identical_relation_different_adequacy_and_bound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.fin3Enumeration
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.chain3
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.fork3
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonNormal_has_one_terminal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.singletonLoop_has_no_terminal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.chain3_source_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.fork3_source_not_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.rank_zero_found
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.bounded_rank_exhausted

end OperatorKO7.Test.FiniteCoordinateAlgorithmsReach
