import OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage

/-! Permanent reach and axiom audit for `FixedInputLanguage`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.FixedInputLanguageBoundary
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.DimensionPresent
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.DependsOnDimension
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.ConstrainsTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.DecidesTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.dimension_present
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.fixed_counterfactual_witness
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.fixed_input_counterfactual_witness
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.target_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.derivable_denotation_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.derivable_denotation_verdictDeterminedBy
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.derivable_denotation_eq_of_observation_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.decidesTarget_implies_constrainsTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.no_derivable_constrainsTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.no_derivable_statement_decides_target
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.target_not_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.target_has_no_quotientFactorization
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.operationalQuestion
#check @OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.operationalQuestion_operationallyIncomplete

#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.FixedInputLanguageBoundary
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.DimensionPresent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.DependsOnDimension
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.ConstrainsTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.DecidesTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.dimension_present
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.fixed_counterfactual_witness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.fixed_input_counterfactual_witness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.target_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.derivable_denotation_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.derivable_denotation_verdictDeterminedBy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.derivable_denotation_eq_of_observation_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.decidesTarget_implies_constrainsTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.no_derivable_constrainsTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.no_derivable_statement_decides_target
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.target_not_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.target_has_no_quotientFactorization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.operationalQuestion
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.operationalQuestion_operationallyIncomplete
