import OperatorKO7.Meta.HigherOrderRewriting_CaptureDecidable

namespace HigherOrderRewritingCaptureDecidableReach

open OperatorKO7

#check OperatorKO7.HigherOrderRewritingCaptureDecidable.freeVarOccurs?
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.freshFor?
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.freeVariableSummary
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.binderOccurrenceSummary
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.binderOccurs?
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.freeVarOccurs_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.freeVarOccurs_classifier_eq_false_iff
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.freshFor_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.freshFor_classifier_eq_false_iff
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionGate
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionGate
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionGate_eq_true_iff
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionGate_eq_true_iff
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.binderFree_not_lam
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.binderFree_implies_betaFree
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_success_implies_obligation
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck_success_implies_obligation
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_succeeds_of_captureSafeSubstitutionObligation
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_succeeds_of_binderFree_shareFree
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_succeeds_of_closedFragment_shareFree
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck_succeeds_of_contextSafeSubstitutionObligation
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck_succeeds_of_binderFree_betaFree
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck_succeeds_of_closedFragment
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_success_preserves_binderFree
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_success_preserves_shareFree
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_success_preserves_betaFree
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck_success_preserves_binderFree_plug
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck_success_preserves_betaFree_plug
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_success_is_obligation_scoped
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.capture_decision_full_capture_semantics_exact_boundary
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.CaptureDecisionExactBoundaryStatus
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.capture_decision_exact_boundary_status
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.HigherOrderCaptureDecidableCatalog
#check OperatorKO7.HigherOrderRewritingCaptureDecidable.higher_order_capture_decidable_catalog

example : OperatorKO7.HigherOrderRewritingCaptureDecidable.HigherOrderCaptureDecidableCatalog :=
  OperatorKO7.HigherOrderRewritingCaptureDecidable.higher_order_capture_decidable_catalog

example {name binderName : Nat} {arg body : OperatorKO7.HigherOrderRewritingSyntax.HOTerm}
    (h : OperatorKO7.HigherOrderRewritingCaptureSubfamilies.CaptureSafeSubstitutionObligation name binderName arg body) :
    ∃ cert,
      OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck name binderName arg body =
        some cert :=
  OperatorKO7.HigherOrderRewritingCaptureDecidable.captureSafeSubstitutionCheck_succeeds_of_captureSafeSubstitutionObligation h

example {c : OperatorKO7.HigherOrderRewritingSyntax.Context}
    {t : OperatorKO7.HigherOrderRewritingSyntax.HOTerm}
    (h : OperatorKO7.HigherOrderRewritingCaptureSubfamilies.ContextSafeSubstitutionObligation c t) :
    ∃ cert,
      OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck c t = some cert :=
  OperatorKO7.HigherOrderRewritingCaptureDecidable.contextSafeSubstitutionCheck_succeeds_of_contextSafeSubstitutionObligation h

end HigherOrderRewritingCaptureDecidableReach