import OperatorKO7.Meta.HigherOrderRewriting_CaptureSubfamilies

namespace HigherOrderRewritingCaptureSubfamiliesReach

open OperatorKO7

#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.IsLam
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BinderFreeHOTerm
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.ShareFreeHOTerm
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BetaFreeHOTerm
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.LinearHOTerm
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.DAGSharedHOTerm
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BetaFreeContext
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.CaptureSafeSubstitutionObligation
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.ContextSafeSubstitutionObligation
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BetaCounterexamplePackage
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.ShareFreeBoundaryEmbedding
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.FullCaptureSemanticsStatus
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.HigherOrderCaptureSubfamilyCatalog
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.closedFragment_not_lam
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.closedFragment_betaFree
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.closedFragment_binderFree
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.embedSharedTerm_dagShared
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.shareFree_closedFragment_linear
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.binderFree_substitute
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.shareFree_substitute
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BinderFreeContext.plug_binderFree
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BetaFreeContext.plug_betaFree
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.shareFree_closedFragment_has_boundary_term
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.shareFree_fragment_embeds_old_no_sharing_boundary
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.beta_compatible_counterexample_package
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_projects_binder_aware
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_requires_freshness
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_projects_argument_binder_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_projects_argument_share_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_projects_body_binder_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_projects_body_share_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_under_binder
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_preserves_binder_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.captureSafeSubstitutionObligation_preserves_share_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.contextSafeSubstitutionObligation_projects_binder_free_context
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.contextSafeSubstitutionObligation_projects_beta_free_context
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.contextSafeSubstitutionObligation_projects_term_binder_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.contextSafeSubstitutionObligation_projects_term_beta_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.contextSafeSubstitutionObligation_plug_binder_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.contextSafeSubstitutionObligation_plug_beta_free
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.full_capture_semantics_open
#check OperatorKO7.HigherOrderRewritingCaptureSubfamilies.capture_subfamily_catalog

example : OperatorKO7.HigherOrderRewritingCaptureSubfamilies.HigherOrderCaptureSubfamilyCatalog :=
  OperatorKO7.HigherOrderRewritingCaptureSubfamilies.capture_subfamily_catalog

example : OperatorKO7.HigherOrderRewritingCaptureSubfamilies.FullCaptureSemanticsStatus :=
  OperatorKO7.HigherOrderRewritingCaptureSubfamilies.full_capture_semantics_open

example : OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BetaCounterexamplePackage :=
  OperatorKO7.HigherOrderRewritingCaptureSubfamilies.beta_compatible_counterexample_package

example {t : OperatorKO7.HigherOrderRewritingSyntax.HOTerm}
    (ht : OperatorKO7.HigherOrderRewritingSyntax.ClosedFragment t) :
    OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BetaFreeHOTerm t :=
  OperatorKO7.HigherOrderRewritingCaptureSubfamilies.closedFragment_betaFree ht

example {t : OperatorKO7.HigherOrderRewritingSyntax.HOTerm}
    (ht : OperatorKO7.HigherOrderRewritingSyntax.ClosedFragment t) :
    OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BinderFreeHOTerm t :=
  OperatorKO7.HigherOrderRewritingCaptureSubfamilies.closedFragment_binderFree ht

example {t : OperatorKO7.HigherOrderRewritingSyntax.HOTerm}
    (ht : OperatorKO7.HigherOrderRewritingSyntax.ClosedFragment t)
    (hs : OperatorKO7.HigherOrderRewritingCaptureSubfamilies.ShareFreeHOTerm t) :
    OperatorKO7.HigherOrderRewritingCaptureSubfamilies.ShareFreeBoundaryEmbedding t :=
  OperatorKO7.HigherOrderRewritingCaptureSubfamilies.shareFree_fragment_embeds_old_no_sharing_boundary ht hs

end HigherOrderRewritingCaptureSubfamiliesReach
