import OperatorKO7.Meta.HigherOrderRewriting_DecidableClassifiers

namespace HigherOrderRewritingDecidableClassifiersReach

open OperatorKO7

#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.isLam
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.binderFree?
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.shareFree?
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.betaFree?
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.linear?
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.dagShared?
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.binderFreeContext?
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.betaFreeContext?
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.isLam_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.isLam_classifier_eq_false_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.binderFree_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.shareFree_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.betaFree_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.linear_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.dagShared_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.binderFreeContext_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.betaFreeContext_classifier_eq_true_iff
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.closedFragment_implies_betaFree_classifier_true
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.closedFragment_implies_binderFree_classifier_true
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.shareFree_closedFragment_implies_linear_classifier_true
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.embedSharedTerm_implies_dagShared_classifier_true
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.binderFreeContext_classifier_true_implies_plug_preserves_binderFree
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.betaFreeContext_classifier_true_implies_plug_preserves_betaFree
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.HigherOrderDecidableClassifierCatalog
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.higher_order_decidable_classifier_catalog
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableIsLam
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableBinderFreeHOTerm
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableShareFreeHOTerm
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableBetaFreeHOTerm
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableLinearHOTerm
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableDAGSharedHOTerm
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableBinderFreeContext
#check OperatorKO7.HigherOrderRewritingDecidableClassifiers.decidableBetaFreeContext

example : OperatorKO7.HigherOrderRewritingDecidableClassifiers.HigherOrderDecidableClassifierCatalog :=
  OperatorKO7.HigherOrderRewritingDecidableClassifiers.higher_order_decidable_classifier_catalog

example (t : OperatorKO7.HigherOrderRewritingSyntax.HOTerm) :
    Decidable (OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BinderFreeHOTerm t) := inferInstance

example (c : OperatorKO7.HigherOrderRewritingSyntax.Context) :
    Decidable (OperatorKO7.HigherOrderRewritingCaptureSubfamilies.BetaFreeContext c) := inferInstance

end HigherOrderRewritingDecidableClassifiersReach
