import OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog

/-! Permanent reach and axiom audit for `HypothesisNecessityCatalog`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.rotate3
#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.isZeroObserver
#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.compatibility_is_required_for_finite_stabilization
#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.finiteness_is_required_for_exact_capacity
#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.certificate_existence_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.hypothesisNecessity_catalog

#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.rotate3
#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.isZeroObserver
#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.compatibility_is_required_for_finite_stabilization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.finiteness_is_required_for_exact_capacity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.certificate_existence_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.hypothesisNecessity_catalog
