import OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity

/-! Paired reach and axiom inventory for joint-target capacity. -/

set_option autoImplicit false

namespace OperatorKO7.Test.JointTargetCapacityReach

#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.pairedTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.licensed_pairedTarget_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.product_side_channels_license_pairedTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.licensed_duplicatedTarget_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.pairedTarget_exact_side_capacity
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.constantBoolObserver
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.boolTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.boolTarget_fiberMultiplicity_two
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.duplicatedBoolTarget_fiberMultiplicity_two
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.duplicated_target_product_bound_not_tight

#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.pairedTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.licensed_pairedTarget_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.product_side_channels_license_pairedTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.licensed_duplicatedTarget_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.pairedTarget_exact_side_capacity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.constantBoolObserver
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.boolTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.boolTarget_fiberMultiplicity_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.duplicatedBoolTarget_fiberMultiplicity_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.duplicated_target_product_bound_not_tight

end OperatorKO7.Test.JointTargetCapacityReach
