import OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage

/-! Permanent reach and axiom audit for `KO7DeclaredInventoryCoverage`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.DirectProfileCovered
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileCovered
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.u6ClassOf_ne_temporaryUnclassified
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.AtlasClassificationReceipt
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassificationReceipt
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassification_nonresidual_partition
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassification_exact_counts
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryRow
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileInventoryRows
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.methodAtlasInventoryRows
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileInventoryRows_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.methodAtlasInventoryRows_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_nodup
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_complete
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryRow.Covered
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_coverage_total
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_profile_or_atlas_classified
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileRow_ne_methodAtlasRow
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_exactProvedScope
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryClosed
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperA_declared_inventory_closed

#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.DirectProfileCovered
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileCovered
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.u6ClassOf_ne_temporaryUnclassified
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.AtlasClassificationReceipt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassificationReceipt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassification_nonresidual_partition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassification_exact_counts
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryRow
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileInventoryRows
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.methodAtlasInventoryRows
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileInventoryRows_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.methodAtlasInventoryRows_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_nodup
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryRow.Covered
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_coverage_total
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_profile_or_atlas_classified
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileRow_ne_methodAtlasRow
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_exactProvedScope
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryClosed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperA_declared_inventory_closed
