import OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage

/-! Permanent reach and axiom audit for `KO7FixedInputLanguage`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.KO7Statement
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7FixedInput
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7WorldInput
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.KO7Statement.denotes
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.KO7Statement.derivable
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7FixedInputBoundary
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_fixedInput_counterfactual_witness
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_no_derivable_statement_decides_termination
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_importedTerminationVerdict_decides_target
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_importedTerminationVerdict_not_derivable
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_derivable_statement_nonempty

#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.KO7Statement
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7FixedInput
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7WorldInput
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.KO7Statement.denotes
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.KO7Statement.derivable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7FixedInputBoundary
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_fixedInput_counterfactual_witness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_no_derivable_statement_decides_termination
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_importedTerminationVerdict_decides_target
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_importedTerminationVerdict_not_derivable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_derivable_statement_nonempty
