import OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel

/-! Permanent reach and axiom audit for `KO7LicensedChannel`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_recursor_relation_eq_step
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_selfEmbedding_relation_eq_selfEmbeddingStep
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.relationSystem_card_eq_two
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior_total
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior_nonnegative
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior_positive
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel_observe_eq_directProfile
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_directProfile_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7CommonDirectProfile
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_everySource_has_common_directProfile
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel_everySource_commonFiber
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_terminationVerdict_ne
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_total
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_nonnegative
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformTargetDistribution
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformTargetDistribution_matches_uniformPrior
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_commonFiber_calibrated
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_calibrated
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_target_mass_half
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7ChannelRecSuccRule
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.LicensedTerminationCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.KO7LicensedCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.recursorLicensedCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.selfEmbedding_rejected_by_licenseSoundness_and_nontermination
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.LicensedDecision
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.licensedDecision
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.licensedAccept
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedCertificate_separates
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedAccept_eq_terminationVerdict
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedChannel
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior_total
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior_nonnegative
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior_target_mass_one
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel_cellEntropy_eq_log_two
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedChannel_cellEntropy_eq_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.directResidual
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.licensedResidual
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedDeficit
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_direct_residual_eq_log_two
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensed_residual_eq_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensed_deficit_eq_log_two
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_channelSeparation_with_separate_licenseProvenance
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedChannel_headline
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedChannel_nonvacuous

#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_recursor_relation_eq_step
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_selfEmbedding_relation_eq_selfEmbeddingStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.relationSystem_card_eq_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior_total
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior_nonnegative
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior_positive
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel_observe_eq_directProfile
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_directProfile_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7CommonDirectProfile
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_everySource_has_common_directProfile
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel_everySource_commonFiber
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_terminationVerdict_ne
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_total
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_nonnegative
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformTargetDistribution
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformTargetDistribution_matches_uniformPrior
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_commonFiber_calibrated
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_calibrated
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_target_mass_half
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7ChannelRecSuccRule
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.LicensedTerminationCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.KO7LicensedCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.recursorLicensedCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.selfEmbedding_rejected_by_licenseSoundness_and_nontermination
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.LicensedDecision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.licensedDecision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.licensedAccept
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedCertificate_separates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedAccept_eq_terminationVerdict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedChannel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior_total
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior_nonnegative
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior_target_mass_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectChannel_cellEntropy_eq_log_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedChannel_cellEntropy_eq_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.directResidual
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.licensedResidual
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedDeficit
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_direct_residual_eq_log_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensed_residual_eq_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensed_deficit_eq_log_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_channelSeparation_with_separate_licenseProvenance
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedChannel_headline
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedChannel_nonvacuous
