import OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict

/-! Permanent reach and axiom audit for `KO7ObservationVerdict`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectOrienter
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectBarrierRepresentable
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.Candidate
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectUniverse
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.candidateOfDeclaredDirectUniverse
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.simpleSizeDeclaredDirectUniverse
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredLinearEval
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredTransparentCompositionalMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredTransparentCompositionalMeasure_transparent
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredAffineMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredAffineWithPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredQuadraticCounterMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredQuadraticWithPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCrossTermQuadraticMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCrossQuadraticWithPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBoundedMultilinearMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMultilinearWithPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBoundedPolynomialMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredPolynomialWithPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMaxEval
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMaxMeasure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMaxWithPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredPairEval
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMeasure2
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMeasure2WithPrimaryPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredIdentityLin2
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMix2Measure
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMix2WithSumPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFunctionalEval
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredUnitWeight
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixFunctionalMeasure1
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixFunctionalMeasure1WithProjectedAffinePump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredVectorEval
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexMeasure1
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexMeasure1WithPrimaryPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexPermMeasure1
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexPermMeasure1WithPrimaryPump
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredFamilyTag
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredFamilyMatches
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger_nodup
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger_nodup
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseContinuationFamilyLedgers_disjoint
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_nonempty
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_nodup
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_complete
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_matches_tag
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_witness
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredDirectUniverse_nonempty
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.Orients
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectOrienter.Orients
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.orients_ko7_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCandidate_not_orients_ko7
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.StronglyNormalizing
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.selfEmbeddingStep_not_stronglyNormalizing
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.selfEmbeddingStep_not_orients_of_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.pairLt_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.pairLexLt_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.vecLt_wellFounded_at
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.vecPermLexLt_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCandidate_not_orients_selfEmbedding
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.RelationSystem
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.RelationSystem.relation
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.directProfile
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.candidateProfile_covers_declared_direct_universe
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_profile_coverage
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_profile_coverage
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.simpleSize_candidateProfile_blocked_on_both_relations
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.metaObserve
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.StrongNormalizationVerdict
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.directProfile_recursor_eq_selfEmbedding
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.recursor_strongNormalizationVerdict
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.selfEmbedding_not_strongNormalizationVerdict
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.terminationVerdict
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.terminationVerdict_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.terminationVerdict_recursor_ne_selfEmbedding
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7_profile_operationallyInexpressible
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7ProfileTypedBoundary
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7_verdict_not_candidateProfile_function
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7_profile_not_quotientFactorization

#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectOrienter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectBarrierRepresentable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.Candidate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectUniverse
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.candidateOfDeclaredDirectUniverse
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.simpleSizeDeclaredDirectUniverse
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredLinearEval
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredTransparentCompositionalMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredTransparentCompositionalMeasure_transparent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredAffineMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredAffineWithPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredQuadraticCounterMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredQuadraticWithPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCrossTermQuadraticMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCrossQuadraticWithPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBoundedMultilinearMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMultilinearWithPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBoundedPolynomialMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredPolynomialWithPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMaxEval
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMaxMeasure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMaxWithPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredPairEval
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMeasure2
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMeasure2WithPrimaryPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredIdentityLin2
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMix2Measure
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMix2WithSumPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFunctionalEval
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredUnitWeight
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixFunctionalMeasure1
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixFunctionalMeasure1WithProjectedAffinePump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredVectorEval
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexMeasure1
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexMeasure1WithPrimaryPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexPermMeasure1
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixLexPermMeasure1WithPrimaryPump
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredFamilyTag
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredFamilyMatches
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger_nodup
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger_nodup
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseContinuationFamilyLedgers_disjoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_nonempty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_nodup
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_complete
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_matches_tag
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_witness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredDirectUniverse_nonempty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.Orients
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectOrienter.Orients
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.orients_ko7_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCandidate_not_orients_ko7
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.StronglyNormalizing
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.selfEmbeddingStep_not_stronglyNormalizing
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.selfEmbeddingStep_not_orients_of_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.pairLt_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.pairLexLt_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.vecLt_wellFounded_at
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.vecPermLexLt_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredCandidate_not_orients_selfEmbedding
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.RelationSystem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.RelationSystem.relation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.directProfile
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.candidateProfile_covers_declared_direct_universe
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_profile_coverage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_profile_coverage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.simpleSize_candidateProfile_blocked_on_both_relations
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.metaObserve
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.StrongNormalizationVerdict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.directProfile_recursor_eq_selfEmbedding
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.recursor_strongNormalizationVerdict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.selfEmbedding_not_strongNormalizationVerdict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.terminationVerdict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.terminationVerdict_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.terminationVerdict_recursor_ne_selfEmbedding
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7_profile_operationallyInexpressible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7ProfileTypedBoundary
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7_verdict_not_candidateProfile_function
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7_profile_not_quotientFactorization
