import OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance

/-! Permanent reach and axiom audit for `KO7StepArgumentInstance`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.stepArgumentProjection
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.FixedDuplicatingCarrierStep
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.evalOnCarrier
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSchema
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSystem
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSystem_step_nonempty
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.GloballyOrientsFixedDuplicatingCarrier
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_eval_eq_stepArgumentProjection
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.adequateForDupOrientation_iff_fixedCarrierStep
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.globallyOrientsFixedDuplicatingCarrier_iff_adequateForDupOrientation
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.counter_globallyOrientsFixedDuplicatingCarrier
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_not_globallyOrientsFixedDuplicatingCarrier
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.StepArgumentDimensionPresent
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgumentQuestion
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.derivable_iff_typedDirectGrammarDerivation
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.every_directGrammar_claim_derivable
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_directGrammarDerivation
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.counter_directGrammarDerivation
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_dimensionPresent
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.dependsOnDimension_iff_usesPayload
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.constrainsTarget_iff_globalOrientation
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.constrainsTarget_iff_orientsDupStep
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_predicates_nonconstant
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.derivable_claim_stepArgument_boundary
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_operationallyIncomplete

#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.stepArgumentProjection
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.FixedDuplicatingCarrierStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.evalOnCarrier
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSchema
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSystem
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSystem_step_nonempty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.GloballyOrientsFixedDuplicatingCarrier
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_eval_eq_stepArgumentProjection
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.adequateForDupOrientation_iff_fixedCarrierStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.globallyOrientsFixedDuplicatingCarrier_iff_adequateForDupOrientation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.counter_globallyOrientsFixedDuplicatingCarrier
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_not_globallyOrientsFixedDuplicatingCarrier
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.StepArgumentDimensionPresent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgumentQuestion
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.derivable_iff_typedDirectGrammarDerivation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.every_directGrammar_claim_derivable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_directGrammarDerivation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.counter_directGrammarDerivation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_dimensionPresent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.dependsOnDimension_iff_usesPayload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.constrainsTarget_iff_globalOrientation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.constrainsTarget_iff_orientsDupStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_predicates_nonconstant
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.derivable_claim_stepArgument_boundary
#print axioms OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_operationallyIncomplete
