import OperatorKO7.Meta.LCELReversibility
import OperatorKO7.Meta.LCELDpInstance

open OperatorKO7.LCELReversibility

#check BaseReversibilitySupport
#check LicenseIrreversibilitySupport
#check ReimportReversibilitySupport
#check BoundaryFactorizationSupport

#check baseReversibilitySupport_of_semanticBase
#check licenseIrreversibilitySupport_of_semanticTransfer
#check reimportReversibilitySupport_of_semanticTransfer
#check boundaryFactorizationSupport_of_supports

#check lcelReversibilityAsymmetry_of_strongerSupports
#check lcelBoundaryFactorization_of_strongerSupport

#check godel1931BaseReversibilitySupport
#check godel1931LicenseIrreversibilitySupport
#check godel1931ReimportReversibilitySupport
#check godel1931BoundaryFactorizationSupport
#check godel1931LCELReversibilityAsymmetryFromSupport
#check godel1931LCELBoundaryFactorizationFromSupport

#check benchmarkTransportBaseReversibilitySupport
#check benchmarkTransportLicenseIrreversibilitySupport
#check benchmarkTransportReimportReversibilitySupport
#check benchmarkTransportBoundaryFactorizationSupport
#check benchmarkTransportLCELReversibilityAsymmetryFromSupport
#check benchmarkTransportLCELBoundaryFactorizationFromSupport

#check OperatorKO7.LCELDpInstance.dpEmitterBaseReversibilitySupport
#check OperatorKO7.LCELDpInstance.dpEmitterLicenseIrreversibilitySupport
#check OperatorKO7.LCELDpInstance.dpEmitterReimportReversibilitySupport
#check OperatorKO7.LCELDpInstance.dpEmitterBoundaryFactorizationSupport
#check OperatorKO7.LCELDpInstance.dpEmitterLCELReversibilityAsymmetryFromSupport
#check OperatorKO7.LCELDpInstance.dpEmitterLCELBoundaryFactorizationFromSupport
