import OperatorKO7.Meta.OperationalInexpressibility.LicenseCore

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.LicenseCore`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.LicenseCoreReach

#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.Licensed
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_iff_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_iff_quotientFactorization
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.unlicensed_iff_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.ObserverRefines
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.observerRefines_iff_licenseTheory_inclusion
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.ObserverRefines.refl
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.ObserverRefines.trans
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.Licensed.of_refinement
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.not_licensed_coarse_of_not_licensed_fine
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_identity_iff_injective
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_of_injective
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.mutual_refinement_iff_same_kernel
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_of_coarser
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_chain_lost_once
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.fixedTarget_licenseTheory_inclusion_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.observerRefines_iff_binary_licenseTheory
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.same_binary_licenseTheory_iff_same_kernel
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.singleton_targets_do_not_detect_refinement

#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.coarsening_refines_of_le
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_of_coarsening_later
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.unlicensed_of_coarsening_earlier
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.first_license_loss_exists
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.first_license_loss_unique
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_cutoff_witness
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_coarsening_dichotomy

#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.Licensed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_iff_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_iff_quotientFactorization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.unlicensed_iff_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.ObserverRefines
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.observerRefines_iff_licenseTheory_inclusion
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.ObserverRefines.refl
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.ObserverRefines.trans
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.Licensed.of_refinement
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.not_licensed_coarse_of_not_licensed_fine
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_identity_iff_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_of_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.mutual_refinement_iff_same_kernel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_of_coarser
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_chain_lost_once
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.fixedTarget_licenseTheory_inclusion_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.observerRefines_iff_binary_licenseTheory
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.same_binary_licenseTheory_iff_same_kernel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.singleton_targets_do_not_detect_refinement
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.coarsening_refines_of_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.licensed_of_coarsening_later
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.unlicensed_of_coarsening_earlier
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.first_license_loss_exists
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.first_license_loss_unique
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_cutoff_witness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseCriterion.license_coarsening_dichotomy

end OperatorKO7.Test.LicenseCoreReach
