import OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances

/-! Permanent reach and axiom audit for `LiftOrRefuseInstances`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.sum_role
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.generatorValue_apply
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_lift_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_dpChannel_least_lift
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_maximal_refusals
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_least_refusal
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_lift_or_refuse
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.isDiagonal
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.pairBlind
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.correctSet_different
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.correctSet_same
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_maximal_refusals
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_self_lift
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_no_one_symbol_lift
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.sigmaVoidTest
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.no_sigmaVoidTest_lift
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.disequality_not_sigma_expressible_of_no_lift
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.safeStep_eqDiff_iff_mem_correctSet
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.safeStep_eqRefl_mem_correctSet
#check @OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonalGuard_lift_or_refuse

#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.sum_role
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.generatorValue_apply
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_lift_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_dpChannel_least_lift
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_maximal_refusals
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_least_refusal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.roleGate_lift_or_refuse
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.isDiagonal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.pairBlind
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.correctSet_different
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.correctSet_same
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_maximal_refusals
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_self_lift
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonal_no_one_symbol_lift
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.sigmaVoidTest
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.no_sigmaVoidTest_lift
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.disequality_not_sigma_expressible_of_no_lift
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.safeStep_eqDiff_iff_mem_correctSet
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.safeStep_eqRefl_mem_correctSet
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LiftOrRefuseInstances.diagonalGuard_lift_or_refuse
