import OperatorKO7.Meta.MatrixBarrierArcticTropical

namespace MatrixBarrierArcticTropicalReach

open OperatorKO7.StepDuplicating

#check StepDuplicatingSchema.ArcticMatrixVec
#check StepDuplicatingSchema.TropicalMatrixVec
#check StepDuplicatingSchema.arcticFinitePart
#check StepDuplicatingSchema.tropicalFinitePart
#check StepDuplicatingSchema.ArcticMatrixCertificate
#check StepDuplicatingSchema.ArcticMatrixMeasure
#check StepDuplicatingSchema.TropicalMatrixCertificate
#check StepDuplicatingSchema.TropicalMatrixMeasure
#check StepDuplicatingSchema.no_arcticMatrix_orients_dup_step_of_scalar_dominance_pump
#check StepDuplicatingSchema.no_tropicalMatrix_orients_dup_step_of_scalar_dominance_pump
#check OperatorKO7.MatrixBarrierArcticTropical.no_global_step_orientation_arcticMatrix_of_scalar_dominance_pump
#check OperatorKO7.MatrixBarrierArcticTropical.no_global_step_orientation_tropicalMatrix_of_scalar_dominance_pump

end MatrixBarrierArcticTropicalReach
