import OperatorKO7.Meta.MatrixBarrierArbitrary_Instances

namespace MatrixBarrierArbitraryInstancesReach

open OperatorKO7.StepDuplicating

#check StepDuplicatingSchema.MatrixScalarDominance.of_pointwise_lt
#check StepDuplicatingSchema.MatrixScalarDominance.of_pointwise_le_lt
#check StepDuplicatingSchema.unitWeight
#check StepDuplicatingSchema.allOnesWeight
#check StepDuplicatingSchema.MixedMatrix.respectsWeight_unit_of_fixedRow
#check StepDuplicatingSchema.MixedMatrix.respectsWeight_allOnes_of_columnSums
#check StepDuplicatingSchema.no_matrixArbitrary_orients_dup_step_of_unit_scalar_dominance_pump
#check StepDuplicatingSchema.no_matrixArbitrary_orients_dup_step_of_rowSum_scalar_dominance_pump
#check OperatorKO7.StepDuplicating.MatrixBarrierArbitraryInstances.no_global_step_orientation_matrixArbitrary_unit_of_scalar_dominance_pump
#check OperatorKO7.StepDuplicating.MatrixBarrierArbitraryInstances.no_global_step_orientation_matrixArbitrary_rowSum_of_scalar_dominance_pump

end MatrixBarrierArbitraryInstancesReach
