import OperatorKO7.Meta.MatrixBarrierNatural

/-!
# Reach gate: certificate-free natural-matrix barrier (schema layer and KO7 witnesses)

Pins every public declaration of the modules listed below with a paired
`#check @name` and `#print axioms name`. Source-to-reach and reach-to-axiom
differences are empty by construction: this file is generated from the
namespace-aware declaration inventory of those sources. Every axiom closure must
be a subset of `{propext, Classical.choice, Quot.sound}` and no closure may
mention `sorryAx`. This gate is import-and-check only; it proves no new content.

* `OperatorKO7/Meta/MatrixBarrierNatural_Schema.lean`: 29 public declarations
* `OperatorKO7/Meta/MatrixBarrierNatural.lean`: 19 public declarations
* structure constructor and projections pinned explicitly: 16
-/

set_option autoImplicit false

namespace OperatorKO7.Test.MatrixBarrierNaturalReach

-- OperatorKO7/Meta/MatrixBarrierNatural_Schema.lean
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.MixedMatrix.diag_mul_le_act
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.MixedMatrix.diag_mul_le_act
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.MixedMatrix.coord_le_act_of_diag_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.MixedMatrix.coord_le_act_of_diag_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.WrapDiagPositive
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.WrapDiagPositive
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrap_coord_lower_bound
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.wrap_coord_lower_bound
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.recur_coord_eq
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.recur_coord_eq
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.coord_bounded_of_nonincreasing
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.coord_bounded_of_nonincreasing
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_coord_ge
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.eval_wrapDouble_coord_ge
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_of_tracked_nonincreasing
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_of_tracked_nonincreasing
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_of_tracked_strict
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_of_tracked_strict
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_componentwise
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_componentwise
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_ewz
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_ewz
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_lexD_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_lexD_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_lexPermD_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_lexPermD_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_componentwiseWeakStrict
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_componentwiseWeakStrict
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_lexPriority
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_lexPriority
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_permutationLexPriority
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_permutationLexPriority
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_paretoProduct_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_paretoProduct_of_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_rowColumnDominance_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_rowColumnDominance_of_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_conePositive_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_conePositive_of_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_spectralNorm_of_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_natMatrix_orients_dup_step_spectralNorm_of_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_of_tracked_strict
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_of_tracked_strict
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_of_tracked_nonincreasing
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_of_tracked_nonincreasing
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_componentwise
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_componentwise
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_ewz
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_ewz
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_lexD_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_lexD_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_lexPermD_of_primary_pos
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.no_global_orients_natMatrix_lexPermD_of_primary_pos
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.MatrixArbitraryMeasure.toNatMatrixMeasure
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.MatrixArbitraryMeasure.toNatMatrixMeasure
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.MatrixArbitraryMeasure.toNatMatrixMeasure_eval
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.MatrixArbitraryMeasure.toNatMatrixMeasure_eval

-- OperatorKO7/Meta/MatrixBarrierNatural.lean
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.weightedColumn_unitWeight
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.weightedColumn_unitWeight
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.MatrixArbitraryMeasure.wrapDiagPositive_of_unitWeight
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.MatrixArbitraryMeasure.wrapDiagPositive_of_unitWeight
#check @OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_of_tracked_strict
#print axioms OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_of_tracked_strict
#check @OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_of_tracked_nonincreasing
#print axioms OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_of_tracked_nonincreasing
#check @OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_componentwise
#print axioms OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_componentwise
#check @OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_ewz
#print axioms OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_ewz
#check @OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_lexD_of_primary_pos
#print axioms OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_lexD_of_primary_pos
#check @OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_lexPermD_of_primary_pos
#print axioms OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_naturalMatrix_lexPermD_of_primary_pos
#check @OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_matrixArbitrary_unit_certificateFree
#print axioms OperatorKO7.MatrixBarrierNatural.no_global_step_orientation_matrixArbitrary_unit_certificateFree
#check @OperatorKO7.MatrixBarrierNatural.onesMatrix
#print axioms OperatorKO7.MatrixBarrierNatural.onesMatrix
#check @OperatorKO7.MatrixBarrierNatural.simpleSizeNatMatrixMeasure
#print axioms OperatorKO7.MatrixBarrierNatural.simpleSizeNatMatrixMeasure
#check @OperatorKO7.MatrixBarrierNatural.simpleSizeNatMatrixMeasure_wrapDiagPositive
#print axioms OperatorKO7.MatrixBarrierNatural.simpleSizeNatMatrixMeasure_wrapDiagPositive
#check @OperatorKO7.MatrixBarrierNatural.upperMatrix
#print axioms OperatorKO7.MatrixBarrierNatural.upperMatrix
#check @OperatorKO7.MatrixBarrierNatural.mixedPair
#print axioms OperatorKO7.MatrixBarrierNatural.mixedPair
#check @OperatorKO7.MatrixBarrierNatural.pairVec
#print axioms OperatorKO7.MatrixBarrierNatural.pairVec
#check @OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure
#print axioms OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure
#check @OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure_wrapDiagPositive
#print axioms OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure_wrapDiagPositive
#check @OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure_not_ewz_orients
#print axioms OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure_not_ewz_orients
#check @OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure_no_common_weight
#print axioms OperatorKO7.MatrixBarrierNatural.mixedNatMatrixMeasure_no_common_weight

-- structure constructor and projections
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.mk
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.mk
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.base_vec
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.base_vec
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.succ_bias
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.succ_bias
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.succ_mat
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.succ_mat
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.wrap_bias
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.wrap_bias
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.wrap_left
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.wrap_left
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.wrap_right
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.wrap_right
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_bias
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_bias
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_base
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_base
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_step
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_step
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_counter
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.recur_counter
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_base
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_base
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_succ
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_succ
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_wrap
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_wrap
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_recur
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.NatMatrixMeasure.eval_recur

end OperatorKO7.Test.MatrixBarrierNaturalReach
