import OperatorKO7.Meta.MatrixToolSearchMapping

namespace MatrixToolSearchMappingReach

open OperatorKO7

#check OperatorKO7.MatrixToolSearchMapping.FixedRowFragment
#check OperatorKO7.MatrixToolSearchMapping.RowSumFragment
#check OperatorKO7.MatrixToolSearchMapping.ArcticFixedRowFragment
#check OperatorKO7.MatrixToolSearchMapping.ArcticRowSumFragment
#check OperatorKO7.MatrixToolSearchMapping.TropicalFixedRowFragment
#check OperatorKO7.MatrixToolSearchMapping.TropicalRowSumFragment
#check OperatorKO7.MatrixToolSearchMapping.fixedRow_fragment_no_global_orientation
#check OperatorKO7.MatrixToolSearchMapping.rowSum_fragment_no_global_orientation
#check OperatorKO7.MatrixToolSearchMapping.arcticFixedRow_fragment_no_global_orientation
#check OperatorKO7.MatrixToolSearchMapping.arcticRowSum_fragment_no_global_orientation
#check OperatorKO7.MatrixToolSearchMapping.tropicalFixedRow_fragment_no_global_orientation
#check OperatorKO7.MatrixToolSearchMapping.tropicalRowSum_fragment_no_global_orientation
#check OperatorKO7.MatrixToolSearchMapping.MatrixProjectionResidualStatusHook
#check OperatorKO7.MatrixToolSearchMapping.matrix_projection_fragments_refine_exact_residual_statuses

example : OperatorKO7.MatrixToolSearchMapping.MatrixProjectionResidualStatusHook := by
  exact OperatorKO7.MatrixToolSearchMapping.matrix_projection_fragments_refine_exact_residual_statuses

end MatrixToolSearchMappingReach
