import OperatorKO7.Meta.MutualDuplication_FiniteSchema_Closeout

namespace MutualDuplicationFiniteSchemaCloseoutReach

open OperatorKO7

#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.H3CloseoutRow
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.H3CloseoutRowStatus
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.h3CloseoutRows
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.h3CloseoutRowStatus
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.h3CloseoutRows_length
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.h3CloseoutRows_mem_iff
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.h3CloseoutRows_nodup
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.final_catalog_projects_finite_schema
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.algorithmic_search_space_nonempty
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.MutualDuplicationFiniteSchemaCloseoutCatalog
#check OperatorKO7.MutualDuplicationFiniteSchemaCloseout.mutual_duplication_finite_schema_closeout_catalog

example : OperatorKO7.MutualDuplicationFiniteSchemaCloseout.MutualDuplicationFiniteSchemaCloseoutCatalog :=
  OperatorKO7.MutualDuplicationFiniteSchemaCloseout.mutual_duplication_finite_schema_closeout_catalog

example : OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleMutualDuplicationFinalCatalog
    OperatorKO7.MutualDuplicationFiniteSchema.KCycleSystem.twoRuleWitnessGraphSearchCertificate :=
  OperatorKO7.MutualDuplicationFiniteSchemaCloseout.mutual_duplication_finite_schema_closeout_catalog.twoRuleInstanceRowEvidence.1

example : ∃ W : OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.CycleCandidate
    OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.twoRuleWitnessEncodedSearchSpace,
      OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.searchCycle?
        OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.twoRuleWitnessEncodedSearchSpace = some W :=
  OperatorKO7.MutualDuplicationFiniteSchemaCloseout.mutual_duplication_finite_schema_closeout_catalog.twoRuleInstanceRowEvidence.2

end MutualDuplicationFiniteSchemaCloseoutReach
