import OperatorKO7.Meta.MutualDuplication_FiniteSchema_AlgorithmicSearch

namespace MutualDuplicationFiniteSchemaAlgorithmicSearchReach

open OperatorKO7

#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.Edge
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.requiredSuccessorPair
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.edgeLookup?
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.successorEdge?
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.CycleCandidate
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.MissingSuccessorEdgeStatus
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.assembleCycleCandidate?
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.searchCycle?
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.CycleCandidate.toGraphSearchCertificate
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.cycleCandidate_sound
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.exists_searchCycle?_eq_some
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.searchCycle?_eq_none_iff_missingSuccessorEdgeStatus

#check OperatorKO7.MutualDuplicationFiniteSchema.Constructors.TwoRuleData.toEncodedSearchSpace
#check OperatorKO7.MutualDuplicationFiniteSchema.Constructors.ThreeRuleData.toEncodedSearchSpace

#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.twoRuleWitnessEncodedSearchSpace
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.threeRuleWitnessEncodedSearchSpace
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.twoRuleWitness_searchCycle?_succeeds
#check OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.threeRuleWitness_searchCycle?_succeeds

example :
    ∃ W : OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.CycleCandidate
      OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.twoRuleWitnessEncodedSearchSpace,
      OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.searchCycle?
        OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.twoRuleWitnessEncodedSearchSpace = some W :=
  OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.twoRuleWitness_searchCycle?_succeeds

example :
    ∃ W : OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.CycleCandidate
      OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.threeRuleWitnessEncodedSearchSpace,
      OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.EncodedSearchSpace.searchCycle?
        OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.threeRuleWitnessEncodedSearchSpace = some W :=
  OperatorKO7.MutualDuplicationFiniteSchema.FiniteCycleGraphSearch.KCycleSystem.threeRuleWitness_searchCycle?_succeeds

end MutualDuplicationFiniteSchemaAlgorithmicSearchReach
