import OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.NormalFormFaithfulTransportReach

#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.RelationNormal
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.RelationUNred
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StepStarSimulation
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.map_reflTransGen
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.relationUNred_transfer
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.conv_map_of_stepStarSimulation
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.UNred_transfer
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.UNconv_transfer
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.encode
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.stutterRank
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.forward
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.relation_wellFounded_of_stutteringSimulation
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.LoopUnitStep
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.loopUnit_stepStar_simulates
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.emptyUnit_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.loopUnit_not_wellFounded
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.stutter_descent_is_required_for_termination_transport
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState.source
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState.left
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState.right
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkStep
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkStep.toLeft
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkStep.toRight
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.EmptyUnitStep
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.collapseFork
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.collapseFork_simulates
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.collapseFork_preserves_normal
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.emptyUnit_relationUNred
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.fork_left_normal
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.fork_right_normal
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.fork_not_relationUNred
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.normalForm_injectivity_is_required

#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.RelationNormal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.RelationUNred
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StepStarSimulation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.map_reflTransGen
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.relationUNred_transfer
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.conv_map_of_stepStarSimulation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.UNred_transfer
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.UNconv_transfer
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.encode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.stutterRank
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.StutteringSimulation.forward
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.relation_wellFounded_of_stutteringSimulation
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.LoopUnitStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.loopUnit_stepStar_simulates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.emptyUnit_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.loopUnit_not_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.stutter_descent_is_required_for_termination_transport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState.source
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState.left
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkState.right
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkStep.toLeft
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.ForkStep.toRight
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.EmptyUnitStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.collapseFork
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.collapseFork_simulates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.collapseFork_preserves_normal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.emptyUnit_relationUNred
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.fork_left_normal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.fork_right_normal
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.fork_not_relationUNred
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.normalForm_injectivity_is_required

end OperatorKO7.Test.NormalFormFaithfulTransportReach
