import OperatorKO7.Meta.OperationalInexpressibility.ObserverTargetCore

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.ObserverTargetCore`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.ObserverTargetCoreReach

#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.VerdictDeterminedBy
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.OperationallyInexpressibleAt
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.not_factorsThrough_of_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.not_factorsThrough_iff_exists_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.factorsThrough_of_verdictDeterminedBy
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_of_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_of_factorsThrough_of_surjective
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_iff_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_iff_factorsThrough_of_surjective
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.QuotientFactorization
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.quotientFactorization_iff_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.quotient_factorization_failure_iff_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldObserve
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget_has_no_collision
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget_not_verdictDeterminedBy

#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.VerdictDeterminedBy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.OperationallyInexpressibleAt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.not_factorsThrough_of_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.not_factorsThrough_iff_exists_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.factorsThrough_of_verdictDeterminedBy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_of_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_of_factorsThrough_of_surjective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_iff_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.verdictDeterminedBy_iff_factorsThrough_of_surjective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.QuotientFactorization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.quotientFactorization_iff_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.quotient_factorization_failure_iff_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldObserve
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget_has_no_collision
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.emptyWorldTarget_not_verdictDeterminedBy

end OperatorKO7.Test.ObserverTargetCoreReach
