import OperatorKO7.Meta.OperationalInexpressibility.ExecutableLicense
import OperatorKO7.Meta.OperationalInexpressibility.ConfusabilityGraph
import OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity
import OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance
import OperatorKO7.Meta.OperationalInexpressibility.CostComparison
import OperatorKO7.Meta.Decision.RecursorStopping
import OperatorKO7.Meta.Recursor.RaryDuplicatorLaws
import OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms
import OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog
import OperatorKO7.Meta.OperationalInexpressibility.FiberEntropyBound
import OperatorKO7.Meta.OperationalInexpressibility.RolePartitionCore
import OperatorKO7.Meta.OperationalInexpressibility.ExecutableResolvingChannel
import OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity
import OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryHorizon
import OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet
import OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax
import OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine
import OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances
import OperatorKO7.Meta.OperationalInexpressibility.RaryCertificate
import OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorKernel
import OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorContext
import OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport
import OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport
import OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary

/-! Predeclared controls of the Operational Inexpressibility closeout (P7): one block per
control; every declaration is checked and its axioms printed. -/

-- Empty source and target types
#check @OperatorKO7.Meta.OperationalInexpressibility.ExecutableLicense.licensedB_emptyEnumeration
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ExecutableLicense.licensedB_emptyEnumeration
#check @OperatorKO7.Meta.OperationalInexpressibility.Confusability.zero_symbol_channel_iff_isEmpty
#print axioms OperatorKO7.Meta.OperationalInexpressibility.Confusability.zero_symbol_channel_iff_isEmpty

-- Unattained observations
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity_exact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity_exact
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_identityModel_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_identityModel_iff

-- Zero payload, price, depth, and arity
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_tie_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_tie_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_never_strict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.zero_payload_never_strict
#check @OperatorKO7.Meta.Decision.RecursorStopping.zero_payload_control
#print axioms OperatorKO7.Meta.Decision.RecursorStopping.zero_payload_control
#check @OperatorKO7.Meta.Decision.RecursorStopping.positiveBenefit_zeroPrice_continues
#print axioms OperatorKO7.Meta.Decision.RecursorStopping.positiveBenefit_zeroPrice_continues
#check @OperatorKO7.Meta.Decision.RecursorStopping.zero_unitCost_control
#print axioms OperatorKO7.Meta.Decision.RecursorStopping.zero_unitCost_control
#check @OperatorKO7.Meta.Decision.RecursorStopping.zero_arity_marginalCost
#print axioms OperatorKO7.Meta.Decision.RecursorStopping.zero_arity_marginalCost
#check @OperatorKO7.Meta.Recursor.RaryDuplicatorLaws.conMassR_zero_arity
#print axioms OperatorKO7.Meta.Recursor.RaryDuplicatorLaws.conMassR_zero_arity

-- Weak versus strict crossing and ties
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_le_crossingPoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weakCrossingPoint_le_crossingPoint
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_le_weakCrossingPoint_succ
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_le_weakCrossingPoint_succ
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weak_tie_iff_strict_threshold_next
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.weak_tie_iff_strict_threshold_next
#check @OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_eq_weak_succ_of_tie
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CostComparison.crossingPoint_eq_weak_succ_of_tie

-- Bounded search exhaustion versus global impossibility
#check @OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiniteCoordinateAlgorithms.boundedWitnessRank?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.certificate_existence_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.certificate_existence_is_required

-- Positive-support versus whole-carrier recovery
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_eq_zero_iff_licensedOnSupport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.conditionalEntropy_eq_zero_iff_licensedOnSupport
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.zeroMass_collision_conditionalEntropy_eq_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.zeroMass_collision_conditionalEntropy_eq_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.fullyNoisyBinary_sufficient_not_licensedOnJointSupport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.fullyNoisyBinary_sufficient_not_licensedOnJointSupport

-- Nonuniform and zero-mass laws
#check @OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.nonuniform_fiber_law_lt_log_fiberMultiplicity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FiberEntropy.nonuniform_fiber_law_lt_log_fiberMultiplicity
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint_default_independent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint_default_independent

-- Changed enumeration order
#check @OperatorKO7.Meta.OperationalInexpressibility.ExecutableResolvingChannel.alphabetSize_enumeration_independent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ExecutableResolvingChannel.alphabetSize_enumeration_independent

-- Pairwise versus global common witnesses
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_pairwise_compatible_capacity_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_pairwise_compatible_capacity_two

-- Classical existence versus executable synthesis
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_iff_capacity_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_iff_capacity_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_some
#check @OperatorKO7.Meta.OperationalInexpressibility.ExecutableLicense.licensedB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ExecutableLicense.licensedB_eq_true_iff

-- Duplicated-target capacity
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.licensed_duplicatedTarget_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.licensed_duplicatedTarget_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.duplicated_target_product_bound_not_tight
#print axioms OperatorKO7.Meta.OperationalInexpressibility.JointTargetCapacity.duplicated_target_product_bound_not_tight

-- Retained history versus current observation
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.revealingObserver_first_sufficient_horizon
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.revealingObserver_first_sufficient_horizon
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.forgettingObserver_first_sufficient_horizon
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.forgettingObserver_first_sufficient_horizon

-- Canonical serialization versus arbitrary parser input
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.padded_successorCertificate_accepted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.padded_successorCertificate_accepted
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.checkSerializedBitsStrict_length_canonical
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateAcceptedSet.checkSerializedBitsStrict_length_canonical

-- Malformed and trailing certificates
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.malformed_rule_rejected
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.malformed_rule_rejected
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.out_of_range_path_rejected
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.out_of_range_path_rejected
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.trailing_words_rejected
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.trailing_words_rejected
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_rejects_trailing
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_rejects_trailing
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_width
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_width
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_payload
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_zero_payload

-- All-input cost bounds
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_bitInspections_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_bitInspections_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted_snd_le_budget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted_snd_le_budget
#check @OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_eq_of_wordStream
#print axioms OperatorKO7.Meta.OperationalInexpressibility.CertificateBitMachine.runBitMachine_eq_of_wordStream

-- Finite reduction-closed embeddings versus arbitrary TRSs
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_no_adapter_realizes_f
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_no_adapter_realizes_f
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_no_adapter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_no_adapter
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.fork_joinable_a_b
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.fork_joinable_a_b

-- Root versus contextual rewriting
#check @OperatorKO7.Meta.OperationalInexpressibility.RaryCertificate.no_strict_certificate_for_G_source
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RaryCertificate.no_strict_certificate_for_G_source
#check @OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorKernel.freeRecursor_root_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorKernel.freeRecursor_root_confluent
#check @OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorContext.freeRecursor_ctx_confluent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorContext.freeRecursor_ctx_confluent

-- Uniqueness transport with collapsed normal endpoints
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.normalForm_injectivity_is_required
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.normalForm_injectivity_is_required
#check @OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.uniqueness_is_required_for_confluence
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ConfluenceTransport.uniqueness_is_required_for_confluence

-- Termination transport without a stutter rank
#check @OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.stutter_descent_is_required_for_termination_transport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.NormalFormFaithfulTransport.stutter_descent_is_required_for_termination_transport

-- Relative obstruction
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_orients
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_orients
#check @OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_not_grammar_denotable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payloadSensitiveOrienter_not_grammar_denotable

-- Positive control: a direct natural-valued contextual measure for the free recursor
#check @OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorContext.rootWeight_context_decreases
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorContext.rootWeight_context_decreases
#check @OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorContext.freeRecursor_ctx_rev_wellFounded
#print axioms OperatorKO7.Meta.OperationalInexpressibility.FreeRecursorContext.freeRecursor_ctx_rev_wellFounded

-- Closing control: hypothesis necessity catalog
#check @OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.hypothesisNecessity_catalog
#print axioms OperatorKO7.Meta.OperationalInexpressibility.HypothesisNecessityCatalog.hypothesisNecessity_catalog
