import OperatorKO7.Meta.ArtsGiesl_ProofLengthBySize
import OperatorKO7.Meta.BenchmarkedPrimitiveRecursionFamily
import OperatorKO7.Meta.ConfessionMethod_Unification
import OperatorKO7.Meta.InformationAccess
import OperatorKO7.Meta.LCELSchema
import OperatorKO7.Meta.LCELStructuralIdentity
import OperatorKO7.Meta.ProofTheoreticRegister
import OperatorKO7.Meta.RecordEmissionNecessity
import OperatorKO7.Meta.RecordEmissionNecessity_BeyondFirstOrder
import OperatorKO7.Meta.Recursor.TRSEquivalence
import OperatorKO7.Meta.ReverseMath.ArtsGieslPi02
import OperatorKO7.Meta.SchemaCanonicalTrace
import OperatorKO7.Meta.SchemaConfessionDominance
import OperatorKO7.Meta.SchemaNormMismatch
import OperatorKO7.Meta.SchemaOffsetAndWrapper
import OperatorKO7.Meta.SchemaSeedCarrierFactorization
import OperatorKO7.Meta.SchemaWitnessOrder

/-!
# Full-anchor gate 1 for the OI paper

Pins 44 declarations cited by the paper that no other gate covers.
Each carries a paired `#check @` and `#print axioms`. Import-and-check only;
this file proves no new content.
-/

set_option maxHeartbeats 1000000

#check @OperatorKO7.Meta.ArtsGieslProofLengthBySize.agProofLength
#print axioms OperatorKO7.Meta.ArtsGieslProofLengthBySize.agProofLength
#check @OperatorKO7.BenchmarkedPRCFamily.fullDuplicating_unique_blocked_complete_member
#print axioms OperatorKO7.BenchmarkedPRCFamily.fullDuplicating_unique_blocked_complete_member
#check @OperatorKO7.ConfessionMethodFamily.all_confession_routes_yield_certified_forgetting_witnesses
#print axioms OperatorKO7.ConfessionMethodFamily.all_confession_routes_yield_certified_forgetting_witnesses
#check @OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.live_computation_channel_unique
#print axioms OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.live_computation_channel_unique
#check @OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.live_computation_vs_terminal_record
#print axioms OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.live_computation_vs_terminal_record
#check @OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.terminalRecordMap
#print axioms OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.terminalRecordMap
#check @OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.terminal_record_recovers_progress_exactly
#print axioms OperatorKO7.InformationAccess.PrimitiveDuplicatorTerm.terminal_record_recovers_progress_exactly
#check @OperatorKO7.InformationAccess.meta_trace_mutual_information_at_terminal
#print axioms OperatorKO7.InformationAccess.meta_trace_mutual_information_at_terminal
#check @OperatorKO7.InformationAccess.progressEntropyBits
#print axioms OperatorKO7.InformationAccess.progressEntropyBits
#check @OperatorKO7.LCELSchema.LCELSlotProfile
#print axioms OperatorKO7.LCELSchema.LCELSlotProfile
#check @OperatorKO7.LCELStructuralIdentity.LCELComparisonWitness.structural_identity
#print axioms OperatorKO7.LCELStructuralIdentity.LCELComparisonWitness.structural_identity
#check @OperatorKO7.LCELStructuralIdentity.LCELQuasiFunctor.transports_realization
#print axioms OperatorKO7.LCELStructuralIdentity.LCELQuasiFunctor.transports_realization
#check @OperatorKO7.ProofTheoreticRegister.dp_confession_is_reflection_family_ascent
#print axioms OperatorKO7.ProofTheoreticRegister.dp_confession_is_reflection_family_ascent
#check @OperatorKO7.ProofTheoreticRegister.dp_confession_not_lawvere_yanofsky_diagonal
#print axioms OperatorKO7.ProofTheoreticRegister.dp_confession_not_lawvere_yanofsky_diagonal
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.architectural_necessity_of_payload_duplication
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.architectural_necessity_of_payload_duplication
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.emitsNewRecordFrame
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.emitsNewRecordFrame
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.no_record_without_duplication_or_generator_erasure
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.no_record_without_duplication_or_generator_erasure
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.primitiveDuplicatorRhs_witnesses_duplication
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.RecordTerm.primitiveDuplicatorRhs_witnesses_duplication
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.record_emission_extension_to_externalized_trace
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.record_emission_extension_to_externalized_trace
#check @OperatorKO7.Meta.Recursor.TRSEquivalence.LicensedQuotientLinearGrowthAgreement
#print axioms OperatorKO7.Meta.Recursor.TRSEquivalence.LicensedQuotientLinearGrowthAgreement
#check @OperatorKO7.Meta.Recursor.TRSEquivalence.recursor_circular_orbit_system_isomorphism
#print axioms OperatorKO7.Meta.Recursor.TRSEquivalence.recursor_circular_orbit_system_isomorphism
#check @OperatorKO7.ReverseMath.artsGieslSctSoundness_isPi02
#print axioms OperatorKO7.ReverseMath.artsGieslSctSoundness_isPi02
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.canonicalTrace
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.canonicalTrace
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.offset_conservation
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.offset_conservation
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.per_step_exchange
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.per_step_exchange
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.ProofEntropyNonDecreasing
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.ProofEntropyNonDecreasing
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.confessedBurdenDoubled
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.confessedBurdenDoubled
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.total_confessed_burden_doubled
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.total_confessed_burden_doubled
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.explicitDescription_linear_gap
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.explicitDescription_linear_gap
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.gaugeEntropy
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.gaugeEntropy
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.inefficiencyCoefficient
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.inefficiencyCoefficient
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.inefficiencyCoefficient_isTheta_quadraticLog
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.inefficiencyCoefficient_isTheta_quadraticLog
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.inefficiencyCoefficient_unbounded_atTop
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.inefficiencyCoefficient_unbounded_atTop
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.counter_unique_retained_coordinate
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.counter_unique_retained_coordinate
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.permutation_gauge_symmetry_package
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.permutation_gauge_symmetry_package
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.wrapperCellWeight
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.wrapperCellWeight
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.wrapperStack
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.BaseDuplicatingSystem.wrapperStack
#check @OperatorKO7.SchemaSeedCarrier.Diagonal
#print axioms OperatorKO7.SchemaSeedCarrier.Diagonal
#check @OperatorKO7.SchemaSeedCarrier.additiveObservable_not_factors
#print axioms OperatorKO7.SchemaSeedCarrier.additiveObservable_not_factors
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.SchemaWitnessTower.OB
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.SchemaWitnessTower.OB
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.SchemaWitnessTower.OB_iff_no_directWhole
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.SchemaWitnessTower.OB_iff_no_directWhole
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.SchemaWitnessTower.kappaLe
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.SchemaWitnessTower.kappaLe
#check @OperatorKO7.StepDuplicating.StepDuplicatingSchema.WLevel
#print axioms OperatorKO7.StepDuplicating.StepDuplicatingSchema.WLevel
