import OperatorKO7.Meta.Methods.OrientationClosure.SeparableSlopesAffineStrata

/-! # SeparableSlopesAffineStrata reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseSlice
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseSlice
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.uEval_unit_cons
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.uEval_unit_cons
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biEvalNat_eq_baseSlices
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biEvalNat_eq_baseSlices
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffineB
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffineB
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.BaseAffine
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.BaseAffine
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_pos
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_pos
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_neg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_neg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decideBaseAffinePositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decideBaseAffinePositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decideBaseAffinePositive_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decideBaseAffinePositive_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failBaseAffine
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failBaseAffine
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failBaseAffine_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failBaseAffine_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decideBaseAffinePositive_residual_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decideBaseAffinePositive_residual_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failBaseAffine_residual_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failBaseAffine_residual_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biMonoSwap
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biMonoSwap
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biSwap
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biSwap
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biEvalNat_biSwap
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biEvalNat_biSwap
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.mem_biSwap
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.mem_biSwap
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.signedSwap
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.signedSwap
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.signedSwap_eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.signedSwap_eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.PayloadAffine
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.PayloadAffine
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decidePayloadAffinePositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decidePayloadAffinePositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decidePayloadAffinePositive_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decidePayloadAffinePositive_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failPayloadAffine
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failPayloadAffine
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failPayloadAffine_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failPayloadAffine_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decidePayloadAffinePositive_residual_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.decidePayloadAffinePositive_residual_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failPayloadAffine_residual_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.failPayloadAffine_residual_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_of_payloadOnly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffine_of_payloadOnly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.payloadAffine_of_baseOnly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.payloadAffine_of_baseOnly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.bilinearPositiveControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.bilinearPositiveControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.bilinearPositiveControl_strata
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.bilinearPositiveControl_strata
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.bilinearPositiveControl_decided
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.bilinearPositiveControl_decided
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffineFailControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffineFailControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffineFailControl_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.baseAffineFailControl_rejected
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.mixedControl_payloadAffine_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.mixedControl_payloadAffine_rejected
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biquadraticControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biquadraticControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biquadraticControl_outside_affine_strata
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesAffineStrata.biquadraticControl_outside_affine_strata
