import OperatorKO7.Meta.Methods.OrientationClosure.FreeOrdinalCalibration

/-! # FreeOrdinalCalibration reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.rank_le_natRank
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.rank_le_natRank
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.rank_lt_omega_of_natRank
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.rank_lt_omega_of_natRank
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.rank_add_le_of_relPow
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.rank_add_le_of_relPow
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.CtxRev
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.CtxRev
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight_le_qw
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight_le_qw
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight_lt_omega
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight_lt_omega
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.le_ctxHeight_of_relPow
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.le_ctxHeight_of_relPow
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.le_two_pow
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.le_two_pow
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight_unbounded
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctxHeight_unbounded
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctx_calibrated_omega
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.ctx_calibrated_omega
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.iSup_ctxHeight
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.iSup_ctxHeight
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.CallRev
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.CallRev
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callRank_lt
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callRank_lt
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callHeight
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callHeight
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callHeight_le
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callHeight_le
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callChain
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.callChain
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.le_callHeight_of_relPow
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.le_callHeight_of_relPow
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.call_calibrated_omega
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.call_calibrated_omega
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.headRank
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.headRank
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeArgs
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeArgs
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.FreeMPO
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.FreeMPO
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpo_recurZero
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpo_recurZero
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpo_recurSucc
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpo_recurSucc
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpo_orients_rootStep
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpo_orients_rootStep
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freePayloadOrd
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freePayloadOrd
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_eq_veblen
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_eq_veblen
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_limit
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_limit
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_fixed
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_fixed
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.one_lt_freeMpoOrd
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.one_lt_freeMpoOrd
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_lt_succ
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_lt_succ
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.pair_lt_freeMpoOrd_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.pair_lt_freeMpoOrd_wrap
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.triple_lt_freeMpoOrd_recur
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.triple_lt_freeMpoOrd_recur
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_arg_lt
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_arg_lt
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freePayloadOrd_lt
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freePayloadOrd_lt
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_lt_of_byPrec
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_lt_of_byPrec
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_strict_of_mpo
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_strict_of_mpo
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_four_isSuccLimit
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_four_isSuccLimit
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_four_fixed
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_four_fixed
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_lt_veblen_four
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_lt_veblen_four
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_lt_veblen_four
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_lt_veblen_four
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.recurTower
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.recurTower
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.iterate_le_freeMpoOrd_tower
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.iterate_le_freeMpoOrd_tower
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_four_zero_eq_nfp
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.veblen_four_zero_eq_nfp
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_cofinal
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.freeMpoOrd_cofinal
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.iSup_freeMpoOrd
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.iSup_freeMpoOrd
#check @OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.mpo_calibration
#print axioms OperatorKO7.Methods.OrientationClosure.FreeOrdinalCalibration.mpo_calibration
