import OperatorKO7.Meta.Methods.OrientationClosure.CertificateControls

/-!
Reach gate for `CertificateControls`: every public declaration with `#check @`
and `#print axioms`.
-/

#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeCertificate_interpretation_canonical
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeCertificate_unique
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.standardKBO_has_no_dependent_certificate
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.cichon_has_no_dependent_certificate
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.kboWithStatus_certificate_canonical
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeRows_erase_kboWithStatus_length
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeRows_erase_kboWithStatus_not_full
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.extractSource
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.extractRHS
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.extractCall
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.extractSource_extracts_call
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.zero_rule_extracts_nothing
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.extractCall_occurs_in_source_rhs
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.call_as_rhs_rejected
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.altered_payload_rhs_rejected
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.resetConnector_control
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.sct_counter_coordinate_strict
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.wrong_sct_base_coordinate_rejected
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.wrong_sct_payload_coordinate_rejected
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.empty_output_not_neutral
#check @OperatorKO7.Methods.OrientationClosure.CertificateControls.pair_only_source_transfer_rejected

#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeCertificate_interpretation_canonical
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeCertificate_unique
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.standardKBO_has_no_dependent_certificate
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.cichon_has_no_dependent_certificate
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.kboWithStatus_certificate_canonical
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeRows_erase_kboWithStatus_length
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.dependentNativeRows_erase_kboWithStatus_not_full
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.extractSource
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.extractRHS
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.extractCall
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.extractSource_extracts_call
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.zero_rule_extracts_nothing
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.extractCall_occurs_in_source_rhs
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.call_as_rhs_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.altered_payload_rhs_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.resetConnector_control
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.sct_counter_coordinate_strict
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.wrong_sct_base_coordinate_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.wrong_sct_payload_coordinate_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.empty_output_not_neutral
#print axioms OperatorKO7.Methods.OrientationClosure.CertificateControls.pair_only_source_transfer_rejected
