import OperatorKO7.Meta.Methods.OrientationClosure.CellClassificationFamilies

/-! # CellClassificationFamilies reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.FailsAt
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.FailsAt
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.CellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.CellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.not_orients_of_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.not_orients_of_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.barrier_cell_excludes_nonstrict_orientation
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.barrier_cell_excludes_nonstrict_orientation
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.barrierCell_of_retention
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.barrierCell_of_retention
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.failsAt_of_zero
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.failsAt_of_zero
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.additive_barrierCell
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.additive_barrierCell
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.additive_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.additive_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_additive_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_additive_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.affine_zero_or_barrierCell
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.affine_zero_or_barrierCell
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.affine_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.affine_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_affine_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_affine_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.quadratic_zero_or_barrierCell
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.quadratic_zero_or_barrierCell
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.quadratic_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.quadratic_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_quadratic_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_quadratic_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.max_gain_eventually_zero_wrap_cost_pos
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.max_gain_eventually_zero_wrap_cost_pos
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.max_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.max_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_max_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_max_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.compositional_transparent_gain_zero_wrap_cost_pos
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.compositional_transparent_gain_zero_wrap_cost_pos
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.compositional_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.compositional_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_compositional_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_compositional_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.crossTerm_zero_or_barrierCell_of_noCrossGrowth
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.crossTerm_zero_or_barrierCell_of_noCrossGrowth
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.crossTerm_eventually_fails_of_bounded
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.crossTerm_eventually_fails_of_bounded
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.crossTerm_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.crossTerm_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_crossTerm_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_crossTerm_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.multilinear_zero_or_barrierCell_of_noStepGrowth
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.multilinear_zero_or_barrierCell_of_noStepGrowth
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.multilinear_eventually_fails_of_dominated
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.multilinear_eventually_fails_of_dominated
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.multilinear_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.multilinear_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_multilinear_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_multilinear_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.polynomial_eventually_fails_of_dominated
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.polynomial_eventually_fails_of_dominated
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.polynomial_cellOrPointwiseFailure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.polynomial_cellOrPointwiseFailure
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_polynomial_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_polynomial_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixD_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixD_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrix2_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrix2_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixMix2_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixMix2_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixFunctional_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixFunctional_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixLexD_orients_dup_step_via_cells
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.no_matrixLexD_orients_dup_step_via_cells
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_recur
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_recur
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_recur_succ
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_recur_succ
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_wrap_recur
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_wrap_recur
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_gainBoundedAt
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.profile_gainBoundedAt
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.grammar_profile_barrierCell_iff
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.grammar_profile_barrierCell_iff
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.grammar_profile_boundedBounded_of_const
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.grammar_profile_boundedBounded_of_const
#check @OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.grammar_orients_iff_no_barrierCell_and_counterStrict
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassificationFamilies.grammar_orients_iff_no_barrierCell_and_counterStrict
