import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsProcessCalculi

/-! # MethodRowsProcessCalculi reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.PiProc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.PiProc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.PiLinearStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.PiLinearStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSize
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSize
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piLinearStep_size
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piLinearStep_size
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piLinearStep_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piLinearStep_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSender
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSender
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piReceiver
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piReceiver
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSession
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSession
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSession_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piSession_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.server
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.server
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.encCounter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.encCounter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.counterDepth
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.counterDepth
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.counterDepth_encCounter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.counterDepth_encCounter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.PiCounterStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.PiCounterStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCounterStep_depth
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCounterStep_depth
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCounterStep_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCounterStep_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationMutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslationMutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.TerminationTranslation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.TerminationTranslation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.TerminationTranslation.sourceWellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.TerminationTranslation.sourceWellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.NatCountdownStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.NatCountdownStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.encCounter_simulates_countdown
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.encCounter_simulates_countdown
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCounterTerminationTranslation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCounterTerminationTranslation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piOperationalTerminationTranslation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piOperationalTerminationTranslation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.piCalculusTerminationTranslation_methodIdentity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.LMTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.LMTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBoundZeroOccurs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBoundZeroOccurs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSubstZero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSubstZero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSubstZero_eq_self_of_not_occurs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSubstZero_eq_self_of_not_occurs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.LMBeta
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.LMBeta
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBeta_substitution_exact
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBeta_substitution_exact
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSize
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSize
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBeta_size
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBeta_size
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBeta_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmBeta_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.cps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.cps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSize_cps_pos
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lmSize_cps_pos
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSMutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPSMutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuCPSTerminationTranslation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuCPSTerminationTranslation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsProcessCalculi.lambdaMuSNViaCPS_methodIdentity
