import OperatorKO7.Meta.Methods.OrientationClosure.VectorComparison

/-!
# VectorComparison reach and axiom check

Paired declaration reach and axiom checks for `VectorComparison.lean`.
-/

#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.allStrict_requires_all_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.allStrict_requires_all_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.lex_requires_primary_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.lex_requires_primary_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.strictPrimaryWeak_requires_primary_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.strictPrimaryWeak_requires_primary_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.primarySomeDecrease_cyclic
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.primarySomeDecrease_cyclic
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.vector_order_separation
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.vector_order_separation
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.counter_vector_orients_both_standard_orders
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.counter_vector_orients_both_standard_orders
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.payload_primary_blocks_lex
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.payload_primary_blocks_lex
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.payload_coordinate_blocks_allStrict
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.payload_coordinate_blocks_allStrict
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.matrix_scalarizations_are_dominated
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.matrix_scalarizations_are_dominated
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.counterThenPayloadMeasure
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.counterThenPayloadMeasure
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.counterThenPayload_orients_vecLexLt
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.counterThenPayload_orients_vecLexLt
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.counterThenPayload_secondary_reads_payload
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.counterThenPayload_secondary_reads_payload
#check @OperatorKO7.Methods.OrientationClosure.VectorComparison.lex_orientation_keeps_later_payload
#print axioms OperatorKO7.Methods.OrientationClosure.VectorComparison.lex_orientation_keeps_later_payload
