import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsLabelingBounds

/-! # MethodRowsLabelingBounds reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CtxClosure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CtxClosure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_iff_ctxClosure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_iff_ctxClosure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_measure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_measure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_wf_of_measure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_wf_of_measure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.evalList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.evalList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.evalList_eq_map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.evalList_eq_map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.Alg.eval_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSymList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSymList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSymList_eq_map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSymList_eq_map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mapSym_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linSum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linSum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linForm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linForm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linSum_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linSum_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linForm_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linForm_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linAlg_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linAlg_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RulesP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RulesP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.PRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.PRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.PStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.PStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.inR
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.inR
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_iff_pStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_iff_pStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.acc_step_of_acc_pStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.acc_step_of_acc_pStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.labList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.labList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.labList_eq_map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.labList_eq_map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_lab
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_lab
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.blindAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.blindAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eval_lab_blind
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eval_lab_blind
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.LRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.LRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.LStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.LStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.IsModel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.IsModel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eval_eq_of_pStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eval_eq_of_pStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_lift_model
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lab_lift_model
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.acc_of_lab_model
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.acc_of_lab_model
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_lstep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_lstep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lstep_wf_of_interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.lstep_wf_of_interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sn_of_model_labelling
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sn_of_model_labelling
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mem_freeRecursorTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.mem_freeRecursorTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.FreeTerminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.FreeTerminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SemLabData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SemLabData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SemLabData.base
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SemLabData.base
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabeling_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabeling_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterModel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterModel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterLab
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterLab
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterC0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterC0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterCoef
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterCoef
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterCoef_pos
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterCoef_pos
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterModel_isModel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.counterModel_isModel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fz
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fz
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fw
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fw
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sub3
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sub3
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.constLab
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.constLab
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingMutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabelingMutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabeling_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.semanticLabeling_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLab
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLab
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_eval_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_eval_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RootChanges
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RootChanges
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fcRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fcRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_model_fc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_model_fc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_of_fcStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.step_of_fcStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fcStep_of_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.fcStep_of_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sn_of_fc_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sn_of_fc_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sn_of_rootLabelling
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sn_of_rootLabelling
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sum_lt_of_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.sum_lt_of_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.getD_le_of_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.getD_le_of_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg_orients
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg_orients
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabeling_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabeling_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.succRule_rootChanges
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.succRule_rootChanges
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.zeroRule_rootChanges
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.zeroRule_rootChanges
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_not_model
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootAlg_not_model
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabeling_linear_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabeling_linear_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpLinAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpLinAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linSum_one
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.linSum_one
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.blind_cpLinAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.blind_cpLinAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabeling_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabeling_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.rootLabelingWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.pStep_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.pStep_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.EqCongr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.EqCongr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_arg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_arg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_args
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_args
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqSetoid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqSetoid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.EqClass
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.EqClass
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quotAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quotAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forall₂_map_of
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forall₂_map_of
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quotAlg_eval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quotAlg_eval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quotAlg_model
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quotAlg_model
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLab
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLab
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.pStep_nil_false
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.pStep_nil_false
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.eqCongr_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeEqs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeEqs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vdAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vdAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vdAlg_model
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vdAlg_model
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_invariant
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_invariant
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_mk_out
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_mk_out
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_quot_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_quot_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_quot_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.vd_quot_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SelfLabData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SelfLabData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SelfLabData.base
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SelfLabData.base
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SelfLabData.base_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SelfLabData.base_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquational_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquational_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquationalWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquational_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.selfLabelingEquational_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.acc_not_self
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.acc_not_self
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.le_sum_of_mem'
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.le_sum_of_mem'
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CStepN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CStepN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.QuasiDecreasingBy
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.QuasiDecreasingBy
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.QuasiDecreasing
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.QuasiDecreasing
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.QuasiDecreasingBy.terminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.QuasiDecreasingBy.terminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CallRel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CallRel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.transGen_of_transGen_or
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.transGen_of_transGen_or
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasing_iff_callRel_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasing_iff_callRel_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ofTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ofTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cStepN_succ_ofTRS_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cStepN_succ_ofTRS_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cStep_ofTRS_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cStep_ofTRS_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasing_ofTRS_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasing_ofTRS_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_of_properSubterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_of_properSubterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_closure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_closure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_of_cStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.algGt_of_cStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_app_inv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.ctxClosure_app_inv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.isSubterm_trans
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.isSubterm_trans
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.isSubterm_size_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.isSubterm_size_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.properSubterm_size_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.properSubterm_size_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.properSubterm_trans
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.properSubterm_trans
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeCTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeCTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingness_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingness_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg_sub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.cpAlg_sub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.CSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveH
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveH
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveG
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveG
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveCTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveCTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveC0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveC0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_eval_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_eval_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_sub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_sub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveAlg_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.live_quasiDecreasing
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.live_quasiDecreasing
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.live_step_ga
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.live_step_ga
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveCTRS_no_step_b
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveCTRS_no_step_b
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveCTRS_no_step_hb
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.liveCTRS_no_step_hb
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.live_no_step_gb
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.live_no_step_gb
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS_no_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS_no_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS_terminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS_terminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS_not_quasiDecreasing
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.loopCTRS_not_quasiDecreasing
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingnessWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.subtermGt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.subtermGt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingness_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.quasiDecreasingness_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RaisedTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RaisedTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RaisedTerm.erase
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RaisedTerm.erase
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RaisedTerm.size
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.RaisedTerm.size
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseQW
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseQW
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_raiseQW
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_raiseQW
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.size_raiseQW
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.size_raiseQW
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.relPow_raise
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.relPow_raise
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.relPow_le_height
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.relPow_le_height
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.FreeSchemaTerminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.FreeSchemaTerminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeSchemaTerminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeSchemaTerminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeSchemaTerminates_of_raisedHeight
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.freeSchemaTerminates_of_raisedHeight
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.one_le_two_pow
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.one_le_two_pow
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.self_lt_two_pow
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.self_lt_two_pow
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.exists_linear_lt_pow
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.exists_linear_lt_pow
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.no_linear_raised_certificate
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.no_linear_raised_certificate
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBounds_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBounds_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsCountdown
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsCountdown
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsCountdown_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsCountdown_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsCountdown_bound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsCountdown_bound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBoundsWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBounds_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchBounds_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBounds_consistency
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBounds_consistency
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBounds_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBounds_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBoundsWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBounds_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.raiseConsistencyMatchBounds_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaLhsZero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaLhsZero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaLhsSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaLhsSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaRhsSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaRhsSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SymTag
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.SymTag
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.MatchAutomaton
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.MatchAutomaton
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.MatchAutomaton.run
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.MatchAutomaton.run
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchHeightAutomaton
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.matchHeightAutomaton
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBounds_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBounds_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBoundsWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBounds_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.leftLinearMatchBounds_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.labelPredict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.labelPredict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabeling_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabeling_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_labelPredict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.erase_labelPredict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.payloadCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.payloadCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabelingWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabeling_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.predictiveLabeling_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaRhsZero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.schemaRhsZero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosures_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosures_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresChained
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresChained
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresChained_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresChained_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresChained_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresChained_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosuresWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosures_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsLabelingBounds.forwardClosures_mutation
