/-
Permanent reach and axiom gate for the exact P3.6 residual embedding.
-/
import OperatorKO7.Meta.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary

#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.mk
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.mk
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.coeff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.coeff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.bDeg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.bDeg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.sDeg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.BiMono.sDeg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.mk
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.mk
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.pos
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.pos
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.neg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.neg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biMulMono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biMulMono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biMul
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biMul
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biScale
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biScale
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.square
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.square
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_append
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_append
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_biScale
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_biScale
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_map_biMulMono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_map_biMulMono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_biMul
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.biEvalNat_biMul
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.eval_square
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.SignedBiPoly.eval_square
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.mk
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.mk
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.coeff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.coeff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.bDeg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.bDeg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.sDeg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.IntBiMono.sDeg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.intBiEval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.intBiEval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.intPositivePart
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.intPositivePart
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.intNegativePart
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.intNegativePart
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.int_parts_sub
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.int_parts_sub
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positivePart
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positivePart
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.negativePart
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.negativePart
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signedOfIntPoly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signedOfIntPoly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positive_negative_eval_sub
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positive_negative_eval_sub
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signedOfIntPoly_eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signedOfIntPoly_eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.liftPositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.liftPositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.liftNegative
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.liftNegative
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualSentinelHigh
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualSentinelHigh
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualSentinelLow
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualSentinelLow
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.monomialCounterPoly_two_one_two_zero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.monomialCounterPoly_two_one_two_zero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.monomialCounterPoly_two_one_two_one
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.monomialCounterPoly_two_one_two_one
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper_wLin
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper_wLin
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper_no_ySquare
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper_no_ySquare
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper_no_yPayload
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualWrapper_no_yPayload
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_append
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_append
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_map_liftPositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_map_liftPositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_map_liftNegative
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_map_liftNegative
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_encodeResidual
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.rEval_encodeResidual
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.nDegMax_append
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.nDegMax_append
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.nDegMax_liftPositive_le_one
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.nDegMax_liftPositive_le_one
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.nDegMax_liftNegative
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.nDegMax_liftNegative
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_nDegMax
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_nDegMax
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_not_allHigh
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_not_allHigh
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_sepDiff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_sepDiff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_decision_is_open
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_decision_is_open
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualGoal_encode_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualGoal_encode_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encoded_orients_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encoded_orients_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.int_square_pos_iff_ne_zero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.int_square_pos_iff_ne_zero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualGoal_square_iff_noZero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residualGoal_square_iff_noZero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residual_open_class_contains_signed_bivariate_positivity
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.residual_open_class_contains_signed_bivariate_positivity
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.mixedControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.mixedControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_empty_control
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_empty_control
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_positive_constant_control
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_positive_constant_control
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_negative_constant_control
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_negative_constant_control
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_cancellation_control
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.signed_cancellation_control
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.mixedControl_eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.mixedControl_eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.mixedControl_signed_eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.mixedControl_signed_eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.square_control_zero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.square_control_zero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.square_control_nonzero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.square_control_nonzero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positiveControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positiveControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.zeroControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.zeroControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positiveControl_orients
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.positiveControl_orients
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.zeroControl_fails_at_one
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.zeroControl_fails_at_one
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.zeroControl_is_open
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.zeroControl_is_open
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_counter_independent
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDiophantineBoundary.encodeResidual_counter_independent

