import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityLabelingSorted

/-! # RowNecessityLabelingSorted reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabelingLabelLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabelingLabelLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabelingNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabelingNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabelingNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabelingNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabeling_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.semanticLabeling_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingRecurLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingRecurLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingRecurLens_set_linear
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingRecurLens_set_linear
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabelingNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabeling_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rootLabeling_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalReadingLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalReadingLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalZeroReading_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalZeroReading_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquationalNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquational_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.selfLabelingEquational_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessPoint
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessPoint
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessRow
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessRow
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessPointLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessPointLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_apply
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_apply
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessRow_below
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessRow_below
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_below
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_below
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingness_eval_le_of_isSubterm
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingness_eval_le_of_isSubterm
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingness_properSubterm_point_eval_le
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingness_properSubterm_point_eval_le
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessRow_not_contractum
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessRow_not_contractum
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessReducedOrder_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingnessNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingness_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiDecreasingness_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBoundsNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBounds_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matchBounds_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsSysLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsSysLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsEmptySys_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsEmptySys_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBoundsNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBounds_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.raiseConsistencyMatchBounds_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBoundsNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBounds_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftLinearMatchBounds_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingSysLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingSysLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingEmptySys_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingEmptySys_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabelingNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabeling_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.predictiveLabeling_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosuresNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosures_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.forwardClosures_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPRecurLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPRecurLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPRecurLens_set_blocked
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPRecurLens_set_blocked
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDPNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDP_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.contextSensitiveDP_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_zeroRule_not_duplicating
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_zeroRule_not_duplicating
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_zeroRule_size_lt
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_zeroRule_size_lt
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_zeroRule_sn
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_zeroRule_sn
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNonduplicatingControl_holds
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNonduplicatingControl_holds
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroductionNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.typeIntroduction_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistence_accepts_all
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistence_accepts_all
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistenceNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistenceNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistenceNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistenceNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistence_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistence_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistence_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.manySortedPersistence_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDPNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDPNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDPNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDPNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDP_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDP_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDP_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.orderSortedDP_no_feature_control
