import OperatorKO7.Meta.Methods.OrientationClosure.PolynomialOrientationDecision

/-! # PolynomialOrientationDecision reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.UMono
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.UMono
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.WMono
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.WMono
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.RMono
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.RMono
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_append
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_append
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rAtBN
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rAtBN
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rAtSN
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rAtSN
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wAtY0
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wAtY0
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_rAtBN
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_rAtBN
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_rAtSN
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_rAtSN
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_wAtY0
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_wAtY0
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wLin
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wLin
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.nDegMax
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.nDegMax
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.HasYSquare
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.HasYSquare
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.HasYPayload
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.HasYPayload
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.AllHigh
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.AllHigh
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_ge_mem
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_ge_mem
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ge_mem
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ge_mem
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_ge_wLin_mul
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_ge_wLin_mul
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wLin_ge_mem
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wLin_ge_mem
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.nDeg_le_nDegMax
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.nDeg_le_nDegMax
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.nDegMax_tail_le
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.nDegMax_tail_le
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.exists_growing_of_nDegMax
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.exists_growing_of_nDegMax
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_counter_const
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_counter_const
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.OrientsSucc
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.OrientsSucc
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.OrientsZero
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.OrientsZero
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_mono
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_mono
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_normal
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_normal
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_supermod
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_supermod
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_zero_counter_of_allHigh
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_zero_counter_of_allHigh
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_high
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_high
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.orientsSucc_iff_wZero
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.orientsSucc_iff_wZero
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.orientsSucc_iff_wOne
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.orientsSucc_iff_wOne
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.orientsSucc_iff_high
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.orientsSucc_iff_high
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.pow_add_mul_sub_le
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.pow_add_mul_sub_le
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ratio_pow_le
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ratio_pow_le
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ratio_aux
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ratio_aux
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ratio
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ratio
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.leadFailN
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.leadFailN
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.leading_excludes
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.leading_excludes
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.yPayload_excludes
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.yPayload_excludes
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_ge_sq
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_ge_sq
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ge_counter
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_ge_counter
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ySquareFailN
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ySquareFailN
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ySquare_excludes
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ySquare_excludes
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.coeffAt
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.coeffAt
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uDeg
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uDeg
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_eq_sum
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.uEval_eq_sum
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.leadCoeff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.leadCoeff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.horner_split
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.horner_split
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.horner_sign
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.horner_sign
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.diffCoeff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.diffCoeff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.diff_sum_eq
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.diff_sum_eq
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.diff_abs_sum_le
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.diff_abs_sum_le
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.checkBound
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.checkBound
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ltAllB
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ltAllB
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ltAllB_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.ltAllB_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.firstFail
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.firstFail
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.firstFail_spec
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.firstFail_spec
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.failSuccAff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.failSuccAff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.failSuccAff_spec
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.failSuccAff_spec
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff_spec
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff_spec
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff_eq_none_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff_eq_none_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff_unit_ne_none
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccAff_unit_ne_none
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccUnit
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccUnit
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccUnit_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideSuccUnit_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.failSuccUnit_spec
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.failSuccUnit_spec
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideZero
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideZero
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideZero_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideZero_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideZero_false_witness
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideZero_false_witness
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.polyInterpretation
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.polyInterpretation
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rootRuleOrients_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rootRuleOrients_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideRootUnit
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideRootUnit
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideRootUnit_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.decideRootUnit_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.regionW
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.regionW
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.regionR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.regionR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_regionW
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_regionW
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_regionR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_regionR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.region_decides
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.region_decides
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.region_decides_agrees
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.region_decides_agrees
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.forall_linear_lt_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.forall_linear_lt_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.affineW
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.affineW
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.multilinearR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.multilinearR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_affineW_zero
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_affineW_zero
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_multilinearR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_multilinearR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.multilinear_affine_classification
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.multilinear_affine_classification
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.affine_retentive_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.affine_retentive_rejected
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.doubled_wrapper_decided
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.doubled_wrapper_decided
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.doubled_wrapper_orients
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.doubled_wrapper_orients
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.doubled_wrapper_unit_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.doubled_wrapper_unit_rejected
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residualW
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residualW
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residualR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residualR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residualRFail
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residualRFail
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_residualW
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_residualW
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_residualR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_residualR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residual_orienting_member
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residual_orienting_member
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residual_nonorienting_member
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.residual_nonorienting_member
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.sig_decideRootUnit_iff
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.sig_decideRootUnit_iff
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.quadraticR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.quadraticR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_affineW
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.wEval_affineW
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_quadraticR_base
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_quadraticR_base
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_quadraticR
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.rEval_quadraticR
#check @OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.quadratic_retentive_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.PolynomialOrientationDecision.quadratic_retentive_rejected
