import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsDependencyPairs

/-! # MethodRowsDependencyPairs reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.freeArity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.freeArity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FCall
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FCall
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FProblem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FProblem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FreeTerminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.FreeTerminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.free_finiteDP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.free_finiteDP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.succRule_rhs_call
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.succRule_rhs_call
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSource
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSource
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpTarget
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpTarget
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.free_dpPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.free_dpPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.finiteDP_empty
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.finiteDP_empty
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterion_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterion_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterionWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.payloadProj
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.payloadProj
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterion_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpSubtermCriterion_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.LinearData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.LinearData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linEval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linEval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedEval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedEval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linList_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linList_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedList_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedList_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.RulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.RulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.PairsStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.PairsStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linEval_step_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linEval_step_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedEval_argStep_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.markedEval_argStep_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linearPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linearPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linear_terminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linear_terminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.pairsStrict_dpPairs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.pairsStrict_dpPairs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_wrap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_c_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_succ0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_succ0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_wrap0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_wrap0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_wrap1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_wrap1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_recur0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_recur0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_recur1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_recur1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_recur2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_a_recur2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_mc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_mc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_ma0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_ma0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_ma1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_ma1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_ma2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_ma2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_rulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_rulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.free_pair_shape
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.free_pair_shape
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_pairsStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterLinear_pairsStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_c
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_c
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_a
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_a
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_mc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_mc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_ma0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_ma0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_ma1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_ma1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_ma2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_ma2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_rulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_rulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_pairsStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterBaseLinear_pairsStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.retainLinear
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.retainLinear
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.retainLinear_not_rulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.retainLinear_not_rulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_c
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_c
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_a
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_a
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_mc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_mc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_ma
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_ma
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_markedList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_markedList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_markedEval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_markedEval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_rulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_rulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_not_pairsStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.blindLinear_not_pairsStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessor_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessor_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sepSource
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sepSource
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sepTarget
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sepTarget
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessorWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessor_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionPairProcessor_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterLinear
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterLinear
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterLinear_c
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterLinear_c
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterLinear_a
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterLinear_a
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.filterList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.size_filterTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.size_filterTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFiltering_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFiltering_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_c
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_c
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_succ0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_succ0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_wrap0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_wrap0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_wrap1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_wrap1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_recur0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_recur0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_recur1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_recur1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_recur2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.fw_a_recur2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFilteringWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterOnlyFilter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.counterOnlyFilter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.baseOnlyFilter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.baseOnlyFilter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFiltering_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpArgumentFiltering_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessors_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessors_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessorsWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.deleteAllProcessor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.deleteAllProcessor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessors_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpNeutralProcessors_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linearTriple
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.linearTriple
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.triple_finiteDP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.triple_finiteDP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriples_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriples_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriplesWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriples_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpReductionTriples_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.ProcKind
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.ProcKind
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.procOut
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.procOut
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.procCond
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.procCond
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.proc_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.proc_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.runProcs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.runProcs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.chainCond
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.chainCond
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.runProcs_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.runProcs_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassification_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassification_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassificationWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassification_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.dpProcessorClassification_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopArgs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopArgs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_vars
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_vars
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_defined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_defined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoop_depPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoop_depPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.not_properSubterm_of_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.not_properSubterm_of_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.mem_selfLoopGraph
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.mem_selfLoopGraph
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopGraph_idem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopGraph_idem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_not_sct
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_not_sct
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_not_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.selfLoopRecTRS_not_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscape_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscape_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscapeWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscape_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsDependencyPairs.sizeChangeTerminationEscape_mutation
