import OperatorKO7.Meta.Methods.OrientationClosure.SourceChainSoundness

/-!
# SourceChainSoundness reach and axiom check

Paired declaration reach and axiom checks for `SourceChainSoundness.lean`.
-/

#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.succDepth
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.succDepth
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.recursiveCallRank
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.recursiveCallRank
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeRecursiveCallPair
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeRecursiveCallPair
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeCallOccurrence
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeCallOccurrence
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall_some_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall_some_iff
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_iff_extract
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_iff_extract
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_has_source
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_has_source
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_rank_decreases
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_rank_decreases
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.freeRecursiveCallPair_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall_zero_rule_none
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall_zero_rule_none
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall_successor_exact
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.extractRecursiveCall_successor_exact
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainStep
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainStep
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.connectorStar_weak
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.connectorStar_weak
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.chainStep_strict
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.chainStep_strict
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.chainStep_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.chainStep_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.source_wellFounded_of_lexBridge
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.source_wellFounded_of_lexBridge
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.pairFreeLoopSource
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.pairFreeLoopSource
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.emptyPair
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.emptyPair
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.emptyPair_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.emptyPair_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.pairFreeLoopSource_not_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.pairFreeLoopSource_not_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.pair_wellFounded_does_not_imply_source_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.pair_wellFounded_does_not_imply_source_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeRecursiveCallPair.successor
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeRecursiveCallPair.successor
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeCallOccurrence.successor
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.FreeCallOccurrence.successor
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.mk
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.mk
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.weak
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.weak
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.strict
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.strict
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.weak_refl
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.weak_refl
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.weak_trans
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.weak_trans
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.strict_reverse_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.strict_reverse_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.pair_strict
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.pair_strict
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.connector_weak
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.connector_weak
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.strict_weak
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.ChainReductionPair.strict_weak
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.mk
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.mk
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.primary
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.primary
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.secondary
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.secondary
#check @OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.decreases
#print axioms OperatorKO7.Methods.OrientationClosure.SourceChainSoundness.SourceLexBridge.decreases
