import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsSubstrate

/-! # MethodRowsSubstrate reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SRSStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SRSStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.srsStep_length
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.srsStep_length
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sumRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sumRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rhs_length_le_sumRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rhs_length_le_sumRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.srsStep_length_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.srsStep_length_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.Rotation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.Rotation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rotation_length
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rotation_length
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rotation_refl
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rotation_refl
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.CycleStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.CycleStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleStep_length_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleStep_length_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleStep_of_srsStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleStep_of_srsStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.srs_wf_of_cycle_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.srs_wf_of_cycle_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swapRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swapRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones_append
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones_append
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01_zero_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01_zero_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01_one_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01_one_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones_one_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones_one_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones_zero_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ones_zero_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01_append_swap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.inv01_append_swap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_srs_decreases
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_srs_decreases
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_srs_terminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_srs_terminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_cycle_loop
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_cycle_loop
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_cycle_not_terminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.swap_cycle_not_terminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewriting_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewriting_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.deleteRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.deleteRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.delete_cycle_decreases
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.delete_cycle_decreases
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.delete_cycle_terminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.delete_cycle_terminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.StringMethodData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.StringMethodData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.CompositionalLength
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.CompositionalLength
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.leafChain
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.leafChain
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.leafChain_length
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.leafChain_length
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.dup_length_gap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.dup_length_gap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.encoding_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.encoding_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish_append_inj
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish_append_inj
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish_injective
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish_injective
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unaryRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unaryRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.succPow
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.succPow
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish_succPow
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polish_succPow
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unary_rule_simulated
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unary_rule_simulated
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unary_srs_decreases
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unary_srs_decreases
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unary_srs_terminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.unary_srs_terminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polishData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polishData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polishData_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.polishData_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.degenerateStringData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.degenerateStringData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicability_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicability_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicabilityWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicability_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.stringRewritingInapplicability_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicability_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicability_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicabilityWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicability_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cycleRewritingInapplicability_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.EqStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.EqStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ECongr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ECongr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ModStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ModStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.modStep_of_contextStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.modStep_of_contextStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.wf_of_modStep_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.wf_of_modStep_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.freeVars
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.freeVars
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.RegularEquations
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.RegularEquations
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_rootStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_rootStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_plug_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_plug_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_contextStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_contextStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_plug_eq
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_plug_eq
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.commEquations
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.commEquations
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_eqStep_comm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_eqStep_comm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_eCongr_comm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_eCongr_comm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_modStep_comm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.qw_modStep_comm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.comm_modStep_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.comm_modStep_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.RecurFree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.RecurFree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.recurFree_plug
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.recurFree_plug
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.not_contextStep_of_recurFree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.not_contextStep_of_recurFree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.nfLeft
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.nfLeft
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.nfRight
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.nfRight
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.comm_merges_normal_forms
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.comm_merges_normal_forms
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.loopEquations
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.loopEquations
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.commEquations_regular
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.commEquations_regular
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.loopEquations_regular
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.loopEquations_regular
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.loop_modStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.loop_modStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativity_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativity_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativityWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativity_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.equationalQuotientNonConservativity_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.replaceAll
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.replaceAll
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.Occurs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.Occurs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SharedStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SharedStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rtg_plug
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.rtg_plug
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.tg_plug
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.tg_plug
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.tg_of_rtg_tg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.tg_of_rtg_tg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.replaceAll_rtg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.replaceAll_rtg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_wrap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.occurs_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.replaceAll_tg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.replaceAll_tg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharedStep_simulates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharedStep_simulates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharedStep_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharedStep_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.contextStep_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.contextStep_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.costRedex
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.costRedex
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.costContractum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.costContractum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cost_rootStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.cost_rootStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharing_cost_control
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharing_cost_control
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyamaReplaceAll
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyamaReplaceAll
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaOccurs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaOccurs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaShared
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.ToyamaShared
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyamaStart
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyamaStart
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.acc_irrefl
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.acc_irrefl
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_term_not_acc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_term_not_acc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_leaf_occurs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_leaf_occurs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_leaf_not_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_leaf_not_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_leaves_normal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_leaves_normal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_g01_case
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_g01_case
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_shared_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_shared_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_shared_acc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_shared_acc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_sharing_nonconservative
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.toyama_sharing_nonconservative
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SharingPolicy
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.SharingPolicy
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.policyStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.policyStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativity_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativity_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativityWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativity_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSubstrate.sharingNonConservativity_mutation
