import OperatorKO7.Meta.Methods.OrientationClosure.SeparableSlopesMonomialStratum

/-! # SeparableSlopesMonomialStratum reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.MonomialDifference
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.MonomialDifference
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monomialDifferenceB
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monomialDifferenceB
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monomialDifference_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monomialDifference_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonoPairPositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonoPairPositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonomialDifferencePositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonomialDifferencePositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonoPairPositive_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonoPairPositive_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonoPair
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonoPair
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonoPair_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonoPair_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonomialDifference
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonomialDifference
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonomialDifferencePositive_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonomialDifferencePositive_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonomialDifferencePositive_residual_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.decideMonomialDifferencePositive_residual_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonomialDifference_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonomialDifference_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonomialDifference_residual_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.failMonomialDifference_residual_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectControl_strata
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectControl_strata
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectControl_decided
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectControl_decided
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl_decided
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl_decided
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl_strata
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl_strata
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl_residual
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairAcceptControl_residual
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectGrowing_decided
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPairRejectGrowing_decided
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPair_decision_table
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesMonomialStratum.monoPair_decision_table
