import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsOtherCalculi

/-! # MethodRowsOtherCalculi reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_zero_view
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_zero_view
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_zero_const
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_zero_const
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succ_view
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succ_view
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_wrap_view
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_wrap_view
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_recur_view
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_recur_view
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_truncAt_of_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_truncAt_of_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.wrapIter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.wrapIter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.succIter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.succIter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_wrapIter_self
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_wrapIter_self
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_wrapIter_of_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_wrapIter_of_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succIter_self
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succIter_self
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succIter_of_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succIter_of_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succIter_eq_of_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_succIter_eq_of_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.wrapIter_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.wrapIter_wrap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.InfinitaryTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.InfinitaryTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.omegaTower
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.omegaTower
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_dupStage_congruent
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.truncAt_dupStage_congruent
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_trunks
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_trunks
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.ctorTag
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.ctorTag
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_zero_ne_one
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_zero_ne_one
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.InfDupStepAt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.InfDupStepAt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.ConvergesTo
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.ConvergesTo
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.finiteFragment_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.finiteFragment_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infiniteTree_converges
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infiniteTree_converges
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.RootActiveStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.RootActiveStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.rootActive_loop_control
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.rootActive_loop_control
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTerminationWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.InfDupStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.InfDupStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_infDupStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.dupStage_infDupStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infDupStep_not_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infDupStep_not_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.infinitaryRewritingTermination_methodIdentity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiSymCost
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiSymCost
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCostList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCostList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCostList_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCostList_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCostList_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCostList_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost_toA
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiCost_toA
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_dup
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_dup
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_succ_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_succ_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_wrapLeft_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_wrapLeft_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_wrapRight_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_wrapRight_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_recurBase_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_recurBase_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_recurStep_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_recurStep_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_recurCounter_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_recurCounter_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_context_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_context_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_root_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_root_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_contextStep_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.hotiFreeCost_contextStep_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.CostSizeTupleCertificate
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.CostSizeTupleCertificate
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.CostSizeTupleCertificate.wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.CostSizeTupleCertificate.wellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationCertificate
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretationCertificate
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.typedIteratorRelation_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.typedIteratorRelation_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsOtherCalculi.higherOrderTupleInterpretation_methodIdentity
