import OperatorKO7.Meta.Methods.OrientationClosure.DirectFamilyHypothesisNecessity

/-! # DirectFamilyHypothesisNecessity reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectBarrierFamily
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectBarrierFamily
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.allDirectBarrierFamilies
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.allDirectBarrierFamilies
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.allDirectBarrierFamilies_length
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.allDirectBarrierFamilies_length
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.allDirectBarrierFamilies_nodup
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.allDirectBarrierFamilies_nodup
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.mem_allDirectBarrierFamilies
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.mem_allDirectBarrierFamilies
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DupOrientsBy
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DupOrientsBy
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterWeight
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterWeight
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterWeight_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterWeight_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepWeight
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepWeight
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepWeight_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepWeight_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.unbounded_of_orients_rightRetaining
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.unbounded_of_orients_rightRetaining
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepChain
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepChain
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.unbounded_of_orients_leftRetaining
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.unbounded_of_orients_leftRetaining
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.not_orients_of_unbounded_of_eventualFailure
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.not_orients_of_unbounded_of_eventualFailure
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeWeight
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeWeight
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeWeight_neg
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeWeight_neg
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeOrderedAdditive
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeOrderedAdditive
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeOrderedAdditive_not_attained
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeOrderedAdditive_not_attained
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeOrderedAdditive_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeOrderedAdditive_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveAttainment_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveAttainment_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveAttainment_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveAttainment_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.OrderedAdditiveNoRetention
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.OrderedAdditiveNoRetention
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.OrderedAdditiveNoRetention.WrapRetention
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.OrderedAdditiveNoRetention.WrapRetention
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.OrderedAdditiveNoRetention.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.OrderedAdditiveNoRetention.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveWrapRetention_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveWrapRetention_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailWeight
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailWeight
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailWeight_nonneg
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailWeight_nonneg
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailAdditive
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailAdditive
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailAdditive_not_retention
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailAdditive_not_retention
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailAdditive_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.retentionFailAdditive_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveWrapRetention_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveWrapRetention_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoRetention
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoRetention
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoRetention.WrapperRetention
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoRetention.WrapperRetention
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawWrapperRetention_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawWrapperRetention_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.botRightDirectLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.botRightDirectLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.botRightDirectLaw_not_retention
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.botRightDirectLaw_not_retention
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawWrapperRetention_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawWrapperRetention_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoGain
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoGain
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoGain.BoundedCounterGain
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DirectLawNoGain.BoundedCounterGain
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawBoundedCounterGain_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawBoundedCounterGain_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossCoupledDirectLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossCoupledDirectLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossCoupledDirectLaw_not_boundedGain
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossCoupledDirectLaw_not_boundedGain
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawBoundedCounterGain_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawBoundedCounterGain_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AdditiveNoWrapPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AdditiveNoWrapPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additive_wrapPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additive_wrapPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledWeight
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledWeight
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledMeasure
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledMeasure
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledMeasure_not_transparent
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledMeasure_not_transparent
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledMeasure_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compCoupledMeasure_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transparentSuccessor_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transparentSuccessor_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transparentSuccessor_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transparentSuccessor_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm2
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm2
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm2.WrapSubterm2
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm2.WrapSubterm2
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm2.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm2.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositionalWrapSubterm2_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositionalWrapSubterm2_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapWeight
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapWeight
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapCompositional
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapCompositional
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapCompositional_not_subterm2
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapCompositional_not_subterm2
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapCompositional_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.leftWrapCompositional_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositionalWrapSubterm2_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositionalWrapSubterm2_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm1
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CompositionalNoSubterm1
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositional_wrapSubterm1_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositional_wrapSubterm1_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapLeftPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapLeftPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapLeftPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapLeftPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapRightPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.AffineNoWrapRightPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterAffine
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterAffine
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepAffine
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepAffine
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapLeftPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapLeftPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapRightPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapRightPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.WrapFirstFreeCoefficients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.WrapFirstFreeCoefficients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.WrapSecondFreeCoefficients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.WrapSecondFreeCoefficients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoefficientConditionOrder
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoefficientConditionOrder
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weighted_barrier_of_wrapPositivity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weighted_barrier_of_wrapPositivity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapFirst_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapFirst_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapSecond_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapSecond_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapFirstFreeWitness
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapFirstFreeWitness
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapSecondFreeWitness
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.wrapSecondFreeWitness
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedConditionOrder
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedConditionOrder
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapLeftPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapLeftPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapRightPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapRightPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineNonstrictPositivity_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineNonstrictPositivity_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroAffine_not_positive
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroAffine_not_positive
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineNonstrictPositivity_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineNonstrictPositivity_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapLeftPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapLeftPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapLeftPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapLeftPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapRightPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.QuadraticNoWrapRightPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterQuadratic
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterQuadratic
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepQuadratic
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepQuadratic
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapLeftPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapLeftPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapRightPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapRightPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapLeftPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapLeftPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapRightPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapRightPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermCore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermCore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermCore.BoundedAtBase
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermCore.BoundedAtBase
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermCore.eventually_fails
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermCore.eventually_fails
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermNoWrapLeftPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermNoWrapLeftPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CrossTermNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTerm_wrapLeftPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTerm_wrapLeftPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTerm_wrapRightPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTerm_wrapRightPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTermBaseDominance_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTermBaseDominance_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTermBaseDominance_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTermBaseDominance_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearCore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearCore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearCore.DominatedAtBase
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearCore.DominatedAtBase
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearCore.eventually_fails
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearCore.eventually_fails
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearNoWrapLeftPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearNoWrapLeftPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MultilinearNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinear_wrapLeftPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinear_wrapLeftPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinear_wrapRightPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinear_wrapRightPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearBaseDominance_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearBaseDominance_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearBaseDominance_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearBaseDominance_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.sourceFrozenAtBase
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.sourceFrozenAtBase
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.targetFrozenAtBase
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.targetFrozenAtBase
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.EventuallyDominatedAtBase
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.EventuallyDominatedAtBase
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.eventually_fails
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialCore.eventually_fails
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialNoWrapLeftPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialNoWrapLeftPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PolynomialNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomial_wrapLeftPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomial_wrapLeftPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomial_wrapRightPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomial_wrapRightPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialEventualDominance_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialEventualDominance_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialEventualDominance_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialEventualDominance_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MaxNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MaxNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MaxNoWrapRightPos.eval_succIter
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MaxNoWrapRightPos.eval_succIter
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.max_wrapRightPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.max_wrapRightPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MaxDepthNoWrapPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.MaxDepthNoWrapPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxDepth_wrapPos_nonLoadBearing
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxDepth_wrapPos_nonLoadBearing
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapLeftPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapLeftPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapLeftPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapLeftPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapRightPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.PairNoWrapRightPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterPair
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterPair
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepCounterPair
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepCounterPair
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterPair_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterPair_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepCounterPair_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepCounterPair_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapLeftPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapLeftPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapRightPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapRightPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapLeftPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapLeftPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapRightPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapRightPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroFirstPair
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroFirstPair
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroFirstPair_not_positive
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroFirstPair_not_positive
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroFirstPair_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroFirstPair_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairLexFirstPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairLexFirstPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairLexFirstPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairLexFirstPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_primary
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_primary
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_zero
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_zero
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_vecLexLt_primary
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_vecLexLt_primary
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_vecLexLt_second
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.primaryEmbed_vecLexLt_second
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapLeftPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapLeftPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapRightPos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapRightPos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapLeftPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapLeftPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapRightPos.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LexNoWrapRightPos.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterLex
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterLex
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepLex
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepLex
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterLex_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterLex_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepLex_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stepLex_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroPrimaryLex
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroPrimaryLex
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroPrimaryLex_not_positive
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroPrimaryLex_not_positive
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroPrimaryLex_orients
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroPrimaryLex_orients
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapLeftPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapLeftPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapRightPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapRightPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexPrimaryPositive_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexPrimaryPositive_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapLeftPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapLeftPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapRightPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapRightPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexPrimaryPositive_deleted_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexPrimaryPositive_deleted_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.HypothesisSlot
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.HypothesisSlot
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPlus_has_no_slot
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPlus_has_no_slot
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxDepth_has_no_slot
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxDepth_has_no_slot
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.headPrecedence_has_no_slot
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.headPrecedence_has_no_slot
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.familySlots
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.familySlots
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.mem_familySlots
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.mem_familySlots
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.familySlots_nodup
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.familySlots_nodup
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.familySlots_total
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.familySlots_total
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.SlotSpec
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.SlotSpec
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.slotSpec
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.slotSpec
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedHypothesisCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedHypothesisCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedHypothesisCountermodel.refutes_deleted_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedHypothesisCountermodel.refutes_deleted_barrier
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NecessityEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NecessityEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.slot_barrier_restored
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.slot_barrier_restored
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveAttainmentEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveAttainmentEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveWrapRetentionEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.additiveWrapRetentionEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawWrapperRetentionEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawWrapperRetentionEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawBoundedCounterGainEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.directLawBoundedCounterGainEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transparentSuccessorEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transparentSuccessorEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositionalWrapSubterm2Evidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.compositionalWrapSubterm2Evidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapLeftPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapLeftPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapRightPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineWrapRightPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineNonstrictPositivityEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.affineNonstrictPositivityEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapLeftPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapLeftPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapRightPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quadraticWrapRightPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTermBaseDominanceEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.crossTermBaseDominanceEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearBaseDominanceEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearBaseDominanceEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialEventualDominanceEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialEventualDominanceEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapLeftPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapLeftPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapRightPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairWrapRightPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairLexFirstPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pairLexFirstPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexPrimaryPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexPrimaryPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapLeftPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapLeftPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapRightPositiveEvidence
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lexWrapRightPositiveEvidence
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.used_hypothesis_has_countermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.used_hypothesis_has_countermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.slot_premise_exactly_necessary
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.slot_premise_exactly_necessary
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterRank_cell_countermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.counterRank_cell_countermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coupledClosedMeasure_cell_countermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coupledClosedMeasure_cell_countermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.barrier_cell_wrap_unbounded_hypothesis_necessary
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.barrier_cell_wrap_unbounded_hypothesis_necessary
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.barrier_cell_gain_bounded_hypothesis_necessary
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.barrier_cell_gain_bounded_hypothesis_necessary
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.barrier_cell_hypotheses_individually_necessary
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.barrier_cell_hypotheses_individually_necessary
