import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityInterpretations

/-! # RowNecessityInterpretations reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQ_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyQ_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyROtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyROtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyRNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyR_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearPolyR_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialSuccLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialSuccLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialIdSuccDatum
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialIdSuccDatum
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialIdSuccDatum_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialIdSuccDatum_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialIdSuccDatum_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialIdSuccDatum_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialSuccControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialSuccControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomialNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomial_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.negativeCoefficientPolynomial_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialRecurLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialRecurLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialRecurControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialRecurControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomialNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomial_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.maxPolynomial_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialSuccLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialSuccLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialSuccControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialSuccControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomialNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomial_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.nonlinearHigherDegreePolynomial_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationRecurLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationRecurLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearUncoupled_rEval
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearUncoupled_rEval
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationUncoupled_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationUncoupled_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationRecurControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationRecurControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretation_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.multilinearInterpretation_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjectionNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjection_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixNScalarProjection_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjectionNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjection_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.matrixQRScalarProjection_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionPartA
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionPartA
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionPartB
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionPartB
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arctic_wrap_masking
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arctic_wrap_masking
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_partA_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_partA_barrier
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_partB_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_partB_barrier
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionNonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionNonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_nonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_nonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_nonduplicating_context_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_nonduplicating_context_rejected
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjectionNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.arcticScalarProjection_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionPartA
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionPartA
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionPartB
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionPartB
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tAct_tConst_zero_le
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tAct_tConst_zero_le
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropical_wrap_tops
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropical_wrap_tops
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_partA_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_partA_barrier
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_partB_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_partB_barrier
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionNonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionNonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_nonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_nonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_nonduplicating_context_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_nonduplicating_context_rejected
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjectionNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tropicalScalarProjection_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrixNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrix_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.triangularMatrix_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleRecurCode
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleRecurCode
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSRecurLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSRecurLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSRecurLens_set_code
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSRecurLens_set_code
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupledRecur
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupledRecur
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupledRecur_ne
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupledRecur_ne
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupled_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupled_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupled_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleUncoupled_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSRecurControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSRecurControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictSNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictS_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupleInterpretationStrictS_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanRecurLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanRecurLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanRecurControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanRecurControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedeanNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedean_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.strictMonotoneAlgebraArchimedean_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.emaVecCode
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.emaVecCode
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraStrictLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraStrictLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraStrictLens_set_code
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraStrictLens_set_code
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupW_pointwise_strict
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.tupW_pointwise_strict
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraPointwise_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraPointwise_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraStrictControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraStrictControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebraNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebra_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.extendedMonotoneAlgebra_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationLaws_split
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationLaws_split
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTerminationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTermination_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.finiteModelTermination_necessity
