import OperatorKO7.Meta.Methods.OrientationClosure.ScalarGrammarDecision

/-!
# ScalarGrammarDecision reach and axiom check

Paired declaration reach and axiom checks for `ScalarGrammarDecision.lean`.
-/

#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?_eq_true_iff
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?_eq_true_iff
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.eval_one_one_eq_zero_implies_zero
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.eval_one_one_eq_zero_implies_zero
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?_false_implies_zero
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?_false_implies_zero
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?_eval_ge_one
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.positiveAtUnit?_eval_ge_one
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_true_lower_bound
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_true_lower_bound
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_false_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_false_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_true_not_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_true_not_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_eq_false_iff_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_eq_false_iff_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_eq_true_iff_not_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.readsPayload?_eq_true_iff_not_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.eval_counterMonotone
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.eval_counterMonotone
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.mul_step_convex
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.mul_step_convex
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.eval_counterStepConvex
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.eval_counterStepConvex
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.initialCounterRise_implies_counterStrict
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.initialCounterRise_implies_counterStrict
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.counterStrict_iff_initial_of_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.counterStrict_iff_initial_of_payloadBlind
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.payloadFailureWitness
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.payloadFailureWitness
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.counterFailureWitness
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.counterFailureWitness
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.classify
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.classify
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.classify_sound
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.classify_sound
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.classify_isOrienting_iff
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.classify_isOrienting_iff
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.productPayloadCounterExpr
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.productPayloadCounterExpr
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.productPayloadCounter_classified_blockedPayload
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.productPayloadCounter_classified_blockedPayload
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.payload_mul_counter_detected
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.payload_mul_counter_detected
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.zero_smul_payload_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.zero_smul_payload_rejected
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.max_counter_hundred_initial_plateau
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.max_counter_hundred_initial_plateau
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.counter_square_orients
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.counter_square_orients
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.mk
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.mk
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.counter
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.counter
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.payload
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.payload
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.increment
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.increment
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.increment_pos
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.increment_pos
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.fails
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.FailedDupWitness.fails
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.orients
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.orients
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.blockedPayload
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.blockedPayload
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.blockedCounter
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.blockedCounter
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.const_payloadBlind_not_counterStrict
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.const_payloadBlind_not_counterStrict
#check @OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.IsOrienting
#print axioms OperatorKO7.Methods.OrientationClosure.ScalarGrammarDecision.Decision.IsOrienting
