import OperatorKO7.Meta.Methods.OrientationClosure.CaptureAvoidingSubstitution

/-!
# CaptureAvoidingSubstitution reach and axiom check

Paired declaration reach and axiom checks for `CaptureAvoidingSubstitution.lean`.
-/

#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freeVars
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freeVars
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.allNames
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.allNames
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.maxName
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.maxName
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freeVars_subset_allNames
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freeVars_subset_allNames
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.mem_allNames_le_maxName
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.mem_allNames_le_maxName
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.termDepth
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.termDepth
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.renameBound
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.renameBound
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.renameBound_depth
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.renameBound_depth
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName_ne_target
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName_ne_target
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName_not_free_replacement
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName_not_free_replacement
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName_not_in_body
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.freshName_not_in_body
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.termDepth_pos
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.termDepth_pos
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteFuel
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteFuel
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteCA
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteCA
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteFuel_sound
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteFuel_sound
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteCA_sound
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.substituteCA_sound
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.legacy_substitution_capture_control
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.legacy_substitution_capture_control
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.capture_avoiding_control
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.capture_avoiding_control
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.inserted_variable_remains_free
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.inserted_variable_remains_free
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.binder_shadow_control
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.binder_shadow_control
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.nonconflicting_binder_control
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.nonconflicting_binder_control
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.variableHit
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.variableHit
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.variableMiss
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.variableMiss
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.atom
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.atom
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.succ
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.succ
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.app
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.app
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.lamShadow
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.lamShadow
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.lamSafe
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.lamSafe
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.lamRename
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.lamRename
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.recur
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.recur
#check @OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.share
#print axioms OperatorKO7.Methods.OrientationClosure.CaptureAvoidingSubstitution.CaptureAvoidingDerivation.share
