import OperatorKO7.OrientationBoundaryAPI

namespace OrientationBoundaryAPIReach

open Ordinal
open OperatorKO7.MetaCM
open OperatorKO7.MetaDM
open MetaSN_KO7

#check OperatorKO7.Meta.BoundaryGeneral.DirectMeasureGrammarClosure.orients_iff_payloadBlind_and_counterStrict
#check OperatorKO7.Meta.BoundaryGeneral.DirectMeasureGrammarClosure.counterAdmissible_orients_iff_payloadBlind
#check OperatorKO7.Meta.BoundaryGeneral.DirectMeasureGrammarClosure.counter_is_counterAdmissible
#check OperatorKO7.Meta.BoundaryGeneral.DirectMeasureGrammarClosure.const_zero_not_orients

#check OperatorKO7.SafeTraceTripleLexExactness.trace_code_eq_iff_mu3c_eq
#check OperatorKO7.SafeTraceTripleLexExactness.ambientTraceSurjectivityObstructionCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.trace_exact_order_type_residual_false
#check OperatorKO7.SafeTraceTripleLexExactness.integrateChain
#check OperatorKO7.SafeTraceTripleLexExactness.zeroDmPhaseZeroCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.phaseOneZeroDmCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.payloadTowerPhaseZeroCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.flaggedTowerPhaseOneCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.trace_realizes_zeroDmPhaseZeroCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.trace_realizes_payloadTowerPhaseZeroCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.trace_realizes_flaggedTowerPhaseOneCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.trace_dmComponent_has_one_of_phase_one
#check OperatorKO7.SafeTraceTripleLexExactness.no_trace_realizes_phase_one_without_one
#check OperatorKO7.SafeTraceTripleLexExactness.no_trace_realizes_phaseOneZeroDmCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.traceImageRangeStatus
#check OperatorKO7.SafeTraceTripleLexExactness.TraceRealizableCarrier
#check OperatorKO7.SafeTraceTripleLexExactness.traceRealizableCarrierRealization
#check OperatorKO7.SafeTraceTripleLexExactness.traceRealizableCarrier_code_eq_iff_eq
#check OperatorKO7.SafeTraceTripleLexExactness.traceRealizableCarrier_order_iff
#check OperatorKO7.SafeTraceTripleLexExactness.traceToFullTripleLexCarrier_not_surjective
#check OperatorKO7.SafeTraceTripleLexExactness.TraceImageSubtypeStatus
#check OperatorKO7.SafeTraceTripleLexExactness.traceImageSubtypeStatus
#check OperatorKO7.SafeTraceTripleLexExactness.zeroDmPhaseZero_order_iff
#check OperatorKO7.SafeTraceTripleLexExactness.payloadTowerPhaseZero_order_iff
#check OperatorKO7.SafeTraceTripleLexExactness.flaggedTowerPhaseOne_order_iff
#check OperatorKO7.SafeTraceCertificateBridge.traceRealizableCarrierOfTrace
#check OperatorKO7.SafeTraceCertificateBridge.traceRealizableCarrierOfTrace_carrier
#check OperatorKO7.SafeTraceCertificateBridge.SafeStepEndpointPackage
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpointPackage
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpointPackage_source_realizes
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpointPackage_target_realizes
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpoint_tau_pos_of_source
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpoint_source_fundamentalSequence
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpoint_source_exact_pred_step
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpoint_target_repr_le_source_pred
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpoint_root_length_le_tau
#check OperatorKO7.SafeTraceCertificateBridge.safeStepEndpoint_root_length_le_mwRootBound
#check OperatorKO7.SafeTraceCertificateBridge.SafeStepCtxChainPackage
#check OperatorKO7.SafeTraceCertificateBridge.safeStepCtxChainPackage
#check OperatorKO7.SafeTraceCertificateBridge.externalizedTraceImageToRealizableCarrier
#check OperatorKO7.SafeTraceCertificateBridge.externalizedTraceImageToRealizableCarrier_carrier
#check OperatorKO7.SafeTraceCertificateBridge.externalizedTraceImageToRealizableCarrier_realizes
#check OperatorKO7.SafeTraceCertificateBridge.externalizedTraceImage_code_eq_iff_realizable_eq
#check OperatorKO7.SafeTraceCertificateBridge.externalizedTraceImage_order_iff_realizable_order
#check OperatorKO7.SafeTraceCertificateBridge.externalizedTraceImage_realizable_upper_bound
#check OperatorKO7.SafeTraceCertificateBridge.SafeTraceCertificateBridgeCatalog
#check OperatorKO7.SafeTraceCertificateBridge.safe_trace_certificate_bridge_catalog
#check OperatorKO7.SafeTraceComplexityBridge.SafeStepEndpointComplexityPackage
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_tau_pos_of_source
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_source_exact_pred_step
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_target_repr_le_source_pred
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_root_length_le_tau
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_root_length_le_mwRootBound
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_source_code_eq_iff_eq
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_source_order_iff
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_source_upper_bound
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_target_code_eq_iff_eq
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_target_order_iff
#check OperatorKO7.SafeTraceComplexityBridge.safeStepEndpointComplexityPackage_target_upper_bound
#check OperatorKO7.SafeTraceComplexityBridge.SafeStepCtxComplexityPackage
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_ctxFuel_antitone
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_exact_drop
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_length_le_ctxFuel_drop
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_length_le_ctxFuel
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_length_le_mwCtxBound
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_length_bounded_by_size
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_length_le_fgOmegaEnvelope
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_source_code_eq_iff_eq
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_source_order_iff
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_source_upper_bound
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_target_code_eq_iff_eq
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_target_order_iff
#check OperatorKO7.SafeTraceComplexityBridge.safeStepCtxComplexityPackage_target_upper_bound
#check OperatorKO7.SafeTraceComplexityBridge.externalizedTraceImageRecovery_code_eq_iff_realizable_eq
#check OperatorKO7.SafeTraceComplexityBridge.externalizedTraceImageRecovery_order_iff_realizable_order
#check OperatorKO7.SafeTraceComplexityBridge.externalizedTraceImageRecovery_upper_bound
#check OperatorKO7.SafeTraceComplexityBridge.SafeTraceComplexityBridgeCatalog
#check OperatorKO7.SafeTraceComplexityBridge.safe_trace_complexity_bridge_catalog
#check OperatorKO7.SafeTraceCertificateAudit.SafeTraceCertificateAuditRow
#check OperatorKO7.SafeTraceCertificateAudit.safeTraceCertificateAuditRows
#check OperatorKO7.SafeTraceCertificateAudit.SafeTraceExternalizedRecoveryEvidence
#check OperatorKO7.SafeTraceCertificateAudit.SafeTraceCertificateAuditRowEvidence
#check OperatorKO7.SafeTraceCertificateAudit.safeTraceCertificateAuditRows_length
#check OperatorKO7.SafeTraceCertificateAudit.safeTraceCertificateAuditRows_nodup
#check OperatorKO7.SafeTraceCertificateAudit.safeTraceCertificateAuditRows_mem_iff
#check OperatorKO7.SafeTraceCertificateAudit.safeTraceCertificateAuditRows_complete
#check OperatorKO7.SafeTraceCertificateAudit.safeTraceCertificateAudit_row_projects_evidence
#check OperatorKO7.SafeTraceCertificateAudit.SafeTraceCertificateAuditCatalog
#check OperatorKO7.SafeTraceCertificateAudit.safe_trace_certificate_audit_catalog
#check OperatorKO7.SafeTraceCertificateAudit.safeTraceCertificateAudit_catalog_projects_evidence
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceRootEndpointBoundsEvidence
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceContextExactDropEvidence
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceMWCtxBoundEvidence
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceFGEnvelopeBoundEvidence
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceRootAPIExportBundle
#check OperatorKO7.SafeTraceRoadmapCloseout.safe_trace_root_api_export_bundle
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceRoadmapCloseoutRow
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceRoadmapCloseoutStatus
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseoutRows
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceRoadmapCloseoutRowEvidence
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseoutRows_length
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseoutRows_nodup
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseoutRows_mem_iff
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseoutRows_complete
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_row_status
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_row_projects_evidence
#check OperatorKO7.SafeTraceRoadmapCloseout.SafeTraceRoadmapCloseoutCatalog
#check OperatorKO7.SafeTraceRoadmapCloseout.safe_trace_roadmap_closeout_catalog
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_row_status
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_row_evidence
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_image_subtype_status
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_image_subtype_exactness
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_full_carrier_obstruction
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_certificate_bridge_catalog
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_complexity_bridge_catalog
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_root_endpoint_bounds
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_context_exact_drop
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_mw_ctx_bound
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_fg_envelope_bound
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_externalized_image_recovery
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_certificate_audit_catalog
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_root_api_export
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_root_api_image_subtype_status
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_root_api_full_carrier_obstruction
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_root_api_certificate_bridge_catalog
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_root_api_complexity_bridge_catalog
#check OperatorKO7.SafeTraceRoadmapCloseout.safeTraceRoadmapCloseout_catalog_projects_root_api_certificate_audit_catalog
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.safe_trace_triple_lex_exactness_final_catalog
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_no_exact_order_type_package
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_image_range_status
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_image_subtype_status
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_certificate_bridge_catalog
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_complexity_bridge_catalog
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_certificate_audit_catalog
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_roadmap_closeout_catalog
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_traceRealizableCarrierOfTrace
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_traceRealizableCarrierOfTrace_carrier
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointPackage
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointPackage_source_realizes
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointPackage_target_realizes
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpoint_tau_pos_of_source
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpoint_source_fundamentalSequence
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpoint_source_exact_pred_step
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpoint_target_repr_le_source_pred
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpoint_root_length_le_tau
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpoint_root_length_le_mwRootBound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxChainPackage
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImageToRealizableCarrier
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImageToRealizableCarrier_realizes
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImage_code_eq_iff_realizable_eq
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImage_order_iff_realizable_order
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImage_realizable_upper_bound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_tau_pos_of_source
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_source_exact_pred_step
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_target_repr_le_source_pred
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_root_length_le_tau
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_root_length_le_mwRootBound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_source_code_eq_iff_eq
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_source_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_source_upper_bound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_target_code_eq_iff_eq
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_target_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpointComplexityPackage_target_upper_bound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_ctxFuel_antitone
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_exact_drop
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_length_le_ctxFuel_drop
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_length_le_ctxFuel
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_length_le_mwCtxBound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_length_bounded_by_size
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_length_le_fgOmegaEnvelope
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_source_code_eq_iff_eq
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_source_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_source_upper_bound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_target_code_eq_iff_eq
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_target_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_target_upper_bound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImageRecovery_code_eq_iff_realizable_eq
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImageRecovery_order_iff_realizable_order
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalizedTraceImageRecovery_upper_bound
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeTraceCertificateAuditRows
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeTraceCertificateAuditRows_length
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeTraceCertificateAuditRows_nodup
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeTraceCertificateAuditRows_mem_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeTraceCertificateAuditRows_complete
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeTraceCertificateAudit_row_projects_evidence
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_certificate_audit_catalog_projects_evidence
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_realizable_carrier_code_eq_iff_eq
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_realizable_carrier_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_traceToFullTripleLexCarrier_not_surjective
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_zeroDmPhaseZero_realizable
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_payloadTowerPhaseZero_realizable
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_flaggedTowerPhaseOne_realizable
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_phaseOne_has_one
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_phaseOne_without_one_blocked
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_phaseOne_zero_dm_blocked
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_zeroDmPhaseZero_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_payloadTowerPhaseZero_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_flaggedTowerPhaseOne_order_iff
#check OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalized_image_exact_order_type_of_surjective

example : True := by
  have := @OperatorKO7.DMTripleLexExactnessFinalCatalog.triple_lex_exactness_final_catalog
  trivial

example :
    ∀ x y : FullTripleLexCarrier,
      Lex3c x.toLex3cTuple y.toLex3cTuple ↔
        lex3cToOrd x.toLex3cTuple < lex3cToOrd y.toLex3cTuple := by
  exact OperatorKO7.DMTripleLexExactnessFinalCatalog.final_catalog_projects_exact_order_type.1

example : True := by
  have := @OperatorKO7.MutualDuplicationFiniteSchemaAPI.two_rule_witness
  trivial

example : True := by
  have := @OperatorKO7.MutualDuplicationFiniteSchemaAPI.three_rule_witness
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactness.trace_code_eq_iff_mu3c_eq
  trivial

example : True := by
  have := OperatorKO7.SafeTraceTripleLexExactness.ambientTraceSurjectivityObstructionCarrier
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactness.trace_exact_order_type_residual_false
  trivial

example : True := by
  have := OperatorKO7.SafeTraceTripleLexExactness.traceImageRangeStatus
  trivial

example : True := by
  have := OperatorKO7.SafeTraceTripleLexExactness.traceImageSubtypeStatus
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactness.traceToFullTripleLexCarrier_not_surjective
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceCertificateBridge.safe_trace_certificate_bridge_catalog
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceComplexityBridge.safe_trace_complexity_bridge_catalog
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceCertificateAudit.safe_trace_certificate_audit_catalog
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceRoadmapCloseout.safe_trace_roadmap_closeout_catalog
  trivial

noncomputable example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_roadmap_closeout_catalog
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceCertificateBridge.safeStepEndpoint_root_length_le_mwRootBound
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactness.flaggedTowerPhaseOne_order_iff
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.safe_trace_triple_lex_exactness_final_catalog
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_no_exact_order_type_package
  trivial

example : True := by
  have := OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_image_range_status
  trivial

example : True := by
  have := OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_image_subtype_status
  trivial

example : True := by
  have := OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_certificate_bridge_catalog
  trivial

example : True := by
  have := OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_complexity_bridge_catalog
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_certificate_audit_catalog
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepCtxComplexityPackage_length_le_fgOmegaEnvelope
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_certificate_audit_catalog_projects_evidence
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_safeStepEndpoint_root_length_le_mwRootBound
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_trace_realizable_carrier_code_eq_iff_eq
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_phaseOne_without_one_blocked
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_flaggedTowerPhaseOne_order_iff
  trivial

example : True := by
  have := @OperatorKO7.SafeTraceTripleLexExactnessFinalCatalog.final_catalog_projects_externalized_image_exact_order_type_of_surjective
  trivial

example : True := by
  have := OperatorKO7.HigherOrderSharingBoundaryAPI.final_catalog
  trivial

example : True := by
  have := OperatorKO7.HigherOrderSharingBoundaryAPI.unqualified_lift_blocker
  trivial

example : True := by
  have := OperatorKO7.HigherOrderSharingBoundaryAPI.full_higher_order_outside_catalog
  trivial

end OrientationBoundaryAPIReach
