import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsInterpretations

/-! # MethodRowsInterpretations reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupLhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupLhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dup_rootStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dup_rootStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupOrientedOn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupOrientedOn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupOriented
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupOriented
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupOrientedOn_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupOrientedOn_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupOriented_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupOriented_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.CertifiesFreeTermination
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.CertifiesFreeTermination
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.certifiesFreeTermination_of_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.certifiesFreeTermination_of_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.valueSchema
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.valueSchema
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.not_dupOriented_of_barrierCell
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.not_dupOriented_of_barrierCell
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ordered_barrier_cell_on
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ordered_barrier_cell_on
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.orderedCell_nat_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.orderedCell_nat_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sigDupLhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sigDupLhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sigDupRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sigDupRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sigDup_rootStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sigDup_rootStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sig_dupOrientedOn_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sig_dupOrientedOn_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natSigExtension
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natSigExtension
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natSigExtension_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natSigExtension_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nat_signature_termination
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nat_signature_termination
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.LinearPolyData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.LinearPolyData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.LinearPolyData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.LinearPolyData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sepLt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sepLt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.LinearPolyLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.LinearPolyLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sepLt_wf_rat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sepLt_wf_rat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sepLt_wf_real
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.sepLt_wf_real
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rat_lt_not_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rat_lt_not_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.real_lt_not_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.real_lt_not_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQ_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQ_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQ_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQ_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQ_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyQ_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyR_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyR_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyRWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyR_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyR_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyR_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.linearPolyR_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nat_strict_ge
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nat_strict_ge
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wrap_ge_of_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wrap_ge_of_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nat_escape_coupling
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nat_escape_coupling
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ZPoly
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ZPoly
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ZPoly.eval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ZPoly.eval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ZPoly.WeakMono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ZPoly.WeakMono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NegCoeffData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NegCoeffData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NegCoeffData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NegCoeffData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NegCoeffLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NegCoeffLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomial_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomial_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negCubeBase
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negCubeBase
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.int_cube_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.int_cube_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.int_cube_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.int_cube_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.cube_toNat_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.cube_toNat_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_wrap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_step_key
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_step_key
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negW_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_coupling
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomialWitness_coupling
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomial_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomial_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomial_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.negativeCoefficientPolynomial_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.eval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.eval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.MulFree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.MulFree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.size
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.size
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.eval_le_of_mulFree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.eval_le_of_mulFree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MaxPolyData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MaxPolyData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MaxPolyData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MaxPolyData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_maxPlus_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_maxPlus_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_coupling
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialWitness_coupling
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialMutant
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomialMutant
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.maxPolynomial_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatPolyData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatPolyData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatPolyData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatPolyData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.unitSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.unitSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.uEval_unitSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.uEval_unitSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natPoly_rootRuleOrients_iff_decide
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natPoly_rootRuleOrients_iff_decide
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.residual_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.residual_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_decides
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_decides
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.uncoupledR
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.uncoupledR
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_coupling
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomialWitness_coupling
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonlinearHigherDegreePolynomial_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MultilinearLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MultilinearLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_decides
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_decides
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.mlW_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.mlW_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_coupling
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretationWitness_coupling
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.multilinearInterpretation_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NVec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NVec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NMat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NMat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_zero_mat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_zero_mat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_ge_diag
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_ge_diag
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nUnit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nUnit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nUnit_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nUnit_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatMatrixData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatMatrixData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatMatrixData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatMatrixData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatMatrixLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NatMatrixLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natMatrix_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natMatrix_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natMatrix_recur_additive
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.natMatrix_recur_additive
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.idMat2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.idMat2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.shearMat2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.shearMat2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_idMat2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nAct_idMat2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.coupledVectorInterp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.coupledVectorInterp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.coupledVectorInterp_orients
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.coupledVectorInterp_orients
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.e0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.e0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjection_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjection_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjectionWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjection_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjection_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjection_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixNScalarProjection_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.UpperTri
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.UpperTri
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nMul
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nMul
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nOne
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nOne
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nPow
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nPow
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.upperTri_mul
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.upperTri_mul
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.upperTri_nOne
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.upperTri_nOne
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.upperTri_nPow
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.upperTri_nPow
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tri2_pow_offdiag
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tri2_pow_offdiag
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TriangularLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TriangularLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrix_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrix_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrixWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrix_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrix_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrix_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.triangularMatrix_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RVec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RVec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RMat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RMat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_zero_mat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_zero_mat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NonnegVec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NonnegVec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NonnegMat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.NonnegMat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_nonneg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_nonneg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_ge_diag
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_ge_diag
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rUnit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rUnit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rUnit_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rUnit_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rUnit_nonneg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rUnit_nonneg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RealMatrixData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RealMatrixData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RealMatrixData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RealMatrixData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rvecLt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rvecLt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RealMatrixLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.RealMatrixLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rvecLt_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rvecLt_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.realMatrix_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.realMatrix_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjection_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjection_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.idR2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.idR2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wrapR2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wrapR2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_idR2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.rAct_idR2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonnegMat_idR2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonnegMat_idR2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonnegMat_wrapR2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonnegMat_wrapR2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonnegVec_e0R
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.nonnegVec_e0R
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.idR2_pos
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.idR2_pos
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wrapR2_pos
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wrapR2_pos
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjectionWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjection_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjection_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjection_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.matrixQRScalarProjection_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupCtxStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupCtxStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupCtxStep.contextStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupCtxStep.contextStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupCtxOrientedOn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.DupCtxOrientedOn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupCtx_wrap_instances
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.dupCtx_wrap_instances
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.AVec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.AVec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.AMat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.AMat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aAct
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aAct
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aConst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aConst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aUnit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aUnit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ArcticData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ArcticData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ArcticData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ArcticData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.AFin
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.AFin
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcLt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcLt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ArcticLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.ArcticLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wb_exists_ge
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wb_exists_ge
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wb_le_coe_add
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wb_le_coe_add
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wb_coe_lt_one_add
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wb_coe_lt_one_add
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aAct_aUnit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aAct_aUnit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arctic_context_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arctic_context_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arctic_nonErasing_root_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arctic_nonErasing_root_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aAct_one
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.aAct_one
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjection_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjection_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcW_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcW_wrap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcW_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcW_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjectionWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjection_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjection_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjection_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.arcticScalarProjection_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TVec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TVec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TMat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TMat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tAct
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tAct
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tConst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tConst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TropicalData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TropicalData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TropicalData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TropicalData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TFin
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TFin
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropLt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropLt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TropicalLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TropicalLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tAct_le_diag
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tAct_le_diag
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tfin_add
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tfin_add
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wt_zero_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wt_zero_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wt_coe_lt_one_add
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.wt_coe_lt_one_add
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropical_eval_fin
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropical_eval_fin
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.min3_lt_right
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.min3_lt_right
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.min3_lt_left
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.min3_lt_left
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropical_context_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropical_context_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tAct_one
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tAct_one
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjection_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjection_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropW_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropW_wrap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropW_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropW_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropW_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropW_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjectionWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjection_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjection_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjection_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tropicalScalarProjection_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.eval_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.MExpr.eval_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLe
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLe
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLt_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLt_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLt_pair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecLt_pair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args1_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args1_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args2_le_left
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args2_le_left
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args2_le_right
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args2_le_right
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args3_le_base
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args3_le_base
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args3_le_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args3_le_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args3_le_counter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.args3_le_counter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TupleData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TupleData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TupleData.interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TupleData.interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TupleLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.TupleLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_arg_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_arg_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_weakContextLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_weakContextLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_strictContextLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_strictContextLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_wrap_ge
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tuple_wrap_ge
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecSigExtension
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecSigExtension
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecSigExtension_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.vecSigExtension_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_firstComponent
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_firstComponent
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_affineFirst_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_affineFirst_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_succ0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_succ0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_succ1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_succ1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_wrap0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_wrap0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_wrap1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_wrap1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_recur0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_recur0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_recur1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_recur1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_dup_second
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_dup_second
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupW_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.lexLtPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.lexLtPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictSWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.tupleInterpretationStrictS_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_uniformGain_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_uniformGain_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedeanWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.strictMonotoneAlgebraArchimedean_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.EMAData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.EMAData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.EMALaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.EMALaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_boundedGain_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_boundedGain_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebraWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.extendedMonotoneAlgebra_signature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.belowCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.belowCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.belowCount_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.belowCount_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.belowCount_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.belowCount_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finite_strict_dup_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finite_strict_dup_barrier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finite_no_strict_growth
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finite_no_strict_growth
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.FiniteModelData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.FiniteModelData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.FiniteModelLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.FiniteModelLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.boolModel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.boolModel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTermination_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTermination_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTerminationWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTermination_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTermination_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTermination_signature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsInterpretations.finiteModelTermination_signature
