import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsConditionalConstrained

/-! # MethodRowsConditionalConstrained reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ArgStepOf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ArgStepOf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.not_argStepOf_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.not_argStepOf_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepOf_cons_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepOf_cons_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.accOf_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.accOf_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.accArgsOf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.accArgsOf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepOf_preserve
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepOf_preserve
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepsOf_preserve
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepsOf_preserve
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_of_mid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_of_mid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_refl
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_refl
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_trans
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_trans
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.filterVals
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.filterVals
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_filterVals
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_filterVals
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalL
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalL
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalL_eq_map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalL_eq_map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalT_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalL_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.evalL_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgMono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgMono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_map_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.forall₂_map_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CtxStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CtxStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.RSN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.RSN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_app_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_app_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_var_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_var_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_arg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_arg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_isSubterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_isSubterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_of_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_of_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.MinChainOf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.MinChainOf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_minChainOf_acc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_minChainOf_acc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_minChainOf_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_minChainOf_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.crule_lhs_eq_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.crule_lhs_eq_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Judg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Judg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condGoals
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condGoals
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Infer
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Infer
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Derivable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Derivable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CSteps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CSteps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CondsHold
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CondsHold
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_inv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_inv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.infer_step_inv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.infer_step_inv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.infer_steps_inv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.infer_steps_inv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_inv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_inv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_cong
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_cong
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_repl
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_repl
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_refl
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_refl
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_head
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_head
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_of_rtg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_of_rtg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_steps_rtg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_steps_rtg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_iff_rtg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_iff_rtg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_trans
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_trans
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_of_cstep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_of_cstep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_cong
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_cong
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Expand
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Expand
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Good
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Good
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LFin
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LFin
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.expand_append
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.expand_append
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_append
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_append
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_of_good_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_of_good_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_rtg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_rtg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.reach_append
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.reach_append
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_reach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_reach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_of_reach_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_of_reach_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_append_of
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_append_of
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_cons_of_lfin
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_cons_of_lfin
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.GoodSeq
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.GoodSeq
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_goodSeq
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_goodSeq
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.goodSeq_condGoals
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.goodSeq_condGoals
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree.frontier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree.frontier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree.frontierList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree.frontierList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree.rec'
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PTree.rec'
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.TExpand
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.TExpand
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.frontierList_append
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.frontierList_append
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.frontierList_map_goal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.frontierList_map_goal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.frontierList_eq_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.frontierList_eq_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tExpand_frontier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tExpand_frontier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.expand_of_tExpand
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.expand_of_tExpand
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.split_frontierList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.split_frontierList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tExpand_of_frontier
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tExpand_of_frontier
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.acc_tree_of_good
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.acc_tree_of_good
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_acc_tree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.good_of_acc_tree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.OperationallyTerminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.OperationallyTerminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationallyTerminating_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationallyTerminating_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.OTt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.OTt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_steps_of_cstep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_steps_of_cstep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_step_of_lfin_steps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_step_of_lfin_steps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_steps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_steps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_cstep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_cstep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_csteps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_csteps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.acc_cstep_of_lfin
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.acc_cstep_of_lfin
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.acc_cstep_of_ot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.acc_cstep_of_ot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_steps_of
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lfin_steps_of
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_arg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_arg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_mem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_mem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_isSubterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_isSubterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CDefined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CDefined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cdefined_of_instance
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cdefined_of_instance
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_app_of_not_defined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_app_of_not_defined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.isSubterm_subst_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.isSubterm_subst_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_var_of_lhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_var_of_lhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Pair2D
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Pair2D
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.MinChain2D
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.MinChain2D
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CDeterministic
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CDeterministic
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CType3
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CType3
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_cond_lhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_cond_lhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_app_of_2D_acc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_app_of_2D_acc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_2D
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_2D
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationallyTerminating_of_2D
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationallyTerminating_of_2D
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgCondsHold
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgCondsHold
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgRulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgRulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_eval_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_eval_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_eval_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_eval_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_eval_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_eval_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argSteps_evals_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argSteps_evals_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.algCondsHold_of_condsHold
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.algCondsHold_of_condsHold
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CondAlgebra
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CondAlgebra
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.callVal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.callVal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.callVal_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.callVal_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgHorizontalStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgHorizontalStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgVerticalStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgVerticalStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_minChain2D_of_algebra
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_minChain2D_of_algebra
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.subtermsT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.subtermsT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.subtermsL
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.subtermsL
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_subtermsT_self
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_subtermsT_self
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_subtermsL_of_mem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_subtermsL_of_mem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_subtermsT_of_isSubterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_subtermsT_of_isSubterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.isSubterm_trans
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.isSubterm_trans
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uncond
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uncond
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.getD_le_of_forall₂
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.getD_le_of_forall₂
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.izZeroRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.izZeroRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.izSuccRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.izSuccRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.predRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.predRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.recZeroRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.recZeroRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.recSuccRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.recSuccRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_condRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_condRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_defined_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_defined_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.singleton_split
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.singleton_split
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_deterministic
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_deterministic
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_type3
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_type3
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cArity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cArity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condBase
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condBase
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condBase_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condBase_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condBase_rulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condBase_rulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.sC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.sC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.pC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.pC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.izC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.izC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ttC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ttC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ffC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ffC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_of_undefined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_of_undefined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_zC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_zC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_ffC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_ffC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_sC_zC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_cstep_sC_zC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_izC_sC_zC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.cstep_izC_sC_zC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_izC_sC_zC
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.csteps_izC_sC_zC
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_live
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.condRecursor_live
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCondRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCondRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS_derivable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS_derivable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS_no_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS_no_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS_not_operationallyTerminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.loopCTRS_not_operationallyTerminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uncond_loopCTRS_terminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uncond_loopCTRS_terminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uncond_condRecursor_not_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uncond_condRecursor_not_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitnessAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitnessAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRS_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRS_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitness_marked_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitness_marked_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitness_horizontal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitness_horizontal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitness_vertical
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDWitness_vertical
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRSWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDPayloadAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDPayloadAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRS_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.twoDDPForCTRS_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.USym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.USym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embL
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embL
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embL_eq_map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embL_eq_map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT_isApp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT_isApp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.embT_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tvarsT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tvarsT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tvarsL
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.tvarsL
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uChain
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uChain
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravelRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravelRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravelFrom
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravelFrom
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravelFrom_mem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravelFrom_mem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.applyList_vars
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.applyList_vars
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rtg_step_arg0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rtg_step_arg0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.transGen_step_arg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.transGen_step_arg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.step_rule_inst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.step_rule_inst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uChain_sim_H
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uChain_sim_H
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uChain_sim_V
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uChain_sim_V
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_unravel_sim
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.derivable_unravel_sim
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.transGen_stepOrSub_of_steps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.transGen_stepOrSub_of_steps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rtg_stepOrSub_of_steps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rtg_stepOrSub_of_steps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_unravel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ot_of_unravel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationallyTerminating_of_unravel
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationallyTerminating_of_unravel
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.MarkedAlgebra
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.MarkedAlgebra
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgTRSWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgTRSWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgPairsStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.AlgPairsStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.step_eval_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.step_eval_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.algCallPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.algCallPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.sn_of_markedAlgebra
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.sn_of_markedAlgebra
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uIzZero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uIzZero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uIzSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uIzSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uPred
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uPred
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecZ1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecZ1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecZ2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecZ2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecS1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecS1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecS2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uRecS2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uCondRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uCondRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravel_condRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.unravel_condRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_uCondRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_uCondRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uCondRules_defined_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uCondRules_defined_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uCondRules_vars
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uCondRules_vars
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitnessAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitnessAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRS_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRS_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_base_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_base_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_marked_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_marked_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_rulesWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_rulesWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_pairsStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uWitness_pairsStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRSWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uBlindAlg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.uBlindAlg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRS_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.operationalTerminationCTRS_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepOf_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepOf_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepsOf_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepsOf_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rtg_eq_of_nf'
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rtg_eq_of_nf'
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_argStepOf_of_nf'
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_argStepOf_of_nf'
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepsOf_cons_nf'
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argStepsOf_cons_nf'
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argSteps_head_only'
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.argSteps_head_only'
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_lift_subterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_lift_subterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ctxStep_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalL
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalL
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalL_eq_map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalL_eq_map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalT_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.zevalT_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IntSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IntSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.pdEval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.pdEval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ISym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ISym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iconst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iconst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PDRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PDRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.FullRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.FullRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.INF
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.INF
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.InnerRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.InnerRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.UserRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.UserRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.not_rootStep_inr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.not_rootStep_inr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.not_ctxStep_iconst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.not_ctxStep_iconst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iconst_inf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iconst_inf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_full
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_full
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_iconst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_iconst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inl_undefined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inl_undefined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_subst_itrs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_subst_itrs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.itrs_terminating_of_chains
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.itrs_terminating_of_chains
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IProblem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IProblem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PEdge
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PEdge
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IChain
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IChain
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IInterp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IInterp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.icallVal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.icallVal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IInterpretation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IInterpretation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Connects
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Connects
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PStrict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PStrict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PBound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.PBound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.RhsWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.RhsWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_iChain_of_processor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_iChain_of_processor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_iChain_single
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_iChain_single
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_istep_of_inf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_istep_of_inf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_app_inr_inv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_app_inr_inv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_root_rule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_root_rule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_pd
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.istep_pd
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.reach_gt_tt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.reach_gt_tt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.reach_sub_one
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.reach_sub_one
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IUser
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IUser
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ITerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ITerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ilit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ilit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iRecRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iRecRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iIfTrueRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iIfTrueRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iIfFalseRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iIfFalseRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_intRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_intRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_userRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_userRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_vars
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_vars
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_defined_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_defined_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ip1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ip1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ip2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ip2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intDP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intDP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intPair_edge
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intPair_edge
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intChain_of_minChain
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intChain_of_minChain
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intDP_rhsWeak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intDP_rhsWeak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.sub3
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.sub3
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intPol
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intPol
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intWitnessInterp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intWitnessInterp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intPol_interp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intPol_interp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewriting_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewriting_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_negative
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intRecursor_negative
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iNoTestRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.iNoTestRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intNoTest
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intNoTest
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intNoTest_not_terminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intNoTest_not_terminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewritingWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intBound2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.intBound2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewriting_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.integerTermRewriting_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.TSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.TSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LVal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LVal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jop
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jop
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jevalL
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jevalL
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_app_inr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_app_inr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_app_inl
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_app_inl
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jevalL_some_mem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jevalL_some_mem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jevalL_congr_mid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jevalL_congr_mid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.valT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.valT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_valT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_valT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IsValue
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IsValue
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LVars
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LVars
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Respects
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.Respects
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IsCalc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.IsCalc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CalcRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.CalcRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LTermRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LTermRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LDefined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LDefined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.valT_eq_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.valT_eq_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_lstep_valT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.no_lstep_valT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_valT
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_valT
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_isValue
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_of_isValue
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inr_lctrs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inr_lctrs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inl_undefined_lctrs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_app_inl_undefined_lctrs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_subst_lctrs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.rsn_subst_lctrs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrs_terminating_of_chains
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrs_terminating_of_chains
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_lstep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_lstep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_lsteps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.jeval_lsteps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ValueCriterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.ValueCriterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.bind_getElem_eq_some
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.bind_getElem_eq_some
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_lChain_of_valueCriterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.wf_lChain_of_valueCriterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LUser
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LUser
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.llit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.llit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lRecSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lRecSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lRecZero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lRecZero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_lctrsRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.mem_lctrsRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsRecursor_termRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsRecursor_termRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsRecursor_defined_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsRecursor_defined_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lsub3
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lsub3
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.respects_lRecSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.respects_lRecSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LValueData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.LValueData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrs_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrs_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsBound1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrsBound1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrs_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsConditionalConstrained.lctrs_mutation
