import OperatorKO7.Meta.Methods.OrientationClosure.OrientationBoundaryPublicationCapstone

set_option autoImplicit false

#check @OperatorKO7.Methods.OrientationClosure.OrientationBoundaryPublicationCapstone.free_successor_orientation_iff_payloadBlind_and_counterStrict
#print axioms OperatorKO7.Methods.OrientationClosure.OrientationBoundaryPublicationCapstone.free_successor_orientation_iff_payloadBlind_and_counterStrict

#check @OperatorKO7.Methods.OrientationClosure.OrientationBoundaryPublicationCapstone.free_successor_counterAdmissible_orients_iff_payloadBlind
#print axioms OperatorKO7.Methods.OrientationClosure.OrientationBoundaryPublicationCapstone.free_successor_counterAdmissible_orients_iff_payloadBlind

#check @OperatorKO7.Methods.OrientationClosure.OrientationBoundaryPublicationCapstone.no_decisive_certificate_of_payload_erasure
#print axioms OperatorKO7.Methods.OrientationClosure.OrientationBoundaryPublicationCapstone.no_decisive_certificate_of_payload_erasure
