import OperatorKO7.Meta.Methods.OrientationClosure.ContextLiftMetatheorem

/-! # ContextLiftMetatheorem reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.OrientsFreeContext
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.OrientsFreeContext
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.free_context_orientation_implies_root
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.free_context_orientation_implies_root
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.barrier_cell_excludes_context_orientation
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.barrier_cell_excludes_context_orientation
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.interpretation_context_consumption
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.interpretation_context_consumption
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.interpretation_context_reverse_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.interpretation_context_reverse_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.minWrapInterpretation
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.minWrapInterpretation
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.minWrapInterpretation_rootRuleOrients
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.minWrapInterpretation_rootRuleOrients
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.minWrapInterpretation_not_context_orienter
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.minWrapInterpretation_not_context_orienter
#check @OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.context_lift_controls
#print axioms OperatorKO7.Methods.OrientationClosure.ContextLiftMetatheorem.context_lift_controls
