import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityDependencyPairsSubstrate

/-! # RowNecessityDependencyPairsSubstrate reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearMarkedCoeffLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearMarkedCoeffLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroMarkedCoeff_ne_counterLinear
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.zeroMarkedCoeff_ne_counterLinear
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpSubtermCriterionNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpSubtermCriterionNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpSubtermCriterionNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpSubtermCriterionNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpSubtermCriterion_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpSubtermCriterion_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionPairProcessorNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionPairProcessorNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionPairProcessorNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionPairProcessorNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionPairProcessor_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionPairProcessor_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionTriplesNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionTriplesNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionTriplesNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionTriplesNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionTriples_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpReductionTriples_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpArgumentFilteringNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpArgumentFilteringNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpArgumentFilteringNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpArgumentFilteringNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpArgumentFiltering_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpArgumentFiltering_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessorsNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessorsNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessorsNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessorsNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessors_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessors_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessors_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpNeutralProcessors_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.blindProcessorSequence_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.blindProcessorSequence_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.blindProcessorSequence_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.blindProcessorSequence_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpProcessorClassificationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpProcessorClassificationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpProcessorClassificationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpProcessorClassificationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpProcessorClassification_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.dpProcessorClassification_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ruleRhsLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ruleRhsLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctNonDescendingRule
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctNonDescendingRule
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctLoopTerm
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctLoopTerm
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctNonDescending_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctNonDescending_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctLoop_step
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctLoop_step
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctLoopTerm_not_sn
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctLoopTerm_not_sn
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctNonDescending_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sctNonDescending_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizeChangeTerminationEscapeNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizeChangeTerminationEscapeNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizeChangeTerminationEscapeNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizeChangeTerminationEscapeNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizeChangeTerminationEscape_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizeChangeTerminationEscape_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesProblemLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesProblemLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableEmptyProblemData
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableEmptyProblemData
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.loopRecRule_vars
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.loopRecRule_vars
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.loopRec_dpPair
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.loopRec_dpPair
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.loopRec_var_sn
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.loopRec_var_sn
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesMinimalityNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesMinimalityNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesMinimalityNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesMinimalityNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesMinimality_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.usableRulesMinimality_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRules_accepts_of_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRules_accepts_of_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRulesNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRulesNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRulesNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRulesNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRules_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRules_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRules_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.formativeRules_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativityNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativityNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativityNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativityNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativity_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativity_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativity_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sharingNonConservativity_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationRhsLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationRhsLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reabsorbEquations
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reabsorbEquations
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reabsorbEquations_regular
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reabsorbEquations_regular
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reabsorb_modStep
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reabsorb_modStep
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationalQuotientNonConservativityNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationalQuotientNonConservativityNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationalQuotientNonConservativityNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationalQuotientNonConservativityNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationalQuotientNonConservativity_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.equationalQuotientNonConservativity_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicabilityNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicability_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.stringRewritingInapplicability_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicabilityNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicability_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cycleRewritingInapplicability_necessity
