import OperatorKO7.Meta.Methods.OrientationClosure.HypothesisNecessityBase

/-! # HypothesisNecessityBase reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.RowNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.RowNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedPremiseCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedPremiseCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedPremiseCountermodel.refutes_deleted_barrier
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.DeletedPremiseCountermodel.refutes_deleted_barrier
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.BarrierPremiseNecessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.BarrierPremiseNecessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.BarrierPremiseNecessity.retained_barrier_false
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.BarrierPremiseNecessity.retained_barrier_false
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LawFreeBarrierNecessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.LawFreeBarrierNecessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.UniversalBarrierNecessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.UniversalBarrierNecessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.UniversalBarrierNecessity.no_deleted_premise_countermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.UniversalBarrierNecessity.no_deleted_premise_countermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoveredBarrierNecessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoveredBarrierNecessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoveredBarrierNecessity.barrier_of_partA
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoveredBarrierNecessity.barrier_of_partA
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoveredBarrierNecessity.barrier_of_partB
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.CoveredBarrierNecessity.barrier_of_partB
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.FeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.FeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.FeatureChangeControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.FeatureChangeControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.FeatureChangeControl.restore
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.FeatureChangeControl.restore
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.EscapeFeatureNecessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.EscapeFeatureNecessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoHypothesisReason
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoHypothesisReason
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoHypothesisReason.Holds
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoHypothesisReason.Holds
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoApplicableHypothesis
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoApplicableHypothesis
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoApplicableHypothesis.no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.NoApplicableHypothesis.no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pointLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.pointLens
