import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsGraphCalculi

/-! # MethodRowsGraphCalculi reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_wrap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_wrap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.symArity_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.Hypergraph
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.Hypergraph
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.DPRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.DPRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.TypeGraph
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.TypeGraph
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.StrictPreserving
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.StrictPreserving
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.GeneralizedTypeGraph
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.GeneralizedTypeGraph
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.SharedTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.SharedTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.Hypergraph.shift
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.Hypergraph.shift
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.Hypergraph.sum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.Hypergraph.sum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.TypeGraph.flower
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.TypeGraph.flower
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.noAtt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.noAtt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.oneAtt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.oneAtt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoAtt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoAtt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.threeAtt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.threeAtt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeWeightAt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeWeightAt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeSum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeSum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sum_append_nat
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sum_append_nat
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_attained
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_attained
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeSum_sum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeSum_sum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeSum_sum_split
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.edgeSum_sum_split
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_sum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_sum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_eq_of_const
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_eq_of_const
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurZeroLhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurZeroLhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurZeroRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurZeroRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurSuccLhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurSuccLhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurSuccRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.recurSuccRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.freeRecursorDPRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.freeRecursorDPRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.termSymbols
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.termSymbols
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphSymbols
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphSymbols
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.ofSymbolEdges
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.ofSymbolEdges
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.ofSymbols
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.ofSymbols
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphSymbols_ofSymbols
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphSymbols_ofSymbols
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.ReadsBack
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.ReadsBack
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_rule_decrease
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_rule_decrease
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_step_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_step_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGraph
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGraph
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGraphSecond
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGraphSecond
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharingPatternLeft
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharingPatternLeft
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharingPatternRight
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharingPatternRight
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_sharingPatternLeft
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_sharingPatternLeft
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_sharingPatternRight
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphWeight_sharingPatternRight
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharingPatterns_symbols_eq
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharingPatterns_symbols_eq
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscapeWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.wmul
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.wmul
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.gEdgeSum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.gEdgeSum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.IsMinOver
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.IsMinOver
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.GeneralizedTypeGraph.flower
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.GeneralizedTypeGraph.flower
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra.lt_of_le_of_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra.lt_of_le_of_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra.lt_of_lt_of_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra.lt_of_lt_of_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithWeight
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithWeight
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight_attained
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight_attained
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight_isMin
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.arithGraphWeight_isMin
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_rule_decrease
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_rule_decrease
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_step_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_step_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGTypeGraph
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGTypeGraph
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGTypeGraphSecond
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGTypeGraphSecond
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.constantGTypeGraph
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.constantGTypeGraph
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.constantGTypeGraph_rejected
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.constantGTypeGraph_rejected
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGTypeGraph_aggregation_control
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.twoNodeGTypeGraph_aggregation_control
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphsWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.unshare
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.unshare
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.freeSize
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.freeSize
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharedCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.sharedCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra.wellFounded_union_of_strict_measure_and_weak
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.WeightAlgebra.wellFounded_union_of_strict_measure_and_weak
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphContextStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphContextStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphContextStep_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphContextStep_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphContextStep_le
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.graphContextStep_le
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.weightedTypeGraphEscape_methodIdentity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedGraphRule_decrease
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedGraphRule_decrease
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_unglued_extension
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_unglued_extension
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.collapsingGraphRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.collapsingGraphRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.collapsingGraphGlue
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.collapsingGraphGlue
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_unglued_extension_false
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_unglued_extension_false
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.generalizedWeightedTypeGraphs_methodIdentity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.SharingAwareQuasiTerminationCertificate
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.SharingAwareQuasiTerminationCertificate
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLoop
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLoop
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLoop_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLoop_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLoop_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAwareLoop_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_unpaired_termination
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_unpaired_termination
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_unpaired_termination_false
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_unpaired_termination_false
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsGraphCalculi.quasiInterpretationsSharingAware_methodIdentity
