import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsTypingDisciplines

/-! # MethodRowsTypingDisciplines reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RV
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RV
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succLhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succLhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRule_rootStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRule_rootStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recurSucc_instance
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recurSucc_instance
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.occ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.occ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.occ_succLhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.occ_succLhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.occ_succRhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.occ_succRhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupCount_eq_one
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupCount_eq_one
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy.ExpFree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy.ExpFree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy.IsBang
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy.IsBang
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy.not_isBang_of_expFree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LTy.not_isBang_of_expFree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LSig
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LSig
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrOn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrOn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakOn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakOn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctxCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctxCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.countP_single
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.countP_single
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.balance
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.balance
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.noStructural
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.noStructural
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.occ_eq_ctxCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.occ_eq_ctxCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearRuleTyping_occ_eq
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearRuleTyping_occ_eq
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ruleCtx
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ruleCtx
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctxCount_ruleCtx
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctxCount_ruleCtx
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrier_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrier_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.atA
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.atA
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.atB
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.atB
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.atN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.atN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.witnessSig
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.witnessSig
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearCtx
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearCtx
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableCtx
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableCtx
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.recast
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.recast
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrCount_recast
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrCount_recast
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakCount_recast
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakCount_recast
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recCallDeriv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recCallDeriv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.lhsLinDeriv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.lhsLinDeriv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.rhsLinDeriv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.rhsLinDeriv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx_lhs_eq
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx_lhs_eq
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx_rhs_eq
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx_rhs_eq
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx_swap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ctx_swap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableLhsDeriv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableLhsDeriv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableRhsDeriv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableRhsDeriv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableRhsDeriv_contrCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableRhsDeriv_contrCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableLhsDeriv_contrCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableLhsDeriv_contrCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableRhsDeriv_weakCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableRhsDeriv_weakCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableLhsDeriv_weakCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reusableLhsDeriv_weakCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrCount_eq_sum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.contrCount_eq_sum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakCount_eq_sum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.LDeriv.weakCount_eq_sum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRule_contractions_eq_dupCount
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRule_contractions_eq_dupCount
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRule_contractions_ge
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.succRule_contractions_ge
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrierWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrier_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrier_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrier_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.linearLogicTypingBarrier_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val.size
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val.size
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val.hgt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val.hgt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.numeral
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.numeral
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recurVal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recurVal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val.size_pos
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Val.size_pos
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recIter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recIter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.REx
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.REx
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RTy
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RTy
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hgt_getD_le_hAt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hgt_getD_le_hAt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove_le_of_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove_le_of_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove_cons_lt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove_cons_lt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove_cons_self
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAbove_cons_self
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAt_cons_self
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAt_cons_self
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAt_cons_ne
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.hAt_cons_ne
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RB
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RB
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RB_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RB_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RB_polynomial
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RB_polynomial
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RTy.hgt_bound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.RTy.hgt_bound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorR
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorR
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reval_recursorR
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.reval_recursorR
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.rvTiers
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.rvTiers
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrier_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrier_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramified_accepts_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramified_accepts_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.expProg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.expProg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.expProg_untypable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.expProg_untypable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrierWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrier_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrier_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupTreeProg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupTreeProg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupTreeProg_typed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupTreeProg_typed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupTreeProg_size
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.dupTreeProg_size
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrier_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.ramifiedRecursionTypingBarrier_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.BEx
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.BEx
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nsf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nsf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.BSafe
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.BSafe
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval_safe_indep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval_safe_indep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval_nsf_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval_nsf_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.mxs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.mxs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.one_le_mxs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.one_le_mxs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.size_getD_le_mxs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.size_getD_le_mxs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.QB
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.QB
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.QB_mono
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.QB_mono
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.QB_polynomial
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.QB_polynomial
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bsafe_size_bound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bsafe_size_bound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Pos
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Pos
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.isN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.isN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.idxN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.idxN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.idxS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.idxS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bref
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bref
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorB
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorB
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nlist
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nlist
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.slist
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.slist
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nsf_bref
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nsf_bref
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.BSafe_bref
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.BSafe_bref
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplit_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplit_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCook_accepts_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCook_accepts_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorB_witness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorB_witness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval_recursorB_witness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.beval_recursorB_witness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplitWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.size_numeral
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.size_numeral
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.safePayloadSplit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.safePayloadSplit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplit_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplit_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplit_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.bellantoniCookSplit_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GExp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GExp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GFix
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GFix
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.upd
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.upd
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.upd_same
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.upd_same
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.upd_other
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.upd_other
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.params
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.params
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.argAt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.argAt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.valAt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.valAt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.params_dec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.params_dec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GEval
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GEval
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GEval_var_inv
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GEval_var_inv
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GEval.at_dec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GEval.at_dec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.insP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.insP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.delP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.delP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Guarded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.Guarded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GuardOK
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.GuardOK
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.guarded_eval_total
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.guarded_eval_total
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.guarded_total
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.guarded_total
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorBody
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.recursorBody
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardFix
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardFix
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittance_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittance_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.eval_recursorBody
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.eval_recursorBody
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.loopBody
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.loopBody
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.loop_not_guarded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.loop_not_guarded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.loop_diverges
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.loop_diverges
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nestedBody
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nestedBody
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nested_not_guarded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nested_not_guarded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nested_total
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.nested_total
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittanceWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittance_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittance_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittance_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsTypingDisciplines.coqGuardAdmittance_scope
