import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityCalculi

/-! # RowNecessityCalculi reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSRecurFilterLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSRecurFilterLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSPayloadFilter_eq
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSPayloadFilter_eq
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSRecurFilterLens_set_payload
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSRecurFilterLens_set_payload
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRSNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRS_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.twoDDPForCTRS_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSRecurMarkedLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSRecurMarkedLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSBlindMarked_eq
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSBlindMarked_eq
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSRecurMarkedLens_set_blind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSRecurMarkedLens_set_blind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSBlind_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSBlind_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSBlind_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRSBlind_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRS_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.operationalTerminationCTRS_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewritingBoundLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewritingBoundLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewritingNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewritingNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewritingNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewritingNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewriting_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.integerTermRewriting_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrsBoundLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrsBoundLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrsNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrsNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrsNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrsNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrs_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lctrs_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittanceRankLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittanceRankLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittanceNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittanceNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittanceNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittanceNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittance_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.abstractInterpretationAdmittance_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_hom_acc
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_hom_acc
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_accepts_of_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_accepts_of_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTerminationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTerminationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTerminationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTerminationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.categoricalToposTermination_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRSBoundLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRSBoundLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRSNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRSNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRSNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRSNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRS_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderLCTRS_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittance_accepts_all
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittance_accepts_all
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittanceNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittanceNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittanceNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittanceNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittance_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittance_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittance_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.horpoAdmittance_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittance_accepts_all
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittance_accepts_all
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittanceNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittanceNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittanceNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittanceNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittance_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittance_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittance_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cpoAdmittance_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittance_accepts_all
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittance_accepts_all
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittanceNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittanceNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittanceNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittanceNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittance_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittance_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittance_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalSchemaAdmittance_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceNatLabelsLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceNatLabelsLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceSoBaseLabels
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceSoBaseLabels
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittance_var_b_so
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittance_var_b_so
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceSoBase_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceSoBase_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceSoBase_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceSoBase_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittanceNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittance_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.sizedTypesAdmittance_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittanceStructArgLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittanceStructArgLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittanceNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittanceNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittanceNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittanceNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittance_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.coqGuardAdmittance_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplitPayloadPosLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplitPayloadPosLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplitNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplitNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplitNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplitNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplit_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.bellantoniCookSplit_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierDeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierDeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrierNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrier_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.linearLogicTypingBarrier_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrierPayloadTierLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrierPayloadTierLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrierNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrierNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrierNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrierNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrier_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.ramifiedRecursionTypingBarrier_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeTypeGraphLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeTypeGraphLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeFlatWrapGraph
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeFlatWrapGraph
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeWrapProbe
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeWrapProbe
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeFlatWrap_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeFlatWrap_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeFlatWrap_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeFlatWrap_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscapeNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscape_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.weightedTypeGraphEscape_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsTable
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsTable
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsGraphOf
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsGraphOf
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsDataOf
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsDataOf
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsWrapLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsWrapLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsBaseTable
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsBaseTable
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsBaseTable_pos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsBaseTable_pos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsDataOf_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsDataOf_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsFlatWrapTable
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsFlatWrapTable
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsFlatWrapTable_pos
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsFlatWrapTable_pos
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsFlatWrap_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsFlatWrap_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphsNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphs_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedWeightedTypeGraphs_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareEvalLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareEvalLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareHeavyShareEval
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareHeavyShareEval
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareHeavyShare_laws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareHeavyShare_laws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareHeavyShare_rejects
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareHeavyShare_rejects
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAwareNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAware_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.quasiInterpretationsSharingAware_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslation_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslation_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslation_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.piCalculusTerminationTranslation_no_feature_control
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPSNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPSNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPSNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPSNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPS_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPS_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPS_no_feature_control
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaMuSNViaCPS_no_feature_control
