import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsSortedConstrained

/-! # MethodRowsSortedConstrained reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.PStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.PStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_pstep_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_pstep_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.pstep_cons_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.pstep_cons_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.acc_pstep_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.acc_pstep_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.acc_pstep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.acc_pstep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.getElem?_mid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.getElem?_mid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.getElem?_mid_ne
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.getElem?_mid_ne
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.split_of_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.split_of_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.pstep_preserve
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.pstep_preserve
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.pstep_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.pstep_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.psteps_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.psteps_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RSN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RSN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RArgStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RArgStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActArgsSN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActArgsSN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ProperActSub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ProperActSub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Conservative
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Conservative
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RChainStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RChainStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RStepOrSub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RStepOrSub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RPairInst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RPairInst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RSubtermCriterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.RSubtermCriterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rstep_app_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rstep_app_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_rstep_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_rstep_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_rroot_of_not_defined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_rroot_of_not_defined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actArgsSN_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actArgsSN_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_app_of_not_defined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_app_of_not_defined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actSub_lift
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actSub_lift
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_actSub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_actSub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.trans
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.trans
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actSub_var_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actSub_var_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actSub_app_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.actSub_app_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_rstep_const
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_rstep_const
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_acc_of_cycle
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_acc_of_cycle
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.of_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.of_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_rchain_acc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_rchain_acc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_rchain_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_rchain_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.acc_rStepOrSub_of_actSub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.acc_rStepOrSub_of_actSub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.reflTransGen
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ActSub.reflTransGen
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ProperActSub.transGen
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ProperActSub.transGen
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ProperActSub.subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ProperActSub.subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsteps_reflTransGen
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsteps_reflTransGen
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rchainStep_proj
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rchainStep_proj
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rchain_wf_of_criterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rchain_wf_of_criterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_criterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.rsn_of_criterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.exists_getElem?_cons
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.exists_getElem?_cons
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_exists_getElem?_nil
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_exists_getElem?_nil
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuSN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuSN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuSub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuSub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuConservative
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuConservative
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuSubtermCriterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.MuSubtermCriterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.muCriterion_inst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.muCriterion_inst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.muTerminating_of_criterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.muTerminating_of_criterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fArity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fArity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.FTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.FTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDP_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDP_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.muProj
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.muProj
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.blockedTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.blockedTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.callBlockedMap
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.callBlockedMap
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Ex4Sym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Ex4Sym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4RuleA
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4RuleA
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4RuleF
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4RuleF
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4TRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4TRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4Map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4Map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4Start
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4Start
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4_loop
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ex4_loop
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPMutant
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDPMutant
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDP_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.contextSensitiveDP_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.SortAttach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.SortAttach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.HasSort
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.HasSort
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ArgsSorted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ArgsSorted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.SortedStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.SortedStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.SortedTerminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.SortedTerminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_var_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_var_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_app_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_app_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.argsSorted_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.argsSorted_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_mk
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_mk
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_arg_mid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_arg_mid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_replace
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_replace
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.occ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.occ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.occList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.occList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.IsCollapsing
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.IsCollapsing
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.IsDuplicating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.IsDuplicating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ZantemaCondition
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ZantemaCondition
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.sizeList_append
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.sizeList_append
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_acc_of_transGen_self
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.not_acc_of_transGen_self
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_not_zantema
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_not_zantema
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroduction_universal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroduction_universal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ToySym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.ToySym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyArity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyArity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyRuleF
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyRuleF
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyRuleG1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyRuleG1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyRuleG2
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyRuleG2
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyAttach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyAttach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyGab
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyGab
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyLoop
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyLoop
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyAttach_consistent
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toyAttach_consistent
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_cycle
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_cycle
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_not_zantema
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_not_zantema
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_not_defined_g_a
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_not_defined_g_a
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_step0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_step0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_step1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_step1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_steps1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_steps1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn_f_blocked
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn_f_blocked
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn_f
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn_f
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sn1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sortedTerminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.toy_sortedTerminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionMutant
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionMutant
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroduction_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroduction_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.typeIntroductionWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.lsort
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.lsort
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSWF
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSWF
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSHasSort
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSHasSort
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSSubst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSSubst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSSN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSSN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSCall
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSCall
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSOrderLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSOrderLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSRuleLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSRuleLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSArgsOK
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.OSArgsOK
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oswf_app_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oswf_app_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.osArgsOK_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.osArgsOK_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oswf_mk
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oswf_mk
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oswf_of_actSub
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oswf_of_actSub
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_subject_reduction
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_subject_reduction
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oscall_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oscall_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oscall_steps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.oscall_steps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_calls_of_rhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_calls_of_rhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_calls_of_term
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.os_calls_of_term
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.osTerminating_of_criterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.osTerminating_of_criterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_conservative_all
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_conservative_all
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDP_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDP_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_os_criterion
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_os_criterion
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.illSortedRecur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.illSortedRecur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPMutant
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDPMutant
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDP_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.orderSortedDP_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.FNF
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.FNF
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_not_defined_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_not_defined_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_not_defined_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_not_defined_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_no_step_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_no_step_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_step_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_step_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_shape
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_shape
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_det
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_root_det
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.set_mid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.set_mid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.argStep_iff_set
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.argStep_iff_set
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_join_root_arg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_join_root_arg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_join_arg_arg
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_join_arg_arg
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_localConfluent
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_localConfluent
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_confluent_of_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.free_confluent_of_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.exists_fnf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.exists_fnf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_spec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_spec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_self_steps
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_self_steps
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_unique
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_unique
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.sn_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.sn_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_succ
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fnf_succ
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Fits
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Fits
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0List
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0List
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliensList
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliensList
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0List_length
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0List_length
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0List_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0List_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList_length
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList_length
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList_getElem?
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList_getElem?
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_inh
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_inh
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_proj0
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_proj0
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_proj
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.hasSort_proj
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Consistent
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.Consistent
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.consistent_of_rules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.consistent_of_rules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.AlienLt
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.AlienLt
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.alienLt_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.alienLt_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.sn_of_isSubterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.sn_of_isSubterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fits_change
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.fits_change
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj_fit_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj_fit_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0_fit_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj0_fit_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj_nofit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj_nofit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_nofit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_nofit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_fit_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_fit_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList_mid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.projList_mid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliensList_mid
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliensList_mid
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliensList_mem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliensList_mem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_isSubterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_isSubterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_fit_below
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.aliens_fit_below
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj_eq_proj0_fnf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.proj_eq_proj0_fnf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.alien_case
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.alien_case
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.simulation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.simulation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceAliensSN
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceAliensSN
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sorted_wf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sorted_wf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sn_of_invariant_measure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sn_of_invariant_measure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sn_of_invariant_lex
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sn_of_invariant_lex
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_layer_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_layer_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_argStep_length
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_argStep_length
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_root_source_arity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_root_source_arity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_bad_arity_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_bad_arity_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_aliens_sn_of_args
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_aliens_sn_of_args
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sn_of_sorted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sn_of_sorted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sorted_iff_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sorted_iff_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceActiveSort
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceActiveSort
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceActiveInh
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceActiveInh
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_layer_sn_of_typed_projection
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_layer_sn_of_typed_projection
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTwoSortAttach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTwoSortAttach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_getElem?_none
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_getElem?_none
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_inh
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_inh
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_zeroRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_zeroRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_succRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_succRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_counter_normal
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_counter_normal
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_nil_of_length_zero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_nil_of_length_zero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_singleton
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_singleton
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_pair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_pair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_triple
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_eq_triple
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_recur_sn_of_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_recur_sn_of_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_recur_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_recur_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sorted_term_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sorted_term_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistence_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistence_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_terminates_via_manySorted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_terminates_via_manySorted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceIllTyped
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceIllTyped
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTypedRedex
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTypedRedex
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceSuccRedex
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceSuccRedex
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceSuccTarget
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceSuccTarget
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_succ_redex_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_succ_redex_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceMutant
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceMutant
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistence_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistence_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceBadInhabitant
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceBadInhabitant
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceBadInhabitant_law_failure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceBadInhabitant_law_failure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceOneSortAttach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceOneSortAttach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceOneSortDatum
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceOneSortDatum
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_oneSort_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_oneSort_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceOneSortDatum_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceOneSortDatum_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_one_sort_control
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_one_sort_control
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceSortedSubst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceSortedSubst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceNativeSortedStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceNativeSortedStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_unique
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_unique
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_match_var_sort
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_match_var_sort
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_map_agree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_map_agree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_subst_agrees
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_subst_agrees
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_complete_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_complete_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_step_preserves_sort
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_step_preserves_sort
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_rstep_to_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_rstep_to_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_native_rstep_of_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_native_rstep_of_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_native_step_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_native_step_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_acc_congr
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_acc_congr
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_native_termination_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_native_termination_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_succ_redex_native
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_succ_redex_native
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_unsorted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_unsorted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_terminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_terminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_nested_alien_sn
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_nested_alien_sn
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_wrong_arity_controls
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_wrong_arity_controls
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_successor_native_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_successor_native_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sort_mutation_control
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_sort_mutation_control
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_stutter_needs_descent
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_stutter_needs_descent
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_invariant_preservation_needed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_invariant_preservation_needed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceFreshRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceFreshRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_rhs_variable_condition_needed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_rhs_variable_condition_needed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceArbitraryTRSCounterexample
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceArbitraryTRSCounterexample
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_arbitrary_trs_counterexample
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_arbitrary_trs_counterexample
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.manySortedPersistenceWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_fits
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_ill_typed_fits
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_proj0_no_simulation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_proj0_no_simulation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_proj_not_global_fnf
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_proj_not_global_fnf
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_duplication_control
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_duplication_control
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_active_sort_cases
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_active_sort_cases
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_active_inh_spec
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_active_inh_spec
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_proj0_active
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_proj0_active
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_proj_active
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_proj_active
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sorted_persistence
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sorted_persistence
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sorted_persistence_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.freeRecursor_sorted_persistence_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTwoSortToThree
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTwoSortToThree
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTwoSortToThree_ne_two
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceTwoSortToThree_ne_two
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceUnusedSortAttach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceUnusedSortAttach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_map
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_hasSort_map
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceUnusedSort_rules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistenceUnusedSort_rules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_unused_sort_control
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSortedConstrained.persistence_unused_sort_control
