import OperatorKO7.Meta.Methods.OrientationClosure.RowNecessityOrders

/-! # RowNecessityOrders reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONonduplicatingControl_holds
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONonduplicatingControl_holds
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.standardKBO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNonduplicatingControl_holds
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNonduplicatingControl_holds
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatusNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatus_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.kboWithStatus_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBOFeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBOFeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.generalizedKBO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBOOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBOOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBODeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBODeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBOCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBOCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.subtermCoefficientKBO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONonduplicatingControl_holds
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONonduplicatingControl_holds
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acKBO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOOtherLaws
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOOtherLaws
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBODeletedLaw
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBODeletedLaw
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodelWeight
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodelWeight
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodel
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodel
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodel_weight_lt
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodel_weight_lt
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodel_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBOCountermodel_accepts
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.transfiniteKBO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONonduplicatingControl
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONonduplicatingControl
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONonduplicatingControl_holds
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONonduplicatingControl_holds
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.lambdaFreeKBO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBOFeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBOFeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.polynomialKBO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reversedSymPrec
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reversedSymPrec
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reversedSymPrec_trans
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reversedSymPrec_trans
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reversedSymPrec_wf
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.reversedSymPrec_wf
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPONecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPONecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPOFeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPOFeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPONecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPONecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPO_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.acRPO_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutationFeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutationFeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutation_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.rpoModuloPermutation_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderTypeNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderTypeNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderTypeFeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderTypeFeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderTypeNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderTypeNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderType_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.simpleTerminationOrderType_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamilyNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamilyNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamilyFeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamilyFeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamilyNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamilyNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamily_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.popStarFamily_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowingNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowingNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowingFeatureLens
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowingFeatureLens
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowingNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowingNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowing_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.cichonSlowGrowing_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderTupleInterpretationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderTupleInterpretationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderTupleInterpretationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderTupleInterpretationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderTupleInterpretation_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.higherOrderTupleInterpretation_necessity
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.infinitaryRewritingTerminationNecessityKind
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.infinitaryRewritingTerminationNecessityKind
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.infinitaryRewritingTerminationNecessityStatement
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.infinitaryRewritingTerminationNecessityStatement
#check @OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.infinitaryRewritingTermination_necessity
#print axioms OperatorKO7.Methods.OrientationClosure.HypothesisNecessity.infinitaryRewritingTermination_necessity
