import OperatorKO7.Meta.Methods.OrientationClosure.FreePolynomialTermination

/-!
# FreePolynomialTermination reach and axiom check

Paired declaration reach and axiom checks for `FreePolynomialTermination.lean`.
-/

#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupledInterpretation
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupledInterpretation
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupled_rootRuleOrients
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupled_rootRuleOrients
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.successor_strict
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.successor_strict
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.wrapper_strict_left_general
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.wrapper_strict_left_general
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.wrapper_strict_right_general
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.wrapper_strict_right_general
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.recursor_strict_base_general
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.recursor_strict_base_general
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.recursor_strict_step_general
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.recursor_strict_step_general
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.recursor_strict_counter_general
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.recursor_strict_counter_general
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupled_strictContextLaws
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupled_strictContextLaws
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupled_contextStep_decreases
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.coupled_contextStep_decreases
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.free_contextStep_reverse_wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.free_contextStep_reverse_wellFounded
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.main_free_contextual_termination
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.main_free_contextual_termination
#check @OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.main_free_root_termination
#print axioms OperatorKO7.Methods.OrientationClosure.FreePolynomialTermination.main_free_root_termination
