import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsSemanticFrameworks

/-! # MethodRowsSemanticFrameworks reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_next_of_root
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_next_of_root
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_lift
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_lift
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_next_of_contextStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_next_of_contextStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittanceInterp
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittanceInterp
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittanceValue
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittanceValue
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittancePush
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittancePush
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittancePush_comm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittancePush_comm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittancePush_strict
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittancePush_strict
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceSpuriousCycle
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceSpuriousCycle
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceSpuriousCycle_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceSpuriousCycle_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceSpuriousCycle_not_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceSpuriousCycle_not_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_unlinked_rank
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_unlinked_rank
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittanceValue_recurSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.admittanceValue_recurSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittanceWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.RankingAbstraction
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.RankingAbstraction
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.RankingAbstraction.wellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.RankingAbstraction.wellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.abstractInterpretationAdmittance_methodIdentity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.coalgebraWellFounded
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.coalgebraWellFounded
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.coalgebraWellFounded_iff_acc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.coalgebraWellFounded_iff_acc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.no_infinite_path_of_acc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.no_infinite_path_of_acc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.coalgebraWellFounded_no_infinite_path
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.coalgebraWellFounded_no_infinite_path
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop_path
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop_path
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop_not_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop_not_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop_not_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationLoop_not_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_coalgebra
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_coalgebra
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTerminationWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.categoricalToposTermination_methodIdentity
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.HUser
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.HUser
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.HTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.HTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hlit
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hlit
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecZero
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecZero
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.mem_higherOrderRecursor
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.mem_higherOrderRecursor
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor_termRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor_termRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor_defined_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor_defined_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor_happ_not_defined
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderRecursor_happ_not_defined
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSucc_rhs_recur_subterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSucc_rhs_recur_subterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hsub3
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hsub3
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.respects_hRecSucc
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.respects_hRecSucc
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSuccTrue
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSuccTrue
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLoop
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLoop
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSuccTrue_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hRecSuccTrue_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hsubCounter
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hsubCounter
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopCtx
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopCtx
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopCtx_lift
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopCtx_lift
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopTerm_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopTerm_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.not_acc_of_chain
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.not_acc_of_chain
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopTerm_not_terminating
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.hloopTerm_not_terminating
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSBound1
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRSBound1
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_scope_proven
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_scope_proven
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_methodIdentity
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsSemanticFrameworks.higherOrderLCTRS_methodIdentity
