/-
Permanent reach and axiom gate for the P3.6 residual decision layer.
-/
import OperatorKO7.Meta.Methods.OrientationClosure.SeparableSlopesDecision

#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.mk
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.mk
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.W
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.W
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.R
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.R
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.β
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.β
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.a
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.a
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.slope
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.slope
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.openBranch
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.OpenResidualInstance.openBranch
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.mk
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.mk
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.decide
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.decide
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.fail
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.fail
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.true_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.true_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.false_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualDecisionProcedure.false_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.encodedOpenInstance
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.encodedOpenInstance
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BivariateNoZeroDecider
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BivariateNoZeroDecider
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BivariateNoZeroDeciderCorrect
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BivariateNoZeroDeciderCorrect
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.noZeroDeciderOfResidual
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.noZeroDeciderOfResidual
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.noZeroDeciderOfResidual_correct
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.noZeroDeciderOfResidual_correct
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BivariateZeroDeciderCorrect
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BivariateZeroDeciderCorrect
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.zeroDeciderOfResidual
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.zeroDeciderOfResidual
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residual_decider_implies_bivariate_zero_decider
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residual_decider_implies_bivariate_zero_decider
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.NondecreasingBN
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.NondecreasingBN
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualGoal_iff_payload_axis
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualGoal_iff_payload_axis
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.scaleUPoly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.scaleUPoly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.uEval_scaleUPoly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.uEval_scaleUPoly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualLowerAtZero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualLowerAtZero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualUpperAtZero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualUpperAtZero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.uEval_residualLowerAtZero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.uEval_residualLowerAtZero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.uEval_residualUpperAtZero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.uEval_residualUpperAtZero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payload_axis_iff_ltAllB
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payload_axis_iff_ltAllB
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideResidualMonotone
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideResidualMonotone
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideResidualMonotone_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideResidualMonotone_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failResidualMonotone
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failResidualMonotone
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failResidualMonotone_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failResidualMonotone_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonomialCertificateB
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonomialCertificateB
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualMonotoneCertificate
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.ResidualMonotoneCertificate
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonotoneCertificateDecidable
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonotoneCertificateDecidable
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_zero
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_zero
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_one
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_one
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_one_nonneg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_one_nonneg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_one_mono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.monomialCounterPoly_degree_one_mono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonomialCertificate_of_mem
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonomialCertificate_of_mem
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.certified_monomial_base_mono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.certified_monomial_base_mono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.certified_monomial_counter_mono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.certified_monomial_counter_mono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualTermSum
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualTermSum
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualTermSum_base_mono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualTermSum_base_mono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualTermSum_counter_mono
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualTermSum_counter_mono
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonotoneCertificate_sound
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.residualMonotoneCertificate_sound
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.certifiedResidualDecision_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.certifiedResidualDecision_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.positiveControl_certificate
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.positiveControl_certificate
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.cancelBControl
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.cancelBControl
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.cancelBControl_monotone_outside_certificate
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.cancelBControl_monotone_outside_certificate

#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biToPayload
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biToPayload
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnlyB
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnlyB
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.PayloadOnly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.PayloadOnly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnlyDecidable
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnlyDecidable
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnly_pos
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnly_pos
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnly_neg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnly_neg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biEvalNat_biToPayload
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biEvalNat_biToPayload
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnly_eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.payloadOnly_eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decidePayloadOnlyPositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decidePayloadOnlyPositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decidePayloadOnlyPositive_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decidePayloadOnlyPositive_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failPayloadOnly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failPayloadOnly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failPayloadOnly_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failPayloadOnly_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failPayloadOnly_residual_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failPayloadOnly_residual_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biToBase
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biToBase
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnlyB
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnlyB
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BaseOnly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.BaseOnly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnlyDecidable
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnlyDecidable
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnly_pos
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnly_pos
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnly_neg
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnly_neg
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biEvalNat_biToBase
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.biEvalNat_biToBase
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnly_eval
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.baseOnly_eval
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideBaseOnlyPositive
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideBaseOnlyPositive
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideBaseOnlyPositive_iff
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.decideBaseOnlyPositive_iff
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failBaseOnly
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failBaseOnly
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failBaseOnly_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failBaseOnly_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failBaseOnly_residual_spec
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.failBaseOnly_residual_spec
#check @OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.mixedControl_outside_univariate_strata
#print axioms OperatorKO7.Methods.OrientationClosure.SeparableSlopesDecision.mixedControl_outside_univariate_strata
