import OperatorKO7.Meta.Methods.OrientationClosure.CellClassification

/-! # CellClassification reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.CellClassification.WrapUnboundedAt
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.WrapUnboundedAt
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.WrapBoundedAt
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.WrapBoundedAt
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.GainUnboundedAt
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.GainUnboundedAt
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.GainBoundedAt
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.GainBoundedAt
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.wrap_growth_dichotomy
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.wrap_growth_dichotomy
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.gain_growth_dichotomy
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.gain_growth_dichotomy
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.four_cell_coverage
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.four_cell_coverage
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.barrier_cell_excludes_orientation
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.barrier_cell_excludes_orientation
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.closedEval
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.closedEval
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.closedEval_counterTerm_of_unitSucc
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.closedEval_counterTerm_of_unitSucc
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.zeroMeasure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.zeroMeasure
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.counterRank_bounded_bounded
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.counterRank_bounded_bounded
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.counterRank_is_orienter
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.counterRank_is_orienter
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.zeroMeasure_bounded_bounded_nonorienter
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.zeroMeasure_bounded_bounded_nonorienter
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure_counterTerm
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure_counterTerm
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure_unbounded_unbounded
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure_unbounded_unbounded
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure_is_orienter
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.coupledClosedMeasure_is_orienter
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapperInterpretation
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapperInterpretation
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapperMeasure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapperMeasure
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapperMeasure_counterTerm
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapperMeasure_counterTerm
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapper_unbounded_unbounded_nonorienter
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.doubledWrapper_unbounded_unbounded_nonorienter
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperInterpretation
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperInterpretation
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure_counterTerm
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure_counterTerm
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure_bounded_unbounded
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure_bounded_unbounded
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure_is_orienter
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.boundedWrapperMeasure_is_orienter
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGainInterpretation
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGainInterpretation
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGainMeasure
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGainMeasure
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGainMeasure_counterTerm
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGainMeasure_counterTerm
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGain_bounded_unbounded_nonorienter
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.alternatingGain_bounded_unbounded_nonorienter
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.nonbarrier_cells_have_both_verdicts
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.nonbarrier_cells_have_both_verdicts
#check @OperatorKO7.Methods.OrientationClosure.CellClassification.NonBarrierCellWitnessCatalog
#print axioms OperatorKO7.Methods.OrientationClosure.CellClassification.NonBarrierCellWitnessCatalog
