import OperatorKO7.Meta.Methods.OrientationClosure.MethodRowsUsableFormative

/-! # MethodRowsUsableFormative reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FTerm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FTerm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FCall
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FCall
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FProblem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FProblem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FTRS
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FTRS
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_finiteDP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_finiteDP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.dpSource
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.dpSource
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.dpTarget
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.dpTarget
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.succRule_rhs_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.succRule_rhs_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_dpPair
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_dpPair
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.isSubterm_trans
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.isSubterm_trans
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.isSubterm_app_decompose
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.isSubterm_app_decompose
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.IsSubterm_subst_var
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.IsSubterm_subst_var
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.ruleRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.ruleRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.ruleRoot_of_lhs_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.ruleRoot_of_lhs_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.occursRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.occursRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.occursRoot_subst
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.occursRoot_subst
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.pairTargetRoot
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.pairTargetRoot
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableSym
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableSym
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.IsUsableRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.IsUsableRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.SeedRules
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.SeedRules
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.RuleSetClosed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.RuleSetClosed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableSym_rule_mem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableSym_rule_mem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRules_least
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRules_least
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRules_closed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRules_closed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableArgStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableArgStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.CallUsableRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.CallUsableRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableChainP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableChainP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRooted_app
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRooted_app
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRooted_of_subterm
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRooted_of_subterm
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableStep_of_step
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableStep_of_step
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.step_of_usableStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.step_of_usableStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.argStep_of_usableArgStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.argStep_of_usableArgStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.argStep_usableRooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.argStep_usableRooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableArgStep_of_argStep
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableArgStep_of_argStep
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableReach_and_rooted
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableReach_and_rooted
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableReach_of_reach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableReach_of_reach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.chainReach_of_usableReach
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.chainReach_of_usableReach
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableChainP_of_chainP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableChainP_of_chainP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableChainP_to_chainP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableChainP_to_chainP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesClosedSet
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesClosedSet
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesClosed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesClosed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesLeast
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesLeast
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableFragmentTerminates
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.UsableFragmentTerminates
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_seed_recur
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_seed_recur
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_usableSym_iff
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_usableSym_iff
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_zeroRule_usable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_zeroRule_usable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_succRule_usable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.free_succRule_usable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.recur_occursRoot_succRule_rhs
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.recur_occursRoot_succRule_rhs
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimalityWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.loopRecRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.loopRecRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.wrapCallRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.wrapCallRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.wrapReturnRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.wrapReturnRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlR
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlR
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlSource
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlSource
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlTarget
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlTarget
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlP
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableControlP
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.ruleRoot_wrapReturnRule
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.ruleRoot_wrapReturnRule
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_seed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_seed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_recur_usable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_recur_usable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_wrap_usable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_wrap_usable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_wrapReturn_usable
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.control_wrapReturn_usable
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.not_occursRoot_wrap_recur_vars
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.not_occursRoot_wrap_recur_vars
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_missingBase_breaks_closure
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_missingBase_breaks_closure
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_droppedLeastness_breaks_theorem
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_droppedLeastness_breaks_theorem
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_mutation
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_scope
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.usableRulesMinimality_scope
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesData
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesData
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FormativeRuleCatalog
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FormativeRuleCatalog
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FormativePairCatalog
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.FormativePairCatalog
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesSufficient
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesSufficient
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesClosed
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesClosed
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesLaws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesLaws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesAccepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesAccepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesResult
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesResult
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_sufficient_of_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_sufficient_of_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_closed_of_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_closed_of_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_sound
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_sound
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_laws
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_laws
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_accepts
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_accepts
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_result
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_result
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_feature
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRulesWitness_feature
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.blindFormativeSelector
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.blindFormativeSelector
#check @OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_mutation
#print axioms OperatorKO7.Methods.OrientationClosure.MethodRowsUsableFormative.formativeRules_mutation
