import OperatorKO7.Meta.Methods.OrientationClosure.ObserverSufficiency

/-! # ObserverSufficiency reach and axiom check -/

#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.LicensesRank
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.LicensesRank
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.licensesRank_iff_factoredRank
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.licensesRank_iff_factoredRank
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.licensesRank_of_factoredRank
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.licensesRank_of_factoredRank
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.not_licensesRank_of_cycle
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.not_licensesRank_of_cycle
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.countdown_observed_path
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.countdown_observed_path
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterFactored_licensesRank_iff_injective
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterFactored_licensesRank_iff_injective
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterFactored_licensesRank_iff_same_kernel
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterFactored_licensesRank_iff_same_kernel
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counter_target_coarsest_sufficient
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counter_target_coarsest_sufficient
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.sufficient_iff_refines_counter_kernel
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.sufficient_iff_refines_counter_kernel
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.sufficient_observer_licensesRank
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.sufficient_observer_licensesRank
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterKernelQuotientEquivNat
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterKernelQuotientEquivNat
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterKernelQuotientEquivNat_unique
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counterKernelQuotientEquivNat_unique
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.succTower
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.succTower
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.succDepth_succTower
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.succDepth_succTower
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.succBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.succBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.recursiveCallRank_zeroBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.recursiveCallRank_zeroBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.recursiveCallRank_succBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.recursiveCallRank_succBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseState_call
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseState_call
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCallCounterSystem
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCallCounterSystem
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_counterFactored_licensesRank_iff_injective
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_counterFactored_licensesRank_iff_injective
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_sufficient_observers
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_sufficient_observers
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseFlag
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseFlag
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseFlag_call
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseFlag_call
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.recursiveCallRank_call
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.recursiveCallRank_call
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.licensesRank_of_call_drop
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.licensesRank_of_call_drop
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised_licensesRank
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised_licensesRank
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised_licensesRank
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised_licensesRank
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised_zeroBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised_zeroBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised_succBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.zeroBaseRaised_succBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised_zeroBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised_zeroBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised_succBaseState
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.otherBaseRaised_succBaseState
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.raised_observers_not_refine_counter
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.raised_observers_not_refine_counter
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.raised_observers_incomparable
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.raised_observers_incomparable
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.common_coarsening_not_licensing
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.common_coarsening_not_licensing
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.no_coarsest_licensing_observer
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.no_coarsest_licensing_observer
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counter_not_coarsest_licensing_observer
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.counter_not_coarsest_licensing_observer
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_counter_order_classification
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_counter_order_classification
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.baseDepth
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.baseDepth
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.baseDepth_call
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.baseDepth_call
#check @OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_rank_orders_infinite
#print axioms OperatorKO7.Methods.OrientationClosure.ObserverSufficiency.freeCall_rank_orders_infinite
