import OperatorKO7.OrientationBoundaryAPI
import OperatorKO7.CrossPaperAPI
import OperatorKO7.InformationalIncompletenessAPI
import OperatorKO7.Meta.Recursor.CanonicalExecution
import OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict
import OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance
import OperatorKO7.Meta.OperationalInexpressibility.DeclaredResponseUniverse
import OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel

/-!
# Tier 17 prior-art repair claim reach

This is an import-and-type reach surface only.  It deliberately contains no
proof aliases.  A permitted external run must elaborate this file and the
separate axiom audit before any declaration below is typed PROVEN-IN-LEAN.
-/

set_option autoImplicit false

-- A-01: genuine order repair and the old relation's two-cycle.
#check OperatorKO7.Meta.BoundaryGeneral.VectorOrderRepair.primaryFirstLt_fin3_two_cycle
#check OperatorKO7.Meta.BoundaryGeneral.VectorOrderRepair.not_wellFounded_primaryFirstLt_fin3
#check OperatorKO7.Meta.BoundaryGeneral.VectorOrderRepair.vecLexLt_wellFounded
#check OperatorKO7.Meta.BoundaryGeneral.VectorOrderRepair.vecLex_orients_implies_primary_payloadBlind
#check OperatorKO7.Meta.BoundaryGeneral.VectorOrderRepair.counterVector_orients_vecLexLt

-- A-02: checked fixed-system negative certificates and scoped classification.
#check OperatorKO7.Meta.BoundaryGeneral.CheckedNonOrientationCertificate.not_system_global_orients
#check OperatorKO7.Meta.BoundaryGeneral.ko7Additive_checkedSystemCertificate
#check OperatorKO7.Meta.BoundaryGeneral.ko7SimpleSize_checkedSystemCertificate
#check OperatorKO7.Meta.BoundaryGeneral.ko7SimpleSize_checkedSystemCertificate_not_global_orients
#check OperatorKO7.Meta.BoundaryGeneral.declaredMethod_classification_exhaustive
#check OperatorKO7.Meta.BoundaryGeneral.atlasFamily_classifies_outside

-- B-01 and D-02: inhabited direct-grammar incompatibility and concrete bridge.
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.no_directGrammar_measure_usesPayload_and_orients
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.payload_side_nonempty
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.target_side_nonempty
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.not_factorsThrough_iff_exists_collision
#check OperatorKO7.Meta.OperationalInexpressibility.FixedInputLanguage.no_derivable_statement_decides_target
#check OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7FixedInputBoundary
#check OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_fixedInput_counterfactual_witness
#check OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_no_derivable_statement_decides_termination
#check OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_importedTerminationVerdict_decides_target
#check OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_importedTerminationVerdict_not_derivable
#check OperatorKO7.Meta.OperationalInexpressibility.KO7FixedInputLanguage.ko7_derivable_statement_nonempty
#check OperatorKO7.Meta.InformationalIncompleteness.SemanticWitnessBridge.semanticBridge_transformedCall
#check OperatorKO7.Meta.InformationalIncompleteness.SemanticWitnessBridge.semanticBridge_cert_complement

-- B-02: fixed execution, full profile collision, and independent verdict split.
#check OperatorKO7.Meta.Recursor.CanonicalExecution.recursorInputFamily_apply
#check OperatorKO7.Meta.Recursor.CanonicalExecution.canonicalExecution_stage_step
#check OperatorKO7.Meta.Recursor.CanonicalExecution.projectedCounterObserver_on_canonicalExecution
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.directProfile_recursor_eq_selfEmbedding
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.terminationVerdict_recursor_ne_selfEmbedding
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.ko7_verdict_not_candidateProfile_function

-- B-03: rule extraction, imported data, proof-valued license, scoped syntax.
#check OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.recSuccRule_extracts_ko7DPPair
#check OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7CheckedTransformedCallCertificate
#check OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractDPPairData_equivariant
#check OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7Projection_ruleDetermined
#check OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConstructionRank_not_ruleDetermined
#check OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPSoundnessLicense_bridge
#check OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7SoundnessLicense_outside_declaredExtractorLanguage
#check OperatorKO7.Meta.OperationalInexpressibility.DeclaredResponseUniverse.declaredResponseUniverse_trichotomy

-- D-04: normalized concrete KO7 licensed channel.
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_directProfile_eq
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_terminationVerdict_ne
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7UniformPrior_total
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7DirectPosterior_calibrated
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedCertificate_separates
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedAccept_eq_terminationVerdict
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7LicensedPosterior_target_mass_one
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_direct_residual_eq_log_two
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensed_residual_eq_zero
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensed_deficit_eq_log_two
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_channelSeparation_with_separate_licenseProvenance
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedChannel_headline
#check OperatorKO7.Meta.OperationalInexpressibility.KO7LicensedChannel.ko7_licensedChannel_nonvacuous

-- B-04: typed derivations, annotated reimport, and genuine inverse equations.
#check OperatorKO7.Meta.LCELTypedDerivations.DerivationMorphism.comp_assoc_onDerivation
#check OperatorKO7.Meta.LCELTypedDerivations.TheoryExtension.comp
#check OperatorKO7.Meta.LCELAnnotatedReimport.boundary_annotation_erases_to_none
#check OperatorKO7.Meta.LCELFactorization.factorsThrough_iff_fiberConstant
#check OperatorKO7.Meta.LCELFactorization.splitProjection_irreversible_of_nontrivial_kernel
#check OperatorKO7.Meta.LCELDPInstance.dpTheoryExtension_sentence_injective
#check OperatorKO7.Meta.LCELDPInstance.dpTheoryExtension_derivation_injective
#check OperatorKO7.MetaDependencyPairs.natLt_wellFounded_of_DPPairRev
#check OperatorKO7.Meta.LCELDPInstance.ko7SourceWellFounded_of_pairCertificate
#check OperatorKO7.Meta.LCELDPInstance.ko7DPCertificateConsumingLicense_yields_sourceWellFounded
#check OperatorKO7.Meta.LCELDPInstance.dpBaseDerivable_iff_observationProxyProvesBase
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemantic_observationProxy_not_truthPreserving
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDP_sourceTermination_boundaryAdmissible
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemantic_no_extensionalFactorization
#check OperatorKO7.Meta.LCELFactorization.ko7_dpRank_does_not_determine_wrapperMultiplicity
#check OperatorKO7.Meta.LCELDPInstance.ko7_typedDP_annotationClass_boundary
#check OperatorKO7.Meta.LCELDPInstance.ko7_typed_lcel_dp_package

-- C-01: actual algebra homomorphisms and the two concrete obstruction faces.
#check OperatorKO7.Meta.BoundaryGeneral.HomomorphicInexpressibility.disequality_not_termDefinable_of_hom_collapse
#check OperatorKO7.Meta.SafeStep.HomomorphicGuardBarrier.ko7_sevenConstructor_disequality_not_termDefinable
#check OperatorKO7.Meta.Recursor.HomomorphicProjectionBarrier.recursorCounterProjection_not_factorsThrough_fold

-- C-02: non-circular local necessity and exact finite-fiber greatestness.
#check OperatorKO7.Meta.DistinctionBoundary.admissibleAtDiagonal_excludes_difference
#check OperatorKO7.Meta.DistinctionBoundary.reflexiveDiagonalRepair_admissible
#check OperatorKO7.Meta.DistinctionBoundary.admissibleDiagonalCriticalPolicy_iff_semantic_admissibility
#check OperatorKO7.Meta.DistinctionBoundary.canonicalDiagonalCriticalPolicy_is_greatest_semantic
#check OperatorKO7.Meta.DistinctionBoundary.diagonalCriticalPolicyFintype
#check OperatorKO7.Meta.DistinctionBoundary.supportedAdmissibleRelation_has_finitePolicy
#check OperatorKO7.Meta.DistinctionBoundary.criticalRepairObjectFintype
#check OperatorKO7.Meta.DistinctionBoundary.canonicalCriticalRepair_isTerminal

-- D-01 and D-03: proof-carrying confession and explicit addressability premise.
#check OperatorKO7.Meta.SafeStep.SafeStepConfessionBridge.safestep_guard_emits_confession
#check OperatorKO7.Meta.SafeStep.SafeStepConfessionBridge.concreteSafeStepEvidence_has_refused_edge
#check OperatorKO7.Meta.SafeStep.SafeStepConfessionBridge.safeStepSemanticClassifier_eq_t3
#check OperatorKO7.Meta.SafeStep.SafeStepConfessionBridge.safeStepSemanticClassifier_eq_t4
#check OperatorKO7.Meta.SafeStep.SafeStepConfessionBridge.safestep_and_termination_share_t3_schema_not_full_output
#check OperatorKO7.Meta.InformationalIncompleteness.CarrierAddressability.individuallyAddressable_exceeds_fixed_budget
#check OperatorKO7.Meta.InformationalIncompleteness.CarrierAddressability.addressability_hypothesis_nonvacuous

-- Existing donor declarations actually proposed for transplantation.
#check OperatorKO7.Meta.InformationalIncompleteness.SharpnessCounterexample.payloadErasure_hypothesis_necessary
#check OperatorKO7.Meta.InformationalIncompleteness.DiagonalEntropy.diagonal_entropy_eq
