import OperatorKO7.Meta.RDRSNotesReconciliationAddendum

#check OperatorKO7.RDRSNotesReconciliationAddendum.NotesReconciliationClosed
#check OperatorKO7.RDRSNotesReconciliationAddendum.notesReconciliationRows_length
#check OperatorKO7.RDRSNotesReconciliationAddendum.notesReconciliationRows_nodup
#check OperatorKO7.RDRSNotesReconciliationAddendum.notesReconciliationRows_complete
#check OperatorKO7.RDRSNotesReconciliationAddendum.notesStatus_total
#check OperatorKO7.RDRSNotesReconciliationAddendum.rdrs_notes_reconciliation_addendum_closed
#check OperatorKO7.RDRSNotesReconciliationAddendum.rdrs_notes_reconciliation_addendum_closed_anchor
