import OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax

set_option autoImplicit false

namespace OperatorKO7.Test.RecursorCertificateSyntaxReach

/-! Current public source surface, including generated structure projections and inductive constructors, for supervisor validation. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.RootRuleRef
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.RootRuleRef.zero
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.RootRuleRef.succ
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.rule
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.activePath
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.projectionArg
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.rankBefore
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.rankAfter
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.certificateVersion
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ruleCode
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeRuleCode
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serialize
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserialize
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserialize_serialize
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serialize_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.CertificateMeaning
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_sound_rootStep
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_sound_successor
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.zeroCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.successorCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_zeroCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_successorCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.buildCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.buildCertificate_isSome_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.buildCertificate_checked
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.rootStep_has_checked_certificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.faithful_rootStep_has_checked_certificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerialized
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerialized_successorCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.faithful_successor_certificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.malformed_rule_rejected
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.out_of_range_path_rejected
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.trailing_words_rejected
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termNodes
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.treeDuplicatingInputWords
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.natBitLength
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.sharedCertificateBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.descentEvidenceBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.legacyFieldCheckerSteps
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.legacyCheckSerializedWithBound
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.legacyCheckSerializedWithBound_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.zeroCertificate_serialized_word_count
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.successorCertificate_serialized_word_count
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termEqCost
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termEqCost_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termEqCost_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.pathEqCost
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.pathEqCost_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.pathEqCost_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deltaPrefixCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deltaPrefixCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deltaPrefixCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.dpRankCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.dpRankCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.dpRankCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkerOperationBudget
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted_snd_le_budget
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_eq_some_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_snd_of_decode
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_snd_le_of_decode
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializedOperationBudget
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_snd_le_budget
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.treeDuplicatingInputWords_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits_encodeNatBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits_encodeWordsBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializeBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefix
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefix_serializeBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializedBinaryBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializedBinaryBits_eq
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits_serializeBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits_serializeBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_serializeBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_rejects_trailing
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_sound_rootStep
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.rootStep_has_strict_binary_certificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.exists_strict_binary_certificate_iff_rootStep
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits_successorCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_successorCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.certificateEnvelopeBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.sharedCertificateBits_decomposition
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.actual_word_cost_decomposition
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.old_assembly_model_formula
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.assembly_model_not_serialized_word_count
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.successor_descent_evidence_nonzero

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.RootRuleRef
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.RootRuleRef.zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.RootRuleRef.succ
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.rule
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.activePath
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.projectionArg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.rankBefore
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ExtractionCertificate.rankAfter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.certificateVersion
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.ruleCode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeRuleCode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serialize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserialize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserialize_serialize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serialize_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.CertificateMeaning
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_sound_rootStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_sound_successor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.zeroCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.successorCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_zeroCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.check_successorCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.buildCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.buildCertificate_isSome_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.buildCertificate_checked
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.rootStep_has_checked_certificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.faithful_rootStep_has_checked_certificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerialized
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerialized_successorCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.faithful_successor_certificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.malformed_rule_rejected
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.out_of_range_path_rejected
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.trailing_words_rejected
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termNodes
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.treeDuplicatingInputWords
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.natBitLength
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.sharedCertificateBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.descentEvidenceBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.legacyFieldCheckerSteps
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.legacyCheckSerializedWithBound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.legacyCheckSerializedWithBound_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.zeroCertificate_serialized_word_count
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.successorCertificate_serialized_word_count
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termEqCost
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termEqCost_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termEqCost_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.pathEqCost
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.pathEqCost_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.pathEqCost_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deltaPrefixCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deltaPrefixCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deltaPrefixCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.dpRankCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.dpRankCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.dpRankCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkerOperationBudget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkCosted_snd_le_budget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_eq_some_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_snd_le_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_snd_of_decode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_snd_le_of_decode
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializedOperationBudget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedWithBound_snd_le_budget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.treeDuplicatingInputWords_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBitsCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatBits_encodeNatBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatBits_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBitsCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsBits_encodeWordsBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsBits_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializeBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefix
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefix_serializeBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializedBinaryBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.serializedBinaryBits_eq
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits_serializeBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits_serializeBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_serializeBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_rejects_trailing
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_sound_rootStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.rootStep_has_strict_binary_certificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.exists_strict_binary_certificate_iff_rootStep
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBits_successorCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrict_successorCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.certificateEnvelopeBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.sharedCertificateBits_decomposition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.actual_word_cost_decomposition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.old_assembly_model_formula
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.assembly_model_not_serialized_word_count
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.successor_descent_evidence_nonzero
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termNodes_pos
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatPayloadWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_success
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_none
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth_encode_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat_bits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth_eq_payloadWidth
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact_encode_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact_encode_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefix_serializeBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits_pos

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.termNodes_pos
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatPayloadWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_success
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.splitPrefixCosted_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidth_encode_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeCompactWidth_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.bitsToNat_bits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatWidth_eq_payloadWidth
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeNatCompact_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompact_encode_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompact_encode_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.encodeWordsCompact_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefix_serializeBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.compactNatFieldBits_pos

/-! Recursive compact-bit runtime surface added by the OI closeout. -/
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_none
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_snd_le_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_snd_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork.bitInspections
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork.wordOperations
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_bitInspections_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.binaryParserWordBudget
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_wordOperations_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_success_length
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_serializeBits_append
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork.parser
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork.checkerOperations
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_fst
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_parser
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_bitInspections_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.strictBinaryCheckerOperationBudget
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_checkerOperations_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_serializeBits

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeCompactWidthRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_none
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_snd_le_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodePayloadRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeNatCompactRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_snd_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.decodeWordsCompactRuntimeCosted_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork.bitInspections
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryParserWork.wordOperations
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_bitInspections_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.binaryParserWordBudget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_wordOperations_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_success_length
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.deserializeBitsPrefixRuntimeWork_serializeBits_append
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork.parser
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.BinaryCheckWork.checkerOperations
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_fst
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_parser
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_bitInspections_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.strictBinaryCheckerOperationBudget
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_checkerOperations_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RecursorCertificateSyntax.checkSerializedBitsStrictRuntimeCosted_serializeBits

end OperatorKO7.Test.RecursorCertificateSyntaxReach
