import OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity

/-! Permanent reach and axiom audit for `RelationalSideCapacity`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.FiberColorable
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_iff_forall_fiberColorable
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.FiberColorable.mono
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.not_fiberColorable_of_no_certificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.no_sideChannel_of_no_certificate
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.singleton_sideChannel_iff_factorsThrough
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberColorable_card
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberChromatic
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberChromatic_spec
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberChromatic_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_iff_capacity_le
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity_exact
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity_singleton
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.finEnumeration
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.cellwiseCompatibleB
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.cellwiseCompatibleB_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.colorableB
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.colorableB_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_of_certificates
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_some
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_none_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.singletonAdmissible_decidable
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_singleton
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_certificates
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWayFinTwoColor
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_finTwo_succeeds
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_one_color_fails
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_capacity_eq_two
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWayAdmissible_decidable
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_relationalSideCapacity?
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_pairwise_compatible_capacity_two

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.FiberColorable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_iff_forall_fiberColorable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.FiberColorable.mono
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.not_fiberColorable_of_no_certificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.no_sideChannel_of_no_certificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.singleton_sideChannel_iff_factorsThrough
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberColorable_card
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberChromatic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberChromatic_spec
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.fiberChromatic_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_iff_capacity_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity_exact
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity_singleton
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.finEnumeration
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.cellwiseCompatibleB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.cellwiseCompatibleB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.colorableB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.colorableB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.exists_sideChannel_of_certificates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_some
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_eq_none_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.singletonAdmissible_decidable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.relationalSideCapacity?_singleton
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_certificates
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWayFinTwoColor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_finTwo_succeeds
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_one_color_fails
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_capacity_eq_two
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWayAdmissible_decidable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_relationalSideCapacity?
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideCapacity.threeWay_pairwise_compatible_capacity_two
