import OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.RelationalRecoveryReach

#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.FiberCommonWitness
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.QuotientRelationalRecovery
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.quotientRelationalRecovery_iff_fiberCommonWitness
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.PairConflictAt
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.pairConflictAt_refutes_quotientRelationalRecovery
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.PairwiseFiberCompatible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.fiberCommonWitness_implies_pairwiseFiberCompatible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.SingletonAdmissible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.singleton_relationalRecovery_iff_quotientFactorization
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.DirectRelationalRecovery
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.LanguageRelationalRecovery
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.languageRelationalRecovery_implies_direct
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWayAdmissible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWayObserver
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.thirdWitness
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.thirdWitness_ne_left
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.thirdWitness_ne_right
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWay_pairwiseFiberCompatible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWay_not_fiberCommonWitness
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.pairwiseFiberCompatible_not_sufficient
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.boolIdentityAdmissible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.boolIdentity_directRelationalRecovery
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.FalseOnlyLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.boolIdentity_falseOnlyLanguage_fails

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.FiberCommonWitness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.QuotientRelationalRecovery
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.quotientRelationalRecovery_iff_fiberCommonWitness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.PairConflictAt
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.pairConflictAt_refutes_quotientRelationalRecovery
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.PairwiseFiberCompatible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.fiberCommonWitness_implies_pairwiseFiberCompatible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.SingletonAdmissible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.singleton_relationalRecovery_iff_quotientFactorization
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.DirectRelationalRecovery
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.LanguageRelationalRecovery
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.languageRelationalRecovery_implies_direct
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWayAdmissible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWayObserver
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.thirdWitness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.thirdWitness_ne_left
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.thirdWitness_ne_right
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWay_pairwiseFiberCompatible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.threeWay_not_fiberCommonWitness
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.pairwiseFiberCompatible_not_sufficient
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.boolIdentityAdmissible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.boolIdentity_directRelationalRecovery
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.FalseOnlyLanguage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalRecovery.boolIdentity_falseOnlyLanguage_fails

end OperatorKO7.Test.RelationalRecoveryReach
