import OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel

/-! Paired reach and axiom inventory for `OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel`. -/

set_option autoImplicit false

namespace OperatorKO7.Test.RelationalSideChannelReach

#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.ColorCell
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.CommonWitnessOn
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.CellwiseCompatible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.PartialRelationalSideChannel
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.partialRelationalSideChannel_iff_cellwiseCompatible
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.FiberContained
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.BadFiberSubset
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.Monochromatic
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.AvoidsBadMonochromaticSubsets
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.cellwiseCompatible_iff_avoidsBadMonochromaticSubsets
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.partialRelationalSideChannel_iff_hypergraphColoring
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWayUnitColor
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWay_one_symbol_fails
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWayTwoColor
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWayTwoDecoder
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWay_two_symbols_succeed
#check @OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWay_higherOrder_sideChannel_separation

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.ColorCell
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.CommonWitnessOn
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.CellwiseCompatible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.PartialRelationalSideChannel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.partialRelationalSideChannel_iff_cellwiseCompatible
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.FiberContained
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.BadFiberSubset
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.Monochromatic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.AvoidsBadMonochromaticSubsets
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.cellwiseCompatible_iff_avoidsBadMonochromaticSubsets
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.partialRelationalSideChannel_iff_hypergraphColoring
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWayUnitColor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWay_one_symbol_fails
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWayTwoColor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWayTwoDecoder
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWay_two_symbols_succeed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RelationalSideChannel.threeWay_higherOrder_sideChannel_separation

end OperatorKO7.Test.RelationalSideChannelReach
