import OperatorKO7.Meta.RepShift.FoundationalIntegration

set_option autoImplicit false

open OperatorKO7.RepShift

#check ko7_truth_representationShiftBottleneck
#check ko7_truth_depth_two_not_representationShiftBottleneck
#check ko7_boundary_representationShiftBottleneck
#check ko7_boundary_depth_one_not_representationShiftBottleneck
#check ko7_boundary_depth_three_not_representationShiftBottleneck
#check natToUnitLayerInterface_unit
#check natToUnitLayerInterface_alpha_not_injective
#check natToUnitLayerInterface_no_leftInverse
#check natToUnitLayerInterface_gamma_has_distinct_states
#check natToUnitLayerInterface_isZero_not_canonically_preserved
#check belowSuccessorTransport_recovers_seven
#check property_transport_coexists_with_noninjective_abstraction

#print axioms ko7_truth_representationShiftBottleneck
#print axioms ko7_truth_depth_two_not_representationShiftBottleneck
#print axioms ko7_boundary_representationShiftBottleneck
#print axioms ko7_boundary_depth_one_not_representationShiftBottleneck
#print axioms ko7_boundary_depth_three_not_representationShiftBottleneck
#print axioms natToUnitLayerInterface_unit
#print axioms natToUnitLayerInterface_alpha_not_injective
#print axioms natToUnitLayerInterface_no_leftInverse
#print axioms natToUnitLayerInterface_gamma_has_distinct_states
#print axioms natToUnitLayerInterface_isZero_not_canonically_preserved
#print axioms belowSuccessorTransport_recovers_seven
#print axioms property_transport_coexists_with_noninjective_abstraction
