import OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance

/-! Permanent reach and axiom audit for `ResponseProvenance`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RuleDetermined
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ImportedData
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ruleDetermined_of_extractor
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.importedData_falsifies_ruleDetermined
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.SoundnessLicense
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.no_soundnessLicense_of_falsifier
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.caller
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.rhs
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.callee
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.DPPairData
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractDPPairData
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.recSuccRule_extracts_ko7DPPair
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractDPPairData_certified
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.TransformedCallCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7CheckedTransformedCallCertificate
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRuleRenaming
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRuleRenaming.symm
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.rename
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.renamePair
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.DPPairData.rename
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.recSucc_sourceRule_equivariant
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPPair_closed_under_renaming
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPPair_renaming_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractDPPairData_equivariant
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.CanonicalDPPairExtractor
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7CanonicalDPPairExtractor
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPPairData_ruleDetermined
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.AdmissibleConstructionRank
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.canonicalConstructionRank
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.shiftedConstructionRank
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.canonicalConstructionRank_ne_shiftedConstructionRank
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConstructionRank_nonunique
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ConstructionChoice
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.constructionRuleView
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.constructionRankData
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConstructionRank_imported
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConstructionRank_not_ruleDetermined
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ExtractedProjection
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ExtractedProjection
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractProjection
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7Projection_ruleDetermined
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.KO7TransformedTermination
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.KO7SourceRootTermination
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPSoundnessLicense
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPSoundnessLicense_bridge
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.LicenseSupply
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.licenseSupplyRuleView
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.licenseAvailable
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7SoundnessLicenseAvailability_imported
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7SoundnessLicense_outside_declaredExtractorLanguage
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ConfessionResponse
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConfessionResponse
#check @OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConfessionResponse_sourceTermination

#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RuleDetermined
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ImportedData
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ruleDetermined_of_extractor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.importedData_falsifies_ruleDetermined
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.SoundnessLicense
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.no_soundnessLicense_of_falsifier
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.caller
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.rhs
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.callee
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.DPPairData
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractDPPairData
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.recSuccRule_extracts_ko7DPPair
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractDPPairData_certified
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.TransformedCallCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7CheckedTransformedCallCertificate
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRuleRenaming
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRuleRenaming.symm
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.RecSuccRule.rename
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.renamePair
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.DPPairData.rename
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.recSucc_sourceRule_equivariant
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPPair_closed_under_renaming
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPPair_renaming_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractDPPairData_equivariant
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.CanonicalDPPairExtractor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7CanonicalDPPairExtractor
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPPairData_ruleDetermined
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.AdmissibleConstructionRank
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.canonicalConstructionRank
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.shiftedConstructionRank
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.canonicalConstructionRank_ne_shiftedConstructionRank
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConstructionRank_nonunique
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ConstructionChoice
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.constructionRuleView
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.constructionRankData
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConstructionRank_imported
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConstructionRank_not_ruleDetermined
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ExtractedProjection
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ExtractedProjection
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.extractProjection
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7Projection_ruleDetermined
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.KO7TransformedTermination
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.KO7SourceRootTermination
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPSoundnessLicense
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7DPSoundnessLicense_bridge
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.LicenseSupply
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.licenseSupplyRuleView
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.licenseAvailable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7SoundnessLicenseAvailability_imported
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7SoundnessLicense_outside_declaredExtractorLanguage
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ConfessionResponse
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConfessionResponse
#print axioms OperatorKO7.Meta.OperationalInexpressibility.ResponseProvenance.ko7ConfessionResponse_sourceTermination
