import OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation

set_option autoImplicit false

namespace OperatorKO7.Test.RolePartitionInformationReach

/-! Current public source surface, including generated structure projections and inductive constructors, for supervisor validation. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.prob
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.mk
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.enum
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.prob
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.toFinRoleLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.enumeratedRoleEntropyBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.reindexedPartition
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.reindexedPartition_realizes
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionMass
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionMass_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionMass_sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.withinCell
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.withinCell_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.withinCell_sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.deterministicPartitionJoint
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.role_zero_of_partitionMass_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint_eq_deterministic
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint_default_independent
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.deterministicPartitionJoint_entropy
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.role_partition_entropy_decomposition
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionSpentBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionResidualBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.role_partition_bits_decomposition
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.enumerated_role_partition_bits_decomposition
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionWeights
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionEvidence
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionEvidence_mixture_eq_prob
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partition_deficitBits_eq_spent
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFramePartition
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb_sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameRoleLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.H_activeFrameProb
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameSpentBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameResidualBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.HBits_activeFrameProb
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_spent_formula
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_residual_formula
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionSpentBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionResidualBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionDeficitBits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionGap
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeMass_one_residual_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeMass_zero_spent_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeMass_zero_residual_all
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.zero_frames_zero_entropy
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.actual_rary_dp_is_active_frame
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformFrameLaw
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformFrameLaw_sum_one
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformFrameLaw_nonneg
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb_uniform_eq_uniformMass
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformActiveMass_mem_unitInterval
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniform_dp_probability_map_agrees
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniform_rary_spent_bits
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniform_rary_residual_gap
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.binary_frameLaw_eq_one
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.binary_frameLaw_entropy_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.arbitrary_binary_role_law_resolves_all
#check @OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.binary_one_frame_resolves_all

#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.prob
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.RoleLaw.sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.mk
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.enum
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.prob
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.EnumeratedRoleLaw.toFinRoleLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.enumeratedRoleEntropyBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.reindexedPartition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.reindexedPartition_realizes
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionMass_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionMass_sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.withinCell
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.withinCell_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.withinCell_sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.deterministicPartitionJoint
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.role_zero_of_partitionMass_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint_eq_deterministic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionJoint_default_independent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.deterministicPartitionJoint_entropy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.role_partition_entropy_decomposition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionSpentBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionResidualBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.role_partition_bits_decomposition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.enumerated_role_partition_bits_decomposition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionWeights
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionEvidence
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partitionEvidence_mixture_eq_prob
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.partition_deficitBits_eq_spent
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFramePartition
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb_sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameRoleLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.H_activeFrameProb
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameSpentBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameResidualBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.HBits_activeFrameProb
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_spent_formula
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_residual_formula
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionSpentBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionResidualBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionDeficitBits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrame_partitionGap
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeMass_one_residual_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeMass_zero_spent_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeMass_zero_residual_all
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.zero_frames_zero_entropy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.actual_rary_dp_is_active_frame
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformFrameLaw
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformFrameLaw_sum_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformFrameLaw_nonneg
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.activeFrameProb_uniform_eq_uniformMass
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniformActiveMass_mem_unitInterval
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniform_dp_probability_map_agrees
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniform_rary_spent_bits
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.uniform_rary_residual_gap
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.binary_frameLaw_eq_one
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.binary_frameLaw_entropy_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.arbitrary_binary_role_law_resolves_all
#print axioms OperatorKO7.Meta.OperationalInexpressibility.RolePartitionInformation.binary_one_frame_resolves_all
end OperatorKO7.Test.RolePartitionInformationReach
