import OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryHorizon

/-! Permanent reach and axiom audit for `SequentialMemoryHorizon`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.licensed_history_of_le
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.first_sufficient_horizon_dichotomy
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.first_sufficient_horizon_unique
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.historyTargetKernel_coarsest_memory
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.revealingObserver
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.revealingObserver_first_sufficient_horizon
#check @OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.forgettingObserver_first_sufficient_horizon

#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.licensed_history_of_le
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.first_sufficient_horizon_dichotomy
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.first_sufficient_horizon_unique
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.historyTargetKernel_coarsest_memory
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.revealingObserver
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.revealingObserver_first_sufficient_horizon
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SequentialMemoryRecovery.forgettingObserver_first_sufficient_horizon
