import OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance

/-! Permanent reach and axiom audit for `SufficiencyInstance`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.Sufficient
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_id
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.observationMass_identityModel
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.joint_identityModel
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.posterior?_identityModel
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_identityModel_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_identityModel_iff_licensed
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.bayesRisk_identityModel_eq_zero
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.bayesRisk_deterministic_eq_zero_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.bayesRisk_eq_fullObservation_iff_sufficient
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.targetKernelQuotient_coarsest_sufficientStatistic
#check @OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.fullyNoisyBinary_sufficient_not_licensedOnJointSupport
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseStabilizer.padoa_definable_iff_stabilizer_invariant
#check @OperatorKO7.Meta.OperationalInexpressibility.LicenseStabilizer.padoa_nonempty_verdict_is_required

#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.Sufficient
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_id
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.observationMass_identityModel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.joint_identityModel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.posterior?_identityModel
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_identityModel_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.sufficient_identityModel_iff_licensed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.bayesRisk_identityModel_eq_zero
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.bayesRisk_deterministic_eq_zero_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.bayesRisk_eq_fullObservation_iff_sufficient
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.targetKernelQuotient_coarsest_sufficientStatistic
#print axioms OperatorKO7.Meta.OperationalInexpressibility.SufficiencyInstance.fullyNoisyBinary_sufficient_not_licensedOnJointSupport
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseStabilizer.padoa_definable_iff_stabilizer_invariant
#print axioms OperatorKO7.Meta.OperationalInexpressibility.LicenseStabilizer.padoa_nonempty_verdict_is_required
