import OperatorKO7.OrientationBoundaryAPI
import OperatorKO7.CrossPaperAPI
import OperatorKO7.InformationalIncompletenessAPI

/-!
# Tier 17B claim reach

This is an import-and-type reach surface for packages P1 through P8.  It
contains no proof aliases and does not strengthen any imported statement.
The mass-profile checks deliberately record the proved replacement after the
same-start `delta`-orbit equality was refuted by the positive-index theorem.
-/

set_option autoImplicit false

-- OB-ML-004: all sixteen semantic rows have a proof-bearing mirror; each of
-- the six projection rows extracts real anchor-indexed transaction evidence.
#check OperatorKO7.RDRSSemanticCoverageLedger.SemanticProjectionHardeningReceipt
#check OperatorKO7.RDRSSemanticCoverageLedger.CanonicalSemanticProjectionWitness
#check OperatorKO7.RDRSSemanticCoverageLedger.canonicalSemanticProjectionWitness
#check OperatorKO7.RDRSSemanticCoverageLedger.TypedProjectionAnchorEvidence
#check OperatorKO7.RDRSSemanticCoverageLedger.EvidenceBackedCoverageRow
#check OperatorKO7.RDRSSemanticCoverageLedger.semanticCoverageEvidenceLedger
#check OperatorKO7.RDRSSemanticCoverageLedger.semanticCoverageEvidenceLedger_length
#check OperatorKO7.RDRSSemanticCoverageLedger.semanticCoverageEvidenceLedger_rows
#check OperatorKO7.RDRSSemanticCoverageLedger.semanticCoverageRow_has_evidence_backing
#check OperatorKO7.RDRSSemanticCoverageLedger.semantic_projection_escape_row_has_typed_evidence
#check OperatorKO7.RDRSSemanticCoverageLedger.semantic_coverage_ledger_closed

-- P1: generalized non-well-foundedness of the old priority relation.
#check OperatorKO7.Meta.BoundaryGeneral.VectorOrderRepair.primaryFirstLt_not_wellFounded_of_three_le

-- P2: canonical execution mass and its honest nonterminating comparison.
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.WeightedCostExecutionAlgebra
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.factorTwoCalibratedExecutionAlgebra
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.factorTwoCalibratedExecutionAlgebra_calibration
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.ko7CanonicalExecution_stage_stepCtxFull
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.canonicalDeltaOrbit_stage_step
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.weightedCost_canonicalExecution_mass_eq_canonicalDeltaOrbit
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.weightedCost_canonicalExecution_massProfile_eq_canonicalDeltaOrbit
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.weightedMassProfileObserver_cannot_separate_canonicalExecution_from_selfEmbeddingOrbit
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.weightedCost_canonicalExecution_massProfile_eq_canonicalDeltaOrbit_iff
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.UniformCostExecutionAlgebra
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.canonicalExecution_mass_affine
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.canonicalExecution_mass_ne_deltaOrbit_of_pos
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.massMatchedCircularStep_not_stronglyNormalizing
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.canonicalExecution_massProfile_eq_massMatchedCircular
#check OperatorKO7.Meta.Recursor.CanonicalExecutionMassProfile.massProfileObserver_cannot_separate_canonicalExecution_from_massMatchedCircular

-- P3: genuine step-argument dimension and nonconstant predicates.
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivation
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivable
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivation
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivable_complete
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.DirectGrammarDerivation.no_payload_orientation
#check OperatorKO7.Meta.OperationalInexpressibility.DirectGrammarBoundary.directGrammarDerivable_no_payload_orientation
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.StepArgumentDimensionPresent
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSystem
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.fixedDuplicatingCarrierSystem_step_nonempty
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.GloballyOrientsFixedDuplicatingCarrier
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.globallyOrientsFixedDuplicatingCarrier_iff_adequateForDupOrientation
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.counter_globallyOrientsFixedDuplicatingCarrier
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_not_globallyOrientsFixedDuplicatingCarrier
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.constrainsTarget_iff_globalOrientation
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.derivable_iff_typedDirectGrammarDerivation
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.every_directGrammar_claim_derivable
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.payload_directGrammarDerivation
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.counter_directGrammarDerivation
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_predicates_nonconstant
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.derivable_claim_stepArgument_boundary
#check OperatorKO7.Meta.OperationalInexpressibility.KO7StepArgumentInstance.ko7StepArgument_operationallyIncomplete

-- P4: mapping from the declared direct universe to recorded candidates.
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectUniverse
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.candidateOfDeclaredDirectUniverse
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectOrienter
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredDirectBarrierRepresentable
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredFamilyTag
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.DeclaredFamilyMatches
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixMix2WithSumPump
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredMatrixFunctionalMeasure1WithProjectedAffinePump
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger_length
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger_length
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseFamilyLedger_nodup
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredContinuationFamilyLedger_nodup
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredBaseContinuationFamilyLedgers_disjoint
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_length
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_nonempty
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_nodup
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_complete
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_matches_tag
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_witness
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredDirectUniverse_nonempty
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.candidateProfile_covers_declared_direct_universe
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyCandidate_profile_coverage
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.declaredFamilyLedger_profile_coverage
#check OperatorKO7.Meta.OperationalInexpressibility.KO7ObservationVerdict.simpleSize_candidateProfile_blocked_on_both_relations
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.DirectProfileCovered
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileCovered
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.u6ClassOf_ne_temporaryUnclassified
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.AtlasClassificationReceipt
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassificationReceipt
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassification_nonresidual_partition
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.atlasClassification_exact_counts
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryRow
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileInventoryRows_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.methodAtlasInventoryRows_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_length
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_nodup
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventoryLedger_complete
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_coverage_total
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_profile_or_atlas_classified
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.directProfileRow_ne_methodAtlasRow
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperADeclaredInventory_exactProvedScope
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.PaperADeclaredInventoryClosed
#check @OperatorKO7.Meta.OperationalInexpressibility.KO7DeclaredInventoryCoverage.paperA_declared_inventory_closed

-- P5: derived annotated reimport and inhabited canonical instances.
#check OperatorKO7.Meta.LCELAnnotatedReimport.mapLicense_comp
#check OperatorKO7.Meta.LCELAnnotatedReimport.annotatedDerivationEquivPayload
#check OperatorKO7.Meta.LCELAnnotatedReimport.annotatedPayload_roundTrip
#check OperatorKO7.Meta.LCELAnnotatedReimport.mapLicense_reimportAnnotated
#check OperatorKO7.Meta.LCELAnnotatedReimport.eraseToBase?_annotateBase
#check OperatorKO7.Meta.LCELAnnotatedReimport.licensedPayload?_reimportAnnotated
#check OperatorKO7.Meta.LCELAnnotatedReimport.extension_derivation_reimports_annotated
#check OperatorKO7.Meta.LCELAnnotatedReimport.annotated_reimport_reversibility_derived
#check OperatorKO7.Meta.LCELCanonicalInstances.godelCanonical_boundary_reimport_overlap
#check OperatorKO7.Meta.LCELCanonicalInstances.godelCanonicalBoundaryAnnotatedProof
#check OperatorKO7.Meta.LCELCanonicalInstances.godelCanonical_unlicensed_not_annotated
#check OperatorKO7.Meta.LCELCanonicalInstances.godelCanonical_boundary_reimport_receipt
#check OperatorKO7.Meta.LCELCanonicalInstances.dpCanonical_boundary_reimport_overlap
#check OperatorKO7.Meta.LCELCanonicalInstances.canonicalAnnotatedClauseInstances_inhabited
#check OperatorKO7.Meta.LCELCanonicalInstances.dpCanonical_plainBase_reimport_impossible
#check OperatorKO7.MetaDependencyPairs.dpCounterEncoding_succ_pairRev
#check OperatorKO7.MetaDependencyPairs.dpCounterEncoding_transGen_of_lt
#check OperatorKO7.MetaDependencyPairs.natLt_wellFounded_of_DPPairRev
#check OperatorKO7.Meta.LCELDPInstance.ko7SourceWellFounded_of_pairCertificate
#check OperatorKO7.Meta.LCELDPInstance.ko7DPCertificateConsumingLicense
#check OperatorKO7.Meta.LCELDPInstance.ko7DPCertificateConsumingLicense_yields_sourceWellFounded
#check OperatorKO7.Meta.LCELDPInstance.dpBaseDerivable_iff_observationProxyProvesBase
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemanticBoundaryModel
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemantic_true_everywhere
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemantic_reference_agrees_with_observationProxy
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemantic_observationProxy_not_truthPreserving
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDP_sourceTermination_boundaryAdmissible
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemantic_not_piIrrSensitive
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDPSemantic_no_extensionalFactorization
#check OperatorKO7.Meta.LCELDPInstance.ko7TypedDP_boundaryAdmissible_set_ne_piIrrSensitive_set

-- P6: factorization inclusion, conditional equality, and non-vacuity fixture.
#check OperatorKO7.Meta.LCELFactorization.FactorizationBoundaryModel
#check OperatorKO7.Meta.LCELFactorization.ExtensionalFactorization
#check OperatorKO7.Meta.LCELFactorization.piIrrSensitive_underivable_of_baseFactorization
#check OperatorKO7.Meta.LCELFactorization.piIrrSensitive_implies_boundaryAdmissible
#check OperatorKO7.Meta.LCELFactorization.boundaryAdmissible_set_eq_piIrrSensitive_set
#check OperatorKO7.Meta.LCELFactorization.boolBaseDerivation_nonempty
#check OperatorKO7.Meta.LCELFactorization.boolIrreversible_not_provesBase
#check OperatorKO7.Meta.LCELFactorization.boolIrreversible_piIrrSensitive
#check OperatorKO7.Meta.LCELFactorization.boolExtensionalFactorization
#check OperatorKO7.Meta.LCELFactorization.ko7WrapperMultiplicity_rec_succ_deposit
#check OperatorKO7.Meta.LCELFactorization.ko7WrapperMultiplicity_rec_succ_strictly_increases
#check OperatorKO7.Meta.LCELFactorization.KO7DPFactorizationSentence
#check OperatorKO7.Meta.LCELFactorization.ko7DPFactorizationBoundaryModel
#check OperatorKO7.Meta.LCELFactorization.ko7DPFactorization_piRev_eq_dpRank
#check OperatorKO7.Meta.LCELFactorization.ko7DPFactorization_piIrr_eq_wrapperMultiplicity
#check OperatorKO7.Meta.LCELFactorization.ko7DPPair_nonempty
#check OperatorKO7.Meta.LCELFactorization.ko7DPFactorization_piRev_decreases_on_pair
#check OperatorKO7.Meta.LCELFactorization.ko7DPFactorization_piIrr_preserved_on_pair
#check OperatorKO7.Meta.LCELFactorization.ko7DP_pair_counter_descent_and_source_wrapper_deposit
#check OperatorKO7.Meta.LCELFactorization.ko7DPBaseDerivation_nonempty
#check OperatorKO7.Meta.LCELFactorization.ko7DPWrapperMultiplicityEven_not_provesBase
#check OperatorKO7.Meta.LCELFactorization.ko7DPBaseDerivationsFactorThroughRev
#check OperatorKO7.Meta.LCELFactorization.ko7DPFactorization_reference_alternate_coordinates
#check OperatorKO7.Meta.LCELFactorization.ko7_dpRank_does_not_determine_wrapperMultiplicity
#check OperatorKO7.Meta.LCELFactorization.ko7_dpRank_does_not_determine_wrapperParity
#check OperatorKO7.Meta.LCELFactorization.ko7_dpRank_has_no_trace_leftInverse
#check OperatorKO7.Meta.LCELFactorization.ko7DPWrapperMultiplicityEven_piIrrSensitive
#check OperatorKO7.Meta.LCELFactorization.ko7DPWrapperMultiplicityEven_boundaryAdmissible
#check OperatorKO7.Meta.LCELFactorization.ko7DPExtensionalFactorization
#check OperatorKO7.Meta.LCELFactorization.ko7DP_boundaryAdmissible_set_eq_piIrrSensitive_set

-- P7: same outer T3 constructor with explicitly unequal evidence payloads.
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.TerminationAxisRefusalEvidence
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisPayloadMeasure
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisPayloadMeasure_mu_eq_reflectedProjection
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisPayloadMeasure_rawSensitive_iiRecursor
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisPayloadMeasure_not_orients_iiRecursor
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisCounterPlusPayloadMeasure
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisCounterPlusPayloadMeasure_mu_eq_projectionSum
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisCounterPlusPayloadMeasure_rawSensitive_iiRecursor
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisCounterPlusPayloadMeasure_orients_iiRecursor
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisCounterPlusPayloadMeasure_counterDominated_iiRecursor
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisCounterPlusPayload_forcedTrilemma_noDecisiveSupport
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisCounterPlusPayload_substantiveNoDecisiveReceipt
#check OperatorKO7.Meta.InformationalIncompleteness.ForcedTrilemma.forced_output_trilemma_no_decisive_support
#check OperatorKO7.Meta.InformationalIncompleteness.ForcedTrilemma.forced_output_trilemma_no_decisive_support_fixedDuplicatingCarrier
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.IiRecursorRootStep
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.fixedDuplicator_actualEdge_not_iiRecursorRootStep
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.directGrammar_noDecisiveSupport_fixedDuplicator
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxis_payloadProjection_actualEdge_not_decreasing
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.canonicalTerminationAxisRefusalEvidence
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxis_refusal_actualDuplicatingEdge
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxis_refusal_actualEdge_not_decreasing
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxis_payloadProjection_not_decisive
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxis_commonSemanticRefusalBridge
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.termination_axis_direct_refusal_emits_confession
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.terminationAxisSemanticClassifier_ne_t4
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.confluence_and_termination_refusals_share_t3_constructor
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.crossAxis_confession_full_outputs_ne
#check OperatorKO7.Meta.SafeStep.CrossAxisConfession.crossAxis_confession_same_constructor_not_full_output

-- P8: termination-derived zero verdict deficit, general and KO7-specific.
#check OperatorKO7.Meta.InformationalIncompleteness.VerdictDeficit.IsSoundVerdict
#check OperatorKO7.Meta.InformationalIncompleteness.VerdictDeficit.SupportedOnSoundVerdicts
#check OperatorKO7.Meta.InformationalIncompleteness.VerdictDeficit.soundVerdict_recursor_eq_true
#check OperatorKO7.Meta.InformationalIncompleteness.VerdictDeficit.verdict_deficit_zero_of_terminating
#check OperatorKO7.Meta.InformationalIncompleteness.VerdictDeficit.canonicalSoundVerdictPrior_supported
#check OperatorKO7.Meta.InformationalIncompleteness.VerdictDeficit.ko7_recursor_verdict_deficit_zero
#check OperatorKO7.Meta.InformationalIncompleteness.VerdictDeficit.ko7_recursor_canonicalPrior_verdict_deficit_zero
