import OperatorKO7.Meta.ToolSearchFragmentCoverage_ListAudit

namespace ToolSearchFragmentCoveragePerFamilyReach

#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.ToolSearchFragmentGroup
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.toolSearchFragmentGroup
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.familyCoveredByCertificate
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.tool_search_fragment_group_catalog
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.tool_search_family_covered_by_certificate
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.tool_search_family_status_and_certificate
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.direct_scalar_families_project_to_direct_certificate
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.extended_direct_families_project_to_extended_certificate
#check OperatorKO7.ToolSearchFragmentCoveragePerFamily.matrix_projection_families_project_to_matrix_certificate

#check OperatorKO7.ToolSearchFragmentCoverageListAudit.theoremBackedToolSearchFamilies
#check OperatorKO7.ToolSearchFragmentCoverageListAudit.residualToolSearchFamilies
#check OperatorKO7.ToolSearchFragmentCoverageListAudit.theoremBackedToolSearchFamilies_complete
#check OperatorKO7.ToolSearchFragmentCoverageListAudit.theoremBackedToolSearchFamilies_status_covered
#check OperatorKO7.ToolSearchFragmentCoverageListAudit.theoremBackedToolSearchFamilies_have_certificate
#check OperatorKO7.ToolSearchFragmentCoverageListAudit.residualToolSearchFamilies_complete
#check OperatorKO7.ToolSearchFragmentCoverageListAudit.residualToolSearchFamilies_status_residual
#check OperatorKO7.ToolSearchFragmentCoverageListAudit.tool_search_fragment_audit_catalog

open OperatorKO7.ToolSearchFragmentCoverage
open OperatorKO7.ToolSearchFragmentCoverageStatus
open OperatorKO7.ToolSearchFragmentCoveragePerFamily
open OperatorKO7.ToolSearchFragmentCoverageListAudit

example : toolSearchFragmentGroup ToolSearchFragmentFamily.directPolynomial =
    ToolSearchFragmentGroup.directScalar := by
  simpa using
    (tool_search_fragment_group_catalog ToolSearchFragmentFamily.directPolynomial)

example {Sys : OperatorKO7.StepDuplicating.StepDuplicatingSchema.StepDuplicatingSystem} :
    familyCoveredByCertificate Sys ToolSearchFragmentFamily.matrixRowSum := by
  exact tool_search_family_covered_by_certificate (Sys := Sys) _

example : ResidualFragmentFamily.unrestrictedMatrixClasses ∈ residualToolSearchFamilies := by
  exact residualToolSearchFamilies_complete _

example : coveredFragmentFamilyStatus ToolSearchFragmentFamily.extendedCrossQuadratic =
    CoverageStatus.covered := by
  exact theoremBackedToolSearchFamilies_status_covered _ (theoremBackedToolSearchFamilies_complete _)

end ToolSearchFragmentCoveragePerFamilyReach
