import OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances

/-! Permanent reach and axiom audit for `TRSFiniteAdapterInstances`. -/

#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constTerm
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ConstantTRS
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ConstEdge
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constTerm_injective
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.rename_constTerm
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.apply_constTerm
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.step_constTerm_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constEdgeB
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constEdgeB_eq_true_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constantAdapter
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constant_reach_iff
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ForkSym
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkEnumeration
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constRule
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkTRS
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkTRS_constant
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkAdapter
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.fork_joinable_a_b
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ForkObs
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObsEnumeration
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObsRealize
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObsTable
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.eq_of_reflTransGen_of_forall_not
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_not_joinable
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_not_reductionClosed
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_no_adapter
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.OrbitSym
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbitRule
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbitTRS
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.sPow
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.size_sPow
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.sPow_injective
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_step
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_stepStar
#check @OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_no_adapter_realizes_f

#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constTerm
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ConstantTRS
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ConstEdge
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constTerm_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.rename_constTerm
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.apply_constTerm
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.step_constTerm_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constEdgeB
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constEdgeB_eq_true_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constantAdapter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constant_reach_iff
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ForkSym
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkEnumeration
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.constRule
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkTRS
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkTRS_constant
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkAdapter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.fork_joinable_a_b
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.ForkObs
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObsEnumeration
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObsRealize
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObsTable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.eq_of_reflTransGen_of_forall_not
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_not_joinable
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_not_reductionClosed
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.forkObs_no_adapter
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.OrbitSym
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbitRule
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbitTRS
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.sPow
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.size_sPow
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.sPow_injective
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_step
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_stepStar
#print axioms OperatorKO7.Meta.OperationalInexpressibility.TRSFiniteAdapterInstances.orbit_no_adapter_realizes_f
