import OperatorKO7.Meta.UniqueNormalization.CertificateCarrierClassification
import OperatorKO7.Meta.UniqueNormalization.CertificateFamilyInstances
import OperatorKO7.Meta.UniqueNormalization.Coalgebra
import OperatorKO7.Meta.UniqueNormalization.CommonGeneralisation
import OperatorKO7.Meta.UniqueNormalization.ConditionalDecreasingAdapter
import OperatorKO7.Meta.UniqueNormalization.ConditionalDerivationData
import OperatorKO7.Meta.UniqueNormalization.ConditionalTRS
import OperatorKO7.Meta.UniqueNormalization.ConsistencyCore
import OperatorKO7.Meta.UniqueNormalization.ConstructorCompatibility
import OperatorKO7.Meta.UniqueNormalization.ConstructorTranslation
import OperatorKO7.Meta.UniqueNormalization.DecreasingDMCancellation
import OperatorKO7.Meta.UniqueNormalization.DecreasingDiagramCarrier
import OperatorKO7.Meta.UniqueNormalization.DecreasingDiagrams
import OperatorKO7.Meta.UniqueNormalization.DecreasingLocalMeasure
import OperatorKO7.Meta.UniqueNormalization.DecreasingPasting
import OperatorKO7.Meta.UniqueNormalization.DecreasingPastingAlgebra
import OperatorKO7.Meta.UniqueNormalization.DecreasingPastingMeasure
import OperatorKO7.Meta.UniqueNormalization.DecreasingResidualAlgebra
import OperatorKO7.Meta.UniqueNormalization.DecreasingSequenceMeasure
import OperatorKO7.Meta.UniqueNormalization.DecreasingStrictSubpeak
import OperatorKO7.Meta.UniqueNormalization.DescendingClassUniqueness
import OperatorKO7.Meta.UniqueNormalization.DownRelation
import OperatorKO7.Meta.UniqueNormalization.DuplicationLabelClassification
import OperatorKO7.Meta.UniqueNormalization.Examples
import OperatorKO7.Meta.UniqueNormalization.Fence
import OperatorKO7.Meta.UniqueNormalization.FenceKernelBridge
import OperatorKO7.Meta.UniqueNormalization.FiniteDownClosure
import OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification
import OperatorKO7.Meta.UniqueNormalization.FiniteUnifierOmegaCore
import OperatorKO7.Meta.UniqueNormalization.Forest
import OperatorKO7.Meta.UniqueNormalization.GlobalUNFailure
import OperatorKO7.Meta.UniqueNormalization.GroundUnification
import OperatorKO7.Meta.UniqueNormalization.HubFreshEncoding
import OperatorKO7.Meta.UniqueNormalization.HubLinearization
import OperatorKO7.Meta.UniqueNormalization.HubSplitConditions
import OperatorKO7.Meta.UniqueNormalization.HubSplitCore
import OperatorKO7.Meta.UniqueNormalization.HubSplitLinearity
import OperatorKO7.Meta.UniqueNormalization.HubVariableConditionBoundary
import OperatorKO7.Meta.UniqueNormalization.InfeasibleOverlapCertificate
import OperatorKO7.Meta.UniqueNormalization.Lemma36
import OperatorKO7.Meta.UniqueNormalization.Lemma52
import OperatorKO7.Meta.UniqueNormalization.Lemma64Counterexample
import OperatorKO7.Meta.UniqueNormalization.LevelLabels
import OperatorKO7.Meta.UniqueNormalization.Linearization
import OperatorKO7.Meta.UniqueNormalization.ModelInfeasibility
import OperatorKO7.Meta.UniqueNormalization.OverlapClasses
import OperatorKO7.Meta.UniqueNormalization.ProofGraph
import OperatorKO7.Meta.UniqueNormalization.Proposition22
import OperatorKO7.Meta.UniqueNormalization.RationalUnification
import OperatorKO7.Meta.UniqueNormalization.RewriteAux
import OperatorKO7.Meta.UniqueNormalization.RuleFamilySupport
import OperatorKO7.Meta.UniqueNormalization.Section7ChainClassification
import OperatorKO7.Meta.UniqueNormalization.Section7Completion
import OperatorKO7.Meta.UniqueNormalization.Section7ConversionCompatibility
import OperatorKO7.Meta.UniqueNormalization.Section7CriticalPairDichotomy
import OperatorKO7.Meta.UniqueNormalization.Section7CutElimination
import OperatorKO7.Meta.UniqueNormalization.Section7DownDerivation
import OperatorKO7.Meta.UniqueNormalization.Section7FiberReduction
import OperatorKO7.Meta.UniqueNormalization.Section7FinalInterface
import OperatorKO7.Meta.UniqueNormalization.Section7GlobalCutElimination
import OperatorKO7.Meta.UniqueNormalization.Section7GlobalDownDerivation
import OperatorKO7.Meta.UniqueNormalization.Section7GuardedClosure
import OperatorKO7.Meta.UniqueNormalization.Section7Joinability
import OperatorKO7.Meta.UniqueNormalization.Section7JointClosure
import OperatorKO7.Meta.UniqueNormalization.Section7KernelCompatibility
import OperatorKO7.Meta.UniqueNormalization.Section7RootSufficiency
import OperatorKO7.Meta.UniqueNormalization.Section7RootTargets
import OperatorKO7.Meta.UniqueNormalization.Section7SameGraphClosure
import OperatorKO7.Meta.UniqueNormalization.Section7SelfGreyCountermodel
import OperatorKO7.Meta.UniqueNormalization.Section7SimultaneousClosure
import OperatorKO7.Meta.UniqueNormalization.Section7StrongRootTargets
import OperatorKO7.Meta.UniqueNormalization.Section7SupportKernel
import OperatorKO7.Meta.UniqueNormalization.Section7SupportSaturation
import OperatorKO7.Meta.UniqueNormalization.Section7Targeting
import OperatorKO7.Meta.UniqueNormalization.Section7TightClosure
import OperatorKO7.Meta.UniqueNormalization.SemiEquationalConfluence
import OperatorKO7.Meta.UniqueNormalization.SignatureExtension
import OperatorKO7.Meta.UniqueNormalization.Summit
import OperatorKO7.Meta.UniqueNormalization.TermMaps
import OperatorKO7.Meta.UniqueNormalization.Theorem37
import OperatorKO7.Meta.UniqueNormalization.Theorem69
import OperatorKO7.Meta.UniqueNormalization.Transfer
import OperatorKO7.Meta.UniqueNormalization.UNStatement
import OperatorKO7.Meta.UniqueNormalization.UnificationTransport
import OperatorKO7.Meta.ProofSearchBoundary.F65Unfolding
import OperatorKO7.Meta.ProofSearchBoundary.DownLeast
import OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms
import OperatorKO7.Meta.NormalizationBoundary.ThreeFaces
import OperatorKO7.Meta.DistinctionBoundary.PersistentLicense
import OperatorKO7.Meta.DistinctionBoundary.WriteClosure
import OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject
import OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryCompletion
import OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder
import OperatorKO7.Meta.LicensedBoundaryCalculus.RecoveryForwardCapabilitySeparation
import OperatorKO7.Meta.LicensedBoundaryCalculus.GuardFreezeGrammar
import OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense
import OperatorKO7.Meta.LicensedBoundaryCalculus.RepairLicenseCapstone
import OperatorKO7.Meta.DistinctionBoundary.DynamicDiagonalGradeTransport
import OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification
import OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient
import OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingCompletionRule
import OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry
import OperatorKO7.Meta.BoundaryGeneral.PersistentExogeny
import OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop
import OperatorKO7.Meta.DistinctionBoundary.GodelQuoteEvalPeak
import OperatorKO7.Meta.DistinctionBoundary.DiagonalLevels
import OperatorKO7.Meta.DistinctionBoundary.GodelObject
import OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint
import OperatorKO7.Meta.DistinctionBoundary.GodelEscapeComplete
import OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor
import OperatorKO7.Meta.LicensedBoundaryCalculus.MetricDynamicLicense
import OperatorKO7.Meta.LicensedBoundaryCalculus.Transport.Strength
import OperatorKO7.Meta.BoundaryOperator.TransportCeiling
import OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations
import OperatorKO7.Meta.DistinctionBoundary.GodelPartialClosure
import OperatorKO7.Meta.DistinctionBoundary.GodelAcceptableNumbering
import OperatorKO7.Meta.DistinctionBoundary.GodelAcceptableNumberingStep
import OperatorKO7.Meta.DistinctionBoundary.GodelAccCodeSelfNumbering
import OperatorKO7.Meta.DistinctionBoundary.GodelRankTransport
import OperatorKO7.Meta.DistinctionBoundary.GodelRobinsonQ
import OperatorKO7.Meta.DistinctionBoundary.GodelGeneralSemantics
import OperatorKO7.Meta.DistinctionBoundary.GodelFirstIncompleteness
import OperatorKO7.Meta.DistinctionBoundary.GodelFixedPointSemantics
import OperatorKO7.Meta.DistinctionBoundary.GodelInternalDerivability
import OperatorKO7.Meta.DistinctionBoundary.GodelNonstandardModel
import OperatorKO7.Meta.DistinctionBoundary.GodelInductionChecker
import OperatorKO7.Meta.DistinctionBoundary.GodelSigmaOne
import OperatorKO7.Meta.DistinctionBoundary.GodelInternalSigmaOne
import OperatorKO7.Meta.DistinctionBoundary.GodelHBL
import OperatorKO7.Meta.DistinctionBoundary.GodelPrimitiveRecursiveSyntax
import OperatorKO7.Meta.DistinctionBoundary.GodelPrimitiveRecursiveSubstitution
import OperatorKO7.Meta.DistinctionBoundary.GodelPrimitiveRecursiveProofChecker
import OperatorKO7.Meta.DistinctionBoundary.GodelPrimitiveRecursiveProofTreeChecker
import OperatorKO7.Meta.DistinctionBoundary.GodelPrimitiveRecursiveBetaBridge
import OperatorKO7.Meta.ProofSearchBoundary
import OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate
import OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination
import OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingDatumCategory
import OperatorKO7.Meta.BoundaryGeneral.GradedOmega

/-!
# Claim-index anchor check for Unique Normal Forms

Every identifier in `3.UNIQUE_NORMAL_FORMS_CLAIM_INDEX.md` that
resolves to a fully qualified `OperatorKO7` or `KO7FenceBridge`
name is `#check`ed and `#print axioms`ed here.
-/

set_option autoImplicit false

#check @OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.lemma64_fails_as_printed
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.lemma64_fails_as_printed
#check @OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.lemma64_as_printed
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.lemma64_as_printed
#check @OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.trap_DownOn_is_consistencyInvariant
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.trap_DownOn_is_consistencyInvariant
#check @OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.selected_redex_returns_to_fiber
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.selected_redex_returns_to_fiber
#check @OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.repair_requires_parent_change
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.repair_requires_parent_change
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.uniqueReachableNormalForms_iff_gapNonpos
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.uniqueReachableNormalForms_iff_gapNonpos
#check @OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.not_every_complete_targeted_graph_universal
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.not_every_complete_targeted_graph_universal
#check @OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.complete_targeted_counterexample
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7Active.Trap.complete_targeted_counterexample
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.positive_reach_zero_forces_one_parent
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.positive_reach_zero_forces_one_parent
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_one_parent_reach_zero
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_one_parent_reach_zero
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_graph_universal_iff_parent
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_graph_universal_iff_parent
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_target_universal_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_target_universal_iff
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_target_eqv_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_target_eqv_iff
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_target_nf_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_target_nf_iff
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.quotient_complete_target_universal_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.quotient_complete_target_universal_iff
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.chain_counterexample_and_repair
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.chain_counterexample_and_repair
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.chain_bad_graph_exists_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.chain_bad_graph_exists_iff
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_nonuniversal_no_edge_extension
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_nonuniversal_no_edge_extension
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_nonuniversal_changed_edge
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.complete_nonuniversal_changed_edge
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.repaired_preserves_eqv
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.repaired_preserves_eqv
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.repair_must_change_edge
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.repair_must_change_edge
#check @OperatorKO7.Meta.UniqueNormalization.cconv_iff_conv
#print axioms OperatorKO7.Meta.UniqueNormalization.cconv_iff_conv
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_cconfluent_linearization
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_cconfluent_linearization
#check @OperatorKO7.Meta.UniqueNormalization.UNred_of_cconfluent_linearization
#print axioms OperatorKO7.Meta.UniqueNormalization.UNred_of_cconfluent_linearization
#check @OperatorKO7.Meta.UniqueNormalization.allPeaksMeasured
#print axioms OperatorKO7.Meta.UniqueNormalization.allPeaksMeasured
#check @OperatorKO7.Meta.UniqueNormalization.allLocalPeaksDecreasing_confluent
#print axioms OperatorKO7.Meta.UniqueNormalization.allLocalPeaksDecreasing_confluent
#check @OperatorKO7.Meta.UniqueNormalization.MeasuredJoin.paste
#print axioms OperatorKO7.Meta.UniqueNormalization.MeasuredJoin.paste
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_linearization_localDecreasing
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_linearization_localDecreasing
#check @OperatorKO7.Meta.UniqueNormalization.isMethodLinearization_linHub
#print axioms OperatorKO7.Meta.UniqueNormalization.isMethodLinearization_linHub
#check @OperatorKO7.Meta.UniqueNormalization.isLinearization_linHub
#print axioms OperatorKO7.Meta.UniqueNormalization.isLinearization_linHub
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_minimalLevel_localDecreasing
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_minimalLevel_localDecreasing
#check @OperatorKO7.Meta.UniqueNormalization.hubCRule_diagRule_conds
#print axioms OperatorKO7.Meta.UniqueNormalization.hubCRule_diagRule_conds
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.ruleLabelStep_iff_step
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.ruleLabelStep_iff_step
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.atom_peak_decreasing_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.atom_peak_decreasing_iff
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.atom_peak_rule_priority_repair
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.atom_peak_rule_priority_repair
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.atom_peak_small_arity
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.atom_peak_small_arity
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.nested_peak_not_decreasing
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.nested_peak_not_decreasing
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.no_constant_rule_labeling
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.no_constant_rule_labeling
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.nested_peak_ordinary_join
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.nested_peak_ordinary_join
#check @OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.minimum_level_refutation_preserved
#print axioms OperatorKO7.Meta.UniqueNormalization.DuplicationLabels.minimum_level_refutation_preserved
#check @OperatorKO7.Meta.UniqueNormalization.cstep_iff_cstepE_cconv
#print axioms OperatorKO7.Meta.UniqueNormalization.cstep_iff_cstepE_cconv
#check @OperatorKO7.Meta.UniqueNormalization.cpar_exists_target
#print axioms OperatorKO7.Meta.UniqueNormalization.cpar_exists_target
#check @OperatorKO7.Meta.UniqueNormalization.oracleStable_cconv
#print axioms OperatorKO7.Meta.UniqueNormalization.oracleStable_cconv
#check @OperatorKO7.Meta.UniqueNormalization.cconfluent_of_noFeasibleOverlap
#print axioms OperatorKO7.Meta.UniqueNormalization.cconfluent_of_noFeasibleOverlap
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_nonOverlapping
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_nonOverlapping
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_noFeasibleOverlap
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_noFeasibleOverlap
#check @OperatorKO7.Meta.UniqueNormalization.KlopSystem.UNconv_trs_and_not_confluent
#print axioms OperatorKO7.Meta.UniqueNormalization.KlopSystem.UNconv_trs_and_not_confluent
#check @OperatorKO7.Meta.UniqueNormalization.InfeasibleOverlap.lin_cconfluent
#print axioms OperatorKO7.Meta.UniqueNormalization.InfeasibleOverlap.lin_cconfluent
#check @OperatorKO7.Meta.ProofSearchBoundary.F65Unfolding.f65_residual_contains_UN_instance
#print axioms OperatorKO7.Meta.ProofSearchBoundary.F65Unfolding.f65_residual_contains_UN_instance
#check @OperatorKO7.Meta.ProofSearchBoundary.F65Unfolding.f65_residual_forces_cd_separation
#print axioms OperatorKO7.Meta.ProofSearchBoundary.F65Unfolding.f65_residual_forces_cd_separation
#check @OperatorKO7.Meta.UniqueNormalization.SymbolInterp.eval_eq_of_conv
#print axioms OperatorKO7.Meta.UniqueNormalization.SymbolInterp.eval_eq_of_conv
#check @OperatorKO7.Meta.UniqueNormalization.noFeasibleOverlap_of_model
#print axioms OperatorKO7.Meta.UniqueNormalization.noFeasibleOverlap_of_model
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_model
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_model
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_model
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_linHub_model
#check @OperatorKO7.Meta.UniqueNormalization.quotientInterp_rulesHold
#print axioms OperatorKO7.Meta.UniqueNormalization.quotientInterp_rulesHold
#check @OperatorKO7.Meta.UniqueNormalization.noFeasibleOverlap_iff_quotient_refutes
#print axioms OperatorKO7.Meta.UniqueNormalization.noFeasibleOverlap_iff_quotient_refutes
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.f45_nonOmegaOverlapping
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.f45_nonOmegaOverlapping
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.f45_rhsDetermined
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.f45_rhsDetermined
#check @OperatorKO7.Meta.UniqueNormalization.F45Certificate.lin_not_nonOverlapping
#print axioms OperatorKO7.Meta.UniqueNormalization.F45Certificate.lin_not_nonOverlapping
#check @OperatorKO7.Meta.UniqueNormalization.F45Certificate.model_refutes
#print axioms OperatorKO7.Meta.UniqueNormalization.F45Certificate.model_refutes
#check @OperatorKO7.Meta.UniqueNormalization.F45Certificate.UNconv_trs
#print axioms OperatorKO7.Meta.UniqueNormalization.F45Certificate.UNconv_trs
#check @OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_certificate_iff_infinite
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_certificate_iff_infinite
#check @OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_certificate_separates
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_certificate_separates
#check @OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_embedding
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_embedding
#check @OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_no_finite_certificate_direct
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_no_finite_certificate_direct
#check @OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_minimal_carrier
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_minimal_carrier
#check @OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_class_and_UNconv
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.capacity_class_and_UNconv
#check @OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.finite_constructions_not_certificate
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateCapacity.finite_constructions_not_certificate
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_nonOmegaOverlapping
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_nonOmegaOverlapping
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_rhsDetermined
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_rhsDetermined
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_nonlinear_and_collapsing
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_nonlinear_and_collapsing
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_infinite_reduction
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_infinite_reduction
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_rhs_occurrence_count
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_rhs_occurrence_count
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.ruleD_duplicates_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.ruleD_duplicates_iff
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_UNconv
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_UNconv
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_certificate_iff_infinite
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_certificate_iff_infinite
#check @OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_minimal_carrier
#print axioms OperatorKO7.Meta.UniqueNormalization.CertificateFamily.family_minimal_carrier
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.fresh_rhs_root_universal
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.fresh_rhs_root_universal
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.fresh_rhs_conversion_universal
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.fresh_rhs_conversion_universal
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_nonOmegaOverlapping
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_nonOmegaOverlapping
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_not_rhsDetermined
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_not_rhsDetermined
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_not_UNconv
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_not_UNconv
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_hub_feasible
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_hub_feasible
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_patterns_not_omegaUnifiable
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.reconstruction_patterns_not_omegaUnifiable
#check @OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.unrestricted_reconstruction_false
#print axioms OperatorKO7.Meta.UniqueNormalization.FreshVariableBoundary.unrestricted_reconstruction_false
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.levelStepData_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.levelStepData_iff
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.levelConvData_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.levelConvData_iff
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.conditionalHistory_iff_cconv
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.conditionalHistory_iff_cconv
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_reverse
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_reverse
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_length_append
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_length_append
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_totalOccurrences
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_totalOccurrences
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_erasure_not_injective
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.history_erasure_not_injective
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.context_history_projection
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.context_history_projection
#check @OperatorKO7.Meta.UniqueNormalization.ConditionHistory.root_history_projection_fails
#print axioms OperatorKO7.Meta.UniqueNormalization.ConditionHistory.root_history_projection_fails
#check @OperatorKO7.Meta.UniqueNormalization.lemma13
#print axioms OperatorKO7.Meta.UniqueNormalization.lemma13
#check @OperatorKO7.Meta.UniqueNormalization.lemma14_forward
#print axioms OperatorKO7.Meta.UniqueNormalization.lemma14_forward
#check @OperatorKO7.Meta.UniqueNormalization.lemma14_back
#print axioms OperatorKO7.Meta.UniqueNormalization.lemma14_back
#check @OperatorKO7.Meta.UniqueNormalization.prop15_forward
#print axioms OperatorKO7.Meta.UniqueNormalization.prop15_forward
#check @OperatorKO7.Meta.UniqueNormalization.prop15_back
#print axioms OperatorKO7.Meta.UniqueNormalization.prop15_back
#check @OperatorKO7.Meta.UniqueNormalization.cor16
#print axioms OperatorKO7.Meta.UniqueNormalization.cor16
#check @OperatorKO7.Meta.UniqueNormalization.normalForm_extended
#print axioms OperatorKO7.Meta.UniqueNormalization.normalForm_extended
#check @OperatorKO7.Meta.UniqueNormalization.conv_var_var
#print axioms OperatorKO7.Meta.UniqueNormalization.conv_var_var
#check @OperatorKO7.Meta.UniqueNormalization.not_consistent_extended
#print axioms OperatorKO7.Meta.UniqueNormalization.not_consistent_extended
#check @OperatorKO7.Meta.UniqueNormalization.symbolAbsent_all_normalForms_false
#print axioms OperatorKO7.Meta.UniqueNormalization.symbolAbsent_all_normalForms_false
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_consistency_of_extensions
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_consistency_of_extensions
#check @OperatorKO7.Meta.UniqueNormalization.normalForm_freeze
#print axioms OperatorKO7.Meta.UniqueNormalization.normalForm_freeze
#check @OperatorKO7.Meta.UniqueNormalization.nonOmegaOverlapping_ext
#print axioms OperatorKO7.Meta.UniqueNormalization.nonOmegaOverlapping_ext
#check @OperatorKO7.Meta.UniqueNormalization.rhsDetermined_ext
#print axioms OperatorKO7.Meta.UniqueNormalization.rhsDetermined_ext
#check @OperatorKO7.Meta.UniqueNormalization.conv_var_var_ext
#print axioms OperatorKO7.Meta.UniqueNormalization.conv_var_var_ext
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_theorem68
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_theorem68
#check @OperatorKO7.Meta.UniqueNormalization.eq_of_ground_infiniteOmegaUnifiable
#print axioms OperatorKO7.Meta.UniqueNormalization.eq_of_ground_infiniteOmegaUnifiable
#check @OperatorKO7.Meta.UniqueNormalization.exists_match_of_ground_infiniteOmegaUnifiable
#print axioms OperatorKO7.Meta.UniqueNormalization.exists_match_of_ground_infiniteOmegaUnifiable
#check @OperatorKO7.Meta.UniqueNormalization.subterm_not_infiniteOmegaUnifiable_of_ground_normalForm
#print axioms OperatorKO7.Meta.UniqueNormalization.subterm_not_infiniteOmegaUnifiable_of_ground_normalForm
#check @OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.decision_infinite_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.decision_infinite_iff
#check @OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.findCertificate_subst_solves
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.findCertificate_subst_solves
#check @OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.rational_iff_infinite
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.rational_iff_infinite
#check @OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.nonOmegaDecision_true_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.nonOmegaDecision_true_iff
#check @OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.findForbiddenOverlap_certificate
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteRationalUnification.findForbiddenOverlap_certificate
#check @OperatorKO7.Meta.UniqueNormalization.cor35
#print axioms OperatorKO7.Meta.UniqueNormalization.cor35
#check @OperatorKO7.Meta.UniqueNormalization.lemma36
#print axioms OperatorKO7.Meta.UniqueNormalization.lemma36
#check @OperatorKO7.Meta.UniqueNormalization.thm37
#print axioms OperatorKO7.Meta.UniqueNormalization.thm37
#check @OperatorKO7.Meta.UniqueNormalization.Down.sigmaClosed
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.sigmaClosed
#check @OperatorKO7.Meta.UniqueNormalization.Down.constructorCompatible
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.constructorCompatible
#check @OperatorKO7.Meta.UniqueNormalization.Down.consistent
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.consistent
#check @OperatorKO7.Meta.UniqueNormalization.cor45
#print axioms OperatorKO7.Meta.UniqueNormalization.cor45
#check @OperatorKO7.Meta.UniqueNormalization.Down.to_conv
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.to_conv
#check @OperatorKO7.Meta.UniqueNormalization.Down.of_conv
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.of_conv
#check @OperatorKO7.Meta.UniqueNormalization.conv_eq_down
#print axioms OperatorKO7.Meta.UniqueNormalization.conv_eq_down
#check @OperatorKO7.Meta.UniqueNormalization.consistent_of_down_trans
#print axioms OperatorKO7.Meta.UniqueNormalization.consistent_of_down_trans
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_section7
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_section7
#check @OperatorKO7.Meta.UniqueNormalization.UNred_of_section7
#print axioms OperatorKO7.Meta.UniqueNormalization.UNred_of_section7
#check @OperatorKO7.Meta.UniqueNormalization.down_iff_join
#print axioms OperatorKO7.Meta.UniqueNormalization.down_iff_join
#check @OperatorKO7.Meta.UniqueNormalization.downOn_iff_join
#print axioms OperatorKO7.Meta.UniqueNormalization.downOn_iff_join
#check @OperatorKO7.Meta.UniqueNormalization.translated_critical_pair_dichotomy
#print axioms OperatorKO7.Meta.UniqueNormalization.translated_critical_pair_dichotomy
#check @OperatorKO7.Meta.UniqueNormalization.argumentChainComposition_eq
#print axioms OperatorKO7.Meta.UniqueNormalization.argumentChainComposition_eq
#check @OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.sigmaClosedOn_of_complete
#print axioms OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.sigmaClosedOn_of_complete
#check @OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.target_rootStep_eqvOn_of_complete_strong
#print axioms OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.target_rootStep_eqvOn_of_complete_strong
#check @OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.universal_of_rootStepsRepresented
#print axioms OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.universal_of_rootStepsRepresented
#check @OperatorKO7.Meta.UniqueNormalization.section7Target_nonempty
#print axioms OperatorKO7.Meta.UniqueNormalization.section7Target_nonempty
#check @OperatorKO7.Meta.UniqueNormalization.exists_equalityComplete_rootStepsRepresented
#print axioms OperatorKO7.Meta.UniqueNormalization.exists_equalityComplete_rootStepsRepresented
#check @OperatorKO7.Meta.UniqueNormalization.PGraph.contextTransitive_iff_contextAbsorbs
#print axioms OperatorKO7.Meta.UniqueNormalization.PGraph.contextTransitive_iff_contextAbsorbs
#check @OperatorKO7.Meta.UniqueNormalization.PGraph.context_iff_downOn_of_rootStepsRepresented
#print axioms OperatorKO7.Meta.UniqueNormalization.PGraph.context_iff_downOn_of_rootStepsRepresented
#check @OperatorKO7.Meta.UniqueNormalization.PGraph.downOn_transitive_of_contextAbsorbs
#print axioms OperatorKO7.Meta.UniqueNormalization.PGraph.downOn_transitive_of_contextAbsorbs
#check @OperatorKO7.Meta.UniqueNormalization.exists_constructorCompatible_equivalence_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.exists_constructorCompatible_equivalence_iff
#check @OperatorKO7.Meta.UniqueNormalization.ConstructorEqClosure.finite_support
#print axioms OperatorKO7.Meta.UniqueNormalization.ConstructorEqClosure.finite_support
#check @OperatorKO7.Meta.UniqueNormalization.constructorClash_iff_finite_seed
#print axioms OperatorKO7.Meta.UniqueNormalization.constructorClash_iff_finite_seed
#check @OperatorKO7.Meta.UniqueNormalization.constructorCompatible_equivalence_finite_character
#print axioms OperatorKO7.Meta.UniqueNormalization.constructorCompatible_equivalence_finite_character
#check @OperatorKO7.Meta.UniqueNormalization.Down.iff_exists_finite_coalgebra
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.iff_exists_finite_coalgebra
#check @OperatorKO7.Meta.UniqueNormalization.Down.pair_exists_finite_coalgebra
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.pair_exists_finite_coalgebra
#check @OperatorKO7.Meta.UniqueNormalization.conv_iff_down_of_finite_context_models
#print axioms OperatorKO7.Meta.UniqueNormalization.conv_iff_down_of_finite_context_models
#check @OperatorKO7.Meta.UniqueNormalization.constructorCompatible_conv_of_finite_context_models
#print axioms OperatorKO7.Meta.UniqueNormalization.constructorCompatible_conv_of_finite_context_models
#check @OperatorKO7.Meta.UniqueNormalization.FiniteDown.bounded_saturation
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteDown.bounded_saturation
#check @OperatorKO7.Meta.UniqueNormalization.FiniteDown.rootTable_exact
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteDown.rootTable_exact
#check @OperatorKO7.Meta.UniqueNormalization.FiniteDown.mem_computeTRS_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.FiniteDown.mem_computeTRS_iff
#check @OperatorKO7.Meta.UniqueNormalization.exists_tightEqualityComplete_rootStepsRepresented_of_strong
#print axioms OperatorKO7.Meta.UniqueNormalization.exists_tightEqualityComplete_rootStepsRepresented_of_strong
#check @OperatorKO7.Meta.UniqueNormalization.Section7SelfGreyCountermodel.selfGrey_countermodel
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7SelfGreyCountermodel.selfGrey_countermodel
#check @OperatorKO7.Meta.UniqueNormalization.Section7SelfGreyCountermodel.not_selfGrey_strong_terminating_soundness
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7SelfGreyCountermodel.not_selfGrey_strong_terminating_soundness
#check @OperatorKO7.Meta.UniqueNormalization.Section7SelfGreyCountermodel.no_sound_support_certificate
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7SelfGreyCountermodel.no_sound_support_certificate
#check @OperatorKO7.Meta.ProofSearchBoundary.DownLeast.downOn_iff_hornDeriv
#print axioms OperatorKO7.Meta.ProofSearchBoundary.DownLeast.downOn_iff_hornDeriv
#check @OperatorKO7.Meta.ProofSearchBoundary.DownLeast.downOn_excludes_unfounded
#print axioms OperatorKO7.Meta.ProofSearchBoundary.DownLeast.downOn_excludes_unfounded
#check @OperatorKO7.Meta.ProofSearchBoundary.DownLeast.MutualCitation.mutual_citation_locally_justified_not_derivable
#print axioms OperatorKO7.Meta.ProofSearchBoundary.DownLeast.MutualCitation.mutual_citation_locally_justified_not_derivable
#check @OperatorKO7.Meta.UniqueNormalization.RuleFamily.conv_iff_finite
#print axioms OperatorKO7.Meta.UniqueNormalization.RuleFamily.conv_iff_finite
#check @OperatorKO7.Meta.UniqueNormalization.RuleFamily.normal_iff_finite
#print axioms OperatorKO7.Meta.UniqueNormalization.RuleFamily.normal_iff_finite
#check @OperatorKO7.Meta.UniqueNormalization.RuleFamily.not_un_iff_finite_witness
#print axioms OperatorKO7.Meta.UniqueNormalization.RuleFamily.not_un_iff_finite_witness
#check @OperatorKO7.Meta.UniqueNormalization.RuleFamily.finite_un_theorem_iff_rule_families
#print axioms OperatorKO7.Meta.UniqueNormalization.RuleFamily.finite_un_theorem_iff_rule_families
#check @OperatorKO7.Meta.UniqueNormalization.KO7Fence.hypothesis_required
#print axioms OperatorKO7.Meta.UniqueNormalization.KO7Fence.hypothesis_required
#check @KO7FenceBridge.step_enc
#print axioms KO7FenceBridge.step_enc
#check @OperatorKO7.Meta.UniqueNormalization.GlobalFailure.not_UNconv_iff_nonempty_globalUNFailure
#print axioms OperatorKO7.Meta.UniqueNormalization.GlobalFailure.not_UNconv_iff_nonempty_globalUNFailure
#check @OperatorKO7.Meta.UniqueNormalization.GlobalFailure.UNconv_iff_no_globalUNFailure
#print axioms OperatorKO7.Meta.UniqueNormalization.GlobalFailure.UNconv_iff_no_globalUNFailure
#check @OperatorKO7.Meta.UniqueNormalization.GlobalFailure.ko7DiagonalFailure
#print axioms OperatorKO7.Meta.UniqueNormalization.GlobalFailure.ko7DiagonalFailure
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.uniqueReachableNormalForms_iff_zeroGainBoundaryEventFree
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.uniqueReachableNormalForms_iff_zeroGainBoundaryEventFree
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.uniqueReachableNormalForms_iff_terminalMultiplicity_le_one
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.uniqueReachableNormalForms_iff_terminalMultiplicity_le_one
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.gapNonpos_of_uniqueConvertibleNormalForms
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.gapNonpos_of_uniqueConvertibleNormalForms
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.boundaryEvent_refutes_uniqueConvertibleNormalForms
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.boundaryEvent_refutes_uniqueConvertibleNormalForms
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.overproductionGap_leaves_uniqueConvertibleNormalForms_undetermined
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.overproductionGap_leaves_uniqueConvertibleNormalForms_undetermined
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.fragment_gapNonpos_of_UNconv
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.fragment_gapNonpos_of_UNconv
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.not_UNconv_of_fragment_boundaryEvent
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.not_UNconv_of_fragment_boundaryEvent
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.UNred_iff_fragmentGapNonpos
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.UNred_iff_fragmentGapNonpos
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.nil_hasFiniteStepClosedFragments
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.nil_hasFiniteStepClosedFragments
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.forkTRS_not_UNconv
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.forkTRS_not_UNconv
#check @OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.bridgeTRS_fragment_gapNonpos_and_not_UNconv
#print axioms OperatorKO7.Meta.BoundaryGeneral.OverproductionGapUniqueNormalForms.bridgeTRS_fragment_gapNonpos_and_not_UNconv
#check @OperatorKO7.Meta.UniqueNormalization.exists_tight_universal_of_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.exists_tight_universal_of_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.Down.trans_of_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.Down.trans_of_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.conv_eq_down_of_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.conv_eq_down_of_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.consistent_of_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.consistent_of_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.consistent_of_constructor_rhs
#print axioms OperatorKO7.Meta.UniqueNormalization.consistent_of_constructor_rhs
#check @OperatorKO7.Meta.UniqueNormalization.PGraph.EqualityComplete.universal_of_exists_universal
#print axioms OperatorKO7.Meta.UniqueNormalization.PGraph.EqualityComplete.universal_of_exists_universal
#check @OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.universal_iff_fiberArgsRepresented
#print axioms OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.universal_iff_fiberArgsRepresented
#check @OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.rootStepsRepresented_iff_no_rootArgumentFailure
#print axioms OperatorKO7.Meta.UniqueNormalization.TermTargetedPGraph.rootStepsRepresented_iff_no_rootArgumentFailure
#check @OperatorKO7.Meta.UniqueNormalization.exists_sameGraph_section7_classification
#print axioms OperatorKO7.Meta.UniqueNormalization.exists_sameGraph_section7_classification
#check @OperatorKO7.Meta.UniqueNormalization.down_transitive_of_finite_complete_targeted_root_models
#print axioms OperatorKO7.Meta.UniqueNormalization.down_transitive_of_finite_complete_targeted_root_models
#check @OperatorKO7.Meta.UniqueNormalization.Section7FiniteTargetedModels
#print axioms OperatorKO7.Meta.UniqueNormalization.Section7FiniteTargetedModels
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_section7FiniteTargetedModels
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_section7FiniteTargetedModels
#check @OperatorKO7.Meta.UniqueNormalization.downOn_threeFold_iff_transitive
#print axioms OperatorKO7.Meta.UniqueNormalization.downOn_threeFold_iff_transitive
#check @OperatorKO7.Meta.UniqueNormalization.ChainClassification.targeted_universal_iff
#print axioms OperatorKO7.Meta.UniqueNormalization.ChainClassification.targeted_universal_iff
#check @OperatorKO7.Meta.UniqueNormalization.SymbolOccurs.here
#print axioms OperatorKO7.Meta.UniqueNormalization.SymbolOccurs.here
#check @OperatorKO7.Meta.UniqueNormalization.SymbolOccurs.of_arg
#print axioms OperatorKO7.Meta.UniqueNormalization.SymbolOccurs.of_arg
#check @OperatorKO7.Meta.UniqueNormalization.wellFounded_extLt
#print axioms OperatorKO7.Meta.UniqueNormalization.wellFounded_extLt
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_extension_consistent
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_extension_consistent
#check @OperatorKO7.Meta.UniqueNormalization.UNred_of_extension_consistent
#print axioms OperatorKO7.Meta.UniqueNormalization.UNred_of_extension_consistent
#check @OperatorKO7.Meta.UniqueNormalization.rhsSymbolsDescend_constructorTranslation_extendedTRS
#print axioms OperatorKO7.Meta.UniqueNormalization.rhsSymbolsDescend_constructorTranslation_extendedTRS
#check @OperatorKO7.Meta.UniqueNormalization.consistent_extSystem_of_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.consistent_extSystem_of_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_translation_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_translation_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.UNred_of_translation_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.UNred_of_translation_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.SymbolsSatisfy.destructorLabel_of_occurs
#print axioms OperatorKO7.Meta.UniqueNormalization.SymbolsSatisfy.destructorLabel_of_occurs
#check @OperatorKO7.Meta.UniqueNormalization.rhsSymbolsDescend_of_rhs_symbols_below_root
#print axioms OperatorKO7.Meta.UniqueNormalization.rhsSymbolsDescend_of_rhs_symbols_below_root
#check @OperatorKO7.Meta.UniqueNormalization.UNconv_of_rhs_symbols_below_root
#print axioms OperatorKO7.Meta.UniqueNormalization.UNconv_of_rhs_symbols_below_root
#check @OperatorKO7.Meta.UniqueNormalization.UNred_of_rhs_symbols_below_root
#print axioms OperatorKO7.Meta.UniqueNormalization.UNred_of_rhs_symbols_below_root
#check @OperatorKO7.Meta.UniqueNormalization.capacityLt_wf
#print axioms OperatorKO7.Meta.UniqueNormalization.capacityLt_wf
#check @OperatorKO7.Meta.UniqueNormalization.capacity_rhs_symbols_below_root
#print axioms OperatorKO7.Meta.UniqueNormalization.capacity_rhs_symbols_below_root
#check @OperatorKO7.Meta.UniqueNormalization.capacity_rhsSymbolsDescend
#print axioms OperatorKO7.Meta.UniqueNormalization.capacity_rhsSymbolsDescend
#check @OperatorKO7.Meta.UniqueNormalization.capacity_rhs_carries_symbol
#print axioms OperatorKO7.Meta.UniqueNormalization.capacity_rhs_carries_symbol
#check @OperatorKO7.Meta.UniqueNormalization.descendingClass_nonvacuous
#print axioms OperatorKO7.Meta.UniqueNormalization.descendingClass_nonvacuous
#check @OperatorKO7.Meta.UniqueNormalization.descendingClass_UNconv
#print axioms OperatorKO7.Meta.UniqueNormalization.descendingClass_UNconv
#check @OperatorKO7.Meta.UniqueNormalization.descendingClass_excludes_ko7
#print axioms OperatorKO7.Meta.UniqueNormalization.descendingClass_excludes_ko7
#check @OperatorKO7.Meta.NormalizationBoundary.DeltaIntegrateLoop.one_way_normalization_well_founded
#print axioms OperatorKO7.Meta.NormalizationBoundary.DeltaIntegrateLoop.one_way_normalization_well_founded
#check @OperatorKO7.Meta.NormalizationBoundary.DeltaIntegrateLoop.two_way_delta_integrate_loops
#print axioms OperatorKO7.Meta.NormalizationBoundary.DeltaIntegrateLoop.two_way_delta_integrate_loops
#check @OperatorKO7.Meta.NormalizationBoundary.AntiNormalizationMap.anti_normalization_no_internal_inverse
#print axioms OperatorKO7.Meta.NormalizationBoundary.AntiNormalizationMap.anti_normalization_no_internal_inverse
#check @OperatorKO7.Meta.NormalizationBoundary.NormalizationLicense.normalization_boundary_is_irreversibility_face
#print axioms OperatorKO7.Meta.NormalizationBoundary.NormalizationLicense.normalization_boundary_is_irreversibility_face
#check @OperatorKO7.Meta.NormalizationBoundary.NormalizationLicense.normalizationObstruction
#print axioms OperatorKO7.Meta.NormalizationBoundary.NormalizationLicense.normalizationObstruction
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.erasedFiberInfinite
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.erasedFiberInfinite
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.erasedHistory_injective
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.erasedHistory_injective
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.no_finite_token_separates_erased_history
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.no_finite_token_separates_erased_history
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.no_finite_type_token_separates_erased_history
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.no_finite_type_token_separates_erased_history
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.exact_erasure_token_carrier_infinite
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.exact_erasure_token_carrier_infinite
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.normalForm_not_constant
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.normalForm_not_constant
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.normalization_redex_is_not_recursor_redex
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.normalization_redex_is_not_recursor_redex
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.normalization_redex_is_not_eqW_diagonal
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.normalization_redex_is_not_eqW_diagonal
#check @OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.integrate_delta_injective
#print axioms OperatorKO7.Meta.NormalizationBoundary.ErasureFiber.integrate_delta_injective
#check @OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.three_faces_share_one_root
#print axioms OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.three_faces_share_one_root
#check @OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.normalization_face_is_not_constant_collapse
#print axioms OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.normalization_face_is_not_constant_collapse
#check @OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.normalization_face_has_unbounded_erasure
#print axioms OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.normalization_face_has_unbounded_erasure
#check @OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.licensedRecover_injective
#print axioms OperatorKO7.Meta.NormalizationBoundary.ThreeFaces.licensedRecover_injective
#check @OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_subset
#print axioms OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_subset
#check @OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_forwardInvariant
#print axioms OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_forwardInvariant
#check @OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_greatest
#print axioms OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_greatest
#check @OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_idempotent
#print axioms OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.box_idempotent
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_subset
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_subset
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_preserves
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_preserves
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_greatest
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_greatest
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.boundaryEdge_removed_by_safeRel
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.boundaryEdge_removed_by_safeRel
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_box_eq
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.safeRel_box_eq
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.box_safeRel_eq
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.box_safeRel_eq
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.state_dynamics_mutual_stabilization
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.state_dynamics_mutual_stabilization
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.dynamicsRepair_greatest_with_fullPredicate
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.dynamicsRepair_greatest_with_fullPredicate
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.predicateRepair_greatest_with_fullDynamics
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.predicateRepair_greatest_with_fullDynamics
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.fixture_endpoint_repairs_incomparable
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.fixture_endpoint_repairs_incomparable
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.fixture_real_stable_repair_frontier
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.fixture_real_stable_repair_frontier
#check @OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.coalescing_is_distinct
#print axioms OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.coalescing_is_distinct
#check @OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.coalescing_not_box
#print axioms OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.coalescing_not_box
#check @OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.stably_distinct_box
#print axioms OperatorKO7.Meta.DistinctionBoundary.PersistentLicense.stably_distinct_box
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.not_box_iff_exists_reachable_failure_classical
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.not_box_iff_exists_reachable_failure_classical
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.not_box_iff_exists_failureObject_classical
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.not_box_iff_exists_failureObject_classical
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.of_explicit_path
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.of_explicit_path
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.crossing_lies_on_path
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.crossing_lies_on_path
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.prefix_is_safe
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.prefix_is_safe
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.crossing_is_boundary
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.FailureObject.crossing_is_boundary
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.confluenceRepair_monotone
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.confluenceRepair_monotone
#check @OperatorKO7.Meta.DistinctionBoundary.WriteClosure.confluenceRepair_idempotent
#print axioms OperatorKO7.Meta.DistinctionBoundary.WriteClosure.confluenceRepair_idempotent
#check @OperatorKO7.Meta.DistinctionBoundary.WriteClosure.confluenceRepair_recDSeed_eq_writeClosure
#print axioms OperatorKO7.Meta.DistinctionBoundary.WriteClosure.confluenceRepair_recDSeed_eq_writeClosure
#check @OperatorKO7.Meta.DistinctionBoundary.WriteClosure.recDSeed_ne_writeClosure
#print axioms OperatorKO7.Meta.DistinctionBoundary.WriteClosure.recDSeed_ne_writeClosure
#check @OperatorKO7.Meta.DistinctionBoundary.WriteClosure.recDSeed_two_histories_same_repair
#print axioms OperatorKO7.Meta.DistinctionBoundary.WriteClosure.recDSeed_two_histories_same_repair
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.same_record_multiple_histories
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.same_record_multiple_histories
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.confluenceRepair_no_global_left_inverse
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.confluenceRepair_no_global_left_inverse
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.freezeAtom_complete
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.freezeAtom_complete
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.freezePolicy_semantic_complete
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.freezePolicy_semantic_complete
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.freezePolicy_writeClose_closed
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.freezePolicy_writeClose_closed
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.freezePolicy_repair_confluent
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.freezePolicy_repair_confluent
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.repairedRecDPolicy_confluent
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.repairedRecDPolicy_confluent
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.interpretGuard_equalityStatusInvariant
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.interpretGuard_equalityStatusInvariant
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.leftVoidGuard_not_equalityStatusInvariant
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.leftVoidGuard_not_equalityStatusInvariant
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.guardGrammar_not_semantically_complete
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.guardGrammar_not_semantically_complete
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.authorized_safeRel
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.authorized_safeRel
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.authorized_target
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.authorized_target
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.refused_boundary
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.refused_boundary
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.replay_refusal
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.replay_refusal
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.boundary_no_authorization
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ProofCarryingLicense.boundary_no_authorization
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.same_input_dependency_fixture
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.same_input_dependency_fixture
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.emptyRecoveryPolicy_confluent
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.emptyRecoveryPolicy_confluent
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.rawRecoveryPolicy_not_confluent
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.rawRecoveryPolicy_not_confluent
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneFailureObject
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneFailureObject
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneFailedGrammar_exact
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneFailedGrammar_exact
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneRepairedPolicy_eq_canonical
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneRepairedPolicy_eq_canonical
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneRepairedPolicy_confluent
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneRepairedPolicy_confluent
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_admitted_path_sound
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_admitted_path_sound
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_refused_path_sound
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_refused_path_sound
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneRawRequest_not_authorizable
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstoneRawRequest_not_authorizable
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_recovery_forward_separation
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_recovery_forward_separation
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_many_to_one_recovery_boundary
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.capstone_many_to_one_recovery_boundary
#check @OperatorKO7.Meta.DistinctionBoundary.DynamicDiagonalGradeTransport.d1p_reflect_of_stepSimulation
#print axioms OperatorKO7.Meta.DistinctionBoundary.DynamicDiagonalGradeTransport.d1p_reflect_of_stepSimulation
#check @OperatorKO7.Meta.DistinctionBoundary.DynamicDiagonalGradeTransport.d1p_transport_of_stepLifting
#print axioms OperatorKO7.Meta.DistinctionBoundary.DynamicDiagonalGradeTransport.d1p_transport_of_stepLifting
#check @OperatorKO7.Meta.DistinctionBoundary.DynamicDiagonalGradeTransport.d2At_transport_codeDenotation
#print axioms OperatorKO7.Meta.DistinctionBoundary.DynamicDiagonalGradeTransport.d2At_transport_codeDenotation
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.d1p_not_transport_of_simulation_alone
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.d1p_not_transport_of_simulation_alone
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.d2_not_reflect_of_lifting_alone
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.d2_not_reflect_of_lifting_alone
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.productStep_star_iff
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.productStep_star_iff
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.box_product_iff
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.box_product_iff
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.licensedPairSubrelation_box_iff_d1p
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.licensedPairSubrelation_box_iff_d1p
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.roleErasure_quotient_no_discriminator
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingProductQuotient.roleErasure_quotient_no_discriminator
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingCompletionRule.box_reflTransGen_iff
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingCompletionRule.box_reflTransGen_iff
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingCompletionRule.d1p_reflTransGen_iff
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingCompletionRule.d1p_reflTransGen_iff
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingCompletionRule.d2At_reflTransGen_iff
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingCompletionRule.d2At_reflTransGen_iff
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channelExpiry
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channelExpiry
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_issue_exogenous
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_issue_exogenous
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_consume_echo
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_consume_echo
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_consume_not_exogenous
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_consume_not_exogenous
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channelExpiry_issue_license_expires
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channelExpiry_issue_license_expires
#check @OperatorKO7.Meta.BoundaryGeneral.PersistentExogeny.license_expiry_iff_reachable_echo
#print axioms OperatorKO7.Meta.BoundaryGeneral.PersistentExogeny.license_expiry_iff_reachable_echo
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.no_hom_channel_eqW
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.no_hom_channel_eqW
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.no_hom_channel_quote
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.no_hom_channel_quote
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.homChannelRole
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.homChannelRole
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.hom_channel_role_nonempty
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.hom_channel_role_nonempty
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.four_live_expiry_witnesses
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.four_live_expiry_witnesses
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_expiry_is_fourth_object
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.ChannelExpiry.channel_expiry_is_fourth_object
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.comp_drop_mechanized
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.comp_drop_mechanized
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.code_pair_equality_computable
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.code_pair_equality_computable
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.comp_behaviour_comparison_not_computable
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.comp_behaviour_comparison_not_computable
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.comp_extensional_computable_predicate_trivial
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.comp_extensional_computable_predicate_trivial
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.zero_mem_zeroBehavior
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.zero_mem_zeroBehavior
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.succ_not_mem_zeroBehavior
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalCompDrop.succ_not_mem_zeroBehavior
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quote_eval_nonjoinable_peak
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quote_eval_nonjoinable_peak
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.eqW_kernel_freeze_does_not_remove_quote_peak
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.eqW_kernel_freeze_does_not_remove_quote_peak
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quote_congruence_freeze_kills_underQuote_arm
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quote_congruence_freeze_kills_underQuote_arm
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.least_freeze_includes_quote_congruence
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.least_freeze_includes_quote_congruence
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalLevels.SelfEvaluationDiagonal
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalLevels.SelfEvaluationDiagonal
#check @OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.selfApplication
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.selfApplication
#check @OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.Represents
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.Represents
#check @OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.represented_composite_has_fixed_point
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.represented_composite_has_fixed_point
#check @OperatorKO7.Meta.DistinctionBoundary.Godel.fixed_point_from_represented_diagonal
#print axioms OperatorKO7.Meta.DistinctionBoundary.Godel.fixed_point_from_represented_diagonal
#check @OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.not_represents_composite_of_fixed_point_free
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.not_represents_composite_of_fixed_point_free
#check @OperatorKO7.Meta.DistinctionBoundary.Godel.fixed_point_free_not_represented
#print axioms OperatorKO7.Meta.DistinctionBoundary.Godel.fixed_point_free_not_represented
#check @OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.not_represents_delta_composite
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.not_represents_delta_composite
#check @OperatorKO7.Meta.DistinctionBoundary.Godel.successor_obstruction
#print axioms OperatorKO7.Meta.DistinctionBoundary.Godel.successor_obstruction
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalLevels.delta_ne_self
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalLevels.delta_ne_self
#check @OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.ClosedUnderLeftDelta
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.ClosedUnderLeftDelta
#check @OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.self_exclusion_of_class
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelFixedPoint.self_exclusion_of_class
#check @OperatorKO7.Meta.DistinctionBoundary.Godel.self_exclusion
#print axioms OperatorKO7.Meta.DistinctionBoundary.Godel.self_exclusion
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.Ingredients
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.Ingredients
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.Obstruction
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.Obstruction
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.Escape
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.Escape
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.escape_iff_not_obstruction
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.escape_iff_not_obstruction
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.escape_sound
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.escape_sound
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.escape_complete
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.escape_complete
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.fuelled_eval_not_total
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.fuelled_eval_not_total
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.unitValued_retraction_impossible
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.unitValued_retraction_impossible
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.schematic_omits_delta_selfap
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.schematic_omits_delta_selfap
#check @OperatorKO7.Meta.DistinctionBoundary.GodelEscape.ko7_not_obstructed
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelEscape.ko7_not_obstructed
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.Bd
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.Bd
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.BdCarrier
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.BdCarrier
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.bd_greatest_forwardInvariant
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.bd_greatest_forwardInvariant
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.bd_transport_of_lifting
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.bd_transport_of_lifting
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.bd_reflect_of_simulation
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.bd_reflect_of_simulation
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.boundaryObject_functorial_on_lifting_morphisms
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.boundaryObject_functorial_on_lifting_morphisms
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.four_fibers_are_instances
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.four_fibers_are_instances
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.ko7_bd_iff_d1p
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.ko7_bd_iff_d1p
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.compactUniformSeparation_iff_forall_bd
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.compactUniformSeparation_iff_forall_bd
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.role_bd_empty
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.role_bd_empty
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.dp_bd_empty_but_issue_licensed
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryObjectFunctor.dp_bd_empty_but_issue_licensed
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.MetricDynamicLicense.metricPersistentLicense_iff_compactUniformSeparation
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.MetricDynamicLicense.metricPersistentLicense_iff_compactUniformSeparation
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.MetricDynamicLicense.guardExpiry_pointwise_nonzero_but_unlicensed
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.MetricDynamicLicense.guardExpiry_pointwise_nonzero_but_unlicensed
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.MetricDynamicLicense.metricPersistentLicense_reciprocal_transport
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.MetricDynamicLicense.metricPersistentLicense_reciprocal_transport
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.ForwardStepSimulation
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.ForwardStepSimulation
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.StepReflection
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.StepReflection
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.StepLifting
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.StepLifting
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.ARSIsomorphism
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.ARSIsomorphism
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.TransportProperty
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.TransportProperty
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.Statement
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.Statement
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.forwardStep_strictly_implies_forwardReach
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.forwardStep_strictly_implies_forwardReach
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_forwardStep
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_forwardStep
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_stepLifting
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_stepLifting
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_reachReflection
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_reachReflection
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_reductionEquivalence
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_reductionEquivalence
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_terminalExactness
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.TransportStrength.arsIsomorphism_terminalExactness
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.forwardStep_stepReflection_antichain
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.forwardStep_stepReflection_antichain
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.Ceiling
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.Ceiling
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.identityTransportCeiling
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.identityTransportCeiling
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.PromotionFailure
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.PromotionFailure
#check @OperatorKO7.Meta.BoundaryOperator.TransportCeiling.collapsePromotionFailure
#print axioms OperatorKO7.Meta.BoundaryOperator.TransportCeiling.collapsePromotionFailure
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.SemanticRepairProfile
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.SemanticRepairProfile
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.ParetoLE
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.ParetoLE
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.paretoLE_preorder
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.paretoLE_preorder
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.pareto_incomparable_witness
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.pareto_incomparable_witness
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.box_maximal_predicate_repair
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.box_maximal_predicate_repair
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.confluenceRepair_minimal_write_closed
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.SemanticRepairOrder.confluenceRepair_minimal_write_closed
#check @OperatorKO7.Meta.DistinctionBoundary.WriteClosure.confluenceRepair_least
#print axioms OperatorKO7.Meta.DistinctionBoundary.WriteClosure.confluenceRepair_least

-- Round 3 (2026-09-17): arithmetical carrier, partial interpreter, rank,
-- four separations, boundary determination, transport request, graded gap
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.selfEvaluation_without_faithfulDiagonalSyntax
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.selfEvaluation_without_faithfulDiagonalSyntax
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.universalEvaluation_without_selfEvaluationCarrier
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.universalEvaluation_without_selfEvaluationCarrier
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.representationClosure_without_universalEvaluation
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.representationClosure_without_universalEvaluation
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.booleanComparison_without_representationClosure
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeReverseSeparations.booleanComparison_without_representationClosure
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.left_compose_any_has_extensional_fp
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.left_compose_any_has_extensional_fp
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.not_universal_on_proj_succ
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.not_universal_on_proj_succ
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.no_universal_interpreter
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.no_universal_interpreter
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.numbering_not_acceptable
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.numbering_not_acceptable
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.freezeSuccOp_not_effective
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.freezeSuccOp_not_effective
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.freeze_succ_operator_has_no_extensional_fp
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.freeze_succ_operator_has_no_extensional_fp
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.live_succ_has_fp_freeze_succ_does_not
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.live_succ_has_fp_freeze_succ_does_not
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.encodeAcc_injective
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.encodeAcc_injective
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.decodeAcc?_encode
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.decodeAcc?_encode
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.smnAcc_spec
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.smnAcc_spec
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.apply_interprets_partialCode
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.apply_interprets_partialCode
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.accCode_acceptable
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.accCode_acceptable
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.apply_not_universalAcc
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.apply_not_universalAcc
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.accCodeSelfNumberingRoute_impossible
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.accCodeSelfNumberingRoute_impossible
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.licensed_implies_budgetDrop
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.licensed_implies_budgetDrop
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.every_licensed_edge_decreases_rank
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.every_licensed_edge_decreases_rank
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quoteJustif_identity_blocked
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quoteJustif_identity_blocked
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quoteJustif_cycle_impossible
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quoteJustif_cycle_impossible
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quotation_mediated_cycle_impossible
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quotation_mediated_cycle_impossible
#check @OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quote_justif_wf
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelPartial.quote_justif_wf
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.check_sound
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.check_sound
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.provable_sound
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.provable_sound
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.provable_sound_in
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.provable_sound_in
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.q_consistent
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.q_consistent
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.q_omega_consistent
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.q_omega_consistent
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.bewOf_representsChecker
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.bewOf_representsChecker
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.eval_arithGodelSentence_iff_not_provable
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.eval_arithGodelSentence_iff_not_provable
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.arithGodelFixedPointSemantics_holds
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.arithGodelFixedPointSemantics_holds
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.godel_first_incompleteness_Q_unconditional
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.godel_first_incompleteness_Q_unconditional
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.modelInf_qAxioms
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.modelInf_qAxioms
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.modelInf_bew_falsum
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.modelInf_bew_falsum
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.modelInf_not_conQ
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.modelInf_not_conQ
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.godel_second_incompleteness_Q_unconditional
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.godel_second_incompleteness_Q_unconditional
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.not_provable_not_conQ_unconditional
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.not_provable_not_conQ_unconditional
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.conQ_independent
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.conQ_independent
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.provableI_sound
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.provableI_sound
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.induction_checker_consistent
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.induction_checker_consistent
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.compiledIDerives_iff_provableI
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.compiledIDerives_iff_provableI
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.checkI_weak_sound
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.checkI_weak_sound
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigmaOneCounterexample_isSigma1
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigmaOneCounterexample_isSigma1
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigmaOneCounterexample_true
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigmaOneCounterexample_true
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigmaOneCounterexample_not_provableI
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigmaOneCounterexample_not_provableI
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigma1_complete_impossible
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.sigma1_complete_impossible
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.internal_sigma1_route_impossible
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.internal_sigma1_route_impossible
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.hbl_routeI_impossible
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.hbl_routeI_impossible
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.godelII_routes_terminal
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.godelII_routes_terminal
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.uncpair_primrec
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.uncpair_primrec
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.substFormCode_primrec
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.substFormCode_primrec
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.substFormAtCode_primrec
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.substFormAtCode_primrec
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.checkProofCode_primrec
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.checkProofCode_primrec
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.isProofCodeB_primrec
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.isProofCodeB_primrec
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.isProofCodeB_encode_iff
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.isProofCodeB_encode_iff
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.acceptable_numbering_precondition
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.acceptable_numbering_precondition
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.proofRelCheckB_encode_iff_betaRel
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.proofRelCheckB_encode_iff_betaRel
#check @OperatorKO7.Meta.DistinctionBoundary.GodelArith.primitiveRecursiveBetaClosure
#print axioms OperatorKO7.Meta.DistinctionBoundary.GodelArith.primitiveRecursiveBetaClosure
#check @OperatorKO7.Meta.ProofSearchBoundary.first_unsupportedPromotion_boundary
#print axioms OperatorKO7.Meta.ProofSearchBoundary.first_unsupportedPromotion_boundary
#check @OperatorKO7.Meta.ProofSearchBoundary.reachable_unsupportedPromotion_not_persistentLicensed
#print axioms OperatorKO7.Meta.ProofSearchBoundary.reachable_unsupportedPromotion_not_persistentLicensed
#check @OperatorKO7.Meta.ProofSearchBoundary.unsupportedPromotion_iff_not_licensed
#print axioms OperatorKO7.Meta.ProofSearchBoundary.unsupportedPromotion_iff_not_licensed
#check @OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.GateResult
#print axioms OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.GateResult
#check @OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.requestSimulation
#print axioms OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.requestSimulation
#check @OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.requestIsoRejected
#print axioms OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.requestIsoRejected
#check @OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.iso_realizes_requested_map
#print axioms OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.iso_realizes_requested_map
#check @OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.simulation_success_ne_rejection
#print axioms OperatorKO7.Meta.DistinctionBoundary.TransportStrengthGate.simulation_success_ne_rejection
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.BoundaryIso
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.BoundaryIso
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.BoundaryIso.reflTransGen_iff
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.BoundaryIso.reflTransGen_iff
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.boundaryIso_equiv_observableClass
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.boundaryIso_equiv_observableClass
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.ensembleLaw
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.ensembleLaw
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.strong_determination_transport
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.strong_determination_transport
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.releaseData_ensembleLaw_ne
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.releaseData_ensembleLaw_ne
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.strong_determination_kill_under_uncoupled_iso
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.strong_determination_kill_under_uncoupled_iso
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.boundary_determination_resolved
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.BoundaryDetermination.boundary_determination_resolved
#check @OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingDatumCategory.licensingDatum_category_laws
#print axioms OperatorKO7.Meta.LicensedBoundaryCalculus.LicensingDatumCategory.licensingDatum_category_laws
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.grade_obstruction_trivial_iff_realized
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.grade_obstruction_trivial_iff_realized
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.dyn_transport_table
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.dyn_transport_table
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.adjacent_reverse_separations_complete
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.adjacent_reverse_separations_complete
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.declaredComputationRules
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.declaredComputationRules
#check @OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.stratification_theorem_at_declared_tags
#print axioms OperatorKO7.Meta.DistinctionBoundary.DiagonalGradeStratification.stratification_theorem_at_declared_tags
#check @OperatorKO7.Meta.BoundaryGeneral.GradedOmega.fork3D0Echo_omega_eq_one
#print axioms OperatorKO7.Meta.BoundaryGeneral.GradedOmega.fork3D0Echo_omega_eq_one
#check @OperatorKO7.Meta.BoundaryGeneral.GradedOmega.fork3D0Resolving_omega_eq_zero
#print axioms OperatorKO7.Meta.BoundaryGeneral.GradedOmega.fork3D0Resolving_omega_eq_zero
#check @OperatorKO7.Meta.BoundaryGeneral.GradedOmega.grade_tag_does_not_determine_omega
#print axioms OperatorKO7.Meta.BoundaryGeneral.GradedOmega.grade_tag_does_not_determine_omega
#check @OperatorKO7.Meta.BoundaryGeneral.GradedOmega.no_grade_only_omega_scalar
#print axioms OperatorKO7.Meta.BoundaryGeneral.GradedOmega.no_grade_only_omega_scalar
