import OperatorKO7.Meta.Rewriting.Term
import OperatorKO7.Meta.Rewriting.Subst
import Mathlib.Logic.Relation

/-!
# The rewrite relation and confluence vocabulary

Roadmap source: `ROADMAP-01-generic-critical-pair-lemma.md`, sections 4 and 5
(`Meta/Rewriting/Rewrite.lean`). This is Wave 2C of the rewriting foundation: the
one-step rewrite relation generated by a term rewriting system, its
reflexive-transitive closure, and the joinability and local-confluence
predicates that the Critical Pair Lemma is stated against.

The SHAPE mirrors the proven `Rstep`/`Rstar` blueprint at
`Meta/EstimatedDPGraphTcap.lean:103,111`: a `root` constructor injecting a
root rule-instance contraction, and an `arg` constructor rewriting inside one
argument position via the `pre ++ a :: post` split. Here the relation is built
over the generic `Term sigma nu` of Wave 1 and uses the Wave-1 substitution
`Subst.apply`. The closure is `Relation.ReflTransGen`, so the downstream Newman
engine and the Critical Pair Lemma can use its full Mathlib API directly.

Trust: kernel-only; baseline-only under `#print axioms` (subset of
`{propext, Classical.choice, Quot.sound}`). Any `Classical.choice`/`propext`
dependence that appears is from `Finset`/`DecidableEq` plumbing inherited
through `Term`/`Subst`.
-/

set_option autoImplicit false

namespace OperatorKO7.Meta.Rewriting

open scoped Subst

universe u v

/-- A first-order rewrite rule: a left-hand side, a right-hand side, and the
standard well-formedness requirement that the left-hand side is an application
(a rewrite rule never has a bare variable as its left-hand side). -/
structure Rule (sigma : Type u) (nu : Type v) where
  /-- The left-hand side of the rule. -/
  lhs : Term sigma nu
  /-- The right-hand side of the rule. -/
  rhs : Term sigma nu
  /-- The left-hand side is an application. -/
  lhs_isApp : lhs.isApp = true

/-- A term rewriting system is a list of rules. -/
abbrev TRS (sigma : Type u) (nu : Type v) := List (Rule sigma nu)

variable {sigma : Type u} {nu : Type v}

/-- A root contraction: `s` is a substitution instance of some rule's left-hand
side and `t` is the same instance of that rule's right-hand side. This is the
rewrite step taken at the very top of the term, with no surrounding context. -/
def rootStep (R : TRS sigma nu) (s t : Term sigma nu) : Prop :=
  ∃ rule ∈ R, ∃ σ : Subst sigma nu, s = σ • rule.lhs ∧ t = σ • rule.rhs

/-- The one-step rewrite relation generated by `R`: the context closure of
`rootStep`. The `root` constructor contracts a rule instance at the top; the
`arg` constructor rewrites inside exactly one argument position, mirroring the
proven `Rstep.arg` congruence via the `pre ++ a :: post` split. -/
inductive Step (R : TRS sigma nu) : Term sigma nu → Term sigma nu → Prop
  | root {s t : Term sigma nu} (h : rootStep R s t) : Step R s t
  | arg (f : sigma) (pre post : List (Term sigma nu)) {a b : Term sigma nu} :
      Step R a b →
      Step R (.app f (pre ++ a :: post)) (.app f (pre ++ b :: post))

/-- The reflexive-transitive closure of the one-step rewrite relation. A term
`s` rewrites to `t` in zero or more steps exactly when `StepStar R s t`. -/
def StepStar (R : TRS sigma nu) : Term sigma nu → Term sigma nu → Prop :=
  Relation.ReflTransGen (Step R)

/-- Two terms are joinable when they both rewrite, in zero or more steps, to a
common term. -/
def joinable (R : TRS sigma nu) (s t : Term sigma nu) : Prop :=
  ∃ u, StepStar R s u ∧ StepStar R t u

/-- Local confluence: every one-step peak `t1 ← s → t2` is joinable. The Critical
Pair Lemma characterizes exactly this predicate. -/
def localConfluent (R : TRS sigma nu) : Prop :=
  ∀ s t1 t2, Step R s t1 → Step R s t2 → joinable R t1 t2

/-! ## A single root rewrite is a `rootStep` -/

/-- Packaging a rule, a matching substitution, and its instances into a
`rootStep` witness. -/
theorem rootStep_intro (R : TRS sigma nu) {rule : Rule sigma nu} (hrule : rule ∈ R)
    (σ : Subst sigma nu) : rootStep R (σ • rule.lhs) (σ • rule.rhs) :=
  ⟨rule, hrule, σ, rfl, rfl⟩

/-- A root contraction of a rule instance is a one-step rewrite. -/
theorem Step.rootStep_step (R : TRS sigma nu) {rule : Rule sigma nu} (hrule : rule ∈ R)
    (σ : Subst sigma nu) : Step R (σ • rule.lhs) (σ • rule.rhs) :=
  Step.root (rootStep_intro R hrule σ)

/-! ## Structural lemmas on the closure -/

/-- The reflexive-transitive closure is reflexive. -/
theorem StepStar.refl (R : TRS sigma nu) (t : Term sigma nu) : StepStar R t t :=
  Relation.ReflTransGen.refl

/-- A single rewrite step embeds into the reflexive-transitive closure. -/
theorem StepStar.single {R : TRS sigma nu} {s t : Term sigma nu} (h : Step R s t) :
    StepStar R s t :=
  Relation.ReflTransGen.single h

/-- The reflexive-transitive closure is transitive: rewrite sequences compose. -/
theorem StepStar.trans {R : TRS sigma nu} {s t u : Term sigma nu}
    (hst : StepStar R s t) (htu : StepStar R t u) : StepStar R s u :=
  Relation.ReflTransGen.trans hst htu

/-- Extend a rewrite sequence by one trailing step. -/
theorem StepStar.tail {R : TRS sigma nu} {s t u : Term sigma nu}
    (hst : StepStar R s t) (htu : Step R t u) : StepStar R s u :=
  Relation.ReflTransGen.tail hst htu

/-- Extend a rewrite sequence by one leading step. -/
theorem StepStar.head {R : TRS sigma nu} {s t u : Term sigma nu}
    (hst : Step R s t) (htu : StepStar R t u) : StepStar R s u :=
  Relation.ReflTransGen.head hst htu

/-! ## Joinability -/

/-- Every term is joinable with itself. -/
theorem joinable.refl (R : TRS sigma nu) (t : Term sigma nu) : joinable R t t :=
  ⟨t, StepStar.refl R t, StepStar.refl R t⟩

/-- Joinability is symmetric. -/
theorem joinable.symm {R : TRS sigma nu} {s t : Term sigma nu} (h : joinable R s t) :
    joinable R t s :=
  let ⟨u, hsu, htu⟩ := h
  ⟨u, htu, hsu⟩

/-- Two terms related by the closure are joinable (the common reduct is the
target). -/
theorem joinable.of_stepStar {R : TRS sigma nu} {s t : Term sigma nu}
    (h : StepStar R s t) : joinable R s t :=
  ⟨t, h, StepStar.refl R t⟩

/-! ## Congruence through one argument position -/

/-- A single rewrite step lifts through a one-position argument context: if
`a` rewrites to `b`, then `app f (pre ++ a :: post)` rewrites to
`app f (pre ++ b :: post)`. This repackages the `arg` constructor as a plain
implication for downstream use. -/
theorem Step.arg_congr (R : TRS sigma nu) (f : sigma) (pre post : List (Term sigma nu))
    {a b : Term sigma nu} (h : Step R a b) :
    Step R (.app f (pre ++ a :: post)) (.app f (pre ++ b :: post)) :=
  Step.arg f pre post h

/-- Congruence of the closure through one argument position: a rewrite sequence
`StepStar R a b` lifts to a rewrite sequence on the surrounding application
`app f (pre ++ · :: post)`. This is what lets joinability and reachability climb
out of a subterm to the whole term, used pervasively in the critical-pair
analysis. -/
theorem StepStar.arg_congr (R : TRS sigma nu) (f : sigma) (pre post : List (Term sigma nu))
    {a b : Term sigma nu} (h : StepStar R a b) :
    StepStar R (.app f (pre ++ a :: post)) (.app f (pre ++ b :: post)) :=
  Relation.ReflTransGen.lift (fun a => Term.app f (pre ++ a :: post))
    (fun _ _ hstep => Step.arg f pre post hstep) h

/-- Joinability lifts through one argument position: if `a` and `b` are joinable
then the surrounding applications are joinable. The common reduct is the
application carrying the common reduct of `a` and `b`. -/
theorem joinable.arg_congr (R : TRS sigma nu) (f : sigma) (pre post : List (Term sigma nu))
    {a b : Term sigma nu} (h : joinable R a b) :
    joinable R (.app f (pre ++ a :: post)) (.app f (pre ++ b :: post)) :=
  let ⟨u, hau, hbu⟩ := h
  ⟨.app f (pre ++ u :: post),
    StepStar.arg_congr R f pre post hau, StepStar.arg_congr R f pre post hbu⟩

/-! ## Non-vacuity

A concrete one-rule system over `Nat`-symbols and `Nat`-variables, with a real
`rootStep` witness, a one-step `Step`, and a `joinable` instance, so the relation
is inhabited rather than vacuously definable. The rule `f(x) -> g(x)` rewrites
`f(c)` to `g(c)` at the root. -/

namespace Example

/-- The left-hand side `f(x)` of the demonstration rule, with `f` the symbol `0`
and `x` the variable `0`. -/
def lhsTerm : Term Nat Nat := .app 0 [.var 0]

/-- The right-hand side `g(x)` of the demonstration rule, with `g` the symbol
`1`. -/
def rhsTerm : Term Nat Nat := .app 1 [.var 0]

/-- The demonstration rule `f(x) -> g(x)`; its left-hand side is an application. -/
def demoRule : Rule Nat Nat where
  lhs := lhsTerm
  rhs := rhsTerm
  lhs_isApp := rfl

/-- A one-rule term rewriting system. -/
def demoTRS : TRS Nat Nat := [demoRule]

/-- The substitution sending the rule variable `0` to the constant `c = app 2 []`
and fixing everything else. -/
def demoSubst : Subst Nat Nat := fun x => if x = 0 then .app 2 [] else .var x

/-- The instantiated left-hand side `f(c)`. -/
def srcTerm : Term Nat Nat := .app 0 [.app 2 []]

/-- The instantiated right-hand side `g(c)`. -/
def tgtTerm : Term Nat Nat := .app 1 [.app 2 []]

/-- The source term is the substitution instance of the rule's left-hand side. -/
theorem apply_lhs : demoSubst • demoRule.lhs = srcTerm := rfl

/-- The target term is the substitution instance of the rule's right-hand side. -/
theorem apply_rhs : demoSubst • demoRule.rhs = tgtTerm := rfl

/-- A concrete `rootStep`: `f(c)` contracts to `g(c)` at the root. -/
theorem demo_rootStep : rootStep demoTRS srcTerm tgtTerm :=
  ⟨demoRule, List.mem_singleton.2 rfl, demoSubst, rfl, rfl⟩

/-- A concrete one-step rewrite `f(c) -> g(c)`. -/
theorem demo_step : Step demoTRS srcTerm tgtTerm :=
  Step.root demo_rootStep

/-- A concrete `StepStar` rewrite sequence `f(c) ->* g(c)`. -/
theorem demo_stepStar : StepStar demoTRS srcTerm tgtTerm :=
  StepStar.single demo_step

/-- A concrete joinability instance: `f(c)` and `g(c)` join at `g(c)`. -/
theorem demo_joinable : joinable demoTRS srcTerm tgtTerm :=
  joinable.of_stepStar demo_stepStar

/-- A concrete contextual one-step rewrite: the redex `f(c)` rewrites inside the
argument position of `h(f(c))`, giving `h(f(c)) -> h(g(c))`. This exercises the
`arg` constructor on a genuine context. -/
theorem demo_step_in_context :
    Step demoTRS (.app 3 [srcTerm]) (.app 3 [tgtTerm]) :=
  Step.arg 3 [] [] demo_step

end Example

end OperatorKO7.Meta.Rewriting

/-! ## Axiom audit -/

#check @OperatorKO7.Meta.Rewriting.Rule
#check @OperatorKO7.Meta.Rewriting.TRS
#check @OperatorKO7.Meta.Rewriting.rootStep
#check @OperatorKO7.Meta.Rewriting.Step
#check @OperatorKO7.Meta.Rewriting.StepStar
#check @OperatorKO7.Meta.Rewriting.joinable
#check @OperatorKO7.Meta.Rewriting.localConfluent
#check @OperatorKO7.Meta.Rewriting.StepStar.refl
#check @OperatorKO7.Meta.Rewriting.StepStar.single
#check @OperatorKO7.Meta.Rewriting.joinable.refl
#check @OperatorKO7.Meta.Rewriting.StepStar.arg_congr
#check @OperatorKO7.Meta.Rewriting.joinable.arg_congr

#print axioms OperatorKO7.Meta.Rewriting.Step
#print axioms OperatorKO7.Meta.Rewriting.localConfluent
#print axioms OperatorKO7.Meta.Rewriting.StepStar.arg_congr
#print axioms OperatorKO7.Meta.Rewriting.joinable.arg_congr
#print axioms OperatorKO7.Meta.Rewriting.Example.demo_rootStep
#print axioms OperatorKO7.Meta.Rewriting.Example.demo_step
#print axioms OperatorKO7.Meta.Rewriting.Example.demo_joinable
#print axioms OperatorKO7.Meta.Rewriting.Example.demo_step_in_context
