import OperatorKO7.Meta.ConfessionMethod
import OperatorKO7.Meta.ConfessionMethod_DP

/-!
# Confession Method Instance: Direct Counter-Projection (Subterm Criterion)

## Formal Scope

The formal result packages rank equality and route-profile evidence for the counter projection. A license is a tag, and a general termination conclusion is outside this surface.
-/

namespace OperatorKO7.ConfessionMethodFamily

open OperatorKO7.Trace
open OperatorKO7.StepDuplicating
open OperatorKO7.StepDuplicating.StepDuplicatingSchema
open OperatorKO7.CompositionalImpossibility

/-- Minimal syntactic subterm relation for the direct counter-projection route.
    We only need enough structure to express that the counter argument is a
    strict syntactic subterm of `delta n`. -/
inductive DirectSubterm : Trace → Trace → Prop
  | delta_arg (n : Trace) : DirectSubterm n (delta n)

/-- Transitive subterm relation generated by `delta`, `app`, and `recΔ`, the
constructors used by the recursive fragment considered here. -/
inductive OriginalSymbolSubterm : Trace → Trace → Prop
  | delta_arg (n : Trace) : OriginalSymbolSubterm n (delta n)
  | app_left (x y : Trace) : OriginalSymbolSubterm x (app x y)
  | app_right (x y : Trace) : OriginalSymbolSubterm y (app x y)
  | recur_base (b s n : Trace) : OriginalSymbolSubterm b (recΔ b s n)
  | recur_step (b s n : Trace) : OriginalSymbolSubterm s (recΔ b s n)
  | recur_counter (b s n : Trace) : OriginalSymbolSubterm n (recΔ b s n)
  | trans {x y z : Trace} :
      OriginalSymbolSubterm x y →
      OriginalSymbolSubterm y z →
      OriginalSymbolSubterm x z

/-- The direct counter-step witness `n ▷ delta n` is also a witness in the
    richer original-symbol subterm relation. -/
theorem directSubterm_to_originalSymbolSubterm {x y : Trace}
    (h : DirectSubterm x y) : OriginalSymbolSubterm x y := by
  cases h with
  | delta_arg => exact OriginalSymbolSubterm.delta_arg x

/-- Witness selecting the third, counter argument of `recΔ`. The structure
asserts the selected position; it does not classify every possible descent
coordinate or prove a termination criterion. -/
structure DirectCounterProjectionWitness where
  selectedCoordinate : Fin 3
  selectedCoordinate_is_counter : selectedCoordinate = ⟨2, by decide⟩

/-- The schema's direct counter-projection witness: select the third argument
    of the recursive call. -/
def schemaDirectCounterProjectionWitness : DirectCounterProjectionWitness where
  selectedCoordinate := ⟨2, by decide⟩
  selectedCoordinate_is_counter := rfl

/-- Route-local projection rank that follows successor depth through the
recursive counter and assigns rank zero to wrappers. -/
@[simp] def counterProjectionRankFn : Trace → Nat
  | void        => 0
  | delta t     => counterProjectionRankFn t + 1
  | integrate _ => 0
  | merge _ _   => 0
  | app _ _     => 0
  | recΔ _ _ n  => counterProjectionRankFn n
  | eqW _ _     => 0

/-- The route-local projection rank is extensionally equal to the DP projection
rank. -/
theorem counterProjectionRankFn_eq_dpProjection :
    counterProjectionRankFn = dpProjection := by
  funext t
  induction t <;> simp [counterProjectionRankFn, dpProjection, *]

/-- The direct counter-projection witness packaged as the intermediate
    confession-core witness. -/
def DirectCounterProjectionWitness.toConfessionCoreWitness
    (_W : DirectCounterProjectionWitness) : ConfessionCoreWitness ko7Schema where
  rank := counterProjectionRankFn
  rank_base := by rfl
  rank_succ := by intro t; rfl
  rank_wrap := by intro x y; rfl
  rank_recur := by intro b s n; rfl

/-- Package `counterProjectionRankFn` as a `ProjectionRank`. The witness is
recorded separately by the route-evidence structure below. -/
def counterProjectionDerivedRank : ProjectionRank ko7Schema where
  rank := counterProjectionRankFn
  rank_base := by rfl
  rank_succ := by intro t; rfl
  rank_wrap := by intro x y; rfl
  rank_recur := by intro b s n; rfl

/-- The packaged counter-projection rank has the same rank function as the DP
projection core. -/
theorem counterProjectionDerivedRank_eq_dp_core :
    counterProjectionDerivedRank.rank = dpProjectionRank.rank := by
  simpa [counterProjectionDerivedRank, dpProjectionRank] using
    counterProjectionRankFn_eq_dpProjection

/-- The two packaged `ProjectionRank` objects are equal by extensionality of
their rank functions. -/
theorem counterProjectionDerivedRank_eq_dpProjectionRank :
    counterProjectionDerivedRank = dpProjectionRank := by
  ext t
  simpa [counterProjectionDerivedRank, dpProjectionRank] using
    congrFun counterProjectionRankFn_eq_dpProjection t

/-- The direct counter-projection witness forgets the wrapper payload at the
    level of the intermediate confession core. -/
theorem directCounterProjectionWitness_forgets_wrapper_payload :
    ∀ x y : Trace,
      schemaDirectCounterProjectionWitness.toConfessionCoreWitness.rank (app x y) = 0 := by
  intro x y
  rfl

/-- The direct counter-projection witness induces the same confession core as
    the canonical DP route. -/
theorem directCounterProjectionWitness_toConfessionCoreWitness_eq_core :
    schemaDirectCounterProjectionWitness.toConfessionCoreWitness.toProjectionRank =
      dpProjectionRank := by
  ext t
  simpa [DirectCounterProjectionWitness.toConfessionCoreWitness, dpProjectionRank] using
    congrFun counterProjectionRankFn_eq_dpProjection t

/-- Pair the counter-projection rank with the `subtermCriterionDirect` license
tag. The tag names the intended external route; it is not theorem evidence. -/
def counterProjectionConfession : ConfessionMethod ko7Schema where
  toProjectionRank := counterProjectionDerivedRank
  license := SoundnessLicense.subtermCriterionDirect

/-- The exported instance contains `counterProjectionDerivedRank`
definitionally. -/
theorem counterProjectionConfession_is_derived :
    counterProjectionConfession.toProjectionRank = counterProjectionDerivedRank := rfl

/-- The counter-projection-tagged confession instance and the DP instance use
the same rank function. The theorem establishes only this equality; it does not
quantify over other methods or rewrite systems. -/
theorem counterProjection_eq_dp_rank :
    counterProjectionConfession.rank = dpConfession.rank := by
  simpa [counterProjectionConfession, dpConfession, dpProjectionRank,
    counterProjectionDerivedRank] using counterProjectionRankFn_eq_dpProjection

/-- Route evidence bundling the selected-coordinate witness, syntactic subterm
facts, and rank equations for strict counter descent and wrapper erasure. -/
structure DirectCounterProjectionRouteEvidence where
  witness : DirectCounterProjectionWitness
  originalSymbolSubterm :
    ∀ n, DirectSubterm n (delta n)
  counterSubtermInOriginalCall :
    ∀ b s n, OriginalSymbolSubterm n (recΔ b s (delta n))
  payloadSubtermInOriginalCall :
    ∀ b s n, OriginalSymbolSubterm s (recΔ b s (delta n))
  strictSubtermDescent :
    ∀ n, witness.toConfessionCoreWitness.rank (delta n) =
      witness.toConfessionCoreWitness.rank n + 1
  payloadDropped :
    ∀ x y, witness.toConfessionCoreWitness.rank (app x y) = 0

/-- Concrete direct counter-projection evidence for the KO7 recursive
fragment. -/
def schemaDirectCounterProjectionRouteEvidence :
    DirectCounterProjectionRouteEvidence where
  witness := schemaDirectCounterProjectionWitness
  originalSymbolSubterm := by
    intro n
    exact DirectSubterm.delta_arg n
  counterSubtermInOriginalCall := by
    intro b s n
    exact OriginalSymbolSubterm.trans
      (OriginalSymbolSubterm.delta_arg n)
      (OriginalSymbolSubterm.recur_counter b s (delta n))
  payloadSubtermInOriginalCall := by
    intro b s n
    exact OriginalSymbolSubterm.recur_step b s (delta n)
  strictSubtermDescent := by
    intro n
    rfl
  payloadDropped := by
    intro x y
    rfl

/-- Forget the subterm fields and retain the generic projection-rank profile
carried by the witness. -/
def DirectCounterProjectionRouteEvidence.toRouteEvidence
    (E : DirectCounterProjectionRouteEvidence) : RouteEvidence ko7Schema where
  rank := E.witness.toConfessionCoreWitness.rank
  rank_base := E.witness.toConfessionCoreWitness.rank_base
  rank_succ := E.witness.toConfessionCoreWitness.rank_succ
  rank_wrap := E.witness.toConfessionCoreWitness.rank_wrap
  rank_recur := E.witness.toConfessionCoreWitness.rank_recur

/-- The concrete direct counter-projection route evidence packaged through the
    generic adapter. -/
abbrev schemaDirectCounterProjectionGenericRouteEvidence : RouteEvidence ko7Schema :=
  schemaDirectCounterProjectionRouteEvidence.toRouteEvidence

/-- The witness component of the route evidence satisfies the four generic
projection-rank equations. The subterm-specific fields are not used in this
theorem. -/
theorem directCounterProjectionRouteEvidence_implies_semantic_profile :
    NormalizedAtBase ko7Schema
      schemaDirectCounterProjectionRouteEvidence.witness.toConfessionCoreWitness.rank
    ∧ TracksSuccessorDepth ko7Schema
      schemaDirectCounterProjectionRouteEvidence.witness.toConfessionCoreWitness.rank
    ∧ ForgetsWrapperPayload ko7Schema
      schemaDirectCounterProjectionRouteEvidence.witness.toConfessionCoreWitness.rank
    ∧ FollowsRecursiveCounter ko7Schema
      schemaDirectCounterProjectionRouteEvidence.witness.toConfessionCoreWitness.rank := by
  have h :=
    ConfessionCoreWitness.satisfies_semantic_profile
      schemaDirectCounterProjectionRouteEvidence.witness.toConfessionCoreWitness
  simpa [schemaDirectCounterProjectionRouteEvidence] using h

/-- The witness's packaged projection rank satisfies the generic profile. -/
theorem directCounterProjectionWitness_has_semantic_profile :
    NormalizedAtBase ko7Schema schemaDirectCounterProjectionWitness.toConfessionCoreWitness.rank
    ∧ TracksSuccessorDepth ko7Schema schemaDirectCounterProjectionWitness.toConfessionCoreWitness.rank
    ∧ ForgetsWrapperPayload ko7Schema schemaDirectCounterProjectionWitness.toConfessionCoreWitness.rank
    ∧ FollowsRecursiveCounter ko7Schema schemaDirectCounterProjectionWitness.toConfessionCoreWitness.rank := by
  exact schemaDirectCounterProjectionWitness.toConfessionCoreWitness.satisfies_semantic_profile

end OperatorKO7.ConfessionMethodFamily
