import OperatorKO7.Meta.StepDuplicatingSchema

/-!
# Free Step-Duplicating Syntax

This module provides the free term algebra for the primitive
step-duplicating schema:

- `base`
- `succ`
- `wrap`
- `recur`

It is the canonical example of a carrier that is genuinely generated by the
schema constructors. This makes the abstract uniqueness theorem from
`StepDuplicatingSchema.lean` concrete.
-/

namespace OperatorKO7.StepDuplicating
namespace StepDuplicatingSchema

/-- The free syntax for the primitive step-duplicating signature. -/
inductive FreeTerm
  | base : FreeTerm
  | succ : FreeTerm → FreeTerm
  | wrap : FreeTerm → FreeTerm → FreeTerm
  | recur : FreeTerm → FreeTerm → FreeTerm → FreeTerm
  deriving DecidableEq, Repr

/-- The free step-duplicating schema. -/
def freeSchema : StepDuplicatingSchema where
  T := FreeTerm
  base := FreeTerm.base
  succ := FreeTerm.succ
  wrap := FreeTerm.wrap
  recur := FreeTerm.recur

/-- The free syntax is generated by the primitive constructors by structural
    induction. -/
def freeSchemaGenerated : GeneratedByConstructors freeSchema where
  generated := by
    intro P hbase hsucc hwrap hrecur t
    induction t with
    | base =>
        exact hbase
    | succ t ih =>
        exact hsucc t ih
    | wrap x y ihx ihy =>
        exact hwrap x y ihx ihy
    | recur b s n ihb ihs ihn =>
        exact hrecur b s n ihb ihs ihn

/-- The canonical counter-depth rank on the free syntax. -/
@[simp] def freeCounterDepth : FreeTerm → Nat
  | .base => 0
  | .succ t => freeCounterDepth t + 1
  | .wrap _ _ => 0
  | .recur _ _ n => freeCounterDepth n

/-- The canonical projection rank on the free syntax. -/
def freeProjectionRank : ProjectionRank freeSchema where
  rank := freeCounterDepth
  rank_base := by rfl
  rank_succ := by intro t; rfl
  rank_wrap := by intro x y; rfl
  rank_recur := by intro b s n; rfl

/-- The corresponding confession-core witness on the free syntax. -/
def freeConfessionCoreWitness : ConfessionCoreWitness freeSchema :=
  ConfessionCoreWitness.ofProjectionRank freeProjectionRank

/-- On the free syntax, every projection rank is the canonical counter-depth
    rank. -/
theorem freeProjectionRank_unique (R : ProjectionRank freeSchema) :
    R = freeProjectionRank := by
  exact projectionRank_unique_of_generated freeSchemaGenerated R freeProjectionRank

/-- On the free syntax, every confession-core witness is the canonical
    counter-depth core witness. -/
theorem freeConfessionCoreWitness_unique (W : ConfessionCoreWitness freeSchema) :
    W = freeConfessionCoreWitness := by
  exact ConfessionCoreWitness.unique_of_generated
    freeSchemaGenerated W freeConfessionCoreWitness

end StepDuplicatingSchema
end OperatorKO7.StepDuplicating
