/-!
# Downstream-closure provenance

This module defines the inductive closure generated by a base predicate and a binary route. The
predicate `ExogenousGainZero` is, by definition, membership in that closure. No information measure,
entropy, causal channel, or numerical gain is defined here.

`ProvenanceCollapse` stores an arbitrary proposition with a witness and a proof that its answer is in
the downstream closure. The concrete example uses `True` for that proposition and a single route step
from `corpus` to `answer`.
-/

set_option autoImplicit false

namespace OperatorKO7.Meta.BoundaryGeneral.EndogenousProvenance

/-! ### Downstream closure of a corpus -/

/-- A carrier with a base predicate and a one-step route. -/
structure ClosureSystem where
  Carrier : Type
  base : Carrier → Prop
  route : Carrier → Carrier → Prop

/-- The inductive closure containing every base element and closed under one route step. -/
inductive Downstream (S : ClosureSystem) : S.Carrier → Prop
  | base {x : S.Carrier} (h : S.base x) : Downstream S x
  | step {x y : S.Carrier} (hx : Downstream S x) (r : S.route x y) : Downstream S y

/-- Historical name for downstream-closure membership. -/
def ExogenousGainZero (S : ClosureSystem) (answer : S.Carrier) : Prop :=
  Downstream S answer

/-! ### Inhabited closure-membership package -/

/-- An answer in the downstream closure, together with a witness of an otherwise unconstrained
proposition `nonvacuous_launch`. -/
structure ProvenanceCollapse (S : ClosureSystem) where
  answer : S.Carrier
  nonvacuous_launch : Prop
  launched : nonvacuous_launch
  answer_endogenous : Downstream S answer

/-- Project downstream-closure membership from a `ProvenanceCollapse` package. -/
theorem provenance_collapse_exogenous_zero (S : ClosureSystem) (P : ProvenanceCollapse S) :
    ExogenousGainZero S P.answer :=
  P.answer_endogenous

/-- Pair the stored proposition witness with downstream-closure membership. -/
theorem provenance_collapse_is_confession (S : ClosureSystem) (P : ProvenanceCollapse S) :
    P.nonvacuous_launch ∧ ExogenousGainZero S P.answer :=
  ⟨P.launched, P.answer_endogenous⟩

/-! ### A two-element closure system -/

/-- Two carriers named `corpus` and `answer`. -/
inductive LivedCarrier where
  | corpus
  | answer

/-- The base is `corpus`; the only inhabited route pair is `corpus` to `answer`. -/
def livedSystem : ClosureSystem where
  Carrier := LivedCarrier
  base := fun x => x = LivedCarrier.corpus
  route := fun x y => x = LivedCarrier.corpus ∧ y = LivedCarrier.answer

/-- A concrete package using `True` as the stored proposition and one closure step to `answer`. -/
def livedCollapse : ProvenanceCollapse livedSystem where
  answer := LivedCarrier.answer
  nonvacuous_launch := True
  launched := trivial
  answer_endogenous := Downstream.step (Downstream.base rfl) ⟨rfl, rfl⟩

/-- The element `answer` belongs to the downstream closure of `livedSystem`. -/
theorem lived_exogenous_zero : ExogenousGainZero livedSystem LivedCarrier.answer :=
  provenance_collapse_exogenous_zero livedSystem livedCollapse

#print axioms provenance_collapse_exogenous_zero
#print axioms lived_exogenous_zero

end OperatorKO7.Meta.BoundaryGeneral.EndogenousProvenance
