import OperatorKO7.Meta.LicensedBoundaryCalculus.Execution.TraceAdequacy
import OperatorKO7.Meta.LicensedBoundaryCalculus.Accounting.EventLedger

/-!
# Execution-ledger soundness

The execution ledger is defined as the finite event count of a result trace.
Sequential execution composes traces by list append, and `countEvents` maps
that append to ledger addition.

## Formal scope

Relation: inherited from each executed boundary edge.
Closure: trace append and finitely supported ledger addition.
Trust: kernel-only list recursion and `Finsupp` arithmetic.
Scope: generic semantic event counts, before resource valuation.
-/

set_option autoImplicit false

namespace OperatorKO7.Meta.LicensedBoundaryCalculus

universe u v w x

/-- Ledger generated by one execution result. -/
noncomputable def BoundaryExecutionResult.ledger
    {A : ARS.{u}} {B : ARS.{v}}
    {F : PartialLicensedReductionMorphism A B}
    {input : BoundaryExecutionInput F}
    (result : BoundaryExecutionResult F input) : EventLedger :=
  countEvents result.trace

/-- The execution ledger is definitionally equal to the event count of its trace. -/
theorem execute_ledger_eq_countEvents
    {A : ARS.{u}} {B : ARS.{v}}
    (F : PartialLicensedReductionMorphism A B)
    (input : BoundaryExecutionInput F) :
    (execute F input).ledger = countEvents (execute F input).trace :=
  rfl

/-- The ledger can equivalently be computed directly from the certified
decision trace. -/
theorem execute_ledger_eq_decisionLedger
    {A : ARS.{u}} {B : ARS.{v}}
    (F : PartialLicensedReductionMorphism A B)
    (input : BoundaryExecutionInput F) :
    (execute F input).ledger =
      countEvents (decisionTrace (execute F input).decision) := by
  unfold BoundaryExecutionResult.ledger
  rw [execute_trace_eq F input]

/-- Rewriting each execution trace as its decision trace preserves their append. -/
theorem execute_comp_trace
    {A : ARS.{u}} {B : ARS.{v}} {C : ARS.{w}} {D : ARS.{x}}
    (F : PartialLicensedReductionMorphism A B)
    (G : PartialLicensedReductionMorphism C D)
    (first : BoundaryExecutionInput F)
    (second : BoundaryExecutionInput G) :
    EventTrace.comp (execute F first).trace (execute G second).trace =
      EventTrace.comp
        (decisionTrace (execute F first).decision)
        (decisionTrace (execute G second).decision) := by
  rw [execute_trace_eq F first, execute_trace_eq G second]

/-- Counting the appended execution traces equals the sum of their two ledgers. -/
theorem execute_comp_ledger
    {A : ARS.{u}} {B : ARS.{v}} {C : ARS.{w}} {D : ARS.{x}}
    (F : PartialLicensedReductionMorphism A B)
    (G : PartialLicensedReductionMorphism C D)
    (first : BoundaryExecutionInput F)
    (second : BoundaryExecutionInput G) :
    countEvents
        (EventTrace.comp (execute F first).trace (execute G second).trace) =
      (execute F first).ledger + (execute G second).ledger := by
  exact countEvents_comp _ _

/-- Three concrete execution fixtures have the displayed event counts. -/
theorem execution_ledgers_nonvacuous_fixture :
    (execute PartialLicensedReductionMorphism.partialChain_fixture
        stateRefusalInput_fixture).ledger .stateRefusal = 1 ∧
      (execute PartialLicensedReductionMorphism.pureEdgeRejection_fixture
        edgeRefusalInput_fixture).ledger .edgeRefusal = 1 ∧
      (execute (PartialLicensedReductionMorphism.id chainARS_fixture)
        commitInput_fixture).ledger .replayStep = 1 := by
  simp [BoundaryExecutionResult.ledger, execute, decisionTrace,
    countEvents, singletonEventLedger, stateRefusalInput_fixture,
    edgeRefusalInput_fixture, commitInput_fixture]

#check @execute_ledger_eq_countEvents
#check @execute_comp_trace
#check @execute_comp_ledger
#check execution_ledgers_nonvacuous_fixture
#print axioms execute_ledger_eq_countEvents
#print axioms execute_ledger_eq_decisionLedger
#print axioms execute_comp_trace
#print axioms execute_comp_ledger
#print axioms execution_ledgers_nonvacuous_fixture

end OperatorKO7.Meta.LicensedBoundaryCalculus
